### ISSUE TITLE
Need to Pass cookies with request for document src

### ISSUE THREAD

**Issue by EricBPower** [VadimDez/ng2-pdf-viewer#10]
We have an authentication cookie that our API requires before returning a PDF response.
When trying to use our url in the src attribute the pdf viewer fails because it gets a 401 status code from the url.  How can we send the current cookies with the request for the pdf?

In an object data attribute the cookies are automatically sent.
In http.get there is a withCredentials attribute that can be sent as true.
But what is the correct way to send cookies using pdf viewer?

**Comment by VadimDez** [comment]
@EricBPower, i updated version and documentation as well, check it [here](https://github.com/VadimDez/ng2-pdf-viewer#options)

**Comment by EricBPower** [comment]
@VadimDez, You rock! Thank you very much.
