### ISSUE TITLE
web worker not found

### ISSUE THREAD

**Issue by damianog** [VadimDez/ng2-pdf-viewer#100]
I am bundling all with ng-cli 

pdfs are rendered correctly, but I get the following error on console:

HTTP404: NOT FOUND
http://localhost:4200/main.bundle.worker.js
Warning: Setting up fake worker.
pdf.js (346,1)

also width -prod compliation

Warning: Setting up fake worker.
vendor.aaafec7fd54304604bec.bundle.js (382,5611)

Which is the right way to load or bundling web worker?

**Comment by VadimDez** [comment]
Should be fixed by 1.2.5 (which is using real web worker)
