### ISSUE TITLE
Draw Highlights

### ISSUE THREAD

**Issue by daniela-alves** [VadimDez/ng2-pdf-viewer#1000]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [X] Feature request
- [ ] Documentation issue or request
```
In my project, I need to create highlights of the document pages.
I don't show all pages because the goal is to preview page by page. I only show the next/previous page if I click on a custom arrow defined by us.

Currently, using the (page-rendered) output I draw the highlights on the canvas but I have many issues when I change the page. Sometimes they don't happen and I would like to have something in the lib to define highlights each time I change the page.

**Example of highlights:**
![image](https://github.com/VadimDez/ng2-pdf-viewer/assets/126074250/5f35a6f9-c4cc-4725-89c9-336cb1c77f15)

They can have colors. The grey color is used to apply confidentiality in the document. When we export the document we can't see that part covered by grey highlight.

**Goal:**
1. Display all highlights according to the opened page 
2. Draw new highlights on the page (We export the documents and we should see them. If it's a confidential highlight, on the export we shouldn't see the text in that area)
3. Delete current highlights on the page

**Comment by marcelocerqueira69** [comment]
I'm having the same issue. Does someone has an idea of how to do it?

**Comment by Ricardo-Guia** [comment]
I have tried to do it too, but couldn't figure it out a good way to do it.. hope to see some news here

**Comment by silviu-sterian** [comment]
I have a somewhat similar issue. 
I basically need to subscribe to when text is selected and grab the text that was selected so I can store it somewhere else.
Anyone knows where is the list of events in pdfComponent.eventBus that I can subscribe to?
