### ISSUE TITLE
Missing text in pdf document

### ISSUE THREAD

**Issue by RobinBomkamp** [VadimDez/ng2-pdf-viewer#1001]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

This document is not shown correctly. There some parts of the invoice missing. If I open the document in the PDF.js example it is shown correctly. 

[invoice-20230307-c6415706-6573-48b4-80cf-5283aa237779.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/11477440/invoice-20230307-c6415706-6573-48b4-80cf-5283aa237779.pdf)

**Comment by RobinBomkamp** [comment]
This is still relevant.

**Comment by VadimDez** [comment]
Seems to be working fine in the latest 10.2.2 version
