### ISSUE TITLE
'ng2-pdf-viewer not found 404

### ISSUE THREAD

**Issue by Gajendrasinh** [VadimDez/ng2-pdf-viewer#101]
Hello,

I have installed 
npm install pdfjs-dist --save
npm install ng2-pdf-viewer --save

app.module.ts file

import { PdfViewerComponent } from 'ng2-pdf-viewer';

  declarations: [
    PdfViewerComponent
]

its return 404 error in console how can i solve this

![image](https://user-images.githubusercontent.com/10431380/27634236-31cc57ea-5c20-11e7-81f6-b2fd23292047.png)

**Comment by VadimDez** [comment]
You have to specify for `SystemJS` where to take the library from.
See the documentation https://github.com/VadimDez/ng2-pdf-viewer/blob/master/SYSTEMJS.md
