### ISSUE TITLE
Angular 16 compatibility

### ISSUE THREAD

**Issue by VaggelisKa** [VadimDez/ng2-pdf-viewer#1019]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

When using the project with Angular 16 the pdf isn't rendered and callback events not triggered. Has anyone managed to make it work or using it with Angular 16?

**Comment by VadimDez** [comment]
Thanks for letting me know - I'll check

**Comment by ftaffelt** [comment]
No problems here: Angular 16.1.5, ng2-pdf-viewer 9.1.5

**Comment by bncunha** [comment]
Same here. Anguar 16.1.7

**Comment by acosme** [comment]
Same here in ionic + capacitor

**Comment by VaggelisKa** [comment]
Coming back to this issue it seemed that the problem was something in my end. (Had mistakenly changed the default worker location).
