### ISSUE TITLE
scroll not working after changing the zoom on mobile

### ISSUE THREAD

**Issue by ghost** [VadimDez/ng2-pdf-viewer#102]
I display the pdf in a div with a fixed size and overflow scroll

    <div class="row" *ngIf="fileUrl" style="height: 80vh; overflow: scroll">
          <pdf-viewer [src]="fileUrl"
                     [render-text]="true"
                     [original-size]="false"
                     [show-all]="true"
                     [zoom]="zoomValue"
                     style="display: block;"
          ></pdf-viewer>
    </div>

If you zoom in or out (incresing or decreasing the zoomValue) then the scroll through the document doesn't work. Also after each change of zoomValue the document is automatically scrolled to top. Is there a way to scroll back to the position before the value change?

**Comment by VadimDez** [comment]
Does this issue appears on version `2.0.2`?

**Comment by lucalanca** [comment]
@VadimDez I can also confirm that this happen. I downgraded to `2.0.1` and the issue is not there.
