### ISSUE TITLE
Rename project to ngx-pdf-viewer

### ISSUE THREAD

**Issue by VadimDez** [VadimDez/ng2-pdf-viewer#104]
Rename this project from `ng2-pdf-viewer` to `ngx-pdf-viewer`

**Comment by stephanrauh** [comment]
Renaming a project is always risky... I suppose there are so many library called "ng2-something" out there that you can safely close this ticket.

**Comment by VadimDez** [comment]
back then thought it would be cool to rename it, to be compliant with standard. Anyway, not a priority right now.
