### ISSUE TITLE
How to print a pdf?

### ISSUE THREAD

**Issue by tonychangcheng** [VadimDez/ng2-pdf-viewer#107]
I am looking for a solution to print a pdf file. 

I found the pdf.js has a web/viewer which supports printing and other features. As ng2-pdf-viewer underneath is using pdf.js. Dose it provide a wrap of the web/viewer? Or does it have a plan to do that?

**Comment by tonychangcheng** [comment]
And does it support displaying a pdf from a base64 buffer?

**Comment by bhupinderkumarbl** [comment]
I did with simply call this function on click 

printpdf() {
        this.winRef.open(this.pdfSrc).print();
    }

**Comment by VadimDez** [comment]
Duplicate of #69

**Comment by jacobbutton** [comment]
@bhupinderkumarbl - how are you declaring and initializing `this.winRef` ?

**Comment by bibhukdas** [comment]
Convert your blob to URL, and print it. Works for me.
const fl = URL.createObjectURL(this.fileBlob);
window.open(fl).print();

**Comment by rohanrp** [comment]
I got it to print using 

const blobUrl  = window.URL.createObjectURL((this.srcBinary);
const iframe = document.createElement('iframe');
iframe.style.display = 'none';
iframe.src = blobUrl;
document.body.appendChild(iframe);
iframe.contentWindow.print();

**Comment by fredfgb** [comment]
> printpdf() {
> this.winRef.open(this.pdfSrc).print();
> }

Here explains how to use "winRef", just a bootstrap for nativeWindow

**Comment by alehro** [comment]
Simpler approach with example is in https://github.com/intbot/ng2-pdfjs-viewer/issues/7
