### ISSUE TITLE
'PdfViewerModule' does not appear to be an NG module class 

### ISSUE THREAD

**Issue by carepollo** [VadimDez/ng2-pdf-viewer#1072]
Using angular 16 and library version 10 and get this error. I looked at the source of the node modules and I need it is just an empty exported class, does anyone else have this problem?

**Comment by RauPro** [comment]
Same problem here, You have to be careful about where are u installing module, in my case the problem was that I installed ng2-pdf-viewer out of my project folder, hope that helps you.
