### ISSUE TITLE
Any plans to upgrade to latest pdf.js version

### ISSUE THREAD

**Issue by Himesh512** [VadimDez/ng2-pdf-viewer#1078]
Any plans to upgrade to latest pdf.js version as it's using **2.14.305** version using for **pdf.js** and pdf-dist.js which have **4.0.379** stable version.

it's around 2 years from the version which we are using.

any road map plan to upgrade ?

**Comment by shamoon** [comment]
I have successfully integrated 3.10 with essentially a fork of this project and there’s a PR for it: https://github.com/VadimDez/ng2-pdf-viewer/pull/1027 but haven’t heard from the main dev for some time, unfortunately.

As I understand it v4 is a much bigger release with breaking changes so not something I’m interested in trying to tackle personally.

Hopefully this isn’t the end of the line for this project.

**Comment by chandan-bcsg** [comment]
Do we have any documentation to follow on Steps to upgrade ?
