### ISSUE TITLE
PDF is loading as plain text as well as PDF, overlapping 

### ISSUE THREAD

**Issue by MilanRaval** [VadimDez/ng2-pdf-viewer#108]
Looks like PDF is first loading as plain text on page and then as PDF, overlapping each other. Till now I know that it occurs on Edge and Safari browsers on mobile and PC both.

**Comment by VadimDez** [comment]
Is this still valid?

**Comment by MilanRaval** [comment]
Setting [render-text]="false" - fixed for me

**Comment by VadimDez** [comment]
Have you tried `[render-text]="true"` with the latest version (`1.1.5`)?

**Comment by bhupinderkumarbl** [comment]
same issue with me http://prntscr.com/g69l4c space is coming with extra character.
my code is like this 
 <pdf-viewer [src]="pdfSrc"
                            [page]="page"
                            [original-size]="true"
                            [zoom]="zoom"
                            [render-text]="true"
                            style="display: block"
                            [show-all]="true">

                </pdf-viewer>

**Comment by VadimDez** [comment]
@bhupinderkumarbl can you upload here the PDF that causing this behaviour ?

**Comment by bhupinderkumarbl** [comment]
@VadimDez  you can take any kind of dummy pdf not any specific

**Comment by VadimDez** [comment]
@bhupinderkumarbl what about https://vadimdez.github.io/ng2-pdf-viewer/ ?

**Comment by bhupinderkumarbl** [comment]
@VadimDez i am using pdf from my local folder like a image it the folder name is asset and there i put the pdf and using it in application it was working fine for me but after to implement angular cli it create issue for me

**Comment by VadimDez** [comment]
@bhupinderkumarbl is this valid for every pdf? Have you tried with this pdf https://github.com/VadimDez/ng2-pdf-viewer/blob/master/pdf-test.pdf ?

**Comment by amit-jamwal** [comment]
Hi 
In my PDF viewer space between character are shown as small box.

![screencapture-localhost-8080-lobby-reports-49-guides-stockssharesetcguide-steps-stockssharesetcguidestep1-1503061695001](https://user-images.githubusercontent.com/9278261/29460207-b5099d06-8444-11e7-9e03-5ee4d2729f45.png)

**Comment by VadimDez** [comment]
fixed in 2.0.0
