### ISSUE TITLE
Cant preview the uploaded pdf using Blob url.

### ISSUE THREAD

**Issue by ududsha** [VadimDez/ng2-pdf-viewer#109]
Following is my URL and I managed to download it successfully and open it using window.open('url').
Url is a generated one and something like "blob:http://localhost:4200/3fb36e8b-a6b7-481b-9d0c-8efa86bb4208".

But I cant show it on my preview-file MdDialog by clicking "Preview" button appeared after my pdf upload get success. 
` <pdf-viewer [src]="url" [original-size]="true"></pdf-viewer> `

I tried to pass the values using  {{url}} in case if above is wrong.

But I cant do that. Please show me a way to handle this issue.

**Comment by VadimDez** [comment]
Have you tried something like `const url = URL.createObjectURL(blob);` ?

**Comment by ududsha** [comment]
Yes this is my function to get that URL using blob.

`export const getObjectUrlForAwsS3File = (data, fileType, fileName)=>{
    let options = {
        type : fileType
    };


	let byteArray = new Uint8Array(data.length);
    for(var i=0; i<data.length; i++) {
        byteArray[i] = data[i];
    }

    let blob:Blob = new Blob([byteArray], options);
    let url = URL.createObjectURL(blob);
	return url;
}`

**Comment by VadimDez** [comment]
You can pass `Uint8Array` directly to `[src]`

**Comment by ududsha** [comment]
That works! Thanks a lot. Is there any location that you documented those in detail @VadimDez .

**Comment by jorugit** [comment]
I have the same Problem, what do you mean with "You can pass Uint8Array directly to [src]"?

**Comment by AcarMeel** [comment]
I'm having this issue. I get a blob file and I convert it to Url but the PDF is not displayed 
const url = URL.createObjectURL(blob);

**Comment by anurag-shj** [comment]
@AcarMeel Facing the same issue. Did you find any solution?
