### ISSUE TITLE
 TS2304: Cannot find name 'WeakKey'.

### ISSUE THREAD

**Issue by belkhiriaHatem** [VadimDez/ng2-pdf-viewer#1094]
##### Bug Report or Feature Request (mark with an `x`)
```
- [x] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

**Comment by ursaciuc-adrian** [comment]
having the same issue. Started about two days ago

**Comment by thinhkimle** [comment]
I'm having the same issue today when upgraded to `10.2.0`

**Comment by souhailharrati** [comment]
i have the same issue in last version 10.2.1

**Comment by belkhiriaHatem** [comment]
i've solved the problem by donwgrading the version to "ng2-pdf-viewer": "^9.1.5",

**Comment by VadimDez** [comment]
Tested 10.2.2 with Angular 17 - works fine.

**Comment by thinhkimle** [comment]
I'm still having the same problem on 10.2.2 with Angular 15 unfortunately... 😢
