### ISSUE TITLE
Critical Security Vulnerability in dependency package "pdfjs"

### ISSUE THREAD

**Issue by bdalvandi-awaremd** [VadimDez/ng2-pdf-viewer#1109]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

The latest version of `ng2-pdf-viewer` (10.2.2) has a dependency to `pdfjs-dist` version `3.11.x` which has recently been discovered to have an extremely critical vulnerability, allowing attacks on the domain.
The latest version of `pdfjs-dist` has remediated that vulnerability, I am wondering if a new version of `ng2-pdf-viewer` coming out soon that uses the latest version and remediates this vulnerability?

**Comment by shamoon** [comment]
Did you search? Multiple issues cover this already

**Comment by bdalvandi-awaremd** [comment]
> Did you search? Multiple issues cover this already

Yes. But I don't see any of them clearly explaining how to overcome the vulnerability. The closest thing I have seen is ppl mentioning to set the `eval` to `false` or something, but where and how is not clear. 
Can you by any chance point me to a clear solution? thanks.

**Comment by mejobloggs-cw** [comment]
I agree it's not clear how to resolve this security issue. Is there a patch or update coming?

**Comment by shamoon** [comment]
Did you try reading the release notes, eg for [v10.2.0](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/10.2.0)

https://github.com/VadimDez/ng2-pdf-viewer/pull/1092 resolves the CVE but does not update the pdfjs package to 4.x, so automated security tools will still complain even though the issue is resolved.

**Comment by DerekLiang** [comment]
Does anyone know what is the effort to update the dependency to pdfjs 4.x?

**Comment by shamoon** [comment]
... https://github.com/VadimDez/ng2-pdf-viewer/pull/1105

**Comment by shamoon** [comment]
Should be closed

**Comment by VadimDez** [comment]
Closing @shamoon
