### ISSUE TITLE
Upgrade pdfjs-dist from 2.5.207 version to latest version

### ISSUE THREAD

**Issue by chandan-bcsg** [VadimDez/ng2-pdf-viewer#1117]
hi , 
Need help in upgrading pdfjsdist package from 2.5.207 package to most recent versions as there is security issues reported in it . 
Getting below error if I try to upgrade to any future versions 

Error: - error TS2305: Module '"pdfjs-dist"' has no exported member 'PDFViewerParams'.

5 import {PDFDocumentProxy, PDFPageProxy, PDFViewerParams} from 'pdfjs-dist';
                                          ~~~~~~~~~~~~~~~

**Comment by shamoon** [comment]
I'm not a maintainer of this project but I must say it's disappointing to me how little effort people put into searching before opening an issue. This is a duplicate of multiple issues.

**Comment by chandan-bcsg** [comment]
@shamoon  ,  if you can please point me to to the solution of this isue it would be great .  I was unable to to find any fix for the same , All I saw that comments are saying to stay to 2.5.207 version ? is that the only fix for this ? Also those comments are 2-3 years back .  Is there any documention / step to upgrade from 2.5.207 to 4.x ?

**Comment by shamoon** [comment]
You cannot upgrade the pdfjs package yourself

https://github.com/VadimDez/ng2-pdf-viewer/issues/1088
https://github.com/VadimDez/ng2-pdf-viewer/issues/1093
https://github.com/VadimDez/ng2-pdf-viewer/issues/1109
https://github.com/VadimDez/ng2-pdf-viewer/issues/1102
https://github.com/VadimDez/ng2-pdf-viewer/issues/1078

https://github.com/VadimDez/ng2-pdf-viewer/pull/1105
https://github.com/VadimDez/ng2-pdf-viewer/pull/1092

Again, this new report is just extra noise.

**Comment by shamoon** [comment]
Should be closed

**Comment by VadimDez** [comment]
Closing @shamoon
