### ISSUE TITLE
security vulnerability issues in angular 17

### ISSUE THREAD

**Issue by rathinamshanmugam** [VadimDez/ng2-pdf-viewer#1119]
Hi 
after upgrading to pdfjs-dist  to V4 , still  pdf-viewer referring  3.11.174 . I have attached my package json

[package.json](https://github.com/user-attachments/files/16487651/package.json)
[package-lock.json](https://github.com/user-attachments/files/16487652/package-lock.json)
![image](https://github.com/user-attachments/assets/e53ce8fc-8b15-4667-b725-78fdf302d2f7)

pdfjs-dist  <=4.1.392
Severity: high
PDF.js vulnerable to arbitrary JavaScript execution upon opening a malicious PDF - https://github.com/advisories/GHSA-wgrm-67xf-hhpq
No fix available
node_modules/ng2-pdf-viewer/node_modules/pdfjs-dist
  ng2-pdf-viewer  *
  Depends on vulnerable versions of pdfjs-dist
  node_modules/ng2-pdf-viewer

2 high severity vulnerabilities

**Comment by shamoon** [comment]
Please look through issues and discussions. This is a duplicate of many other reports and this should be closed

**Comment by rathinamshanmugam** [comment]
Thanks . I will go through  issues

**Comment by shamoon** [comment]
Should be closed
