### ISSUE TITLE
Turn OFF Lazy Loading?

### ISSUE THREAD

**Issue by js10x** [VadimDez/ng2-pdf-viewer#1120]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [X ] Documentation issue or request
```

Looking for an option to turn OFF lazy loading. Need to access DOM elements in all pages on load of the PDF. How can I turn OFF lazy loading?

**Comment by shamoon** [comment]
See #1133 this is a pdfjs thing, issue here can probably be closed
