### ISSUE TITLE
CSP Issue

### ISSUE THREAD

**Issue by micarsls** [VadimDez/ng2-pdf-viewer#1122]
<img width="1703" alt="image" src="https://github.com/user-attachments/assets/99d50b7a-429d-416f-987a-4a8cd67f0654">

Hi, my angular app is having strict csp policy. Is it possible to solve this one?

**Comment by 64knl** [comment]
Related: https://github.com/VadimDez/ng2-pdf-viewer/issues/1135

**Comment by VadimDez** [comment]
See documentation on how to set pdf worker from your preferred secure source: https://github.com/VadimDez/ng2-pdf-viewer?tab=readme-ov-file#set-custom-path-to-the-worker
