### ISSUE TITLE
Latest version requires Typescript 5.6 which current LTS of angular (v18.2.7) does not support

### ISSUE THREAD

**Issue by nb-midwestern** [VadimDez/ng2-pdf-viewer#1137]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
```
└─┬ ng2-pdf-viewer@10.3.1
  └── pdfjs-dist@4.7.76
```

See https://github.com/mozilla/pdf.js/issues/18867 for more info

Typescript version changed in this release https://github.com/mozilla/pdf.js/releases/tag/v4.7.76

**Comment by selangley** [comment]
@VadimDez 
I found this issue after getting 'ng build' errors in my Angular 18 app with the latest 10.4 version installed.

Perhaps the install documentation could be updated to indicate that Angular 18 users should install the 10.3.x version and not the 10.4 version?

**Comment by shamoon** [comment]
Ah this is my fault, this is true. I completely forgot about this, sorry.

I guess question is how to proceed, either bump the requirements of this package to be Angular ≥19 or downgrade pdfjs for now (again).

**Comment by shamoon** [comment]
See #1161 (though defer to VD of course)
