### ISSUE TITLE
After upgrade to the version 10.3.3, the first page of pdf is always rendered twice, with different dimension in viewport each time

### ISSUE THREAD

**Issue by oktesting** [VadimDez/ng2-pdf-viewer#1145]
##### Bug Report or Feature Request (mark with an `x`)
```
- [x] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Hi.
I've notice one problem with this library in this current version 10.3.3 (as far as I know)
The problem is that once the pdf is loaded, then `page-rendered` event is fired. In the latest version 10.3.3, the first page is always rendered twice. The first page render with incorrect `width`, `height` and `scale` in the page viewport. The second page render with correct ones. This behaviour causes the pdf viewer displaying first page quickly flickering as it switching from the first to second render, the page is shrink or expanded depending on its actual view width

I had reproduced and captured the problem in the library stackbliz example: https://stackblitz.com/edit/ng2-pdf-viewer

this reproduction with the library's version 10.0.0 and `pdfjs-dist` version 2.16.105. No issue occurred as each page is rendered once
![image](https://github.com/user-attachments/assets/1e7c14ae-a937-4ece-836e-82d9626ecb66)

this reproduction with the library's latest version 10.3.3 and `pdfjs-dist` version 4.6.82. The issue occurred as the first page is rendered twice
![image](https://github.com/user-attachments/assets/d4dba1c4-f0b6-4bf8-a7ab-a00c796e83cc)

I hope someone could point out what seem to be the problem with this library latest version 10.3.3

Thanks to the author and all contributors for this excellent library. Cheer 🎊

**Comment by VadimDez** [comment]
Fixed in 10.3.4
thanks to @shamoon
