### ISSUE TITLE
Update pdfjs-dist dependency to the latest version for better compatibility

### ISSUE THREAD

**Issue by PatrickFrantzen** [VadimDez/ng2-pdf-viewer#1148]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
- [X ] Change request
```
Hi,

I’m using ng2-pdf-viewer version 10.3.4, which currently relies on pdfjs-dist version 4.6.82. However, this version of pdfjs-dist has rendering issues with images in certain PDFs.

Issue Details:
In a PDF containing a company logo, icons, and text data, the following problems occur when displayed using ng2-pdf-viewer in the latest Firefox browser:

The company logo and icons are not rendered.
Other elements, such as text and scale bars, display correctly.
The same rendering issue occurs when using older versions of the Firefox browser to open the PDF. However, when using the current Version of Firefox in its latest version, the images (logo and icons) are displayed correctly.

Proposed Solution:
Please update the pdfjs-dist dependency to version 4.8.69 or higher to ensure compatibility with Firefox and improve image rendering reliability.

Thank you for maintaining this project!

Best regards,
Patrick

**Comment by shamoon** [comment]
This is a change request not a bug.

Unfortunately, the newest version of pdfjs breaks some stuff here so not just a simple package update.

**Comment by PatrickFrantzen** [comment]
Hi, thanks for the response.
We updated the version of pdfjs-dist in the ng2-pdf-viewer locally in our project and only had to change one type definition and the pdf viewer just runs fine. We only use the pdf-viewer to display our files, maybe therefore no breaking changes occur.

**Comment by shamoon** [comment]
I’ll check again

**Comment by shamoon** [comment]
Think I got it sorted
