### ISSUE TITLE
Text Highlight

### ISSUE THREAD

**Issue by priyabratta1991** [VadimDez/ng2-pdf-viewer#116]
Can we just add a text highlight tool to the app for highlighting the text or any annotation tool just like KAMI PDF, and save the edited pdf page?

If yes then please help me! I am working on a project and urgently require i. It would be a big help. Please!

**Comment by aaronguernsey** [comment]
This would be a cool feature. Any progress on this?

**Comment by LeandroMG** [comment]
Any progress on this cool feature?
