### ISSUE TITLE
SVG conversion issue

### ISSUE THREAD

**Issue by JDL747** [VadimDez/ng2-pdf-viewer#125]
Hi,

After the last update (1.1.4), I'm having these issues and the pdf page has a transparent background

<img width="720" alt="screen shot 2017-08-07 at 14 22 40" src="https://user-images.githubusercontent.com/3844254/29026469-285ff89e-7b7c-11e7-85bb-47a93fbdb472.png">

<img width="772" alt="screen shot 2017-08-07 at 14 25 00" src="https://user-images.githubusercontent.com/3844254/29026476-377527c8-7b7c-11e7-8bc2-15a4385fb6e7.png">

And how to remove the warning : Warning: Setting up fake worker.

Thanks for your help

**Comment by VadimDez** [comment]
Duplicate #124
