### ISSUE TITLE
Ionic - page doesn't work

### ISSUE THREAD

**Issue by Shane-Lester** [VadimDez/ng2-pdf-viewer#127]
Even with show-all = "false" and page ="page" where this.page =1, still shows all 3 pages of test pdf.

**Comment by VadimDez** [comment]
Try to use `[show-all]="false"` instead of `show-all = "false"`.

**Comment by VadimDez** [comment]
@Shane-Lester Any updates here? Do you still have the issue ?

**Comment by Shane-Lester** [comment]
Hi,
thanks for your help. Works perfectly thanks

**Comment by Shane-Lester** [comment]
Any way to pan across when zoomed in?

On 8 Aug 2017, at 19:52, Vadym Yatsyuk <notifications@github.com<mailto:notifications@github.com>> wrote:


@Shane-Lester<https://github.com/shane-lester> Any updates here? Do you still have the issue ?

**Comment by VadimDez** [comment]
@Shane-Lester see #102

**Comment by Shane-Lester** [comment]
I'm OK on vertical scroll (using a variable and binding it) but there's no horizontal scroll

On 8 Aug 2017, at 20:36, Vadym Yatsyuk <notifications@github.com<mailto:notifications@github.com>> wrote:


@Shane-Lester<https://github.com/shane-lester> see #102<https://github.com/VadimDez/ng2-pdf-viewer/issues/102>

**Comment by Shane-Lester** [comment]
I looked at your demo and when it zooms in the right side is lost. Any way to pan across to see the right side after a zoom in?

On 8 Aug 2017, at 20:36, Vadym Yatsyuk <notifications@github.com<mailto:notifications@github.com>> wrote:


@Shane-Lester<https://github.com/shane-lester> see #102<https://github.com/VadimDez/ng2-pdf-viewer/issues/102>

**Comment by VadimDez** [comment]
The right side is not lost. you can still scroll horizontally

**Comment by Shane-Lester** [comment]
No horizontal scroll bars. Vertical only. 
See screenshots- opened in Chrome using original-size toggle true and false. 
PDF is fixed to left of the container and expands off the screen.

**Comment by VadimDez** [comment]
Could you tell me what's the `zoom` value in the moment when you're not able to scroll horizontally?

**Comment by Shane-Lester** [comment]
Zoom level is shown on the images.
As soon as the images is too big for the screen it is clipped by the right edge and doesn't scroll.
The images show 2.600 zoom using your demo program on Chrome

Shane

On 9 Aug 2017, at 11:36, Vadym Yatsyuk <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you tell me what's the zoom value in the moment when you're not able to scroll horizontally?

**Comment by VadimDez** [comment]
Thanks that helps.
I can't see the images, probably because you answered through email.
