### ISSUE TITLE
ng build --prod fails for AOT

### ISSUE THREAD

**Issue by critchie** [VadimDez/ng2-pdf-viewer#130]
ERROR in .../node_modules/ng2-pdf-viewer/dist/pdf-viewer.component.d.ts.PdfViewerComponent.html (5,12): Property 'onPageResize' is private and only accessible within class 'PdfViewerComponent'.

When using AOT, methods called from the template have to be public so "private onPageResize()" does not work with AOT.

See [here](https://github.com/angular/angular-cli/issues/6108)

```
template: `
      <div class="ng2-pdf-viewer-container"
           [ngClass]="{'ng2-pdf-viewer--zoom': zoom < 1}"
           (window:resize)="onPageResize()"
      ></div>
  `,
```

```
  private onPageResize() {
    if (this.resizeTimeout) {
      clearTimeout(this.resizeTimeout);
    }

    this.resizeTimeout = setTimeout(() => {
      this.render();
    }, 100);
  }
```

**Comment by michal-filip** [comment]
Same here. Ended up downgrading to 1.1.5.

**Comment by critchie** [comment]
Works perfectly.  Thanks for the quick turn around.
