### ISSUE TITLE
s

### ISSUE THREAD

**Issue by bhupinderkumarbl** [VadimDez/ng2-pdf-viewer#131]
http://prntscr.com/g69l4c space is coming with extra character.
my code is like this
<pdf-viewer [src]="pdfSrc"
[page]="page"
[original-size]="true"
[zoom]="zoom"
[render-text]="true"
style="display: block"
[show-all]="true">

**Comment by mikelweb** [comment]
Possibly duplicate with https://github.com/VadimDez/ng2-pdf-viewer/issues/108

**Comment by VadimDez** [comment]
@bhupinderkumarbl could you provide me with the PDF that is causing the issue ? So that i can reproduce.

**Comment by bhupinderkumarbl** [comment]
https://www.sendspace.com/file/r4vbe5

**Comment by VadimDez** [comment]
@bhupinderkumarbl i've just tried in demo - https://vadimdez.github.io/ng2-pdf-viewer/  - Looks ok.

**Comment by mikelweb** [comment]
Only happens to me in Chrome, also in the pdf viewer example

**Comment by mikelweb** [comment]
https://github.com/mozilla/pdf.js/issues/8707

**Comment by mikelweb** [comment]
mozilla/pdf.js#8707 didn't solve my problem... :(
