### ISSUE TITLE
PDF not loading. Shows black color

### ISSUE THREAD

**Issue by bbshub** [VadimDez/ng2-pdf-viewer#134]
Hi,

PDF file does not loads and shows only black color. Please refer below screen shot and suggest

![image](https://user-images.githubusercontent.com/26699418/29147825-6c2de330-7d1e-11e7-818a-470438617898.png)

**Comment by VadimDez** [comment]
Could you please upload this PDF so that i can try to reproduce it?

**Comment by bbshub** [comment]
Hi Vadim,

Please refer the attached pdf
[pdf-sample.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/1215633/pdf-sample.pdf)

**Comment by VadimDez** [comment]
What version are you using ?
Tested on the demo - (version 1.2.1, https://vadimdez.github.io/ng2-pdf-viewer/) - works as expected.

**Comment by VadimDez** [comment]
Any updates here ?

**Comment by chunghha** [comment]
I have black color background issue too after upgrading from 1.1.1 to 1.2.x. I've tested every 1.2.x releases including 1.2.6 so far same issue exists. 

My case, if text color is black then it's not possible to read with black background (plz test for 2nd page). I use the pdf file linked for my test after storing it to my local file path.

![image](https://user-images.githubusercontent.com/24458075/30457271-6b507fbc-996c-11e7-990e-c4c8ad31a17a.png)


https://developer.ibm.com/digexp/wp-content/uploads/sites/27/2015/04/Developing-with-IBM-Script-Portlet-1.3.pdf

**Comment by timdoes** [comment]
I am having this same issue. Had to revert back to v1.1.3 to fix the black background issue.

**Comment by VadimDez** [comment]
fixed in 2.0.0

**Comment by chunghha** [comment]
@VadimDez, perfect. Happy to confirm it got fixed with 2.0.0 as well as the single page rotation.
