### ISSUE TITLE
pdf-viewer output options

### ISSUE THREAD

**Issue by amourinho** [VadimDez/ng2-pdf-viewer#136]
Would it be possible to render out a canvas element instead of the SVG elements that is currently being displayed? I've been fighting this issue a few days now, and I keep coming back to your library still unable to do what I need. I'm desperately trying to create an image of each page, (with a canvas to output to, it would be much easier), and then saving those images in a new PDF (with another library).

Would it be a feature you'd be interested in supporting? Different outputs of the read pdf file, blob, base64, canvas, etc?

And if no one has said it lately, thank you for maintaining this library!

**Comment by VadimDez** [comment]
To render canvas you could try to use version `1.1.3` for now

**Comment by amourinho** [comment]
Perfect, I'll have to add some features to it (scaling and whatnot), but canvas is working as I asked for. 
Still it would be a good feature to add in the future. No rush =) Thank you!

**Comment by aa-telali** [comment]
@amourinho how did you get access to the canvas? I added an issue/enhancement request #97 to allow users to save the canvas to a PNG/JPG. If you know a way, could you comment on that issue and show us how please.

Thanks!

**Comment by amourinho** [comment]
@aa-telali, Sorry for the delay in response, I just arrived home the other day. In your package.json file, make sure you're getting version 1.1.3 of ng2-pdf-viewer.

"ng2-pdf-viewer": "1.1.3"

Then create a button that will search for all canvas elements, and convert them toBlob/images. 

const pages = document.getElementsByTagName('canvas');
pages.forEach(page => {
// page.toBlob()
});

You will run into the same issue I'm facing at the time, no automatic resizing, and not able to resize the canvas for saving (higher resolution than browser width). I still hope that @VadimDez will add the ability to choose which method to display the pdf in; canvas and svg elements.

**Comment by aa-telali** [comment]
Ah, I see what you mean.

It might be better to use PhantomJS to display the page with the PDF and capture it in whatever size page you wish. That's the only thing I can think of - I haven't used PhantomJS before but that's it's biggest use (after automated testing).

**Comment by nazarsa** [comment]
To render canvas you could try to use version 1.1.3 for now

Just by using : 1.1.3 it will render in canvas only? I am finding that it works differently in different environments..some uses canvas and some svg and it is causing problems..any way to force use of canvas instead of svg? Many Thanks.
