### ISSUE TITLE
PDF from pdfmake not loading 

### ISSUE THREAD

**Issue by WolfWalter** [VadimDez/ng2-pdf-viewer#139]
I created pdfs with the pdfmake library. I was able to display them until 1.1.3 but not with the newer versions. I attached an [example.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/1231319/example.pdf). I also tried to load it in the demo page ( https://vadimdez.github.io/ng2-pdf-viewer/ ).

In the console I get an error: 

> TypeError: Cannot read property 'setAttributeNS' of undefined

I validated the pdf-files at https://www.pdf-online.com/osa/validate.aspx

**Comment by JimSangwine** [comment]
I have the same issue.
Actually one page (the 2nd) of my PDF loads, but the rest do not.
This page contains all the elements (table, text, header, footer) of the other pages, so I can't see what would be breaking it on them but not this one.

**Comment by VadimDez** [comment]
fixed in 2.0.0
