### ISSUE TITLE
Incorrect Font and Font Size Rendering

### ISSUE THREAD

**Issue by aa-telali** [VadimDez/ng2-pdf-viewer#140]
In the v1.1.4 release, the font rendering was broken.
This is still the case in the current released version v1.2.2.

I have a PDF (generated using pdf make) that uses a TTF font (yantramanav google font). If renders fine using v1.1.3 but not after that version (tested using 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.2).

A sample PDF file is attached.
[Timetable-2017-08.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/1231967/Timetable-2017-08.pdf)

Thanks for a great project!

**Comment by VadimDez** [comment]
@aa-telali do you still have the problem on version `1.2.5` ?

**Comment by jerrydeng** [comment]
I have similar issue on 1.2.5, had to revert back to 1.1.3
