### ISSUE TITLE
Mirror/Upside Down document display

### ISSUE THREAD

**Issue by shayl29** [VadimDez/ng2-pdf-viewer#141]
Hello,

Been using pdf-view for a while now and all was great. I found that in  later versions you added (error), so i updated the package to 1.2.1.
The page seems to display for some reason like a mirror.
Adding an image to back me up and help explain this:

![image](https://user-images.githubusercontent.com/30566828/29433185-ce1c6e0c-83a6-11e7-8f9f-5be60c2107cf.png)

On desktop/google drive/adobe/etc.. seems to work ok.
I tried updating to 1.2.2 but still the same.

Would like a workaround if anyone has an idea how.

p.s
only the font went that way. the image and table stayed the same.

Edit:
Changed to 1.1.3, Works great.

Thanks

**Comment by VadimDez** [comment]
fixed in 2.0.0
