### ISSUE TITLE
Error: <svg:path> attribute d: Expected moveto path command ('M' or 'm'), "L 2318.47 6033.1…".

### ISSUE THREAD

**Issue by qaznine** [VadimDez/ng2-pdf-viewer#142]
This error appears twice when I am trying to loading a 5-pages pdf.

pdf.combined.js:14422 Error: <svg:path> attribute d: Expected moveto path command ('M' or 'm'), "L 2318.47 6033.1…".
SVGGraphics_constructPath @ pdf.combined.js:14422
SVGGraphics_executeOpTree @ pdf.combined.js:14182
SVGGraphics_group @ pdf.combined.js:13990
SVGGraphics_executeOpTree @ pdf.combined.js:14188
SVGGraphics_group @ pdf.combined.js:13990
SVGGraphics_executeOpTree @ pdf.combined.js:14188
(anonymous) @ pdf.combined.js:14034
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:141
(anonymous) @ zone.js:831
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
onInvokeTask @ core.es5.js:3881
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:191
drainMicroTaskQueue @ zone.js:595
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
ZoneTask.invoke @ zone.js:487
timer @ zone.js:1829

**Comment by 007imash** [comment]
I am also getting the same error...any idea what is causing this? started getting this today 23/08

**Comment by VadimDez** [comment]
fixed in 2.0.0
