### ISSUE TITLE
Issue since update from 1.1.1 to 1.2.1 and not fixed in 1.2.2

### ISSUE THREAD

**Issue by xonuzofa** [VadimDez/ng2-pdf-viewer#145]
This problem was not present in 1.1.1 and have not changed any code just updated the packages.  I am getting weird fonts on the pdfs and sometimes weird characters.  Here is a screenshot.

<img width="590" alt="screen shot 2017-08-23 at 9 28 46 pm" src="https://user-images.githubusercontent.com/2785016/29646678-84167a34-884a-11e7-9afa-e8077f49c684.png">

Why is it changing the font to look like this?  How can i fix this?

**Comment by xonuzofa** [comment]
Another example

<img width="636" alt="screen shot 2017-08-23 at 9 34 28 pm" src="https://user-images.githubusercontent.com/2785016/29646749-e82ed9a8-884a-11e7-8725-6cc867ec70ac.png">

**Comment by VadimDez** [comment]
@xonuzofa could you attach the pdf ?

**Comment by xonuzofa** [comment]
[G5S CenXan3500 Label.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/1270927/G5S.CenXan3500.Label.pdf)

**Comment by xonuzofa** [comment]
Looks like this:

![image](https://user-images.githubusercontent.com/2785016/29979449-20ea5256-8f0b-11e7-8d83-1a923c1127a2.png)

**Comment by VadimDez** [comment]
Do you still have the issue with version `1.2.5` ?
Just tested on https://vadimdez.github.io/ng2-pdf-viewer/ and it works fine.

**Comment by xonuzofa** [comment]
Will try in a few hours thanks bud.

**Comment by xonuzofa** [comment]
Still have the same issue, still blacked out like that.

**Comment by VadimDez** [comment]
fixed in 2.0.0

**Comment by xonuzofa** [comment]
Yes it is, thank you!
