### ISSUE TITLE
Is it possible to reduce size of production code? This library takes about 1.5 MB when compiled, and the module using it is only 200kb.

### ISSUE THREAD

**Issue by jackli199311** [VadimDez/ng2-pdf-viewer#146]
In my project I'm using lazy loading with AOT. The compiled chunk of code that contains ng2-pdf-viewer is about 1.8MB, and if I take out the library it's only around 200kb. Is there a way to reduce the size of the compiled code? I do notice inside pdfjs-dist, there is a pdf.combined.js(1.6MB) and a pdf.min.js(219kb). How are they different? Can the use of pdf.min.js reduce the compiled size of this library? Any help will be greatly appreciated. Thanks!

**Comment by VadimDez** [comment]
released under version `1.2.3`

**Comment by tomaskunder** [comment]
Hi, I've got this error on my project when using the current version, seems related to the min version of pdf.js
`Uncaught ReferenceError: Invalid left-hand side in assignment`

**Comment by VadimDez** [comment]
@tomaskunder see #150
