### ISSUE TITLE
GET http://localhost:4200/nullUniGB-UCS2-H 404 (Not Found)

### ISSUE THREAD

**Issue by missingeverytime** [VadimDez/ng2-pdf-viewer#147]
Hi,

I have got an error about `UniGB-UCS2-H `, which caused some characters disappear. 
![2017-08-25 4 23 07](https://user-images.githubusercontent.com/16895572/29705752-001ea1b6-89b2-11e7-9e79-1f5dc914022a.png)
The web page shows like the picture below.
![2017-08-25 4 24 33](https://user-images.githubusercontent.com/16895572/29705770-18120e7a-89b2-11e7-9620-1f2110af6f28.png)
But actually it should be like this.
![2017-08-25 4 24 46](https://user-images.githubusercontent.com/16895572/29705803-35d7ba90-89b2-11e7-8eb2-90c713a88ea4.png)

In this document, it blocks all Chinese Characters. However, it only happened on some special PDF documents.

Has anyone met this issue before? or Any solutions?

Thanks,

Steven Li

**Comment by VadimDez** [comment]
Can you try version `1.1.3`? How does it work there ?

**Comment by missingeverytime** [comment]
Thanks, @VadimDez . Still no luck with the version `1.1.3`.
I also tried `1.2.2` and `1.1.1`, which does not work either.

**Comment by VadimDez** [comment]
fixed in 2.0.0
