### ISSUE TITLE
Error : Cannot read property 'getPage' of undefined

### ISSUE THREAD

**Issue by soyiatgit** [VadimDez/ng2-pdf-viewer#148]
I keep getting the following error while page rendering:

`ERROR TypeError: Cannot read property 'getPage' of undefined
    at PdfViewerComponent.webpackJsonp.../../../../ng2-pdf-viewer/dist/pdf-viewer.component.js.PdfViewerComponent.renderPage (pdf-viewer.component.js:142)
    at PdfViewerComponent.webpackJsonp.../../../../ng2-pdf-viewer/dist/pdf-viewer.component.js.PdfViewerComponent.render (pdf-viewer.component.js:118)
    at pdf-viewer.component.js:91
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:192)
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:499)
    at ZoneTask.invoke (zone.js:488)
    at timer (zone.js:1896)`

Although, the pages can still be rendered. I debugged and found the issue to be in the following block:

`PdfViewerComponent.prototype.renderPage = function (pageNumber) {
        var _this = this;
        return this._pdf.getPage(pageNumber).then(function (page) {
            var viewport = page.getViewport(_this._zoom, _this._rotation);
            var container = _this.element.nativeElement.querySelector('div');
            if (!_this._originalSize) {
                viewport = page.getViewport(_this.element.nativeElement.offsetWidth / viewport.width, _this._rotation);
            }
            if (!_this._showAll) {
                _this.removeAllChildNodes(container);
            }
            return page.getOperatorList().then(function (opList) {
                var svgGfx = new PDFJS.SVGGraphics(page.commonObjs, page.objs);
                return svgGfx.getSVG(opList, viewport).then(function (svg) {
                    var $div = document.createElement('div');
                    $div.classList.add('page');
                    $div.setAttribute('data-page-number', "" + page.pageNumber);
                    $div.appendChild(svg);
                    container.appendChild($div);
                });
            });
        });
    };`

this._pdf doesn't contain getPages() method. Any suggestions ?

**Comment by vincent-cm** [comment]
same here

Cannot read property 'getPage' of undefined
    at PdfViewerComponent.renderPage (http://0.0.0.0:8080/main.bundle.js:278179:26)
    at render (http://0.0.0.0:8080/main.bundle.js:278166:19)
    at PdfViewerComponent.renderMultiplePages (http://0.0.0.0:8080/main.bundle.js:278172:9)
    at PdfViewerComponent.render (http://0.0.0.0:8080/main.bundle.js:278158:18)
    at http://0.0.0.0:8080/main.bundle.js:278128:19

**Comment by VadimDez** [comment]
Are you using ng-cli?

**Comment by soyiatgit** [comment]
Yes..I am..

**Comment by VadimDez** [comment]
Did you set `[show-all]` to `false` ? If so make sure that `[page]` is not null.
Let me know if that fixes your problem.

**Comment by ShoaibIqbal452** [comment]
Same issue here. Same error message.I don't know what is wrong! It was working fine. But suddenly it started giving this exception! Please tell if anyone has workaround for this. That would be a great help.

**Comment by VadimDez** [comment]
@ShoaibIqbal452 have you tried to run `npm update` and see if it helps ?

**Comment by ShoaibIqbal452** [comment]
Thanks alot @VadimDez. You are just saved me. It is working fine now after npm update. How often should I update my modules?

**Comment by VadimDez** [comment]
seems like `npm update` fixes the problem

**Comment by sudiptosen** [comment]
Thanks for the fix. I was on 1.2.6, now it got 1.2.7

**Comment by shivatejabluesilica** [comment]
after npm update also same issue here

**Comment by yakhiramesh090** [comment]
npm update did not  work  still throwing same error
![image](https://user-images.githubusercontent.com/24190811/31307427-09f83bf6-ab82-11e7-871b-8e81591577da.png)

**Comment by nazarsa** [comment]
Same here, even after npm update..it is very erratic , random and completely blocking the pdf rendering..

main.bundle.js:1376 ERROR TypeError: Cannot read property 'getPage' of undefined
    at PdfViewerComponent.renderPage (main.bundle.js:83077)
    at PdfViewerComponent.render (main.bundle.js:83053)
    at main.bundle.js:83026
    at ZoneDelegate.invokeTask (main.bundle.js:50006)
    at Object.onInvokeTask (main.bundle.js:4237)
    at ZoneDelegate.invokeTask (main.bundle.js:50005)
    at Zone.runTask (main.bundle.js:49773)
    at ZoneTask.invokeTask (main.bundle.js:50080)
    at ZoneTask.invoke (main.bundle.js:50069)
    at timer (main.bundle.js:51621)

**Comment by ddyrcz** [comment]
Same here, update to **ng2-pdf-viewer@2.0.2** resolved the problem for me

**Comment by lievenvg** [comment]
Is there a solution found for this problem?
I am using v2.0.2 and sometimes it works and other times I get the 'ERROR TypeError:' message.

**Comment by yakhiramesh090** [comment]
after npm update only it started to throw error .
but we changed it old version "ng2-pdf-viewer": "0.0.13",
and now its working without any errors

**Comment by TriangleJuice** [comment]
@VadimDez Please reopen this issue, it is not fixed in 2.0.2.

**Comment by VadimDez** [comment]
Can somebody provide me with a scenario to reproduce this error ?
Does this error appears during development or prod ?
Do you use AOT or not ?

**Comment by TriangleJuice** [comment]
The error appears sometimes during development, sometimes during production, … it's completely random. The best way to reproduce this error is having a slower backend, meaning: the error appears more often when you have to wait a second or two to get your data. I can see the PDF appear in my Network tab, but the ng2-pdf-viewer plugin keeps showing me a spinner, instead of rendering the PDF. Hope these limited reproduction steps help.

**Comment by EricBPower** [comment]
We were getting this on the latest version, however I found that adding an ngIf condition on the pdf-viewer component solved the problem for us because it postponed the rending of the pdf-viewer tag until AFTER the object that I was using for the [src] attribute was ready.  

`   public setResumePdfInline(profileId: string, profileName: string, resumeId: string, resumeDocumentId: string) {
      const filenameOverride = encodeURI(DownloadFilename.setupResumePdfFileName(profileName));
      if (resumeId && resumeDocumentId) {
         const urlText =
            // tslint:disable-next-line:max-line-length
            `profiles/${profileId}/resumes/${resumeId}/pdf?documentId=${resumeDocumentId}&filenameOverride=${filenameOverride}&profileName=${encodeURI(profileName ? profileName : 'Unknown Candidate')}`;
         const url = this.urlService.getApiUrl(urlText);

         const responseContentType = 'application/pdf';
         const requestHeaders = new Headers();
         requestHeaders.append('Accept', responseContentType);
         this.resumePdfViewerObject = {
            url: url,
            withCredentials: true,
            httpHeaders: {
               'Authorization': this.authToken,
               'Accept': 'application/pdf'
            }
         };
         this.promiseComplete = true;
      }
   }`

`<pdf-viewer *ngIf="promiseComplete"
                  [src]="resumePdfViewerObject"
                  [page]="page"
                  [zoom]="zoom"
                  [rotation]="0"
                  [render-text]="true"
                  [show-all]="showAll"
                  style="overflow-x: auto;"
                  [original-size]="originalSize"
                  (after-load-complete)="onLoadComplete($event)">
      </pdf-viewer>`

**Comment by Shafil** [comment]
same issue..Not able to view the document...getpage error.

**Comment by Shafil** [comment]
Solved by adding this condition check Object.keys(this._PDF).length>0 in page changed function

**Comment by wkarras** [comment]
Any updates on this? I still get the error in the console, but then my pdf proceeds to render.

**Comment by cetv26** [comment]
I change version of webpack to 2.4.1
