### ISSUE TITLE
Failed to execute 'postMessage' on 'Worker'

### ISSUE THREAD

**Issue by TcQPAD** [VadimDez/ng2-pdf-viewer#153]
Hello,

I recently installed pdf-viewer library in my application. 
I have a MEAN stack with a back-end making my Angular 2 application download PDF files. Everything works fine until the URL of the PDF is defined in Angular.

I'm doing: 

```
this.documentsManagementService.downloadDocument(this.document._id).subscribe(blobContent => {
        this.fileURL = URL.createObjectURL(blobContent);
        console.log(this.fileURL);
      }
);
```

and it prints in the console: `blob:http://localhost:4200/cc8faf08-22c0-4b41-bb99-71d37eddfa76`

My HTML looks like this: 

```
<pdf-viewer *ngIf="fileURL"
              [src]="fileURL"
              [original-size]="true"
              style="display: block;">
  </pdf-viewer>
```

When my code reaches the line  `this.fileURL = URL.createObjectURL(blobContent);`, I get an error:

![capture](https://user-images.githubusercontent.com/17066590/30063782-0543268e-9250-11e7-98cc-5d39169deece.PNG)

I've looked at some StackOverflow posts, but I can't seem to find any answer that would fix my problem.

**Comment by VadimDez** [comment]
Can you try this ?
```js
this.documentsManagementService.downloadDocument(this.document._id)
  .subscribe(blobContent => {
    this.fileURL = new Uint8Array(blobContent.arrayBuffer());
  });
```

**Comment by TcQPAD** [comment]
It's working with your solution! 
Thank you! 👍

**Comment by Anujmoglix** [comment]
I am also getting error. my code is 
```
 <pdf-viewer [src]="'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'"
                                 [render-text]="true"
                                 style="display: block;"
                     ></pdf-viewer>
```

getting Error 

> ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Worker': TypeError: Failed to fetch could not be cloned.
> >

**Comment by alamgirqazi** [comment]
> I am also getting error. my code is
> 
> ```
>  <pdf-viewer [src]="'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'"
>                                  [render-text]="true"
>                                  style="display: block;"
>                      ></pdf-viewer>
> ```
> getting Error
> 
> > ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Worker': TypeError: Failed to fetch could not be cloned.
> > >

Did you find a fix?

**Comment by tkssharma** [comment]
any solution on this ?? getting the same error 


```
<pdf-viewer [src]="pdfSrc" [render-text]="false" style="display: block; max-width: 100%;" (after-load-complete)="afterLoadComplete($event)"
        (on-progress)="onProgress($event)" (error)="onError($event)"></pdf-viewer>
```
pdfSrc is a s3 url
```
    this.userRegisterService.getTermsAndConditions(request).subscribe((res) => {
      this.loading = false;
      if (res.success && res.data) {
        this.pdfSrc = res.data.current_version;
        this.pdfSrcId = res.data.id;
      }
    }, () => {
      this.loading = false;
      this.pdfSrc = '';
    });
```

**Comment by TcQPAD** [comment]
Did you try VadimDez's solution? It fixed the problem for me. If it ain't for you, I think you should open a new issue since this one was closed (and probably unsubscribed) by the owner of the repo.
