### ISSUE TITLE
Multiple display issues on Safari (iOS+Desktop)

### ISSUE THREAD

**Issue by LukasKlement** [VadimDez/ng2-pdf-viewer#154]
I'm experiencing multiple issues with the PDF preview on Safari (iOS + desktop). Embedded fonts are not used, borders appear for borderless tables, the colour of a single elements overlays the entire page, etc.

I have uploaded a PDF to illustrate the issue (font not embedded, borders shown). The in-built browser preview renders the PDF correctly, ng2-pdf-viewer does not: https://assets.menutech.com/menu.pdf

**Comment by VadimDez** [comment]
fixed in 2.0.0
