### ISSUE TITLE
Chrome error: Invalid SVG dimensions when 'original-size' = false

### ISSUE THREAD

**Issue by RichardBosworth** [VadimDez/ng2-pdf-viewer#156]
Hi,

When using the PDF viewer with Chrome, and when setting [original-size]="false", the PDF is not displayed and Chrome gives the error: Error: Uncaught (in promise): Error: Invalid SVG dimensions.

The same code works on other browsers.

Is there a way I can resolve this?

Thanks!

**Comment by codetinker** [comment]
I had exactly same problem. Looking for solution to set pdf max size of container.
If anyone has work around, please post here.

**Comment by sdornan** [comment]
Also having this issue.

**Comment by vincent-cm** [comment]
same

**Comment by HugzM** [comment]
I have the same issue on all web browsers

**Comment by Gianlu82b19** [comment]
yep same here

**Comment by VadimDez** [comment]
fixed in 2.0.0
