### ISSUE TITLE
Cannot Open Local File pdf in Ionic 2

### ISSUE THREAD

**Issue by tunathoni** [VadimDez/ng2-pdf-viewer#157]
Hello,

Sorry i want to ask about my issue, i already run with `ionic serve` and i try to open local pdf file, it can work properly, but after i try to check in www/ folder especially on index.html, just clicked it once, show in browser, but file is not loaded and show an error like this : 

> Fetch API cannot load file:///Users/toni/Documents/myApp/www/assets/files/test.pdf. URL scheme must be "http" or "https" for CORS request.

So can you help me to solve this issue ? thanks.

**Comment by tristian-me** [comment]
The problem with this is the version of PDFJS-dist that is being used. NPM seems to ignore the pdfjs-dist version in package.json and installs version 1.9.

A quick work around:
`npm install pdfjs-dist@1.6.329` and check your __package.json__ to version _1.6.329_.

**Comment by VadimDez** [comment]
See method `onFileSelected()` - this is how you can load local pdfs
https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/app.component.ts#L52-L64

**Comment by Yashrad** [comment]
Im getting the same error.
I generate a pdf file and write it to the device dataDirectory , and get the same error trying to set the pdf Source. downgrading pdfjs-dist didnt help as well.

**Comment by tristian-me** [comment]
Hi




Remove the NPM package lock, node_modules and run `npm install ng2-pdf-viewer@1.0.2`. Hopefully that helps. 






On Thu, Oct 19, 2017 at 4:44 PM +0100, "Yashrad" <notifications@github.com> wrote:












Im getting the same error.

I generate a pdf file and write it to the device dataDirectory , and get the same error trying to set the pdf Source. downgrading pdfjs-dist didnt help as well.

**Comment by phpepe** [comment]
Is there a solution for this issue ?
Im using ng2-pdf-viewer v5.0.1 and still getting this error: 

`"Fetch API cannot load file:///data/user/0/MY_APP/files/MY_FILE.pdf. URL scheme "file" is not supported.`

My use case is try to view previously 'downloaded' pdfs on a ionic3 app
Tried other libs like pdfjs and no luck.

Any help would be appreciated
Thanks

**Comment by db-conception** [comment]
Hi, How to resolve the problem ? 
I get this message : 
`polyfills-es2015.js:5958` Access to XMLHttpRequest at 'file:///data/user/0/io.ionic.starter/www/doc/13.pdf' from origin 'http://localhost' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, https."``

**Comment by tristian-me** [comment]
If your having issues it's because of a the new versions of PDFjs library supplied by Mozilla.

Try working with version 1.0.2: `ng2-pdf-viewer@1.0.2`

Hopefully this will help.

**Comment by shoebs115** [comment]
> Hello,
> 
> Sorry i want to ask about my issue, i already run with `ionic serve` and i try to open local pdf file, it can work properly, but after i try to check in www/ folder especially on index.html, just clicked it once, show in browser, but file is not loaded and show an error like this :
> 
> > Fetch API cannot load file:///Users/toni/Documents/myApp/www/assets/files/test.pdf. URL scheme must be "http" or "https" for CORS request.
> 
> So can you help me to solve this issue ? thanks.

You can not open PDF file directly, first you will need to convert it to ArrayBuffer

Yo can check the solution [here](https://stackoverflow.com/questions/50255369/unable-to-view-local-pdf-file-in-ionic-app-using-ng2-pdf-viewer)
