### ISSUE TITLE
'initialPage' since it isn't a known property of 'pdf-viewer'.

### ISSUE THREAD

**Issue by jairoGilC** [VadimDez/ng2-pdf-viewer#16]
I import the library and use the HTML example, but get the following error

	Can't bind to 'initialPage' since it isn't a known property of 'pdf-viewer'.
	1. If 'pdf-viewer' is an Angular component and it has 'initialPage' input, then verify that it is part of this module.
	2. If 'pdf-viewer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
	 ("
	  </div>
	  <pdf-viewer [src]="pdfSrc" 
	              [ERROR ->][initialPage]="page" 
	              [original-size]="true" 
	              style="display: block;">

Search in the code effectively this property does not exist, is a error in the documentation?

**Comment by VadimDez** [comment]
@jairoGilC, Thanks, you're right, "initialPage" was renamed to "page". I forgot to update documentation, will do it immediately.
