### ISSUE TITLE
some pdf showing in invert color

### ISSUE THREAD

**Issue by hunkxxyy** [VadimDez/ng2-pdf-viewer#160]
Some fpdf files showing invert color. When I open this file in any pdfviewer is showing as it should be, but when I open the file with ng2-pdf-viewer the result is inverted
Can you give me any advice

**Comment by richlim** [comment]
The same issue :| 
The document is rendered correctly in a canvas (pdfjs examples).
[2017_09_22_15_16_23.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/1324695/2017_09_22_15_16_23.pdf)

**Comment by abadr82** [comment]
The Same issue here !!!
I tried differents PDFs, but some files shows with invert color

**Comment by richlim** [comment]
Well, I have another problem: some PDFs get rendered quite crasy.
I switched to a combination of iframe + built-in pdf viewer, with no problems at all :)

**Comment by VadimDez** [comment]
fixed in 2.0.0
