### ISSUE TITLE
ng2-pdf-viewer CORS

### ISSUE THREAD

**Issue by mathisGarberg** [VadimDez/ng2-pdf-viewer#161]
I'm developing an Angular application that needs to display PDF files. To achieve this, I'm currenty using the [ng2-pdf-viewer][1] component. The component works fine for files like:

- https://www.tutorialspoint.com/angular2/angular2_tutorial.pdf

I do however run into CORS-issues with files like:

- https://frontendmasters.com/assets/resources/lukasruebbelke/better-apps-angular-2-day1.pdf

The error message I receive:

Failed to load http://frontendmasters.com/assets/resources/lukasruebbelke/better-apps-angular-2-day1.pdf: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

core.es5.js:1020 ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Worker': TypeError: Failed to fetch could not be cloned. Error: Failed to execute 'postMessage' on 'Worker': TypeError: Failed to fetch could not be cloned.

**My Code**

component.html
`<pdf-viewer
    [src]="document.url.url"
    [page]="1"
    [original-size]="false"
    style="display: block;">
  </pdf-viewer>`

component.ts
`document = {
name: 'Angular 2',
description: 'An amazing Angular 2 pdf',
url: {
  url: 'https://frontendmasters.com/assets/resources/lukasruebbelke/better-apps-angular-2-day1.pdf',
  withCredentials: true
  }
}`

If you want me to provide any additional information, please let me know.

**Comment by MiguelGonzalezAravena** [comment]
I have the same issue for read PDF documents in a server with CORS enabled in Apache (Modules enabled required for CORS: mod_rewrite, mod_headers) What can i do for view the files?

**Comment by VadimDez** [comment]
As starting point seems like `frontendmasters.com` does not support `OPTIONS` request


```
OPTIONS https://frontendmasters.com/assets/resources/lukasruebbelke/better-apps-angular-2-day1.pdf
```
returns
```
405 Not Allowed
```

**Comment by septst** [comment]
Hello,

I am also facing the same issue, But, in my case, I am trying to open a PDF document from a sharepoint site.

this.pdfSrc = {
            url: "http://Mysharepoint/Global_PDF_V11.pdf",
            withCredentials: true};

<pdf-viewer [src]="pdfSrc" [render-text]="true" style="display: block;"></pdf-viewer>

Am I doing anything wrong?

Thanks in advance

PS

**Comment by alexdragneel** [comment]
Hello,

Same thing for me, I try to upload pdf on Firebase Storage or on my own server and I just get the DataCloneError. But with the test pdf or pdf on ParseServer it's work.

Thanks

**Comment by tombalcaen** [comment]
@alexdragneel Did you manage to find a solution? I'm experiencing the same with Firebase Storage

**Comment by alexdragneel** [comment]
@tombalcaen Unfortunately no, I was waiting to see if someone had a solution but otherwise we will have to find a trick or an other solution.

**Comment by tombalcaen** [comment]
@alexdragneel So I found a solution. 
I had to configure the cloud storage bucket. This [link](https://cloud.google.com/storage/docs/gsutil_install) will guide you. 

It will guide you to install gsutil (command line tool) and configure the bucket where you need to change the permissions. 

After you completed the installation. configure the CORS like this..
make a cors.json file. and copy paste this json snippet.

[
  {
    "origin": ["*"],
    "method": ["GET"],
    "maxAgeSeconds": 3600
  }
]

after in the command line tool where you installed gsutil use this command: 
`gsutil cors set cors.json gs://<your-cloud-storage-bucket>`

Hope it works!

**Comment by alexdragneel** [comment]
@tombalcaen It's a bit long but you found the trick bravo ! :D

**Comment by VadimDez** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr

**Comment by MrSparklle** [comment]
If you don't want to install the util, a handy way is to go to `console.cloud.google.com/home` and click “**Activate Google Cloud Shell**” icon in the top right. 

This will open a shell with gsutil already installed, and with access to your firebase storage projects. 

In the shell i used pico or nano to create a json. 
Then did the `gsutil cors set cors.json gs://projectname.appspot.com` as mentioned above

**Comment by gxg10** [comment]
i don't know if this issue is still opened but i have a similar problem. 

I have an angular app with a spring backend. 
The app uses JWT authentication so every request to the backend uses an authentication header. When i whitelist my /download/file.pdf route, everything is ok. 

When i set that any request must my authenticated, when i use src = 'http://localhost:8080/download/file.pdf" i have an "Unauthorized error. Message - Full authentication is required to access this resource".
i use src = {
    url: 'http://localhost:8080/download/file.pdf',
    withCredentials: true
   }; and i get a 404 with ccess to fetch at 'http://localhost:8080/download/file.pdf' from origin 'http://localhost:4200' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
In my spring controller i have @CrossOrigin(origins = "http://localhost:4200")

**Comment by marmik18** [comment]
> If you don't want to install the util, a handy way is to go to `console.cloud.google.com/home` and click “**Activate Google Cloud Shell**” icon in the top right.
> 
> This will open a shell with gsutil already installed, and with access to your firebase storage projects.
> 
> In the shell i used pico or nano to create a json.
> Then did the `gsutil cors set cors.json gs://projectname.appspot.com` as mentioned above

Thank you so much this helped me alot

**Comment by ngoahamos** [comment]
so if you still have problem with CORS, i simply used the object tag, and it's working for me
```html
<object [data]="url + '#toolbar=0&navpanes=0' | safeUrl" type="application/pdf" width="100%" height="600px"></object>
```
use the ``` #toolbar=0&navpanes=0 ``` if you want to disable the toolbar.

i also have a simple pipe ```safeUrl``` to deal with XSS
```javascript
import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

@Pipe({
  name: 'safeUrl',
})
export class SafeUrlPipe implements PipeTransform {
  constructor(private sanitized: DomSanitizer) {}
  transform(value) {
    return this.sanitized.bypassSecurityTrustResourceUrl(value);
  }
}
```

**Comment by williambechard** [comment]
@ngoahamos This solution worked well for me, thanks!

**Comment by Kumaravel-datacaliper** [comment]
@ngoahamos But Object tag is slower for larger files
