### ISSUE TITLE
Worker Source

### ISSUE THREAD

**Issue by leonardosalles** [VadimDez/ng2-pdf-viewer#162]
Hi,

I am trying to use the PDFJS.workerSrc with a local file, is it allowed or PDF.js load files from Mozilla?

**Comment by VadimDez** [comment]
For now *(since 2.0.0)* it's loaded from the CDN

**Comment by leonardosalles** [comment]
No problem, I created a local fork of the component and then changed the worker source to a local file, feel free if you want to close this issue or if you want to leave it open as enhancement. Thanks @VadimDez ;)

**Comment by VadimDez** [comment]
I think it make sense to add this as a feature, so that everyone can change location of the worker.
