### ISSUE TITLE
Web pack error 

### ISSUE THREAD

**Issue by eyaconsulting** [VadimDez/ng2-pdf-viewer#163]
I have integrated your code in my project webpack based i have many error 👍 
**Cannot find name 'PDFDocumentProxy'**
 Cannot find name 'PDFSource'

thanks

**Comment by VadimDez** [comment]
how did you integrated it ?

**Comment by eyaconsulting** [comment]
I have copied your code pdf-viewer folder and called as you have doing .

**Comment by VadimDez** [comment]
Use `npm` to install this package instead, take a look here https://github.com/VadimDez/ng2-pdf-viewer
see the `Install` and `Usage` parts.
