### ISSUE TITLE
Error directive not executed when 404

### ISSUE THREAD

**Issue by LordPinhead** [VadimDez/ng2-pdf-viewer#166]
Hi,

when i try to load and pdf from an wrong URL, lets say "http://localhost:4200/assets/i_do-not-exist.pdf", the error directive would not execute. 

In the documentation, the (error) event should be executed. Is there a solution or a try-catch i could use? 

regards

**Comment by quentinmachard-niji** [comment]
@LordPinhead you have some news ?

**Comment by VadimDez** [comment]
@quentinmachard-niji do you still have this issue?
Could you please show me the steps to reproduce it?

**Comment by LiuuY** [comment]
@VadimDez 

https://embed.plnkr.co/vso01d/

👆

When loading pdf from a wrong URL, ie, got an HTTP 404, the (error) event should be executed.

**Comment by VadimDez** [comment]
@LiuuY i've just tried your example, `error` is fired and `handleError()` is executed.

**Comment by LiuuY** [comment]
@VadimDez  Thanks for your reply, I use Chrome Version 65.0.3325.162, the error is not fired, but Firefox 58.0.1 the error event is fired.
