### ISSUE TITLE
using the default app to open pdf, not the html template

### ISSUE THREAD

**Issue by erickrar** [VadimDez/ng2-pdf-viewer#169]
Hi, 
I'm generating a PDF and saving on the mobile app. When i click to view the pdf, its using a default pdf app viewer, not the HTML template...

The HTML code is
````
<ion-header>
    <ion-navbar>
      <ion-title>My PDF</ion-title>
    </ion-navbar>
  </ion-header>

  <ion-content padding>
    <divstyle="display: block;">
      <pdf-viewer src=" {{srcPDF}} " original-size="false"  ></pdf-viewer>
    </divstyle>
</ion-content>
````

And the JS is only:
```
 constructor(public navCtrl: NavController, 
        public navParams: NavParams,
...
 this.srcPDF = this.navParams.get("srcPDF");
  }
```

I need to show the pdf and my navbar..

**Comment by VadimDez** [comment]
What do you mean by `"When i click to view the pdf"`? You probably navigating to the PDF itself, instead of navigation to the view with a `pdf-viewer` component.
