### ISSUE TITLE
Update to Angular 2 Final release

### ISSUE THREAD

**Issue by sireneweb** [VadimDez/ng2-pdf-viewer#17]
Hi, could you update to be compatible with last angular2 version ?

**Comment by VadimDez** [comment]
Hi, @sireneweb, it should be already updated,
it has angular 2.0.0 as peer dependency
```
"peerDependencies": {
    "@angular/core": "^2.0.0",
    "pdfjs-dist": "^1.5.470"
  }
```

What version of pdf viewer are you using ? Do you get any warnings with npm?

**Comment by sireneweb** [comment]
Great news :)  i'm using visual studio.
