### ISSUE TITLE
AOT compile issue

### ISSUE THREAD

**Issue by DHFW** [VadimDez/ng2-pdf-viewer#171]
ERROR in ng:///.../node_modules/ng2-pdf-viewer/dist/pdf-viewer.component.d.ts.PdfViewerComponent.html (2,39): Supplied parameters do not match any signature of call target.

In version 2.0.0

**Comment by smasherprog** [comment]
same here.. I had to revert the previous version

**Comment by smasherprog** [comment]
Cooll thanks Vadimez!
