### ISSUE TITLE
2.0.1 no more scrollbar while zooming

### ISSUE THREAD

**Issue by Gianlu82b19** [VadimDez/ng2-pdf-viewer#174]
`  <mat-card-content style="width:1000px;height:700px;">
          <pdf-viewer [src]="pdfSrc" [page]="page" [rotation]="0" [zoom]="**1.5**" [original-size]="false" [show-all]="false" style="display:block;"></pdf-viewer>
        </mat-card-content>`

with the new version scrollbars doesn't appear and the pdf-viewer is now bigger than the area wich contain it

**Comment by shoaibakhtar26** [comment]
@Gianlu82b19 you can add scroll bars by css. Set `overflow-y:scroll` for vertical scrollbar and ` overflow-x:scroll;` for horizontal scroll bar

**Comment by Gianlu82b19** [comment]
Thanks it works. For some reason I had no problem in the in the older version (1.2.7)

**Comment by b4z81** [comment]
.pdfViewer {
    max-height: 700px;  /* change height value */
    overflow-y: scroll;
}

**Comment by koo9** [comment]
@b4z81 don't seem to do the trick. the viewer still display the full pdf page height
