### ISSUE TITLE
Doesn't shows page after update package

### ISSUE THREAD

**Issue by Lusinia** [VadimDez/ng2-pdf-viewer#175]
Hi, everyone. I have a small issue with the viewer. Last week I installed it to my project and it worked well, but today I have opened the app and see the blank page. Div  'ng2-pdf-viewer-container' is empty and there is no one error in console. I don't understand why it doesn't work. Please, can you help me?
Code:
   <pdf-viewer
      [src]="pageSrc"
      [original-size]="false"
      [show-all]="true"
      [render-text]="true"
       style="display: block;"
    ></pdf-viewer>

**Comment by VadimDez** [comment]
what version are you using ? Try to update to the latest.

**Comment by cbjerg** [comment]
I have kind of the same problem. The pdf is not rendered on screen in CHROME only - the code is there in the element browser. On Firefox it works as it used to.
```

  <pdf-viewer 
  [src]="pdfSrc"
  [page]="page"
  [original-size]="true"
  [render-text]="false"
  style="display: block;"
  [show-all]="true"
  (after-load-complete)="callBackFn($event)"
  >
  </pdf-viewer>
```

**Comment by VadimDez** [comment]
@Lusinia any updates?

**Comment by tarekis** [comment]
@VadimDez I think I have the same issue, console throws no error, I previously got https://github.com/VadimDez/ng2-pdf-viewer/issues/201, but somehow managed to get it to "work", only to get blank pages. The PDF starts loading as soon as you start scrolling horizontally. What's very weird is, that this happens with certain CSS styles on the demo page too. I am on 3.0.2 with this config:

    <pdf-viewer
        [zoom]="1"
        [src]="pdfSrc"
        [original-size]="true"
        [fit-to-page]="true"
        [render-text]="true"
        [autoresize]="true"
        [show-all]="true"
        (mouseup)="onMouseUp($event)"
    ></pdf-viewer>

You can reproduce the loading error by adding this code to the pdf-viewer tag:


    width: 50%;
    height: 800px;
    overflow: auto;

**Comment by tarekis** [comment]
My issue might be a different one, I managed to get an error log now caused by this line setting zoom to 0, which is invalid for the PDF-Viewer.
https://github.com/VadimDez/ng2-pdf-viewer/commit/94774abe83f10e499b970a0906773285ee5a1bc4#diff-d7bcc7e48ba912922efa3d4a76c41484R425

Throws `PDFViewer._setScale: "0" is an unknown zoom value.`.
@Lusinia can you reproduce this error log or is this an entierly different one?

**Comment by tarekis** [comment]
@VadimDez The loading spinner issue is a different one, for which I opened another issue: https://github.com/VadimDez/ng2-pdf-viewer/issues/219. However, my previous comment very probably refers to this issue.
