### ISSUE TITLE
Original size

### ISSUE THREAD

**Issue by erata** [VadimDez/ng2-pdf-viewer#177]
hi, i passed to last version (from 1.1.3 to ng2-pdf-viewer 2.0.2 ). normally A4 page size as 595x841 but at last version i see the same page as 794x1123 (which equals 1.3 X normal size). 

> original-size = "true" 

both of them.

how can show as 595x841 with 2.0.2 version.

when i add  some stamps on pdf (backend) and then  show it with pdf-viewer new sizes are 560X794

thanks.

**Comment by erata** [comment]
hi, is there a way to show pdf in normal size. Otherwise I will have to go back to 1.1.3 version

**Comment by erata** [comment]
[original-size]="true" or [original-size]="false" did not trigger size. got 794x1123 bot of them

**Comment by VadimDez** [comment]
it may depend on your container size as well.
`[original-size]` should work because if works here https://vadimdez.github.io/ng2-pdf-viewer/

**Comment by erata** [comment]
i test [sample pdf file](http://ncu.rcnpv.com.tw/Uploads/20131231103232738561744.pdf) at the adress https://vadimdez.github.io/ng2-pdf-viewer/ and my locale it gives both "width: 816px; height: 1056px". i also tried some other pdf files and i get same results both given address and my locale. 

The problem is that shown sizes are bigger than i estimate in version 2.0.2. because standart A4 sizes are 595X842 and i use A4 file, but it showed 794X1123. 

is it related ppi? when i look at http://www.papersizes.org/a-sizes-in-pixels.htm i see that:
A4 page with 72 PPI: 
![72 ppi](https://user-images.githubusercontent.com/3416873/31171356-0356d2ca-a908-11e7-8083-5891b3958496.PNG)

A4 page with 96 PPI: 
![96 ppi](https://user-images.githubusercontent.com/3416873/31171363-0abb235e-a908-11e7-8bb8-b469699f632c.PNG)

when i used pdf-viewer version 1.1.3 it showed as 595X842

**Comment by lwohlhart** [comment]
is there any update on this issue? I'm also experiencing the same problem; pdfs are oversized by factor 1.33. can't update beyond version 1.1.3.

**Comment by zohabAli** [comment]
Any Update on this issue?

**Comment by kurpav** [comment]
Make sure you set `style="display: block"` on `pdf-viewer` tag
