### ISSUE TITLE
Pdf UnknownErrorException: The API version "1.9.622" does not match the Worker version "1.9.628". 

### ISSUE THREAD

**Issue by Gamerakki** [VadimDez/ng2-pdf-viewer#179]
hi 
Pdf UnknownErrorException: The API version "1.9.622" does not match the Worker version "1.9.628".
i keep getting this error i am using the latest 2.2 version please help. i am using ionic 2 for showing pdf in ios it working well in android

**Comment by Gamerakki** [comment]
hi,

yes i have tried that also... but still same error ... :( can u help my app is stuck due to this

**Comment by VadimDez** [comment]
This issue is since the version `1.2.3`, and is fixed since `2.0.0`.

Try to reinstall:
```
npm uninstall -S ng2-pdf-viewer
```
and then
```
npm install -S ng2-pdf-viewer
```

**Comment by Gamerakki** [comment]
hi thanx will do that... just one thing.. whats thus -s stands for in the command

**Comment by VadimDez** [comment]
Closing, seems like working.
