### ISSUE TITLE
URL scheme "file" is not supported.

### ISSUE THREAD

**Issue by manojbhardwaj** [VadimDez/ng2-pdf-viewer#180]
Fetch API cannot load file:///data/user/0/com.testapp/files//admin/images/question-paper/class-10/Mathematics/2011/Class%20X%202011.pdf. URL scheme "file" is not supported.
 I m not able to open File:///  how fixed this error and pass into src

**Comment by VadimDez** [comment]
Are you trying to render preview for local pdf ?
If so - take a look on the demo project, it has such example 
https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/app.component.ts#L70-L82

**Comment by manojbhardwaj** [comment]
Great Issue is resolved thank you

**Comment by zepedrorocha** [comment]
For future readers.

I stumble upon this problem today. I was using v1.2.x just loading the local url file straight forward but since 2.x.x , @VadimDez  started using Fetch api which doesn't support 'File' scheme eg: 'file:///my-file.pdf'

Here's my curently workaround:
``` javascript
async loadPdf(path: string) {
  return new Promise<string>((resolve, reject) => {

    const request = new XMLHttpRequest();
    request.open('GET', path, true);
    request.responseType = 'blob';

    request.onload = () => {
      const reader = new FileReader();

      reader.onload = (e: any) => resolve(e.target.result);
      reader.onerror = err => reject(err);
      reader.readAsDataURL(request.response);
    };

    request.send();
  });
}

// ...
this.pdfSrc = await this.loadPdf('file:///path/to/file.pdf');
```

I'm building a desktop app (Electron+Angular)

**Comment by johnking** [comment]
@zepedrorocha, @VadimDez 

After building a web app with this repository, I am trying to port it to desktop with Electron+angular, but had a few issues to use this repository:

First, I got an error: 
<img width="827" alt="screen shot 2018-01-26 at 20 09 38" src="https://user-images.githubusercontent.com/1787137/35466764-ef6c5dd0-02d4-11e8-9b30-3ac01a89363d.png">

After googling around, I tried a few workarounds, like the one below by adding following code into index.html, 
```
<script> var exports = {} </script>
```
it made the previous issue disappeared, but with new issue as below. 
<img width="908" alt="screen shot 2018-01-26 at 20 18 45" src="https://user-images.githubusercontent.com/1787137/35466885-3b711f94-02d6-11e8-8977-359dac8ca77b.png">

 @zepedrorocha , I hope you solved such issues before and can help on it. 

thanks

**Comment by qwerqwermhc** [comment]
@zepedrorocha Failed to load file:///D:/pdftest/HGH-18123.pdf: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by mrcoles** [comment]
@zepedrorocha looks like `loadPdf` should also have:

```javascript
request.onerror = err => reject(err);
```

Separately I’m seeing that you’re **building a desktop app (Electron+Angular)**, I don’t think a website or even a Chrome extension can download local files. When I try from within a Chrome extension, I get: 

```
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
```

cc @qwerqwermhc
