### ISSUE TITLE
[render-text]="false" is not working 

### ISSUE THREAD

**Issue by vincent-cm** [VadimDez/ng2-pdf-viewer#181]
the text rendered always selectable. in version  "ng2-pdf-viewer": from "2.0.2" to "3.x,

**Comment by VadimDez** [comment]
Seems to be working here:
https://vadimdez.github.io/ng2-pdf-viewer/

**Comment by jonaschn** [comment]
@VadimDez it is working with the default settings but not if you try following:
1. Open https://vadimdez.github.io/ng2-pdf-viewer/ (Don't change any settings)
1. Try to select text of pdf --> works as expected
1. Turn off 'Render text layer' (`[render-text]="false"`)
1. Try to select text of pdf --> doesn't work as expected
1. Turn off 'Show all pages' (`[show-all]="false"`)
1. Try to select text of pdf --> works (NOT as expected)!
