### ISSUE TITLE
ng2-pdf-viewer breaks Angular animation for safari on iOS

### ISSUE THREAD

**Issue by ElBart00** [VadimDez/ng2-pdf-viewer#184]
ng2-pdf-viewer breaks the Angular animations only on Safari on iOS. Safari on OS X works fine. Chrome, IE and Firefox work fine as well.
See plunker [https://plnkr.co/edit/1EGqrMHVoinzYclltxmH?p=preview](https://plnkr.co/edit/1EGqrMHVoinzYclltxmH?p=preview).
This plunk just has a simple animation and a ng2-pdf-viewer. When you click the step button the colored div slides to the left and a counter below the div is updated. This works as expected except in Safari on iOS.  It loads, but as soon a transition is started, angular just stops without any error. When you remove the transitions and leave the states in it is working again but your'e not able to use transitions. When you remove the ng2-pdf-viewer the animations with transitions work on Safari on iOS.

Another user experiencing this problem: [https://stackoverflow.com/a/45849701](https://stackoverflow.com/a/45849701)

**Comment by javierdpt** [comment]
Same thing happening to me. I had to remove all the animations because it breaks the entire app.

**Comment by cbjerg** [comment]
Having the exact same problem

**Comment by tpmconzentrate** [comment]
We are experiencing the same issue.

The issue may be with pdfjs:
We have tried moving pdfjs-dist from a lazy loaded webpack bundle into our vendor bundle that will be loaded initially. When doing this Angular animations break.

Also - when using functionality that lazy-loads pdfjs-dist animations break.

**Comment by txinfo** [comment]
@tpmconzentrate Did you find a solution for this issue?

**Comment by txinfo** [comment]
It looks like pdf.js fixed this issue with their 2.x branch but it is still present in 1.9 which is what ng2-pdf-viewer is packaged with.

**Comment by TheDuc** [comment]
I also have this exact problem.
The comment above did help me a lot, I shrinkwrapped pdfjs version 2.0.288, but I also had to remove
`require('pdfjs-dist/web/compatibility')`
from ng2-pdf-viewer to make it work, because in the new version of pdfjs the compatibility.js file does not exist anymore. I am not sure if this is a correct fix, but it works for me for now.

**Comment by artdias90** [comment]
Any updates on this issue?

**Comment by artdias90** [comment]
@VadimDez  yes thanks! I had hardcoded V4 sorry. I think we should close this

**Comment by VadimDez** [comment]
Fixed in version `5.0.1` https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/5.0.1
