### ISSUE TITLE
Viewing RAW PDF data in string format

### ISSUE THREAD

**Issue by darcinator** [VadimDez/ng2-pdf-viewer#186]
similar to [https://github.com/VadimDez/ng2-pdf-viewer/issues/88](url) but have a base64 encoded string as the raw pdf data. Tries to request data from the rawdata as if it were a URL. Way to resolve this?

`<pdf-viewer [src]="pdfSrc"
            [page]="1" 
              [original-size]="true" 
              style="display: block;"></pdf-viewer>`

**Comment by riscie** [comment]
how did you solve your problem @darcinator?

**Comment by fergalddaly** [comment]
I have the same issue.

**Comment by fergalddaly** [comment]
https://github.com/VadimDez/ng2-pdf-viewer/issues/247 is helpful.


> base64ToArrayBuffer(base64: string): ArrayBuffer {    
> const binary_string =  window.atob(base64);    
> const len = binary_string.length;   
>  const bytes = new Uint8Array(len);
>     for (let i = 0; i < len; i++)        {
>       bytes[i] = binary_string.charCodeAt(i);
>     }
>     return bytes.buffer;  }
> 

I called
`
getPdfAsArrayBuffer(): ArrayBuffer {
  // create buffer once here
}
`
and the HTML code:

`
             <pdf-viewer [src]="getPdfAsArrayBuffer()"
                                                [original-size]="false" style="display: block;">
                                    </pdf-viewer>
`
