### ISSUE TITLE
can i use it in angular 2.0.0- rc.4

### ISSUE THREAD

**Issue by jose2007kj** [VadimDez/ng2-pdf-viewer#19]
sir ...i wold like to use the pdf-viewer in ionic 2 with rc4.......sir how shall i install

**Comment by jose2007kj** [comment]
sir.......i am going to install version 0.0.7...........hopes it works.....

**Comment by VadimDez** [comment]
Try to use `0.0.7` or `0.0.8-alpha.1`

**Comment by jose2007kj** [comment]
sir........ i have installed 0.0.8-alpha.1... but pdf is not displayed....screen remains blank....i am getting the below warning
Warning: Setting up fake worker.....

**Comment by VadimDez** [comment]
Do you get any other errors ? Maybe in terminal ?

**Comment by jose2007kj** [comment]
sir........in terminal there is no errors

**Comment by jose2007kj** [comment]
sir...now when i replaced pdf src from firebase storge link to https://vadimdez.github.io/ng2-pdf-viewer/pdf-test.pdf......i am able to view pdf file in firefox browser.....but pdf is not visible in chrome browser and also not visible while running in android device
