### ISSUE TITLE
Impossible to add borders between pages 

### ISSUE THREAD

**Issue by lizarusi** [VadimDez/ng2-pdf-viewer#193]
When show all pages, no borders between them. I see 'removePageBorders' class on element, but can't affect on it.

**Comment by VadimDez** [comment]
Have you tried to set `border` for `page` class and use `!important`?

**Comment by lizarusi** [comment]
@VadimDez  No. I suppose it is possible variant, but not elegant enough  :) can be a class names collisions. For Angular a small probability of it but it is.

**Comment by pradeep-ravindran** [comment]
pijp
