### ISSUE TITLE
Pan Scroll

### ISSUE THREAD

**Issue by Barros9** [VadimDez/ng2-pdf-viewer#197]
I can scroll only used the right bar or the central button of the mouse, but i would like to use the "grab hand" to scroll the pdf. It can possible enabled this function?
Thanks

**Comment by spata** [comment]
I was also looking for this functionality. It does work nicely on mobile with touch.

**Comment by Helias** [comment]
implemented in https://github.com/VadimDez/ng2-pdf-viewer/pull/1199
