### ISSUE TITLE
PdfViewerModule error

### ISSUE THREAD

**Issue by vincent-cm** [VadimDez/ng2-pdf-viewer#199]
compiler.es5.js:1694 Uncaught Error: Unexpected module 'PdfViewerModule' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.

I just upgraded to 3.0.0 and it come out the issue.

Also the compiler won't detect PDFDocumentProxy, PDFProgressData in types/pdf.

**Comment by VadimDez** [comment]
What version of angular are you using?

**Comment by cbjerg** [comment]
You shouldn't put modules in declarations but in imports

```
import { PdfViewerModule } from 'ng2-pdf-viewer';
@NgModule({
  imports: [PdfViewerModule ],
  declarations: [PdfComponent],
  exports:      [ PdfComponent]
})
```

regarding PDFDocumentProxy, PDFProgressData - I have the same problem, and had to replace them with 'any'

**Comment by VadimDez** [comment]
@vincent-cm take a look [here](https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app.module.ts#L15) this is how your AppModule should look like

**Comment by vincent-cm** [comment]
Thanks.
