### ISSUE TITLE
PDFDocumentProxy, PDFProgressData are undefined for compiler

### ISSUE THREAD

**Issue by VadimDez** [VadimDez/ng2-pdf-viewer#200]
Reported in #199

**Comment by MattHoneycutt** [comment]
Any update on this?  It is tagged for 3.0.2, but I'm using 3.0.3, but cannot use PDFDocuemntProxy or PDFProgressData.   Has something about the setup changed from what's shown on the readme? 

Thanks!

**Comment by leonardosalles** [comment]
any updates? I removed a local version to use the latest one and we still facing  this issue :@

**Comment by VadimDez** [comment]
https://github.com/VadimDez/ng2-pdf-viewer/pull/238#issuecomment-354975949

**Comment by VadimDez** [comment]
See release notes:
https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/3.0.6

**Comment by leonardosalles** [comment]
Nice work, thanks @VadimDez ;)
