### ISSUE TITLE
Document loaded but the pages keep on showing the loading animation

### ISSUE THREAD

**Issue by dafooz** [VadimDez/ng2-pdf-viewer#201]
Hi,

I installed and used the package as stated on the page. It seems to work as it's loading the PDF (I checked by adding the after-load-complete event and it get's reached properly) the number of pages is correct and the display is correct as well... My only issue is that instead of showing the content of the pages, it shows a loader on each of them and it never goes away...

EDIT: This seem to be the case only in a specific component of my application. If I try the same code in the main component, it works fine... 

In the main component, the pages have the attribute data-loaded=true while in my other component, that attribute isn't there...

Can you please help?

package.json:

```
"dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@ngrx/store": "^4.1.0",
    "ng2-pdf-viewer": "^3.0.0",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
```

code in template:
  `<pdf-viewer [src]="itemInfo.doc" [render-text]="true" style="display: block;" [original-size]="false" [autoresize]="true" (error)="onPDFError($event)"></pdf-viewer>`

Thanks a lot in advance for your help,
Regards,
Dafooz

**Comment by Blustch** [comment]
Hi @dafooz,
I'm encountering the same issue as you did and would like to know if you had any breakthrough (I'm on Angular 6.0)

**Comment by jonathanjouret-ls** [comment]
Hi @Blustch,
I know I made it work but I don't remember how... I will try to check the code and come back to you asap.

**Comment by dafooz** [comment]
Hi @Blustch,
I know I made it work but I don't remember how... I will try to check the code and come back to you asap.

**Comment by Blustch** [comment]
Hi again @dafooz,
Sorry, deleted my previous comment because I posted it before even checking out the linked references ( which was lazy of me). I will also come back to you if I find anything new.

**Comment by MRisto** [comment]
Any updates on this? Have the same Problem. Strange is, that this problem occurs for me in a material dialog.

**Comment by chris2ba** [comment]
Bump I'm having the same issue here.

**Comment by Blustch** [comment]
For me the problem occurs in a material sidenav, and weirdly enough only on Chrome. 
Just to give some context, I am displaying 2 PDFs (one under the other), both of one page each. The issue only affects the bottom PDF which is not displayed immediatly (ie: you have to scroll to see it). It eventually appears after a random number of refresh.

The end-users of my web-app mainly use Edge or Firefox (where it displays just fine) so in the end there was no need for me to try to fix it. It's not the only issue I have with Chrome, so I'm slowly moving away with it.

**Comment by RamaKrishnanGanesan** [comment]
Facing the same issue in my angular 6 application. The pdf downloads fine (able to see in the browser's network traffic). Seeing loading gif in the DOM for each page of the pdf. The DOM for the pdf page is not getting generated.
