### ISSUE TITLE
Module "ng2-pdf-viewer" has no exported member 'PdfViewerModule'

### ISSUE THREAD

**Issue by Tyler-V** [VadimDez/ng2-pdf-viewer#202]
@VadimDez 

Latest changes would require importing the module with the path 'ng2-pdf-viewer/dist' as that is where the index.d.ts resides.

import { PdfViewerModule } from 'ng2-pdf-viewer/dist';

Should move index.d.ts to node_modules/ng2-pdf-viewer so you can use import from 'ng2-pdf-viewer'

[Error](https://puu.sh/yhzJw/12137fe08d.png)

**Comment by robindijkhof** [comment]
Are you on version 3.0.0?

**Comment by Tyler-V** [comment]
Yes.

"version": "3.0.0"

**Comment by robindijkhof** [comment]
Delete your node modules and reinstall

**Comment by Tyler-V** [comment]
Restarting visual studio code has resolved my issue.
