### ISSUE TITLE
Autosize not working

### ISSUE THREAD

**Issue by robindijkhof** [VadimDez/ng2-pdf-viewer#203]
See the plunker on a small screen. The pdf does not resize and requires scroling

https://plnkr.co/edit/Lxyk47QzkS2PIXc5CmhQ?p=preview

**Comment by VadimDez** [comment]
You have to set `[original-size]="false"` and set `style="display: block;"`.
Value of `[original-size]` is `true` by default and therefore adding just `[autoresize]="true"` won't work.
I will add this to `README.md`, thanks for reporting the issue.

Here's plunker:
https://plnkr.co/edit/6t1wFvQY1Qe3XMUAwOEW?p=preview

**Comment by harishsnapcheck** [comment]
Thanks for saving my time :)
