### ISSUE TITLE
Export more variables, PdfViewer, PdfViewerComponent

### ISSUE THREAD

**Issue by jsgoupil** [VadimDez/ng2-pdf-viewer#204]
It would be beneficial to export a couple of variable to fully handle the PdfViewer manually.

Technically, I would love to go play with the EventBus. So I would need

- export PdfViewComponent
- getter for PdfViewer

At the moment, I need to access private variables and go with no type with PdfViewerComponent

**Comment by VadimDez** [comment]
This is resolved since version `3.0.8`
https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/3.0.8
