### ISSUE TITLE
Ability to create a preview/thumbnail

### ISSUE THREAD

**Issue by natcohen** [VadimDez/ng2-pdf-viewer#21]
Thank you very much for sharing this library!

I've followed [this tuto](http://rfvallina.com/blog/2015/08/22/preview-tiff-and-pdf-files-using-html5-file-api/) in order to create a pdf preview (thumbnail). Unfortunately, it is not yet possible to do that with your library... I would realy appreciate if someone could help add this feature to the project!

**Comment by amitads** [comment]
Any update on this?

**Comment by VadimDez** [comment]
Not yet

**Comment by VadimDez** [comment]
I made an example how to render preview by just selecting PDF file with file selector

Add `(change)="onChange()"` to your `input`
```html
<input (change)="onChange()" type="file" id="file">
<pdf-viewer [src]="pdfSrc" [(page)]="page"></pdf-viewer>
```

Add method
```ts
  onChange() {
    var $img: any = document.querySelector('#file');

    if (typeof (FileReader) !== 'undefined') {
      var reader = new FileReader();

      reader.onload = (e: any) => {
        this.pdfSrc = e.target.result;
      };

      reader.readAsArrayBuffer($img.files[0]);
    }
  }
```
