### ISSUE TITLE
URL scheme "file" is not supported

### ISSUE THREAD

**Issue by MoreiraW** [VadimDez/ng2-pdf-viewer#212]
When I insert a local (mobile) pdf I get this error
"URL scheme "file" is not supported"
 <pdf-viewer [src]="pdfSrc" [original-size]="true" [show-all]="true" [zoom]="2"></pdf-viewer>

this.pdfSrc =  "file:///data/user/0/../.pdf"

Can someone help me with this problem?

**Comment by VadimDez** [comment]
Duplicate #180
