### ISSUE TITLE
scroll not working

### ISSUE THREAD

**Issue by Alex61NN5** [VadimDez/ng2-pdf-viewer#214]
Hi Im using this code 
     `<pdf-viewer [src]="pdfSrc"
                 [(page)]="page"
                 [show-all]="true"
                [rotation]="0"
              [stick-to-page]="true"
              [zoom]="0.9"
              [render-text]="true"
              [autoresize]="true"
              [original-size]="false"              
              style="display: block;" (after-load-complete)="callBackFn($event)">
  </pdf-viewer>`

and I cant get the scroll to work, If I set show all to `false` I can get it to go to the page ive set but not if its set to `true`

I would like to be able to have the whole document loaded into the page and have it start at the page I specify

**Comment by VadimDez** [comment]
If I understood you correctly - you want to `jump` to a certain page, to do that use `[stick-to-page]="true"` 
https://github.com/VadimDez/ng2-pdf-viewer#stick-to-page
see how it works here:
https://vadimdez.github.io/ng2-pdf-viewer/

**Comment by Alex61NN5** [comment]
Hey as you can clearly see in my code, I have put `[stick-to-page]="true"` and it only works if `[show-all]="false"` I want to be able to show the whole pdf and it have it `jump` to the page I want
