### ISSUE TITLE
[external-link-target] is not working

### ISSUE THREAD

**Issue by jsfirefly** [VadimDez/ng2-pdf-viewer#215]
Hi,
when I use **external-link-target** attribute with value **blank** I can't open my pdf file in external tab.

**Comment by VadimDez** [comment]
Does it look like this?
```
[external-link-target]="'blank'"
```
See: https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/app.component.html#L170
You can test it here: vadimdez.github.io/ng2-pdf-viewer/

**Comment by jsfirefly** [comment]
This is how I use component:

<pdf-viewer [src]="url"
                        [render-text]="false"
                        [original-size]="false"
                        [show-all]="false"
                        [external-link-target]="'blank'"
                        style="display: block;">
            </pdf-viewer>

"version": "3.0.2"

**Comment by VadimDez** [comment]
You have to set`[render-text]="true"` otherwise your links won't be `clickable`.
I'll update documentation.

**Comment by jsfirefly** [comment]
Stil is not working.

`<pdf-viewer [src]="value"
                        [render-text]="true"
                        [original-size]="false"
                        [show-all]="false"
                        [external-link-target]="'blank'"
                        style="display: block;">
            </pdf-viewer>`

**Comment by VadimDez** [comment]
Could you explain what do you want to achieve in details?

**Comment by jsfirefly** [comment]
I just want to open pdf file in new tab by clicking on component area

**Comment by VadimDez** [comment]
that has nothing to do with `[external-link-target]` and this component. `[external-link-target]` sets target for links inside the PDF.

Use `(click)` with some callback function to achieve your use case.

**Comment by jsfirefly** [comment]
ok, clear.
thanks

**Comment by sai2812** [comment]
how to fix this issue ... Can you please provide code @VadimDez

**Comment by VadimDez** [comment]
@sai2812 Could you describe your issue then?

**Comment by sai2812** [comment]
@vadim I want to open the PDF in new tab by using ng2-pdf-viewer ... Can you please help

**Comment by ThisGuyRghtHereee** [comment]
I've set [external-link-target]="'blank'", however when I look at the rendered pdf component the Target field is empty.

Component template:
`<pdf-viewer [src]="file" [render-text]="true" external-link-target="'blank'" (after-load-complete)="loading = false" (error)="onError($event)" style="height: 600px; height: -moz-available; height: -webkit-fill-available; height: fill-available;"></pdf-viewer>`

Picked a random link in Chrome dev (url removed), target remains empty:
`<a title="" href="**LINK REMOVED**" target="" rel="noopener noreferrer nofollow"></a>`

**Comment by sjsnider** [comment]
I'm having the exact same issue as @ThisGuyRghtHereee (did you figure it out?).  target is not getting set for me...

**Comment by ThisGuyRghtHereee** [comment]
@sjsnider I still have yet to see [external-link-target] work.
I found a work around somewhere on the internet:
Template
`<pdf-viewer id="pdf" (text-layer-rendered)="doneLoading()">`

Component
`doneLoading() {
    var anchors = document.getElementById('pdf').getElementsByTagName('a');
    for (var i=0; i<anchors.length; i++){
      anchors[i].setAttribute('target', '_blank');
    }
  }`

**Comment by sjsnider** [comment]
cool, thanks!

**Comment by sjsnider** [comment]
darn, that callback isn't firing for some reason.  All the other ones I've tried do as expected...

**Comment by ThisGuyRghtHereee** [comment]
Did you try adding [render-text]=“true”
I didn’t need to use it, but I do have more code in there for other purposes (I.e. loading message: Loading Content..., Rendering Content...)

‘<div *ngIf=“file”>
<pdf-viewer id=“pdf” [src]=“file” (after-load-complete)=“doneLoadingContent()” (page-rendered)=“doneRendering()” (text-layer-rendered)=“doneLoading()” (error)=“onError($event)”></pdf-viewer>
</div>’

Only the doneLoading() function after text rendered has the code I listed above to add the target attributes to the a tag elements.

**Comment by jabed07** [comment]
<pdf-viewer [src]="filePath" [external-link-target]="'blank'" [original-size]="true"
              [render-text]="true"  [zoom]="1"  [autoresize]="true"
              (after-load-complete)="hideSpinner($event)"
                ></pdf-viewer> 
Its not opening in new window in electron.
Its opening in same window.
Please help.

**Comment by prashanthyD** [comment]
Hi,
When i am giving 
pdfSrc = 'https://www-aola52p.myappro.com/clients/BDWY/br/imageupload/HEConsumerDisclosureRev2018.pdf'
external url its not working. It's showing below error
from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Please help on this issue.

**Comment by prashanthyD** [comment]
Hi,
When i am giving pdfSrc=  this.sanitizer.bypassSecurityTrustResourceUrl('https://www-aola52p.myappro.com/clients/BDWY/br/imageupload/HEConsumerDisclosureRev2018.pdf').
I am getting below issue.
Invalid parameter object: need either .data, .range or .url
Please help me that how to load external pdf

**Comment by prashanthyD** [comment]
> You have to set`[render-text]="true"` otherwise your links won't be `clickable`.
> I'll update documentation.

We have set [render-text]="true" and [external-link-target]="'blank'" still links opening in same window

**Comment by robindijkhof** [comment]
This issue should be reopenend.

**Comment by ThisGuyRghtHereee** [comment]
> Hi,
> When i am giving pdfSrc= this.sanitizer.bypassSecurityTrustResourceUrl('https://www-aola52p.myappro.com/clients/BDWY/br/imageupload/HEConsumerDisclosureRev2018.pdf').
> I am getting below issue.
> Invalid parameter object: need either .data, .range or .url
> Please help me that how to load external pdf

I'm using Blobs for my PDFs. I'm not sure whether you can do that with external PDF sources; I'm using Firebase storage for my PDFs.
`this.storage.ref(this.pdf.fileRef).getDownloadURL().subscribe(url => {
          // console.log('publication', publication[0], url);
          this.blobSubscription = this.getPDF(url).subscribe((data:any) => {
            var file = new Blob([data._body], {type: "application/pdf"});
            this.file = data;
            // Cleanup blob if subscription updates (new publication published)
            this.cleanupBlob();
            this.publicationDocObject = window.URL.createObjectURL(file);
            this.publicationDocLocalUrl = this.domSanitizer.bypassSecurityTrustResourceUrl(this.publicationDocObject);
            // this.loading = false;
          },
          error => {
            console.error('Storage Error', error);
          })
        }, error => {
          if (error.code == 'storage/quota-exceeded') this.errorMessage = 'Storage Quota Exceeded: Too many files were downloaded today. Please try again later.';
          this.loading = false;
          this.error = true;
          console.error('Storage Error', error);
        })`
`getPDF(downloadURL: string): Observable<any> {
    return this.http.get(downloadURL,
      {
        responseType: ResponseContentType.ArrayBuffer
      }
    );
  }`

**Comment by faraz2116** [comment]
`<pdf-viewer src = "assets/pdf/abc.pdf"  [external-link-target]="'blank'" [original-size]="true"[render-text]="true" [zoom]="1" [autoresize]="true" (after-load-complete)="hideSpinner($event)"></pdf-viewer>`

External Link is not clickable in PDF Please tell me what is wrong in this code.

**Comment by vipul-docdoc** [comment]
The below workaround worked for me:

Important note: 
- You should set render-text to true: [render-text]="true"

> HTML
```
<pdf-viewer id="pdf-report-id" class="pdf-container" [src]="pdfData" [original-size]="false" [fit-to-page]="true" [render-text]="true" [zoom]="1" (text-layer-rendered)="textLayerRendered($event)">
</pdf-viewer>
```

Typescript code:
`
textLayerRendered(e: CustomEvent) {
    let externalLinks: HTMLCollectionOf<HTMLAnchorElement>;
    const pdfReport = document.getElementById('pdf-report-id');

    if (pdfReport) {
      externalLinks = pdfReport.getElementsByTagName('a');
    }
    for (let i = 0; i < externalLinks.length; i++) {
      externalLinks[i].setAttribute('target', '_blank');
    }
  }
`

**Comment by vipul-zambare006** [comment]
The below workaround worked for me:

> Important note:

- You should set render-text to true: [render-text]="true"

> HTML
```
<pdf-viewer id="pdf-report-id" class="pdf-container" [src]="pdfData" [original-size]="false" [fit-to-page]="true"
    [render-text]="true" [zoom]="1" (text-layer-rendered)="textLayerRendered($event)">
</pdf-viewer>
```

> Typescript code:

```
textLayerRendered(e: CustomEvent) {
    let externalLinks: HTMLCollectionOf<HTMLAnchorElement>;
    const pdfReport = document.getElementById('pdf-report-id');

    if (pdfReport) {
      externalLinks = pdfReport.getElementsByTagName('a');
    }
    for (let i = 0; i < externalLinks.length; i++) { externalLinks[i].setAttribute('target', '_blank'); }
  }
```

**Comment by versavice** [comment]
Is anyone else unable to open links at all? These are the properties I have on my pdf-viewer element:

`[render-text]="true" [render-text-mode]="2" [external-link-target]="'blank'" (text-layer-rendered)="textLayerRendered($event)" [src]="pdfSrc" [original-size]="false" (after-load-complete)="pdfLoaded($event)"`

I am able to highlight the links but they arent clickable.

**Comment by ahmadbassir** [comment]
Has Anyone solved this issue? I am facing the same problem currently and my link wont open in a new tab! 
Please help someone

**Comment by rashisf** [comment]
Same I want help too. Not able to open in new tab
