### ISSUE TITLE
Annotation layer on top of PDF viewer

### ISSUE THREAD

**Issue by MKITConsulting** [VadimDez/ng2-pdf-viewer#218]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
Hello Vadym ,

what do you think we would need to add an annotation layer on top of the regular pdf viewer? I think of something like done in the `pdf-annotate` project:  [https://github.com/instructure/pdf-annotate.js/](https://github.com/instructure/pdf-annotate.js/).

The pdf-annotate project is quite old and relies on PDF.js version 1.4 which has problems with some PDFs. It would be great to see some new efforts in that area. The `@types/pdf` package is quite limited (also some years old) and maybe we should think about updating this one to have access to all the new stuff in PDF.js. 

Do you think this is possible without too much effort and maybe depict a good way to realize this? (we could support you on that)

Best regards,
Marcel

**Comment by VadimDez** [comment]
Something similar was discussed previously in #74
