### ISSUE TITLE
Is there any possible way to implement pinch & zoom function in the container canvas?

### ISSUE THREAD

**Issue by nessgor** [VadimDez/ng2-pdf-viewer#22]
For example using hammer.js?

http://hammerjs.github.io/

**Comment by nessgor** [comment]
Just tested the function and it work when i set [zoom]=0.8, but I think this do no support 2 way binding?
It shows error when I use [(zoom)]="zoom"

**Comment by nsuhanshetty** [comment]
Looking forward to this feature, as I am applying this to a mobile app.

**Comment by liangwenzhong** [comment]
+1

**Comment by michaeljcoyne** [comment]
Any news on this? I can't use this without pinch zoom.

**Comment by jjacobs33589** [comment]
I also am looking for this

**Comment by SaeedSyedAli96** [comment]
Anyone Implemented this? Help needed!

**Comment by tabirkeland** [comment]
I implemented this in Ionic 3.9.2 in a modal.  [Here](https://gist.github.com/tabirkeland/426e1ba59ede87843830677b4fda388e) is a Gist to show how to implement.

**Comment by jtcrowson** [comment]
@tabirkeland That's with buttons though.  What about the pinch gesture?

**Comment by tabirkeland** [comment]
@jtcrowson I have not had the chance to try it which pinch.

You could try using the "pinch" gesture outlined [here](https://ionicframework.com/docs/components/#gestures) and calling the `zoomIn()` and `zoomOut()` functions depending on user input.

**Comment by jtcrowson** [comment]
Biggest issue with using a gesture framework (like hammer.js) on the ng2-pdf-viewer is that it disables touch scrolling.

**Comment by sattip** [comment]
Any luck?

**Comment by woutervddn** [comment]
waiting for this as well, tried to get it to work myself but no luck... :(

**Comment by wnabil** [comment]
using hammerjs it is something like that

    const container: HTMLElement = document.getElementById('pdf-file-container');

    const hammer = new Hammer(container, {
      domEvents: true
    });

    hammer.get('pinch').set({
      enable: true
    });

    hammer.on('pinchend', (event: any) => {
      // get the current zoom value
      let zoom = this.currentZoom;
      // get the scaled amount
      const scale = zoom * event.scale / 10;
      // if the user is zooming in
      if (event.additionalEvent === 'pinchout') {
        zoom += scale;
      } else {
        // if zooming out
        zoom -= scale * 10;
      }

      // if zoom is too small or too big set them to max values
      if (zoom < 1) {
        zoom = 1;
      } else if (zoom > 2) {
        zoom = 2;
      }

      // set the current zoom
      this.currentZoom = zoom;
    });

i am not sure if there is a better way but this works fine currently

**Comment by hitmacreed** [comment]
for ionic 3 users[here](https://github.com/hitmacreed/ng2-pdf-viewer-zoom-in-and-out-pinchZoom-Ionic-3)

**Comment by cxw13424219787** [comment]
using ngx-pinch-zoom, specific query google

**Comment by cxw13424219787** [comment]
<pinch-zoom>
    <div class="oat-pdf-container">
      <pdf-viewer [src]="pdfSrc"
        [autoresize]="true" 
        [original-size]="false"
        [show-all]="true"
        [zoom]="currentZoom"
        style="display: block;"
      ></pdf-viewer>
    </div>
  </pinch-zoom>

**Comment by cxw13424219787** [comment]
```
  <pinch-zoom>
    <div class="oat-pdf-container">
      <pdf-viewer [src]="pdfSrc"
        [autoresize]="true" 
        [original-size]="false"
        [show-all]="true"
        [zoom]="currentZoom"
        style="display: block;"
      ></pdf-viewer>
    </div>
  </pinch-zoom>
```

**Comment by dipankarmondal** [comment]
any one able to do this?

**Comment by cxw13424219787** [comment]
您的邮件已收到，我会尽快回复O(∩_∩)O

**Comment by vikaskandari** [comment]
Thanks to @cxw13424219787  the solution works perfectly for angular now here are some additional information  and resources :-  

Angular 18+ support of ngx-pinch-zoom its fork as orignal one is outdated 
https://www.npmjs.com/package/@meddv/ngx-pinch-zoom
```shell 
npm i @meddv/ngx-pinch-zoom
```
Html Code 
```html
<pinch-zoom>
      <div  [style.height.px]="500" [style.width.%]="100">
        <pdf-viewer 
             [src]="'https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf'" 
             [render-text]="true" 
             [original-size]="false" 
            [style.height.px]="500">
         </pdf-viewer>
      </div>
    </pinch-zoom>
```
Make sure to give a height on pdf-viewer and its parent element otherwise it won't show.

i have tested it and works perfectly without any issues with angular 18.

**Comment by cxw13424219787** [comment]
您的邮件已收到，我会尽快回复O(∩_∩)O

**Comment by StefanoBorzi** [comment]
implemented here https://github.com/VadimDez/ng2-pdf-viewer/pull/1199

**Comment by cxw13424219787** [comment]
您的邮件已收到，我会尽快回复O(∩_∩)O
