### ISSUE TITLE
Cannot read property 'div' of undefined

### ISSUE THREAD

**Issue by yanlyan** [VadimDez/ng2-pdf-viewer#224]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

When page changed it's success to change the page number, but It's failed when scrolling to the page because of this error : 

```
ERROR TypeError: Cannot read property 'div' of undefined
    at PDFViewer._resetCurrentPageView (pdf_viewer.js:1556)
    at PDFViewer._setCurrentPageNumber (pdf_viewer.js:1281)
    at PDFViewer.set (pdf_viewer.js:1858)
    at eval (pdf-viewer.component.js:258)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4620)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at ZoneTask.invokeTask (zone.js:499)
    at ZoneTask.invoke (zone.js:488)
```

I'm using Angular 5.0.3 and ng2-pdf-viewer 3.0.2

**Comment by VadimDez** [comment]
Could you provide steps to reproduce this?

**Comment by giacomoalonzi** [comment]
same here! any update?

**Comment by khrice** [comment]
So I see this issue when I render the pdf viewer in a component and its a large pdf and as it is rendering (can see the first page but the rest are not rendered yet) and I decide to close it (removes the pdf-viewer from the page via a *ngIf) then it crashes and gives me that error

**Comment by joaogoya** [comment]
I get this issue when i try to render the pdf viewer inside a bootstrap modal

**Comment by Durdush** [comment]
I am getting the same error when I am trying to render pdf inside iframe.

**Comment by noamyg** [comment]
I'm also having a hard time with this issue.
It seems like the error is thrown whenever the pdf-viewer is hidden or closed.
For example -
1. Like @Durdush mentioned, when you use the pdf-viewer as a fallback to an <iframe>/<object>/<embed> tags (showing a pdf for non-plugin browsers)
2. When it's hidden (for example, pdf-viewer is hidden when hiding a modal)

**Comment by TeXnicians** [comment]
I got the same error when I incorporate `pdf-viewer` into a `MatDialog` and close the dialog.

**Comment by mepreethamgowda** [comment]
I got the same error when I reloaded the pdf-viewer with the same pdf file or a different one, while the current page i.e [page], was set to 2 or more. And solved the same by resetting [page] to 1 before reloading the viewer.

**Comment by koggalage** [comment]
I had the same error and I fixed it with following changes.

* ng2-pdf-viewer has a dependency called pdfjs-dist. You can find it in node_modules.
* Open this file -> node_modules/pdfjs-dist/web/pdf_viewer.js
* In pdf_viewer.js file, search for this line of code -> `var elt = views[index].div;` It is inside 'backtrackBeforeAllVisibleElements' function.
* Change that code line to `var elt = views[index-1].div;` and save.

**Comment by anysunflower** [comment]
I got the error, when I use pdf-viewer in ngbModal  
It caused by the ngif parameter in pdf-viewer got true value before ng-template shown 

error code:

```js
    <ng-template #attachPreview let-modal>
        <div style="text-align: center;width: fit-content;">
            <pdf-viewer 
            [src]="previewDoc.url" 
            [render-text]="true"
            [original-size]="true"
            [stick-to-page]="true"
            >
            </pdf-viewer>
        </div>
    </ng-template>    <ng-template #attachPreview let-modal>
        <div style="text-align: center;width: fit-content;">
            <pdf-viewer 
            *ngif = "previewDoc.url"
            [src]="previewDoc.url" 
            [render-text]="true"
            [original-size]="true"
            [stick-to-page]="true"
            >
            </pdf-viewer>
        </div>
    </ng-template>
```
when I remove *ngif = "previewDoc.url",error disappear

**Comment by wlodekDev** [comment]
I'm using single-pdf-viewer and I had a similar problem:
```
Unable to initialize viewer TypeError: Cannot read property 'div' of undefined
    at PDFSinglePageViewer._ensurePageViewVisible (vendor.js:128660)
    at vendor.js:128635
    at vendor.js:125843
    at Array.forEach (<anonymous>)
    at EventBus.dispatch (vendor.js:125842)
    at vendor.js:126729
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (polyfills.js:2749)
    at Object.onInvoke (vendor.js:69038)
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (polyfills.js:2748)
    at Zone.push.../../node_modules/zone.js/dist/zone.js.Zone.run (polyfills.js:2508)
```
In a node_modules, in a file 'pdf_viewer.js' (node_modules/pdfjs-dist/web/pdf_viewer.js) from line 3326 starts method:
```
value: function _ensurePageViewVisible() {
            var pageView = this._pages[this._currentPageNumber - 1];
            var previousPageView = this._pages[this._previousPageNumber - 1];
            var viewerNodes = this.viewer.childNodes;
            switch (viewerNodes.length) {
              case 0:
                this.viewer.appendChild(pageView.div);
                break;
              case 1:
                if (viewerNodes[0] !== previousPageView.div) {
                  throw new Error('_ensurePageViewVisible: Unexpected previously visible page.');
                }
                if (pageView === previousPageView) {
                  break;
                }
                this._shadowViewer.appendChild(previousPageView.div);
                this.viewer.appendChild(pageView.div);
                this.container.scrollTop = 0;
                break;
              default:
                throw new Error('_ensurePageViewVisible: Only one page should be visible at a time.');
            }
            this._previousPageNumber = this._currentPageNumber;
          }
```
Problem was that 'pageView.div' was 'undefined', and solution was simple:
```
if (pageView !== undefined) {
    this.viewer.appendChild(pageView.div);
}
```
so method looks like:
```
value: function _ensurePageViewVisible() {
            var pageView = this._pages[this._currentPageNumber - 1];
            var previousPageView = this._pages[this._previousPageNumber - 1];
            var viewerNodes = this.viewer.childNodes;
            switch (viewerNodes.length) {
              case 0:
                if (pageView !== undefined) {
                  this.viewer.appendChild(pageView.div);
                }
                // this.viewer.appendChild(pageView.div);
                break;
              case 1:
                if (viewerNodes[0] !== previousPageView.div) {
                  throw new Error('_ensurePageViewVisible: Unexpected previously visible page.');
                }
                if (pageView === previousPageView) {
                  break;
                }
                this._shadowViewer.appendChild(previousPageView.div);
                this.viewer.appendChild(pageView.div);
                this.container.scrollTop = 0;
                break;
              default:
                throw new Error('_ensurePageViewVisible: Only one page should be visible at a time.');
            }
            this._previousPageNumber = this._currentPageNumber;
          }
```

**Comment by matthiasbrix** [comment]
Hi,

I get a similar bug:
`
ERROR TypeError: Cannot read property 'div' of undefined
    at PDFViewer._resetCurrentPageView (pdf_viewer.js:6922)
    at PDFViewer._setCurrentPageNumber (pdf_viewer.js:6536)
    at PDFViewer.set (pdf_viewer.js:7384)
    at ng2-pdf-viewer.js:545
    at ZoneDelegate.push.0TWp.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:28540)
    at ZoneDelegate.push.0TWp.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push.0TWp.Zone.runTask (zone.js:188)
    at push.0TWp.ZoneTask.invokeTask (zone.js:503)
    at ZoneTask.invoke (zone.js:492)
`

Could we change `resetCurrentPageView()` to
`
key: "_resetCurrentPageView",
value: function _resetCurrentPageView() {
  if (this.isInPresentationMode) {
    this._setScale(this._currentScaleValue, true);
  }

  var pageView = this._pages[this._currentPageNumber - 1];

  if (pageView) {
    this._scrollIntoView({
      pageDiv: pageView.div
    });
  }
}
`

**Comment by ceexon** [comment]
Hi @matthiasbrix 
Was this resolved? I'm getting the same error now
