### ISSUE TITLE
ng2-pdf-viewer on incorrect source issue

### ISSUE THREAD

**Issue by Wenqiang01** [VadimDez/ng2-pdf-viewer#227]
##### Bug Report or Feature Request (mark with an `x`)
```
- <pdf-viewer [src]="pdfSrc" ></pdf-viewer>
- [ ] if the pdfSrc is invalid or cannot be found, do we have method to handle these kind issue
- [ ] if the pdfSrc return 404, how should I handle this kind issue, thank you
```

**Comment by aadeez** [comment]
Kindly add fonts from **shree lipi(ttf), kruti dev(ttf), walkman chanakya(ttf)** , if required i will send you the fonts.

**Comment by Wenqiang01** [comment]
Hi @aadeez  
What do you mean by adding fonts,   my question is when the src attribute is not a PDF path or a invalid path, how can we handle this kind issue.

**Comment by VadimDez** [comment]
Similar to #166

**Comment by VadimDez** [comment]
Closing as duplicate of #166
