### ISSUE TITLE
ionic run/build produce different results with ng2-pdf-viewer

### ISSUE THREAD

**Issue by ptangen** [VadimDez/ng2-pdf-viewer#228]
Hello,
We have ng2-pdf-viewer in our app. The PDFs are displayed as expected when the app is opened on the device through: ionic cordova run ios. Feedback comes in the console, too:
[14:49:55] console.log: onProgress PDF: {“loaded”:2609}
[14:49:55] console.log: onProgress PDF: {“loaded”:2609,“total”:2609}
[14:49:55] console.log: onProgress PDF: {“loaded”:23497}
[14:49:55] console.log: onProgress PDF: {“loaded”:23497,“total”:23497}

Unfortunately, when the app is built with: ionic cordova build iOS and installed on the device through xCode, the PDF is not displayed. There is no error or onProgress feedback sent.

Does anyone know why “ionic cordova run ios” and “ionic cordova build ios” would produce different results?

Thank you,
Paul

**Comment by VadimDez** [comment]
Could you tell me your iconic and angular versions?

**Comment by ptangen** [comment]
I am using ionic 3.9.2 and angular 5.03. The trouble was the cordova-plugin-ionic-webview plugin was corrupted. After reinstall, the pdfs displayed properly.
