### ISSUE TITLE
Request to make zoom a two way binding property

### ISSUE THREAD

**Issue by ctbolton** [VadimDez/ng2-pdf-viewer#23]
It appears that the zoom cant be changed on the fly.  Would appreciate if it could be added as an option. Thanks!

**Comment by VadimDez** [comment]
Could you describe how different zoom's behaviour should be ? Take a look at zoom here https://vadimdez.github.io/ng2-pdf-viewer/

**Comment by ctbolton** [comment]
Actually that works perfectly Vadim.  Any chance you could provide example code?  I tried to set the zoom up as a [(zoom)] property and set it thru a function call and it bombed on me.

**Comment by VadimDez** [comment]
Sure, take a look at example code, see ```zoom```, ```incrementZoom()``` in  https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/app.component.ts and how i used it in https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/app.component.html
Let me know if it helps

**Comment by ctbolton** [comment]
Got everything working properly.  My bad Vadim.  Thanks for the assist.
