### ISSUE TITLE
Bookmark option

### ISSUE THREAD

**Issue by dalbir** [VadimDez/ng2-pdf-viewer#233]
Please write code for bookmark option also.

**Comment by dalbir** [comment]
I have found a solution. Can I contribute in your repo for Bookmark

**Comment by VadimDez** [comment]
Sure! Why not?
Just create a pull request, i'll review and merge it.

**Comment by dalbir** [comment]
I have add the code, and created a pull request please review and if fine ok then merge.

**Comment by dalbir** [comment]
@VadimDez Thanks.

**Comment by manojmanic** [comment]
@dalbir of @VadimDez  What is the solution for a bookmark option in pdf? let me know?
