### ISSUE TITLE
Hard coded PDF.workerSrc violates the Content Security Policy sometimes

### ISSUE THREAD

**Issue by pengisgood** [VadimDez/ng2-pdf-viewer#234]
For security reason, sometimes we might have meta tag like this:

```
<meta http-equiv="Content-Security-Policy" content="default-src *; font-src 'self' data: ; style-src 'self'; worker-src 'self' blob:; script-src 'self'; img-src 'self' data:;">
```

In this case, the hard-coded worker file CDN URL will violate the CSP.

**Comment by VadimDez** [comment]
Version `2.0.4` should fix your problem. Now you can define your own path to the worker.
https://github.com/VadimDez/ng2-pdf-viewer#set-custom-path-to-the-worker
