### ISSUE TITLE
Memory crash in browser (after 36-48 hours)

### ISSUE THREAD

**Issue by magdalinks** [VadimDez/ng2-pdf-viewer#235]
##### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

We use pdf-viewer with a timer for a presentation. Application shows a presentation that switch between images, videos and 2 pdf with pdf-viewer (switching occurs after 20 seconds). After 36 - 48 hours of presentation, Chrome crashes because it takes too much memory. Memory it not released in a proper way. Without pdfs documents, the application doesn't crash so problem came from pdf-viewer.

**Comment by VadimDez** [comment]
Thanks for reporting! I'll try to figure out what's going on as soon as i can.

**Comment by magdalinks** [comment]
As workaround, instead of destroy component, we hide it. It seems pdf.js keeps in memory several objects after destroy. After many iterations, the browser crashes. Hiding the component don't consume so many resources, so it's the solution we take. We hope this workaround would be useful for someone with the same problem. I closed the issue because I think it's a pdf.js problem.
