### ISSUE TITLE
IOS device not working display blank

### ISSUE THREAD

**Issue by darshitmaniar** [VadimDez/ng2-pdf-viewer#236]
I am getting strange behavior on the ios device.
I have developed the app in Angular2 and cordova while implementing for IOS app component not display, the component is already loaded but not display when I debug code found some style automatically append app root component tag. 
style ="transform: translateX(-100%); position:fixed;"

once I have uninstalled pdf viewer the app is working fine. 
Thanks in advance!

**Comment by VadimDez** [comment]
That shouldn't happen!
Is `padding-left` added as well?
Could you show me the code/structure where you using `pdf-viewer`?

**Comment by zanda85** [comment]
I have been the same problem! 

in the browser (cordova) platform work. but ios not working!!! why ?

**Comment by asadullazadeh** [comment]
the same

**Comment by VadimDez** [comment]
@asadullazadeh which version of `ng2-pdf-viewer` are you using? What `CSS` props did you use?

**Comment by dima83909** [comment]
@VadimDez the latest version of ng2-pdf-viewer. On iphone 7(IOS 13.3.1) Safari works good, but in cordova app pdf is not show
