### ISSUE TITLE
Accessing PDF properties typescript example

### ISSUE THREAD

**Issue by ctbolton** [VadimDez/ng2-pdf-viewer#24]
Is there a typescript example for accessing the pdf properties?  Specifically i'd like to get the numPages property so i can restrict the previous and next buttons and only show them if there is a next or previous page.  I noticed the app.component.js does this through an onLoadComplete binding to a "pdf" variable and is accessed by doing it thru {{ pdf?.numPages }}.  Could we get an example of this using typescript?  Thanks much!

**Comment by VadimDez** [comment]
Did you try to pass callback to ```[on-load-complete]``` ? There you can get ```pdf``` once it's loaded. See https://github.com/VadimDez/ng2-pdf-viewer#on-load-complete

**Comment by ctbolton** [comment]
Thanks Vadim.  I did try that.  I can see the number of pages from the PDF in the on-load-complete function but the UI isnt showing the update.  I'm sure it has to do with it updating after the UI has already completed rendering or a parent/child type scope issue.  I've tried using the NgZone as well as some other "digest update" type features as well, but can't seem to get it to work.

**Comment by VadimDez** [comment]
It may be because you didn't bind the callback function, did you?
Otherwise show what are you trying to do in the callback function.

**Comment by ctbolton** [comment]
Thanks Vadim.  I took another look at your latest check in for the zoom property and got it working.  Thanks again for the super fast response!

**Comment by nessgor** [comment]
Hello @VadimDez I got a similar issue
```
  pdfDidLoad(pdf: any) {
    this.totalPages = pdf.numPages;
    console.log(this);
    console.log(pdf);
  }
```
I want to retrieve the numPages variable and set to the totalPages variable to my own class 
but "this." is referencing to the PDFViewerComponent Class, not my own class

![image](https://cloud.githubusercontent.com/assets/11316684/19919347/1af38d6e-a10d-11e6-9c7c-7f86586c601e.png)

any hints or clues how to do this? thanks very much !

**Comment by VadimDez** [comment]
@nessgor, did you bind ```pdfDidLoad``` function to your class ?

**Comment by nessgor** [comment]
Don't know how to bind the pdfDidLoad function to my class, by adding the [(on-load-complete)] ??

pdf.html
```
<ion-header>
	<ion-toolbar>
		<ion-buttons left>
			<button ion-button (click)="dismiss()">
        <ion-icon name="arrow-round-back"></ion-icon>
      </button>
		</ion-buttons>
		<ion-title>
			{{name}}
		</ion-title>
	</ion-toolbar>
</ion-header>

<ion-content scroll="false">
	<ion-scroll class="zoom-pane" scrollX="true" scrollY="true" zoom="true" maxZoom="3">
		<pdf-viewer [src]="pdfSrc" [page]="page" [original-size]="true" [zoom]="zoom" [show-all]="false" [on-load-complete]="pdfDidLoad"></pdf-viewer>
	</ion-scroll>
</ion-content>

<ion-footer>
	<ion-item>
		<ion-range min="1" [max]="totalPages" step="1" snaps="true" color="secondary" [(ngModel)]="page">
			<ion-label range-left>
				<button ion-button (click)="prevPage()">
					<ion-icon name="arrow-round-back"></ion-icon>
				</button> 1
			</ion-label>
			<ion-label range-right>
				{{totalPages}}
				<button ion-button (click)="nextPage()">
          			<ion-icon name="arrow-round-forward"></ion-icon>
        		</button>
			</ion-label>
		</ion-range>
	</ion-item>
</ion-footer>
```

pdf.ts
```
import { Component } from '@angular/core';
import { NavParams, NavController, LoadingController } from 'ionic-angular';
import { URL } from '../../url';

@Component({
  selector: 'page-pdf',
  templateUrl: 'pdf.html'
})

export class PDFContentPage {
  name: string;
  pdfSrc: string;
  zoom: number = 0.9;
  page: number = 1;
  totalPages: number;
  loading: any;

  constructor(
    public params: NavParams,
    public navCtrl: NavController,
    public loadingCtrl: LoadingController,
  ) {
    this.name = this.params.get('name');
    this.pdfSrc = URL.BASE_URL + this.params.get('url');

    this.loading = this.loadingCtrl.create({
      content: 'Loading pdf...',
      spinner: "crescent",
      dismissOnPageChange: false,
      duration: 5000
    });
    this.loading.present();
  }

  dismiss() {
    this.navCtrl.pop();
  }

  prevPage() {
    if (this.page > 1) {
      this.page--;
    }
  }
  nextPage() {
    if (this.page < this.totalPages) {
      this.page++;
    }
  }

  pdfDidLoad(pdf: any) {
    this.totalPages = pdf.numPages;
    console.log(this);
    console.log(pdf);
  }

  ionViewDidEnter() {
    this.loading.dismiss();
  }

}
```

**Comment by VadimDez** [comment]
You need to add to the `constructor` of ```PDFContentPage```:
```ts
this. pdfDidLoad = this.pdfDidLoad.bind(this);
```

**Comment by nessgor** [comment]
It works!! thanks a lot !!
