### ISSUE TITLE
Cannot read property 'getPage' of undefined

### ISSUE THREAD

**Issue by muhammadali208** [VadimDez/ng2-pdf-viewer#240]
i have installed 3.0.5 ng2-pdf-viewer version and still getting this error.
i was hoping this error was resolve in previous versions.

**Comment by penkin** [comment]
I seem to get the same issue. Any resolution on this.

**Comment by dalbir** [comment]
I think you have something missing in npm package.

**Comment by muhammadali208** [comment]
@dalbir can you please tell me what am i missing in npm package.

**Comment by dalbir** [comment]
pdfjs-dist and @types/pdf are the dependency, you need to install these packages also.

**Comment by VadimDez** [comment]
@dalbir no you don't need to install it manually, it will be installed automatically by installing `ng2-pdf-viewer` as it depends on it.

**Comment by muhammadali208** [comment]
@VadimDez please suggest me a solution. my project deadline is very close.

**Comment by VadimDez** [comment]
@muhammadali208 please provide more details such as how you use this module or just show some code.
You can as well check the demo project and how to use `pdf-viewer` component:
https://github.com/VadimDez/ng2-pdf-viewer/tree/master/src/app

**Comment by dalbir** [comment]
@VadimDez I don't know the reason but some time npm missed to add the dependency in package.config and in that case I have to clean npm cache and then install these dependency manually. One of my colleague have same problem. @muhammadali208 I suggest you just clean the npm cache and trying to install again, and check the installation in ng_module folder.

**Comment by LukasKlement** [comment]
@dalbir Thanks, running `npm cache verify` and deleting/reinstalling all dependencies did the trick.
