### ISSUE TITLE
multiple component with same src

### ISSUE THREAD

**Issue by Ayrel** [VadimDez/ng2-pdf-viewer#242]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
When I load 2 components of pdf-viewer with the same (or similar) pdf source The second component never renders. Only The loading icon is displayed. 

see my example [here](https://github.com/Ayrel/ng2-pdf-viewer-multiple)

**Comment by serkanferat** [comment]
+ 1 I have the same problem. When you try to render 2 or more pdfs in one page (i am using tabs), the second, third pdfs are not loaded, they remain in the loading phase. Please advise, thank you.

**Comment by annajjj** [comment]
I have the same problem. When I've got one or more pdfs not all of them are rendered. Did anyone find sollution for this issue?

**Comment by serkanferat** [comment]
Yes. Load only one instance of the pdf viewer but change the src dinamically :)

**Comment by annajjj** [comment]
Thanks for your answer. Yes, it works, but I need to have all pdfs listed.

**Comment by cmnajs** [comment]
Hi! I am using version 5.2.3 and facing the same issue. Any ideas on how to get this working. Thanks.
