### ISSUE TITLE
Same url download multiple times

### ISSUE THREAD

**Issue by vincent-cm** [VadimDez/ng2-pdf-viewer#243]
When rendering a specific 100 pages from 1000 pages pdf, the 100 pages need to render separately using [page] = index; But these 100 pages need to download from server or browser cache 100 times. Can you please suggest how to load the pdf file only once within one file?

**Comment by leonardosalles** [comment]
There's no magic in ng2-pdf-viewer, you will need to merge it as one file and the correct way is to do an api that can do this for you and just deliver one pdf with all pages.

**Comment by vincent-cm** [comment]
I modified the src code and it works like a charm!

```
this.lastLoaded = this._appState.state['pdfCache'];

if (this.lastLoaded && this.src && this.lastLoaded['url'] == this.src['url']) {
      this._pdf = this._appState.getPdfCache(this.lastLoaded['url']);
      this.afterLoadComplete.emit(this._pdf);

      this.update();
      return;
    }


(<PDFPromise<PDFDocumentProxy>>loadingTask.promise)
      .then((pdf: PDFDocumentProxy) => {
        this._pdf = pdf;
        this.lastLoaded = src;

        this._appState.set('pdfCache', src);
        this._appState.setPdfCache(src['url'], pdf);

        this.afterLoadComplete.emit(pdf);

        this.update();
      }, (error: any) => {
        this.onError.emit(error);
      });
```

**Comment by leonardosalles** [comment]
Nice, but I think it is not a good practice to make it in frontend but if you have no choice good work ;)

PS: don't forget to close the issue if you find a solution and if there's no solution from/with this plugin.
