### ISSUE TITLE
@types/pdf should not be a hard dependency

### ISSUE THREAD

**Issue by jsgoupil** [VadimDez/ng2-pdf-viewer#246]
Recently, this happened: https://github.com/VadimDez/ng2-pdf-viewer/pull/238/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

This put the @types/pdf in the `peerdependencies` and `dependencies`. I am not super familiar on how to develop a plugin, but rarely I see plugins shipping with a hard `dependency` on things.

I depend myself on `@types/pdf`, so now I receive the following error:

    ERROR in node_modules/@types/pdf/index.d.ts(476,13): error TS2451: Cannot redeclare block-scoped variable 'PDFJS'.
    node_modules/ng2-pdf-viewer/dist/index.d.ts(4,11): error TS2451: Cannot redeclare block-scoped variable 'PDFJS'

Can something be done to prevent this?

**Comment by VadimDez** [comment]
Have you tried latest version `3.0.6`? Do you get the same error?

**Comment by jsgoupil** [comment]
Yes, same thing.

**Comment by VadimDez** [comment]
Can you try deleting `node_modules` and re-instalingl then? Because version `3.0.6` does not use `@types/pdf` anymore, so the error should disappear.

**Comment by jsgoupil** [comment]
Still not working.

    ERROR in node_modules/@types/pdf/index.d.ts(476,13): error TS2451: Cannot redeclare block-scoped variable 'PDFJS'.
    node_modules/ng2-pdf-viewer/dist/index.d.ts(4,11): error TS2451: Cannot redeclare block-scoped variable 'PDFJS'.

**Comment by mcodev1** [comment]
Deleting `node_modules/@types/pdf/` solved this for me.
