### ISSUE TITLE
Unit tests fails on "Binding to event attribute 'on-load-complete' is disallowed for security reasons"

### ISSUE THREAD

**Issue by daBishMan** [VadimDez/ng2-pdf-viewer#25]
I am using Angular 2.0.0, I am trying to write a unit test, I have ` [on-load-complete]="onLoadComplete"` in my HTML template when i try to run my test the error 

> Binding to event attribute 'on-load-complete' is disallowed for security reason

my test is basically trying to create the component that the viewer is impeded in.

` it('should create an instance', () => {
    expect(profileResumeComponent).toBeTruthy();
  });`

Any suggestions?

**Comment by VadimDez** [comment]
@daBishMan, Thanks! I'll change the name, since it starts with "on"...
https://github.com/angular/angular/blob/2300c23332fe8a61427562770fb4e1911aad6e2e/modules/%40angular/compiler/src/template_parser/template_parser.ts#L905-L912
