### ISSUE TITLE
Cannot get viewer to scale different size PDF pages to page width

### ISSUE THREAD

**Issue by AndrWeisR** [VadimDez/ng2-pdf-viewer#251]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I am using the viewer (3.0.8) to view PDF documents where the document pages are different widths.

My HTML is:

`<pdf-viewer [src]="pdf" [page]="page" [original-size]="false" style="display: block;max-width: 300px"></pdf-viewer>`

I can get the first page to scale to the width of my container, but as I scroll down the document and arrive at one of the wider pages in the document, it no longer fits within my container width, and you have to scroll the viewer horizontally to view the whole page width. Is it possible to have the viewer zoom automatically changed to fit the widest page in the document (like Adobe Reader does)? I have tried all sorts of combinations of `original-size`, `fit-to-page` and `auto-resize`, but nothing makes any difference.

**Comment by kreuzersteve** [comment]
Push - I'm having similar issues where I load different pdfs and for some of them I have to scroll vertically despite having fixed width on my container element.

**Comment by morinrod-cardioscan** [comment]
Got the same problem,I have pdf with several pages with different sizes. I set [show-all]="true" and all the classes - canvasWrapper,page,textLayer and canvas element to have {width: 100% !important;
height: 100% !important;} and it's working fine.
But when [show-all]="false" the pdf gets the height property to be 0px - not displayed.
