### ISSUE TITLE
onProgress event not deterministic

### ISSUE THREAD

**Issue by m00dy** [VadimDez/ng2-pdf-viewer#253]
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request

****
Hey,

I use onProgress event to calculate loaded percentage of pdf files. This event basically fires two properties { loaded, total }. 

if(event.loaded === event.total) {
// this block is not deterministic and sometimes it stalls
}

**Comment by danielkuhlwein** [comment]
I am facing the same issue. I'd like to animate a progress spinner to show how much of the pdf has loaded, but the onProgress callback only ever fires 4 times right at the very end of the pdf actually loading.

It seems to be the same 4 values every time, with the last value repeating itself.

**Comment by VadimDez** [comment]
What version of `pdf-viewer` are you using?

**Comment by danielkuhlwein** [comment]
3.0.8
