### ISSUE TITLE
Pdf viewer with custom css

### ISSUE THREAD

**Issue by sajagekar** [VadimDez/ng2-pdf-viewer#256]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Feature request
```
I am trying to show pdf content as html and want to apply custom styles to the content to adhere it with website styling. Is there any way to do that. I have tried to change font and color but it is not working.

**Comment by VadimDez** [comment]
Could you please explain what do you mean by changing font and color? Maybe describe a use case as well.

**Comment by sajagekar** [comment]
Sorry for late reply,

I have dynamically generated pdf's , which has html content, My use case is to read that content and show it on UI with styling as per website (want to change font colour with custom)

**Comment by Ncsabak** [comment]
Hello!
I would like to show pdf with transparent background, because I want to use the whole page background. How can I do this? Thank you!
