### ISSUE TITLE
Remove Cloudflare Dep

### ISSUE THREAD

**Issue by yadbo** [VadimDez/ng2-pdf-viewer#266]
Hello there,

why is the reader getting external ressource and how can I avoid this? This is important because the app is going to work offline, and when I turn my internet off I can still use the viewer.

https://cdnjs.cloudflare.com/ajax/libs/pdf.js/1.9.489/pdf.worker.min.js

Any help? Thanks in advance.

**Comment by VadimDez** [comment]
You can overwrite path to the worker:
https://github.com/VadimDez/ng2-pdf-viewer#set-custom-path-to-the-worker
