### ISSUE TITLE
Error Reading PDF On Android, Cannot read property 'reject' of undefined

### ISSUE THREAD

**Issue by dalezak** [VadimDez/ng2-pdf-viewer#270]
I am trying to read a PDF I've downloaded locally in `Ionic 3.9.2` on Android, but getting the following error:

```
TypeError: Cannot read property 'reject' of undefined
at Object.PDFNetworkStreamFullRequestReader_onError
at XMLHttpRequest.NetworkManager_request.xhr.onerror
at XMLHttoRequest.H
at t,invokeTask
at Object.onInvokeTask
at t.invokeTask
at r.runTask
at e.invokeTask
at p
at XMLHttpRequest.v 
```

The file path looks something like
```
file:///storage/emulated/0/Android/data/my.app.id/files/434307d2992efdf4324f62db1cd7c1a8.pdf
```

![screenshot_1518013835](https://user-images.githubusercontent.com/91811/35921908-a61ac070-0be1-11e8-9e8f-c3ca6415a1a0.png)

The same code works fine on iOS, but fails on Android. Any idea what's wrong?

##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

**Comment by dalezak** [comment]
Any idea @VadimDez what's causing issues with loading PDFs on Android?

**Comment by dalezak** [comment]
Looks like my issue is related to `ng2-pdf-viewer` not being able to support `file://` URL scheme, as @zepedrorocha points out in https://github.com/VadimDez/ng2-pdf-viewer/issues/180#issuecomment-337673418.

**Comment by dalezak** [comment]
Closing issue, duplicate of #180 and #212.

**Comment by qwerqwermhc** [comment]
@dalezak  
Are you there, can you show me your code? I also encountered the same problem as you.
Have you solved it?
Ionic 3.9.2 on Android  me too
I can look at your ts file. How is pdfsrc converted?
Or can you take the time to send me an email? 1334361387@qq.com Show me your relevant code. Thank you very much.
