### ISSUE TITLE
PDFJS prebuilt is pinned

### ISSUE THREAD

**Issue by eseliger** [VadimDez/ng2-pdf-viewer#272]
Is there any reason, that the pdfjs version is pinned? I couldn't find any issue regarding this, but the current version uses worker-loader 0.8.1, which is officially not supporting webpack 3, which is the default when building with `@angular/cli`. Wouldn't it be much more flexible, if pdfjs would be just a `peerDependency`? 
Maybe I'm missing something and there is an incompatibility between this module and the never versions, but if not it'd be awesome if the pdfjs module would get updated :)

**Comment by VadimDez** [comment]
The `worker-loader` package shouldn't be a problem - it's not used in the `pdf-viewer`.
There are some regression issues, like this one https://github.com/mozilla/pdf.js/issues/9103
But once solved i can then change the version. 
There was as well the request to pin it https://github.com/VadimDez/ng2-pdf-viewer/issues/168

**Comment by eseliger** [comment]
Thats why I was thinking of adding PDFjs as a `peerDependency`, so people can 
- decide which version is the most stable for their use-case
- pin it _themselves_ (so #168) is solved automatically
- change to pre-release versions, if there should ever be some 

Let me know what you think!
