### ISSUE TITLE
help to set custom worker path

### ISSUE THREAD

**Issue by BBr4him** [VadimDez/ng2-pdf-viewer#277]
Hi, can you help me to set a custom worker path because i followed your instructions and the worker is loaded correctly on the page from the custom path, but the pdf is not showing correctly and there is no errors logged on console.

can you halp me with that? showing me an example?

**Comment by VadimDez** [comment]
Could you provide screenshots showing correct and incorrect rendered PDFs?

**Comment by BBr4him** [comment]
![screen](https://user-images.githubusercontent.com/30289709/36140980-748338b4-10a3-11e8-813b-cf842b132398.PNG)

As you can see on the screen the worker is loaded but the pdf is not showing.
the thing that i don't understand is when call "setCustomWorkerPath()" in this case i call it on my app.component constructor.

**Comment by VadimDez** [comment]
And how about your HTML? Is the `pdf-viewer` there and it contains something inside?

**Comment by BBr4him** [comment]
![htmlscreen](https://user-images.githubusercontent.com/30289709/36143614-e06e432c-10ab-11e8-9d8f-a563c939ed3c.PNG)
as you can see there's no pdf pages loaded.
with the cdn worker version it works correctly so i don't think it's a html or css problem.

**Comment by VadimDez** [comment]
Ok, then what's the location of `pdf worker` you're trying to set?

**Comment by BBr4him** [comment]
this is the fucntion:
`constructor( ) {
    this.setCustomWorkerPath();
  }

setCustomWorkerPath() {
    (<any>window).PDFJS.workerSrc = './assets/js/pdf.worker.js';
  }`

i don't know if i'm doing correct like that.

**Comment by VadimDez** [comment]
Can you see as well in the "Network" tab whether the pdf worker is loaded or not?

**Comment by BBr4him** [comment]
i resolved the problem was that i use the last version of pdfjs (2.0.363) and you required an old version (1.9.489).
i don't know why it doesn't work.
thank you for your support, for now i'll not update pdfjs i'll try in the future

**Comment by VadimDez** [comment]
There're some breaking changes in pdfjs between version 1 and 2.

**Comment by VadimDez** [comment]
@ihorbond Actual readme is for the latest version. See documentation for the `3.0.8` Setting custom workerSrc was a bit different  https://github.com/VadimDez/ng2-pdf-viewer/tree/c35b3fa4fc114934ef4f89ff72deb99be976cd85#set-custom-path-to-the-worker
