### ISSUE TITLE
How to a blob to on a new tab

### ISSUE THREAD

**Issue by santosmken** [VadimDez/ng2-pdf-viewer#282]
Hello I just have a question on how can I load the pdf (a blob) to a new tab after I click a button.  So here is the scenario, I have a table that contains a lists of information with pdf icon and what I want to achieve is when I click the icon it should open to a new tab and will display the pdf instead of downloading it. This is my sample code on my project.

`this.http.get(document.url, {responseType: 'blob'})
        .subscribe((file: any) => {
          this.pdfSrc = new Uint8Array(file);
        })`

the _document.url_ is the blob file.

**Comment by VadimDez** [comment]
I'm not sure how this is related to `pdf-viewer`

**Comment by DejanVuj** [comment]
Something like:

```
let blob = new Blob([response], {type: 'application/pdf'}); // if you want to download it, use saveAs(blob, filename);
let pdf = URL.createObjectURL(blob); // if you want to display somewhere on the page.
```

Now you can do whatever you want with pdf, to download, or display.

**Comment by santosmken** [comment]
@DejanVuj should I do the second thing you suggested? If yes I tried it but doesn't work for me and I received this error 

> to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
