### ISSUE TITLE
Open password protected PDF

### ISSUE THREAD

**Issue by VadimDez** [VadimDez/ng2-pdf-viewer#283]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```

**Comment by VadimDez** [comment]
You can provide password for password protected pdf:
```html
<pdf-viewer [src]="{ url: './assets/pdf-example-password.original.pdf', password: 'test' }"></pdf-viewer>
```

**Comment by 1ankit8** [comment]
how do i open a password protected file in my file system.
my .ts file reads =>
```
onError(error){
    console.log('error',error);
  }
  onFileSelected(){
    let img:any = document.querySelector("#file");
    if(typeof(FileReader) !== undefined){
      let reader = new FileReader();
      reader.onload = (e:any) =>{
        this.pdfSrc = {url:e.target.result, password:'test'}
      }

      reader.readAsArrayBuffer(img.files[0]);
    }
  }
```

and .html file reads =>

```
<div>
  <label>PDF src</label>
  <input (change)="onFileSelected()" type="file" id="file">
  <input [(ngModel)]="page" type="text" id="page">
</div>
<pdf-viewer [src]="pdfSrc" 
          [render-text]="true"
          [page]="page"
          [show-all]="false"
          style="display: block;"
          (error)="onError($event)"
></pdf-viewer>
```

**Comment by vijay-flexiloans** [comment]
> You can provide password for password protected pdf:
> 
> ```
> <pdf-viewer [src]="{ url: './assets/pdf-example-password.original.pdf', password: 'test' }"></pdf-viewer>
> ```

Hi, thanks!
Is there a way to know if the file is password protected? (like any callback/notification/msg/etc) 

For now, if the file is password protected and we don't pass any password then it shows a blank screen without any pop-up or anything. (works as expected when the password is passed i.e renders pdf)

Hope you are getting the question.

**Comment by vijay-flexiloans** [comment]
> > You can provide password for password protected pdf:
> > ```
> > <pdf-viewer [src]="{ url: './assets/pdf-example-password.original.pdf', password: 'test' }"></pdf-viewer>
> > ```
> 
> Hi, thanks!
> Is there a way to know if the file is password protected? (like any callback/notification/msg/etc)
> 
> For now, if the file is password protected and we don't pass any password then it shows a blank screen without any pop-up or anything. (works as expected when the password is passed i.e renders pdf)
> 
> Hope you are getting the question.

Okay I figured out that there are few callback methods, but the error callback returns undefined on failed pwd case.

**Comment by vijay-flexiloans** [comment]
> how do i open a password protected file in my file system.
> my .ts file reads =>
> 
> ```
> onError(error){
>     console.log('error',error);
>   }
>   onFileSelected(){
>     let img:any = document.querySelector("#file");
>     if(typeof(FileReader) !== undefined){
>       let reader = new FileReader();
>       reader.onload = (e:any) =>{
>         this.pdfSrc = {url:e.target.result, password:'test'}
>       }
> 
>       reader.readAsArrayBuffer(img.files[0]);
>     }
>   }
> ```
> 
> and .html file reads =>
> 
> ```
> <div>
>   <label>PDF src</label>
>   <input (change)="onFileSelected()" type="file" id="file">
>   <input [(ngModel)]="page" type="text" id="page">
> </div>
> <pdf-viewer [src]="pdfSrc" 
>           [render-text]="true"
>           [page]="page"
>           [show-all]="false"
>           style="display: block;"
>           (error)="onError($event)"
> ></pdf-viewer>
> ```

Did you get any solution on this? trying the same..

**Comment by vijay-flexiloans** [comment]
> > how do i open a password protected file in my file system.
> > my .ts file reads =>
> > ```
> > onError(error){
> >     console.log('error',error);
> >   }
> >   onFileSelected(){
> >     let img:any = document.querySelector("#file");
> >     if(typeof(FileReader) !== undefined){
> >       let reader = new FileReader();
> >       reader.onload = (e:any) =>{
> >         this.pdfSrc = {url:e.target.result, password:'test'}
> >       }
> > 
> >       reader.readAsArrayBuffer(img.files[0]);
> >     }
> >   }
> > ```
> > 
> > 
> > and .html file reads =>
> > ```
> > <div>
> >   <label>PDF src</label>
> >   <input (change)="onFileSelected()" type="file" id="file">
> >   <input [(ngModel)]="page" type="text" id="page">
> > </div>
> > <pdf-viewer [src]="pdfSrc" 
> >           [render-text]="true"
> >           [page]="page"
> >           [show-all]="false"
> >           style="display: block;"
> >           (error)="onError($event)"
> > ></pdf-viewer>
> > ```
> 
> Did you get any solution on this? trying the same..

I got the answer[use 'data' as the key] :
this.pdfSrc = {data: e.target.result, password: 'test'};

**Comment by Sathishchary** [comment]
@VadimDez Even I am unable to get the correct error message. so i can't show the password prompt correctly. any work around for this issue?

  ` this.pdfSrc = { url : URL.createObjectURL(result.body) };`

here body is blob object. 

if i set pdf url from assets folder its correctly showing the error message` error['name'] === 'PasswordException'`, 
can you please give any solution ?
