### ISSUE TITLE
Producing massive webpack bundles

### ISSUE THREAD

**Issue by citizentim** [VadimDez/ng2-pdf-viewer#284]
Thanks very much for this great library!

Using version 4.1.2 of ng2-pdf-viewer, it seems to be producing enormous bundles using "ng-build --prod --aot" (using Angular 5.2 and CLI 1.7.1).  Webpack-bundle-analyzer tells me that under *.chunk.js - pdf.worker.js is 1.42 MB and in the main bundle, pdf.js is using 573 K. (screenshot attached).

I found [this](https://github.com/VadimDez/ng2-pdf-viewer/issues/146) issue where it was marked as addressed but I've been unable to reduce the size in my case.  

I'm certainly open to the possibility that I'm doing something wrong, but I can't think of what.

**Comment by VadimDez** [comment]
Are you using custom `workerSrc` for `pdf worker`? Are you using `default path` that gets pdf worker from https://cdnjs.cloudflare.com ?

**Comment by citizentim** [comment]
I've tried it without workerSrc and also with workerSrc.  My current is:

`(<any>window).PDFJS.workerSrc = '/node_modules/pdfjs-dist/build/pdf.worker.min.js';`

But that is a directive for the browser.  I don't think it would have any effect on the AOT compiler.

**Comment by citizentim** [comment]
Sure thing; the network tab shows that *chunk.js is not being loaded, but /resources/pdf.worker.min.js is.

**Comment by VadimDez** [comment]
I guess pdf.worker.js chunk is loaded (fallback) only when pdf worker is disabled

**Comment by citizentim** [comment]
Are you referring to pdf webworker?  As in, if webworker is disabled, it will use the chunk to render in the normal browser js thread?

**Comment by citizentim** [comment]
I guess since it isn't being loaded anyway, it isn't really a problem.  I'll just stick with dumping the minified worker in my resources dir and pointing to it.


Along the lines of the bundle size, there's one thing I'd like to request: could you please provide a way to disable the import of of compatibility.js?  My Angular application only supports the latest Firefox and Chrome releases, so I have no need for it to be there.  Anywhere I can save space on my bundle size is a good thing :)

**Comment by citizentim** [comment]
Closing issue as I will now just load worker_min.js from my resources/ dir, and the worker chunk should never get loaded by the client browser.

**Comment by GauravThakur03** [comment]
Try Adobe Embed APIs: https://www.adobe.com/devnet-docs/dcsdk_io/viewSDK/index.html
- Much smaller
- Easy to integrate
- Much better PDF View quality
- Lots of PDF features
