### ISSUE TITLE
SystemJS setup fails with: Module not already loaded loading "pdfjs-dist/build/pdf"

### ISSUE THREAD

**Issue by stefanocke** [VadimDez/ng2-pdf-viewer#288]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Please see  https://plnkr.co/edit/FlKqlLYXVaaHkvvdR8Cg
ng-pdf-viewer version: 4.1.2  (but likely already since 4.0.0 ?)

It works, if I set module format of ng-pdf-viewer to cjs.  But: Is this the proper approach?  
https://github.com/VadimDez/ng2-pdf-viewer/blob/master/SYSTEMJS.md does not say so...

```packages: {
    app: {
      main: './main.ts',
      defaultExtension: 'ts'
    },
    rxjs: {
      defaultExtension: 'js'
    },
    'ng2-pdf-viewer': {
      format: 'cjs'
     }
```

**Comment by stefanocke** [comment]
@VadimDez ,  I saw your thumbs up in #280 for cjs module format.
So, I guess, only the documentation update is open...

**Comment by jayasris** [comment]
I am trying to run ng2-pdf-viewer(version 5.1.1) with systemJS(0.19.40). I am not able to get it working. I get zlib unavailable errors & does not bring up the PDF. Are there other dependencies that need to be added? Are you able to share the system.js.config file pertinent to the ng2-pdf-viewer? Thanks much appreciated
