### ISSUE TITLE
Make text selectable ?

### ISSUE THREAD

**Issue by Vi-dot** [VadimDez/ng2-pdf-viewer#29]
Hello, 

I don't know if it's because ng2-pdf-viewer use a canvas, but we can't select text in the pdf viewer.
Someone has an idea to make it available ?

Thanks

**Comment by VadimDez** [comment]
Similar to #18

**Comment by mmaclach** [comment]
i've implemented this in a project, can add as a pr

**Comment by Vi-dot** [comment]
Yes please :) Could you do that ? Or push it on your fork

**Comment by VadimDez** [comment]
@mmaclach, sure, that would be great!

**Comment by mmaclach** [comment]
hey guys, i've added a pr with a solution - I'm not certain it will work for every case

**Comment by Vi-dot** [comment]
Hello !
Thanks for your help mmaclach.
But there is a bug. Selected text doesn't fit well the rendered layer.
[screenshot](mg11.hostingpics.net/pics/179843bugtextselectpdfviewer.png)

Can we use the text inside the rendered layer ?
In this [demo](https://mozilla.github.io/pdf.js/web/viewer.html) of pdf.js, you can select text.

**Comment by Vi-dot** [comment]
I succeed using pdf_viewer part of pdfjs.
Here is a [screenshot](http://hpics.li/21a5685)
I'm going to clean my fork and make a pull request.

Using this pdf_viewer part is going to help for others issues (like hyperlinks, dynamic zoom..).
We also have to make our fork of @types/pdf.

**Comment by mmaclach** [comment]
hey @Vi-dot - I am using a slightly different configuration in my project so the styling may be slightly off. I think @VadimDez is fixing it in master

**Comment by Vi-dot** [comment]
Ok mmaclach,
I guess you took time to achieve that,
But, do you don't think that ? > it's better to use what it's already in pdfjs

It's also better for element accessing in debug mode, because I don't have canvas any more.

**Comment by mmaclach** [comment]
Maybe you're misunderstanding me, this is from pdfjs, using the textContent() from the page and creating svg:text objects. If you wanted to you could create html instead. However I think for some pdf documents the text content may not exist

**Comment by Vi-dot** [comment]
Hello,
@mmaclach I understood clearly your way. But it's still not perfect, in the [example](https://vadimdez.github.io/ng2-pdf-viewer/), selection fits not well text.
In fact, from pdfjs you only get raw text. Integration and style are not from pdfjs.

@VadimDez Using PDFPageView solves this and may solve other issues (dynamic update viewport - usefull for big pdf, hyperlinks)
I made a try on this [branch](https://github.com/Vi-dot/ng2-pdf-viewer/tree/page-view-way). If you like I can make a pull request.

**Comment by Vi-dot** [comment]
@mmaclach @VadimDez 
I put a demo online to show you : [https://vi-dot.github.io/ng2-pdf-viewer/](https://vi-dot.github.io/ng2-pdf-viewer/)

**Comment by VadimDez** [comment]
@Vi-dot Looks great! Is there any way to get it work with fake worker? Would simplify integration.
Thanks a lot, make a PR, so that i can merge it.

**Comment by Vi-dot** [comment]
What do you mean by fake worker ?
You may talk about this
`PDFJS.workerSrc = 'lib/pdfjs-dist/build/pdf.worker.js';`
If it's not defined, it can't work, I tried.

But the PDFPageView way may be not perfect. Now I'm trying to have a dynamic zoom (without reloading pdf), it works, but textLayer disapear with this method.
I opened an [issue on pdfjs](https://github.com/mozilla/pdf.js/issues/7871), PDFJS.PDFViewer may be better. I didn't try yet.

**Comment by mmaclach** [comment]
looks good, I wasn't aware of PDFPageView

**Comment by VadimDez** [comment]
@Vi-dot right now it's working with fake worker. I think with `PDFJS.disableWorker = true` you can enable fake worker, otherwise you have to specify worker, like you did, by providing path for `pdf.worker.js`.

**Comment by dean9812** [comment]
- How to select and copy a text after converted into canvas?
- How to avoid right side and bottom gets trim?

Help me out of this. Thanks in advance.
