### ISSUE TITLE
pdf not rendering correctly if element is hidden

### ISSUE THREAD

**Issue by kevupton** [VadimDez/ng2-pdf-viewer#294]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

PDF does not render to the right size if it is not visible by default.
(If it is hidden from a parent ngIf)

I am having to manually call update size after it is showing on the page.

**Comment by mpsycho** [comment]
We have identified a similar issue with the pdf rendering process when the component, or any parent element containing it, becomes hidden (via css) before the rendering is over.
In detail, we need to be able to hide the pdf-viewer component regardless of the pdf rendering process.

**Comment by Maikkiczk** [comment]
My use case is probably different from yours but I will still expose it to you perhaps to provide one or two ideas.

We only had to render the pdf-viewer when it completely rendered all the pages and we encountered the same problem as yours using the ngIf or even the hidden property.

The temporary fix we used is to use the css visibility property to hide or display the rendering of the component. Like this, we were able to hide the rendering of the pdf-viewer until it was finished and display a loader instead.

I hope I could give you some tips.

**Comment by kevupton** [comment]
I wrote a temporary fix for this.
Basically I created a component that watches to see if the element is attached to the body. If it is, then call an update on the pdfViewer

```ts
import { AfterViewChecked, Component, ElementRef, Input, ViewChild } from '@angular/core';
import { PdfViewerComponent as PdfViewer } from 'ng2-pdf-viewer';

@Component({
  selector: 'app-pdf-viewer',
  templateUrl: './pdf-viewer.component.html',
  styleUrls: ['./pdf-viewer.component.less'],
})
export class PdfViewerComponent implements AfterViewChecked {
  @Input()
  src = null;

  private _init = false;

  @ViewChild(PdfViewer)
  private pdfViewer: PdfViewer;

  constructor(
    private ref: ElementRef) {
  }

  update() {
    this.pdfViewer.updateSize();
  }

  ngAfterViewChecked(): void {
    let current: HTMLElement = this.ref.nativeElement;
    let parent = null;

    do {
      current = current.parentElement;
      parent = current;

      if (parent === document.body) {
        this.init();
      }
    } while (current);
  }

  init() {
    if (this._init) {
      return;
    }

    this._init = true;
    this.update();
  }

}
```

**Comment by Maikkiczk** [comment]
Yyou can also use the Mutation Observer to detect a change on the DOM

**Comment by JCepedaVillamayor** [comment]
You saved my day @kevupton works like a charm!!

Thanks a lot
