### ISSUE TITLE
Feature Request: Option to disable import of compatibility.js

### ISSUE THREAD

**Issue by citizentim** [VadimDez/ng2-pdf-viewer#297]
I'd like to request the ability to disable the import of compatibility.js.  This is only needed for legacy browser support, and as my Angular app by design does not support these browsers, this import is superfluous and serves only to increase the size of the output bundle.

Thank you for your consideration and the hard work!

**Comment by VadimDez** [comment]
Version `5.0.1` doesn't use `compatibility.js` anymore
