### ISSUE TITLE
How to stretch the PDF to full width of container element?

### ISSUE THREAD

**Issue by uberspeck** [VadimDez/ng2-pdf-viewer#298]
##### Bug Report or Feature Request (mark with an `x`)
```
- [x] Documentation issue or request
```
My goal is to stretch the PDF to the full width of it's container. Regardless of the settings I use or CSS I apply I'm not getting anywhere.

**Comment by borys-kupar** [comment]
Have you tried setting [[original-size]="false"](https://github.com/VadimDez/ng2-pdf-viewer#original-size), and a fixed width to a container element?

**Comment by alex88** [comment]
I've tried that to shrink the pdf and fit to screen but it doesn't seems to be working

**Comment by VadimDez** [comment]
Have you tried to set `fit-to-page` ?
https://github.com/VadimDez/ng2-pdf-viewer#fit-to-page

**Comment by alex88** [comment]
I was missing the `display: block`, using that plus `[original-size]="false" [autoresize]="true"` works! thanks
