### ISSUE TITLE
Cannot find module 'pdfjs-dist'

### ISSUE THREAD

**Issue by lukaszbaranski** [VadimDez/ng2-pdf-viewer#3]
Hi,
When I cloned the repo I encountered that issue. "Cannot find module 'pdfjs-dist'." in the module.
What more I need to do beside npm install, typings and gulp compiler? 

![image](https://cloud.githubusercontent.com/assets/11609088/17507651/20f5eeda-5e11-11e6-832d-e03041fc6281.png)

![image](https://cloud.githubusercontent.com/assets/11609088/17507667/3c694d60-5e11-11e6-8020-909da21ef58a.png)

Thanks,
Lukasz

**Comment by VadimDez** [comment]
Hi, Lukasz,
if you want to run it locally after installing packages and typings 

```
npm i && npm run typings
```

run

```
npm run all
```

Hope that helps
