### ISSUE TITLE
ng2-pdf-viewer dependencies have conflicts with webpack >= 3

### ISSUE THREAD

**Issue by iexela** [VadimDez/ng2-pdf-viewer#302]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```

When I try to install `ng2-pdf-viewer@4.1.2` in the project having `webpack@3.10.0` npm logs the following error: 
```
npm WARN worker-loader@0.8.1 requires a peer of webpack@>=0.9 <2 || ^2.1.0-beta || ^2.2.0 but none was installed.
```
This problem is happened, because
1. `ng2-pdf-viewer` depends on `pdfjs-dist@1.9.489`
2. `pdfjs-dist@1.9.489` has dependency `worker-loader@^0.8.0`
3. `worker-loader@0.8.1` (which is the latest version till `1.0.0`) has the following peer dependency `webpack`: `>=0.9 <2 || ^2.1.0-beta || ^2.2.0`

`worker-loader` supports `webpack@3.x.x` starting from the version `1.0.0` ([commit](https://github.com/webpack-contrib/worker-loader/commit/f7e213233eba3ca6310bd6d46f7985858cbb3b99#diff-b9cfc7f2cdf78a7f4b91a753d10865a2))
`pdfjs-dist` supports `worker-loader@1.x.x` starting from the version `1.10.x` ([pull request](https://github.com/mozilla/pdf.js/pull/8977))

Is it possible to update  `pdfjs-dist` to version `1.10.x`?

All is much worse when I use npm lock file, because when some constraints are not satisfied lock file is not updated.
```
npm WARN saveError Problems were encountered
npm WARN saveError Please correct and try again.
```
I have to use different workaround to keep lock file consistent, when new dependency is added into the project.

**Environment:**
```
webpack@3.10.0
@angular/*@5.1.3
ng2-pdf-viewer@4.1.2
```

**Comment by CarlosAyala** [comment]
Same problem here.

**Comment by AnirudhWT** [comment]
I have been using "ng2-pdf-viewer": "^7.0.2" for angular :: "@angular/core": "~11.2.13" and
After adding "@angular-builders/custom-webpack": "^12.1.0"  in "devDependencies" pdf is not displaying.
Thank you in Advance .
