### ISSUE TITLE
How do we display the pdf in a viewer with navigation?

### ISSUE THREAD

**Issue by codehippie1** [VadimDez/ng2-pdf-viewer#304]
This viewer created by mozilla helps with navigation of the pdf.
`https://mozilla.github.io/pdf.js/web/viewer.html`. How do we achieve a similar viewer? Ideally on a different tab.

**Comment by VadimDez** [comment]
@codehippie1 could you please specify what do you exactly mean by `"navigation"`?

**Comment by codehippie1** [comment]
@VadimDez I meant a viewer and controls which helps page navigation/search etc of the pdf. Please mark this as a question if it is out of scope for this component.

**Comment by VadimDez** [comment]
How to do search look here: https://github.com/VadimDez/ng2-pdf-viewer/blob/master/README.md#search-in-the-pdf
and for the rest - see the demo project: https://vadimdez.github.io/ng2-pdf-viewer/ and source code: https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/app.component.ts

**Comment by codehippie1** [comment]
Thank you
