### ISSUE TITLE
Is there any way we can read the file from server wherein an authentication is required with JWT?

### ISSUE THREAD

**Issue by xyrintech** [VadimDez/ng2-pdf-viewer#309]
I saw that there is an option to share the link for the link for source path. 
Now lets image that we need to read file from server which required authentication to read the file, the user is implemented with JWT i.e. token based in headers. 

Now, a HTTP call or headers are required to read the PDF from server. 

Is there any way we can achieve this with this package?

**Comment by gdgunnars** [comment]
Could this be achieve by having a GET request that is authorized by the token, and sends back an arraybuffer containing the pdf and then use that to have an UInt8Array as [src] ?

I might be misunderstanding the question.

**Comment by dwegzero** [comment]
Using an auth pipe could solve this:
http://blog.jsgoupil.com/request-image-files-with-angular-2-and-an-bearer-access-token/
So you have to D/L the PDF file by yourself and transform it to an arraybuffer I as gdgunnars already mentioned

**Comment by VadimDez** [comment]
@xyrintech pass `Object` with headers to `[src]` instead of just an `URL string`: 
```
pdfObject = {
  url: 'some url to PDF',
  httpHeaders: { Authorization: 'Bearer XYZ' },
  withCredentials: true,
}
```

and then in the view
```html
<pdf-viewer [src]="pdfObject" ...
```

**Comment by gxg10** [comment]
One little problem i might add. I used this setup, works as expected but if a have a click listener on a button to change the url to a different pdf, the change occurs but the new pdf isn't rendered. What am i missing ? I also opened an issue with more details about this problem of mine. 

Kind regards,

**Comment by dmantelli** [comment]
> pdfObject = {
>   url: 'some url to PDF',
>   httpHeaders: { Authorization: 'Bearer XYZ' },
>   withCredentials: true,
> }

In order to work correctly, you need to specify the tipo of the Object like this:

```
pdfObject:PDFSource = {
  url: 'some url to PDF',
  httpHeaders: { Authorization: 'Bearer XYZ' }
}
```

This is the only way that JWT works for me.

**Comment by kylegibbons** [comment]
It seems like pdf-viewer skips the HttpInterceptor when downloading the PDF. Is there any way to get it to go through the HttpInterceptor, I already have a mechanism to add auth headers via an interceptor, and it would be a lot more convenient than having to get the token wherever I use the pdf-viewer

**Comment by revatim** [comment]
Was this issue fixed ?
