### ISSUE TITLE
Can't seem to scroll

### ISSUE THREAD

**Issue by mark-norgate** [VadimDez/ng2-pdf-viewer#31]
I have the following code:
```
<pdf-viewer [src]="pdfSrc"
            [page]="page"
            [original-size]="false"
            [show-all]="true"
            style="display: block;"></pdf-viewer>
```
Now then, the first page of the PDF is displaying, but the page isn't scrollable. I have tried applying the following CSS:
```
pdf-viewer {
  border: 1px solid red;
  overflow: scroll;
}
```
The border is appearing, but the page isn't scrolling. What am I missing?

**Comment by VadimDez** [comment]
@mark-norgate, looks good, can't say where exactly problem is. What i can offer you is example code [here](https://github.com/VadimDez/ng2-pdf-viewer/tree/master/src/app)

**Comment by mark-norgate** [comment]
Actually @VadimDez, I discovered it was a missing an `overflow: scroll;` on the parent element.

**Comment by jose2007kj** [comment]
html file

`<ion-content >

<scroll-content>
    <ion-scroll scrollX="true" scrollY="true" zoom="true">
  <pdf-viewer [src]="pdfSrc" [page]="page" [original-size]="false" style="display: block;" [zoom]="zoom" [show-all]="false" [after-load-complete]="pdfDidLoad" [render-text]="true"></pdf-viewer></ion-scroll></scroll-content>



  </ion-content>  
`

scss file

`pdf-viewer {
overflow: scroll;
}
		ion-scroll 
	{ 
	white-space: nowrap; 
	height: 100%;
	}

`

in .ts file i have given link as............

`
pdfSrc: string= '/assets/pdf-test.pdf';

`

scroll not working.............other all working fine..................

**Comment by liangwenzhong** [comment]
@jose2007kj have u resolve this problem?

**Comment by jose2007kj** [comment]
no @liangwenzhong ,.........

**Comment by Anujmoglix** [comment]
@mark-norgate Hi ,can you write that css part because it is not working in my web so tough for me to code

**Comment by Anujmoglix** [comment]
It is very confusing that i have fixed css

` [_nghost-c0] .pdfViewer.removePageBorders .page {
    margin: 0px auto 10px auto;
    border: none;
    overflow: scroll !important;
    /* overflow-y: scroll !important; */
  }`

but still it is only showing 1st page ,

**Comment by Anujmoglix** [comment]
Is Anyone handling this plugin?

**Comment by RyanYmeri** [comment]
You might have [page] set to a certain page. 
`[page]="1"`. 
Remove that variable from the pdf tag and set to 
`[show-all] = "true"`. 
Here is some more info about it --> 
[https://github.com/VadimDez/ng2-pdf-viewer/blob/master/README.md#page](https://github.com/VadimDez/ng2-pdf-viewer/blob/master/README.md#page)
