### ISSUE TITLE
Search functionality not working if i set show all false.

### ISSUE THREAD

**Issue by arjunr681** [VadimDez/ng2-pdf-viewer#314]
Search functionality not working if i set show all false.

I just want to search in a single page instead of searching in all page. My search inputs are not highlighting.

I want to know what are the other commands that are available in pdffindcontroller.executecommand

**Comment by JuliaChenJing** [comment]
Similar issue here. showAll has to be set to true if you want highlight to work. But a big pdf file will take more than 15 seconds to render which is not acceptable ....really stuck here...

**Comment by kylewanderson** [comment]
After a bit of poking around, I notice that when _showAll is false, pdfViewer.setDocument is never called. Calling setDocument with _pdf sets the document to the whole file. I'm not super familiar with the inner workings of pdf.js, but calling setDocument seems to set up the needed wiring for findController to function. Setting the document on the viewer with a subset of the PDFDocumentProxy seems like a possible solution, but I don't know how to create a sub document from a full file.
