### ISSUE TITLE
How to best access text in PDF

### ISSUE THREAD

**Issue by swftvsn** [VadimDez/ng2-pdf-viewer#315]
Hi!

Thanks for the excellent lib. Earlier I used this to extract text from PDF:
```ts
    const pdf = await PDFJS.getDocument(docAsUintArray)

    const promises: Promise<string>[] = []
    const texts: string[] = []
    for (let i = 1; i <= pdf.numPages; i++) {
      const promise = this.extractTextForPage(i, pdf).then(text => {
        texts.push(text)
        return text
      })
      promises.push(promise)
    }

    await Promise.all(promises)
    return texts
```
But now it fails because PDFJS is not defined anymore. My question has two parts:

1. How can I access getDocument method now?
2. Is there a better way to collect the text from a PDF that is being rendered? Can I attach some kind of listener to get access to `PDFPageProxy` objects while this library renders the pages? Or perhaps I can access the PDFDocumentProxy?

**Comment by swftvsn** [comment]
Ok, I missed earlier that this
```html
<pdf-viewer  (after-load-complete)="afterLoadComplete($event)" ....></pdf-viewer>
```
can be used to access the document proxy like this.
```ts
afterPdfLoadComplete(pdf: PDFDocumentProxy): void {
```

**Comment by VadimDez** [comment]
Seems to be resolved

**Comment by swftvsn** [comment]
Yes, the only thing that could be improved here is the amount of attention I give to documentation 😂
