### ISSUE TITLE
Not able to view Pdf 

### ISSUE THREAD

**Issue by Anujmoglix** [VadimDez/ng2-pdf-viewer#316]
I am trying with my ionic 3 app but I am getting following issue 

> ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Worker': TypeError: Failed to fetch could not be cloned.

**Comment by Anujmoglix** [comment]
Now got the solution but  pdf is not scrolling vertically :(

**Comment by kurthybela** [comment]
Anujmoglix, how did you fix that?

**Comment by mungpara** [comment]
> Now got the solution but pdf is not scrolling vertically :(
```
<div style="height: 300px;overflow: auto">
    <pdf-viewer [src]="src"></pdf-viewer>
</div>
```

try this
