### ISSUE TITLE
How to do multiple phrase search.

### ISSUE THREAD

**Issue by arjunr681** [VadimDez/ng2-pdf-viewer#319]
##### Bug Report or Feature Request (mark with an `x`)

```

How to do multiple phrase search.

i wanna search multiple phrases and highlight them. May i know how to do in ng2-pdf-viewer

**Comment by Komdosh** [comment]
Is it not implemented yet?

I want to highlight multiple phrases from array

```
this.pdfComponent.pdfFindController.executeCommand('find', {
    caseSensitive: false,
    findPrevious: undefined,
    highlightAll: false,
    phraseSearch: true,
    query: ['first phrase', 'third phrase']
});
```

So I expected that this query highlight text like this

> I said my **_first phrase_**, second phrase and the **_third phrase_**

**Comment by Komdosh** [comment]
@VadimDez I'm not sure that it is a question, I can't find this functionality, so it is seems like feature request

**Comment by sieuanhung001** [comment]
Hi @Komdosh  Has this been resolved yet?
