### ISSUE TITLE
Using IE 11 the pdf viewer does not work.

### ISSUE THREAD

**Issue by erigol** [VadimDez/ng2-pdf-viewer#32]
It works with Firefox and Chrome, but not for IE11.
As it's a requirement we wont be able to use it

**Comment by vksgautam1** [comment]
Missing PDF "http://localhost:8100/HOUSING.pdf".
i have saved a pdf file in folder but it is giving above error

**Comment by sboukris** [comment]
It's the same for me. It's not working in IE11
