### ISSUE TITLE
FindNext in executeCommand

### ISSUE THREAD

**Issue by prven-affirma** [VadimDez/ng2-pdf-viewer#321]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ x] Documentation issue or request
```
Can you please share how to do findNext/findPrevious once an initial 'find' is completed using executeCommand? Passing true in the executeCommand doesn't do anything. Appreciate your help!

**Comment by skush** [comment]
this.pdfComponent.pdfFindController.executeCommand("findagain", {
      caseSensitive: false,
      findPrevious: undefined,
      highlightAll: true,
      phraseSearch: true,
      query: "your search text"
    });

**Comment by skush** [comment]
@ViewChild(PdfViewerComponent) private pdfComponent: PdfViewerComponent;

**Comment by javid-abd** [comment]
Is it possible to add next and previous functionalities to the search like when we do control + f in the browser?
