### ISSUE TITLE
ng2-pdf-viewer PDF preview does not display Chinese

### ISSUE THREAD

**Issue by yangxiaolong405** [VadimDez/ng2-pdf-viewer#324]
GET http://localhost:4200/nullUniGB-UCS2-H 404 (Not Found) 
"ng2-pdf-viewer": "^3.0.8",

**Comment by VadimDez** [comment]
@yangxiaolong405 could you try the latest version of `ng2-pdf-viewer` (`5.0.1`)?
And upload here an example PDF that is not working for you

**Comment by VadimDez** [comment]
Should be fixed in version `5.1.1`
