### ISSUE TITLE
Clear PDF Viewer

### ISSUE THREAD

**Issue by tvl83** [VadimDez/ng2-pdf-viewer#328]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ X ] Feature request
- [ ] Documentation issue or request
```

I am working on an app that has people uploading PDFs and having a preview of it on the screen. Sometimes, they want to delete and reupload a different PDF. I am having difficulty clearing the data. 

```
<pdf-viewer [src]="exhibitMapData"
                    [render-text]="false"
                    [show-all]="false"
                    [original-size]="false"
                    [fit-to-page]="false"
                    style="display: block"
                    >
        </pdf-viewer>
```

In the component I have tried to `this.exhibitMapData = null` and it doesn't change anything. I am guessing there's some sort of local caching other than with the bound variable in `src` ? 

Please advise

**Comment by VadimDez** [comment]
Try removing (or hiding) `pdf-viewer` element.
You could use something like:\
```
<pdf-viewer *ngIf="exhibitMapData"
            [src]="exhibitMapData" 
...
```

**Comment by tvl83** [comment]
Thank you very much. This works perfectly. I just expected to clear the src variable to null and it would clear the preview.
