### ISSUE TITLE
loading pdfs from local machine

### ISSUE THREAD

**Issue by aavelyn** [VadimDez/ng2-pdf-viewer#330]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ x] Feature request
```

the current src works with fetch api. Is there a way to load a local pdf file from file:// ?
I would like to use the plugin inside an electron angular app.

Cheers

**Comment by essentialx** [comment]
My English is not good, but in this way I can do it


```
//component propertie
let filepath: string;
```

```
//this code inner onUploadOutput function
//I use it as a preview once the file has been selected (addedToQueue)

var reader: FileReader = new FileReader();
 reader.onload = e => {
         this.filepath = e.target['result'];
 }
reader.readAsDataURL(output.file.nativeFile);
```


```
//in html file
<pdf-viewer [src]="path" [render-text]="true" style="display: block;" [zoom]="0.12"></pdf-viewer>

```


its is all

![pdfview](https://user-images.githubusercontent.com/40033231/41109914-22bf6b7c-6a46-11e8-8a19-f3eb8a77a35c.JPG)
