### ISSUE TITLE
PDFVeiwerModule issue

### ISSUE THREAD

**Issue by danboone** [VadimDez/ng2-pdf-viewer#332]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I was trying to use the pdf veiwer in project.
i did 3 things i  did npm install ng2-pdf-viewer --save
then i installed the dependencies npm install --save @types/pdfjs-dist
and npm i pdfjs-dist 

then i added the pdf viewer to my app module like this:
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { PdfViewerModule } from 'ng2-pdf-viewer';
import { APP_BASE_HREF, CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { HttpClientModule } from '@angular/common/http';

import { AppComponent } from './app.component';
import { routes } from './app.routes';
import { DashboardModule } from './dashboard/dashboard.module';
import { MyOrderModule } from './order/order.module';
import { SharedModule } from './shared/shared.module';
import { LoginModule } from './login/login.module';
import { FormsModule } from '@angular/forms';


@NgModule({
    imports: [BrowserModule, PdfViewerModule, HttpClientModule, RouterModule.forRoot(routes), SharedModule, DashboardModule
        , MyOrderModule, LoginModule, FormsModule, CommonModule ],
    declarations: [AppComponent],
    providers: [{
        provide: APP_BASE_HREF,
        useValue: '/',
    }],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

and then my site gets an error:
Error: Unexpected token <
  Evaluating http://localhost:5555/ng2-pdf-viewer
  Evaluating http://localhost:5555/app/app.module.js
  Evaluating http://localhost:5555/app/main.js
  Loading app/main
    at eval (<anonymous>)
    at evaluate (evaluate.js:106)
    at instantiate.js:394
    at dynamicExecute (register-loader.js:665)
    at doEvaluate (register-loader.js:612)
    at ensureEvaluate (register-loader.js:520)
    at register-loader.js:538
    at Object.eval (app.module.ts:3)
    at eval (app.module.ts:27)
    at eval (app.module.ts:27) "GENERIC GFS ERROR"

I am using angular 5.2.3

Thank you for an assistance with this.

an FYI how i will be using the control I am hoping that i can do this and feed it to the control

```
downloadPdf() {
        this.loading = true;

        const exportSettings = {
            ReportParameters: [
                { Name: this.orderSummaryReportParameters.Name, Value: this.gfs.state.orderId },
            ],
            ReportPath: this.ssrsFilePath,
            Filename: 'Order Summary.pdf'
        };

        this.gfs.orders.reportPdf(exportSettings)
            .subscribe(blob => this.downloadFile(blob), error => {
                this.loading = false;
                console.log('call got error', error);
            });
    }
    downloadFile(data: Response) {
        const blob = new Blob([data], { type: 'application/pdf' });
        this.url = window.URL.createObjectURL(blob);
        this.filePath = 'Order Summary.pdf';
//here feed to pdf viewer
    }

```

**Comment by VadimDez** [comment]
Did you already put `<pdf-viewer>` into your html or just imported the module?

**Comment by danboone** [comment]
yes i had <pdf-viewer> in the html

**Comment by KlausHans** [comment]
I've got the same issue, but only on a deployed build. Local dev- and prod-build is fine.
Error in the browser console (firefox):
```
SyntaxError: expected expression, got '<'[Weitere Informationen] pdf.js:1
[Mitteilungsdetails anzeigen/ausblenden] ReferenceError: require is not defined[Weitere Informationen] viewer.js:656:3 
```
I give the pdf file as Uint8Array to the pdf component but i don't think that this is the cause for the problem.

**Comment by OleksandrIvanovTheBest** [comment]
> Import looks fine. Are you using webpack? Are you using ng cli?

webpack =)
