### ISSUE TITLE
Feature: PDFjs Controls

### ISSUE THREAD

**Issue by mtpultz** [VadimDez/ng2-pdf-viewer#333]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```

PDFjs seems to be using ViewerJS (https://mozilla.github.io/pdf.js/web/viewer.html) to set controls at the top of the rendered PDF for zoom, paging, and hand tool (panning).  It would be great if this component used the ViewerJS controls as these tools would complete this component making it even more valuable then it already is for PDF rendering.

**Comment by miles-waldron** [comment]
Yes, this would be valuable to me also. A standard toolbar would be useful. Without anything standard how does one implement "print" function, or "email" function?

**Comment by fralewsmi** [comment]
+1

**Comment by AlexandrosG** [comment]
Has anyone figured this out yet? I am trying to print in Edge and the usual iframe trick doesn't work due to Blob url being blocked.

**Comment by longjingjun** [comment]
Basically, the toolbar and menus are not in ng2-pdf-viewer code. It only include the core to display PDF. 

The standard toolbar and menu code is in viewer.html in original PDF.JS code.

**Comment by AlexandrosG** [comment]
@longjingjun That's apparent, I'm not arguing about that. I'm mostly wondering how to hook up the print service from PDFJS. I have a wrapper component for ng2-pdf-viewer that replicates the look and feel of viewer.html but the printing functionality eludes me since it's not part of pdfjs-dist.

**Comment by longjingjun** [comment]
When I run the PDF.JS example locally and access: http://localhost:8888/web/viewer.html, It shows the print button is there on the top right hand side. I tried to print and it shows me the web browser print dialog. From this information, I think the print function is in PDF.JS. The matter is about how to call the print function from Angular app.

**Comment by ISimplifyComplexity** [comment]
Please reopen this issue.

**Comment by ISimplifyComplexity** [comment]
Please reopen

**Comment by andreivictor** [comment]
Please reopen

**Comment by cyptus** [comment]
@VadimDez could we reopen this please?

**Comment by LukasKlement** [comment]
+1
