### ISSUE TITLE
PDF digital signature not showing

### ISSUE THREAD

**Issue by Koketso42** [VadimDez/ng2-pdf-viewer#335]
I'm using ng2-pdf-viewer in an Angular 4 project, but pdf digital signatures are not showing. I also tested using the plugin's demo page https://vadimdez.github.io/ng2-pdf-viewer/ to test but still it doesn't show digital signature.

I went through some few issue regarding pdfjs `annotation.js` , but I still can't get it working on my application. If someone can help and please provide some few demo solutions that I can go through

THANKS!

**Comment by Gaetane** [comment]
I have the same problem.
It' would be really appreciate if someone can provide a way to fix this.
Thanks !

**Comment by VadimDez** [comment]
Could you provide such PDF?

**Comment by Koketso42** [comment]
[testSignedDoc.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/2131160/testSignedDoc.pdf)

**Comment by Koketso42** [comment]
Thank you @Gaetane , got it working too!

**Comment by Jerfran** [comment]
Question:  Which version of ng2-pdf-viewer use you ?

**Comment by vidyashviram** [comment]
Works with   ng2-pdf-viewer : 7.0.2
