### ISSUE TITLE
Avoid reloading after zoom in/out

### ISSUE THREAD

**Issue by 8zler** [VadimDez/ng2-pdf-viewer#337]
hi,
using it under ionic 3 / angular 5, but everytime i change the value of the [zoom] attribute the content is realoaded (with the small loading spinner) is it possible to avoid this reloading everytime le [zoom] value changes ?

Nice work,

Thanks !

**Comment by 8zler** [comment]
Any idea please ? @VadimDez

**Comment by toddchannick** [comment]
I don’t see how this would be possible as it’s re-drawing the canvas from the original source file each time you change the zoom.

**Comment by VadimDez** [comment]
Maybe the version `6.0.0` will help resolve this issue/improve rendering.

**Comment by VadimDez** [comment]
`6.0.0` See https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600

**Comment by Amin0096** [comment]
hi,
using it under ionic 4 / angular 7, but every time i change the value of the [zoom] attribute the content is reloaded (with the small loading spinner) is it possible to avoid this reloading every time value [zoom] value changes ?
