### ISSUE TITLE
Adding unique id to each page that is rendered ie page1, page2, page3, ext

### ISSUE THREAD

**Issue by Warriormuffin** [VadimDez/ng2-pdf-viewer#340]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```
Any chance of being able to get an id on each page that is rendered from the pdf? Trying to grab each page individually from the canvas and don't seem to have a great way of grabbing each page while rendering all pages on the screen. Something like id="page1" instead of just class="page"

**Comment by VadimDez** [comment]
As of now (version `5.1.0`) on each element that has class `page` there's an attribute `data-page-number` (ex. `data-page-number="1"` where `1` is the page number)
