### ISSUE TITLE
closing a modal with ng2-pdf-viewer before the file completely gets rendered causes an error

### ISSUE THREAD

**Issue by hamzahmurrar** [VadimDez/ng2-pdf-viewer#343]
I have ng2-pdf-viewer in a modal
if I close the modal before the all pages get rendered I get this error

**Error: Uncaught (in promise): AbortError: The user aborted a request.**

**Comment by subatomicglue** [comment]
I encountered this error today as well

**Comment by alaahwanas** [comment]
same here!

**Comment by jiangyh1024** [comment]
@alaahwanas  @YeisonVelez11  is there any way to solve this issue ?

**Comment by alaahwanas** [comment]
Testing it on real devices solved the problem

**Comment by YeisonVelez11** [comment]
@alaahwanas what did you mean with "real devices"?

**Comment by alaahwanas** [comment]
I used it with Ionic application, so on the browser there were an issue,
while when I tried it on real mobile there were no issue.

**Comment by bertrandg** [comment]
Still having this error on desktop browser..
