### ISSUE TITLE
After zoom the pdf doc, drag is throwing and error

### ISSUE THREAD

**Issue by Bombaxo** [VadimDez/ng2-pdf-viewer#344]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Hi, 

I am experimenting a error. Once the zoom value is different than 1, if you drag the document to see the zoomed content it gives error. Attached image. 

<img width="905" alt="screen shot 2018-07-09 at 14 10 38" src="https://user-images.githubusercontent.com/7047758/42449875-9e3d280c-8382-11e8-9811-6f252665561e.png">

In an Angular app is only giving the error in the console. But in the ionic app it shows the ionic exception page crashing the user experience. 

Gr.

**Comment by luisfrancajr** [comment]
I have the same problem. Does anyone have a solution?

**Comment by samtsai** [comment]
See the duplicate #367
