### ISSUE TITLE
page.getAnnotations does not return correct border styles/required flag for PDF required form Fields 

### ISSUE THREAD

**Issue by mohanskumar** [VadimDez/ng2-pdf-viewer#348]
##### Bug Report or Feature Request (mark with an `x`)
`page.getAnnotations does not return correct border styles/required flag for PDF required form Fields `
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

**Comment by VadimDez** [comment]
Could you please add more description?

**Comment by mohanskumar** [comment]
Vad,

I think my issue may be due to the underlying PDFjs and not necessarily related to ng2-pdf-viewer. I am trying to read annotations for a fillable PDF form which has a required form field. when I pull the PDF in the browser, It shows a red border around it as it is required, However those border/required field attributes are not getting pulled with getAnnotations method.  I am using the approach described in https://medium.com/factory-mind/angular-pdf-forms-fa72b15c3fbd  besides, the viewer is great and works pretty neatly.  

Thanks.
