### ISSUE TITLE
Does not show images in pdf

### ISSUE THREAD

**Issue by avinashkgit** [VadimDez/ng2-pdf-viewer#353]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

**Comment by VadimDez** [comment]
Could you provide example PDF?

**Comment by VadimDez** [comment]
Works fine in the demo project https://vadimdez.github.io/ng2-pdf-viewer/
Double check your setup/config/settings or maybe upgrade to the latest version of `ng2-pdf-viewer`.
