### ISSUE TITLE
search function not ok

### ISSUE THREAD

**Issue by zxjQAZ** [VadimDez/ng2-pdf-viewer#359]
TypeError: Cannot read property 'executeCommand' of undefined
 
every time run search function in document , this error happened, I debug the code find that "pdfFindController " only defined not go on , so there is nothing about  "executeCommand" function at all.
have you nerve meet this problem

**Comment by KissBalazs** [comment]
The problem is in your code, the @viewChild cannot find the PdfViewerComponent on your page. (hence, it is undefined)

If your code is like this:
  `@ViewChild(PdfViewerComponent) private pdfComponent: PdfViewerComponent;`
Try to check if pdfComponent exists, before calling the search.

**Comment by zxjQAZ** [comment]
thanks a lot ,however I find another problem that if we set show_all= false,the search and heighLigiht is ok ,otherwise the search function is not ok. is the case konwn?or I have something wrong?

**Comment by KissBalazs** [comment]
Yeah, it is a known problem, see the issues.

**Comment by khiemdc** [comment]
Hi VadimDez,
How can I get the number (count) of search results?
Thank you!

**Comment by VadimDez** [comment]
@khiemdc https://github.com/VadimDez/ng2-pdf-viewer/issues/446
