### ISSUE TITLE
[show-all]="true", [stick-to-page]="true", [page]="boundValue" does not work if I set 'max-height' to 'pdf-viewer'

### ISSUE THREAD

**Issue by jiangyh1024** [VadimDez/ng2-pdf-viewer#360]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
The pdf which will be previewed has many pages and I want to have a scroll bar, so I set 'max-height' to 'pdf-viewer', but it doesn't work. (If I remove max-height, it works). 

Any solutions to solve this problem?

Below is my code:
Html

<div style="width: 800px;">
  <pdf-viewer *ngIf="pdfSrc" [page]="pageNumber" class="pdf-viewer" [autoresize]="true" [original-size]="false" [show-all]="true"
    [src]="pdfSrc" [render-text]="false" [stick-to-page]="true">
  </pdf-viewer>
</div>

<div>
  <button (click)="onClick() ">page</button>
</div>

Css
.pdf-viewer {
  max-width: 100%;
  display: block;
  max-height: 550px;
  overflow: auto;
}

Ts
  pdfSrc: any;
  pageNumber = 1;
  ngOnInit() {
    this.http.get('/api/korcula/GetFileBytes?fileId=704868',
      {
        responseType: 'arraybuffer'
      }).subscribe(res => {
        this.pdfSrc = res;
      });
  }

  onClick() {
    this.pageNumber = 6;
  }

**Comment by VadimDez** [comment]
Fixed in `6.0.0` See https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600
