### ISSUE TITLE
Black background before loading

### ISSUE THREAD

**Issue by damatri** [VadimDez/ng2-pdf-viewer#361]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```
Currently before loading a pdf a black background flashes for a short amount of time. Also visible on https://vadimdez.github.io/ng2-pdf-viewer/ if you scroll inhumanely quickly, but very visible in my app where different pdf's are loaded in the same place. Meaning you have a pdf, load a new pdf and then it flashes from black back to white again. I do not see this black screen appearing in the pdf.js demo page. But also cannot find where this is set or where I can change this. 

Any help would be appreciated as this would greatly improve the usability of my app.

**Comment by johnnyWalnut** [comment]
it happens to me, too. If you would like to give me instructions where i can debug it, i want to contribute with a fix..

**Comment by VadimDez** [comment]
Please reopen if this still an issue.
