### ISSUE TITLE
pdf viewer unable to load pdf from blob url some times

### ISSUE THREAD

**Issue by sekh09** [VadimDez/ng2-pdf-viewer#364]
Hi @VadimDez ,
               Nice plugin to use..
But have few issues while previewing the pdf in a modal pop up.. some times (2 out of 10 attemps) its just showing loading icon even we provided the blob Url

usage:
 **<pdf-viewer [src]="data.pdfUrl" [render-text]="true" [original-size]="true" [zoom]="1.0" style="display: block;"></pdf-viewer>**

the pdfUrl we are passing is  _blob:http://<host>:8080/2df9ff10-67b7-4771-b388-62b12c0541b7_

any help on this is really useful for me..

The version I am using is 5.1.0.

Few more observations afterLoadComplete callbackFn is success **but neither pageRendered or onError functions are not even fired.**
 
Thanks.

**Comment by maxime1992** [comment]
Has anyone found a workaround for that? I'm having the exact same issue currently that'd be really helpful

**Comment by avssolutions** [comment]
Did someone find good solution for this, i am having same problems :(

**Comment by johnbrittoa** [comment]
same issue for me

**Comment by AcarMeel** [comment]
I'm having the same issue. Angular 6. I get a blob file from an API and I convert the blob to URL and is not rendered.
let blobFile = new Blob([data], { type: 'application/pdf' });
let blobUrl = URL.createObjectURL(blobFile);

**Comment by lanminik** [comment]
Hi guys, I had the same issue (pdf in a modal) and it was showing infinitive spinners until refresh the page. I resolved that with setting 'src' variable to null every time before fetching a new Blob from my API. So my code looks something like this: 
    <pdf-viewer *ngIf="!!pdfSrc"
            [src]="pdfSrc"
            [render-text]="true"
            [fit-to-page]="true"
            style="display: block;"
    ></pdf-viewer>

    this.authenticationService.loggedUser$.subscribe((user) => {
      this.pdfSrc = null;

      if (user) {
        this.helpService.getHelp().subscribe(data => {
          this.pdfSrc = new Uint8Array(data);
        });
      }
    });

Using Angular 9...
Glad if it helps somebody...
