### ISSUE TITLE
Local file open problem

### ISSUE THREAD

**Issue by qwerqwermhc** [VadimDez/ng2-pdf-viewer#370]
##### Bug Report or Feature Request (mark with an `x`)
```
this.pdfUrl = 'file:///D:/pdftest/HGH-18123.pdf';
 He does not work
How can I make sure that my local file with file:// can display normally? I looked under #180 and 330. Still not sure who can use the code to help me see it? For example, the file I want to load is this.pdfUrl = 'file:///D:/pdftest/HGH-18123.pdf'; Can you explain it to me with code? I am dull, thank you very much.
```

**Comment by qwerqwermhc** [comment]
// const xhr = new XMLHttpRequest();
      // xhr.open('GET', 'file:///D:/pdftest/HGH-18123.pdf', true);
      // xhr.responseType = 'blob';
  
      // xhr.onload = (e: any) => {
      //   console.log(xhr);
      //   if (xhr.status === 200) {
      //     const blob = new Blob([xhr.response], { type: 'application/pdf' });
      //     this.pdfUrl = URL.createObjectURL(blob);
      //   }
      // };
I tried to do this.
Failed to load file:///D:/pdftest/HGH-18123.pdf: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
and #330 i am try
it is not working properly.

**Comment by VadimDez** [comment]
Take a look at the demo project https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/app.component.ts#L86-L98

**Comment by belajarbikinaplikasi** [comment]
with this PR must be done

https://github.com/VadimDez/ng2-pdf-viewer/pull/442
