### ISSUE TITLE
Max size / Scroll bars not visible

### ISSUE THREAD

**Issue by alberthoekstra** [VadimDez/ng2-pdf-viewer#372]
Hi,

Can anyone tell me how I can set max height and width?
The horizontal scrollbar is all the way down the document and not visible for the user.

**Comment by AntonioDell** [comment]
I have the same problem. I'll see if i can tinker with the source code and get it working.

**Comment by VadimDez** [comment]
Fixed in `6.0.0` See https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600
