### ISSUE TITLE
Bundle size too big

### ISSUE THREAD

**Issue by inankai** [VadimDez/ng2-pdf-viewer#379]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
![image](https://user-images.githubusercontent.com/9895913/45533030-d6fe6900-b828-11e8-87af-b786f129fd75.png)
![image](https://user-images.githubusercontent.com/9895913/45533065-f3020a80-b828-11e8-849d-46c7479cf9d2.png)
How can I reduce the bundle size? thanks

**Comment by HangLoop** [comment]
same here

**Comment by jkroepke** [comment]
@VadimDez any idea about this issue?

It also increate the prod build time (additional 30 seconds here). Its possible to use the ng2-pdf-viewer dependency without including the pdf.js worker into webpack?

**Comment by tuibian** [comment]
same here

**Comment by jarodsmk** [comment]
Bump for this to be reopened. 

I can run a build optimizer to reduce it, but the minified versions should be used. @VadimDez
