### ISSUE TITLE
Suddenly PDF viewer is not showing PDF, what can be issue ?

### ISSUE THREAD

**Issue by MilanRaval** [VadimDez/ng2-pdf-viewer#38]
I am using it since long but from today PDF viewer is not showing PDF. Checked the PDF URL its fine, not getting any error in browser when chekced inspect window. How to debug it, what can be the issue

**Comment by chunghha** [comment]
if you updated to 0.1.4, try to set [render-text]="false" to your pdf-viewer element. ( https://github.com/VadimDez/ng2-pdf-viewer/issues/35 )

**Comment by MilanRaval** [comment]
I will check, thanks !

**Comment by VadimDez** [comment]
@MilanRaval, still not working ?

**Comment by MilanRaval** [comment]
Sorry for late reply, I tried but it is still not showing PDF

   ```
 <pdf-viewer 
                        [show-all]="true"
                        [zoom]="zoom"
                        [render-text]="false"
                        [original-size]="true"
                        style="display: block;height: calc(100vh - 270px)"></pdf-viewer>
```

**Comment by VadimDez** [comment]
@MilanRaval having some difficulties to reproduce this issue, is there some kind of PDFs that aren't showing or all of them?

**Comment by MilanRaval** [comment]
@VadimDez : It seems some another issue, I am getting error when bundled with webpack. Any configuration is required with webpack ?

**Comment by MilanRaval** [comment]
@VadimDez : I got the fix.  Thanks for coding it, it is very useful PDF Viewer 👍

**Comment by tomazkuralt** [comment]
@MilanRaval or @VadimDez what was the cause and solution for issue explained here?
As it seems I have very similar issue but do not know what actually caused it?

So in our case suddenly ng2-pdf-viewer stopped displaying PDF content (but only texts). If PDF has some lines in it, they are displayed just fine.

Any help would be much appreciated here

**Comment by Ansh-aasim** [comment]
@MilanRaval or @VadimDez what was the cause and solution for issue explained here?
As it seems I have very similar issue but do not know what actually caused it?

So in our case suddenly ng2-pdf-viewer stopped displaying PDF content (but only texts). If PDF has some lines in it, they are displayed just fine. We are using 7.0.2

Any help would be much appreciated here
