### ISSUE TITLE
Majority of pdf-viewer properties not recognised

### ISSUE THREAD

**Issue by liaothomas** [VadimDez/ng2-pdf-viewer#380]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
**### Resolved**

Using ng2-pdf-viewer 5.1.2 and Angular 6.1.7

Project generated using angular/cli

While following along with a ng2-pdf-viewer video tutorial that is using Angular 5, I discovered that two out of four properties that it uses successfully are not recognized in identical logic that I am creating along with that author.  All of these properties autocomplete in visual studo code (6.1.7600).  
 the following error information is shown in the visual studio code environment and when I am running the application because it successfully compiles.
[Angular]
Can't bind to 'showAll' since it isn't a known property of 'pdf-viewer'.
1. If 'pdf-viewer' is an Angular component and it has 'showAll' input, then verify that it is part of this module.
2. If 'pdf-viewer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

On investigating further I found the same issue with the following properties:

-     [showAll]="false"
-     [renderText]="true"
-     [pattern]="true"
-     [cMapsUrl]=""
-     [externalLinkTarget]="http"
-     [fitToPage]="true"
-     [maxlength]="12"
-     [minlength]="1"
-     [renderText]="true"
-     [required]="false"
-     [stickToPage]="true"

It appears that this behavior is common among reported issues.  Unfortunately, none of the reported issue are relevant to this version of the issue.

I find that the attached logic successfully displays a multipage PDF file with the behavior suggesting that the showAll property is defaulting to true and the [showAll]="true" and [renderText] properties removed from the <pdf-viewer> tag. If either property is provided, the same error is reported.

The attached files for the app and pdf components are based on a publicly available video demo of ng2-pdf-viewer so anything appropriate for that case is permitted for the attached zipped up file.  The simple project was too large to zip up and share.

[pdf.zip](https://github.com/VadimDez/ng2-pdf-viewer/files/2384580/pdf.zip)

I have located my problem.  The names of the properties have changed since the video tutorial that I referenced and since the resolved issues that I found.  They have also changed since the auto complete data in the package was defined.  If the property names that that appear below the the Git archive entry are used, there is no binding problem.

**Resolved**

**Comment by VadimDez** [comment]
Closing as resolved
