### ISSUE TITLE
Issues rendered with ionic3.9 on cordova

### ISSUE THREAD

**Issue by lim-enhui** [VadimDez/ng2-pdf-viewer#381]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
![image](https://user-images.githubusercontent.com/13527348/45583175-a7fefa80-b8ef-11e8-9f48-4f1a51270936.png)

The web component renders effectively but when render on a cordova to android device. it display a shaded area and a block as seen in the picture. any idea of rectifying the issues is greatly appreciated.

**Comment by VadimDez** [comment]
Are you sure it's not some `CSS` rule from ionic?

**Comment by qwerqwermhc** [comment]
@lim-enhui  Are you local? Is it starting with file://? I am running on my Android phone. I can't open the file with file://. What else do I need to set?
