### ISSUE TITLE
Blank page with lots of "Ignoring invalid character n in hex string" error

### ISSUE THREAD

**Issue by mateotherock** [VadimDez/ng2-pdf-viewer#387]
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I hadn't seen anyone else report this, but I'm actually getting a blank page with no errors, but a whole bunch of warnings in the console with the error "Ignoring invalid character n in hex string." I am honestly still semi new with Angular/Ionic (this is actually an Ionic application, but we deploy PWA as well for desktop), so I'm not sure if this is an Angular issue or what. 

Edit: I tried it on Firefox and it works just fine. Seems to only be in Chrome. Also, not sure if it helps, but I get the same errors when running it on an Android device as well.

EditEdit: Also as I observe it appears that I am getting the same set of warnings for any of the pdfs that I'm trying to display. character "33", character "79", character "84", character "89" etc.

**Comment by Hasan-git** [comment]
> I'm going to close this one because I actually ended up going with something else sorry.

to which pdf viewer you have been switched ?

**Comment by mateotherock** [comment]
@Hasan-git 
So I actually just created a directive that can handle both the web or mobile. I use Angular http.get to get blob response with the uri of the file.
For mobile, I can utilize ionic native File and FileOpener plugins (with the appropriate paths depending on iOS vs. Android) to open the file on a device using .writeFile() method from File and .open() method on FileOpener. On the mobile device itself the pdf opens in a viewer and generally has an option to download if the user desires.
For web, I have to create a new Blob with the above blob with the fileType explicitly set (or else many browsers seem to freak out) and then use .createObjectURL() method with the new blob. Generally you should be able to window.open this url in a new tab or wherever you like.
After that we also chose to automatically download the pdf in addition to opening in a new tab and for that you just programmatically create a link and hook up the link.href property to the result of the createObjectURL() method and then click the link.
