### ISSUE TITLE
Tracking page

### ISSUE THREAD

**Issue by mremil6** [VadimDez/ng2-pdf-viewer#388]
Hi!
Thank you for this this component.

I want to show current page like 5/17, but [(page)] doesn`t updating when i scrolling in show-all-pages mode. Have you any offer?

**Comment by arvindnrbt** [comment]
We have the same issue. Is there a way to fix this?

**Comment by mremil6** [comment]
I create my own logic that considers the length of the entire pdf file and look at what position we are now

**Comment by AlexandrosG** [comment]
@mremil6 Could you please share your solution to scrolling and page tracking?

**Comment by mremil6** [comment]
@AlexandrosG sure, share example tomorrow, OK?

**Comment by AlexandrosG** [comment]
@mremil6 that’s great thanks

**Comment by mremil6** [comment]
@AlexandrosG Sorry, lost this example. I can say what you should do.
1. Set [show-all-pages]="true"
2. style for pdf viewer "overflow: auto"
3. get native element height and divide it with height of 1 page.

P.S. do not forget height minus all margin between pages.

**Comment by AlexandrosG** [comment]
Thanks @mremil6. I went another way by triggering an event on scroll and updating the page through this event and disabling the "snapping" function when the page change came from a scroll.

I'm sure @VadimDez will have a  less hacky version once he gets around to tackling this issue.

**Comment by amberwjq** [comment]
> Thanks @mremil6. I went another way by triggering an event on scroll and updating the page through this event and disabling the "snapping" function when the page change came from a scroll.
> 
> I'm sure @VadimDez will have a less hacky version once he gets around to tackling this issue.

Can you elaborate how you disable the event on scroll when it comes from page change? I have a race condition because of it.

**Comment by VadimDez** [comment]
Fixed in `6.0.0` See https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600

**Comment by RameshkrishnanV** [comment]
@VadimDez  Can you please tel me how to track page change? or Do i need to follow the logic explained by @mremil6 . 
Thanks.
