### ISSUE TITLE
pdf viewer is taking time to load content from Uint8Array for the first time, but when the content loads completely for first pdf than it is not taking for other pdfs

### ISSUE THREAD

**Issue by dhavalsharma387** [VadimDez/ng2-pdf-viewer#389]
//TS file

this.file.readAsArrayBuffer(path.substring(0,path.lastIndexOf("/")),fileName).then((arraybuffer)=>{
                var uInt8Arr = new Uint8Array(arraybuffer);
                console.log(uInt8Arr);
                        this.pdfSrc  = uInt8Arr,
                         this.isPDFsaved =  true;
                      });
  }

// HTML
<div *ngIf = "isPDFsaved">
    <pdf-viewer [src]="pdfSrc" style="display: block;" [fit-to-page]="true"></pdf-viewer>
</div>

**Comment by rjpackito** [comment]
+

**Comment by thomas-ama** [comment]
Same issue: slides are loaded slowly the first time they are displayed.
Then, events on the document viewer are not very responsive (e.g., `mousemove`)

**Comment by leo-haerdle** [comment]
Hey there,
I have the same problem, first pdf to load takes between 15 and 25 seconds. After taht first inital loads it is smooth, anything new on that front?
