### ISSUE TITLE
background-color css causes PDF text to become invisible.

### ISSUE THREAD

**Issue by jasonburrows** [VadimDez/ng2-pdf-viewer#39]
If either the containing div specifies a background-color css property, or the pdf-viewer element itself contains this property, the PDF text is no longer visible.  I can tell it is still there as I can select it, but you can't see it.

Specifically, in either of the following examples, the text and background color will both be red and thus, the text will not be visible:

```
        <div>
           <pdf-viewer  [src]="pdfSrc"
                        [(page)] = "page"
                        [original-size]="true"
                        style="display: block;background-color: red;">
           </pdf-viewer>
        </div>
```

```
        <div style="background-color: red;">
           <pdf-viewer  [src]="pdfSrc"
                        [(page)] = "page"
                        [original-size]="true"
                        style="display: block;">
           </pdf-viewer>
        </div>

```

**Comment by abugim** [comment]
I had the same issue and found a work around / cause, when the page is rendered its z-index is set to -1, and if you change this parameter the page became visible again. Just found the issue and tested this.

**Comment by jasonburrows** [comment]
Yeah I've experimented with including "z-index: 2;" in the style attribute but it doesn't make any difference in how it displays.  Where exactly were you changing the z-index?  

Thanks!

**Comment by abugim** [comment]
at styles on the browser F12. There a simple solution, don't know if it fits your problems, but if you set the option render-text to false it works to.

[render-text]
Enable text rendering, allows to select text

Hope it helps.

**Comment by jasonburrows** [comment]
Ah - I see.  I have a workaround as well for now (I just don't specify a background color for the containing div and everything is OK).  Thanks for your help!

**Comment by abugim** [comment]
setting the render text you may set the back color

**Comment by prashanthyD** [comment]
> setting the render text you may set the back color

Hi all,

If i will give render-text = false. then also in Google Pixel 3 i am getting the text in white color from 14th page of PDF. in other devices it is normal.
