### ISSUE TITLE
How can I stop the loading process of a pdf?

### ISSUE THREAD

**Issue by YeisonVelez11** [VadimDez/ng2-pdf-viewer#398]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X ] Bug report -> please search issues before submitting
- [ ] Feature request
- [X ] Documentation issue or request
```

I'm getting this problem:

![captura](https://user-images.githubusercontent.com/1949889/47275933-4f1f2380-d579-11e8-8bfb-82f04a312dcc.JPG)

`
     pageRendered(e: CustomEvent) {
      this.showButtons=true;
     }
     this.archivo_adjunto=this.navParams.data.source;

      <pdf-viewer [src]="archivo_adjunto"
                  *ngIf="archivo_adjunto"
                  [render-text]="true"
                  [original-size]="true"
                  [page]="1"
                  [autoresize]="true"
                  [show-all]="true"
                  style="display: block;"
                  (page-rendered)="pageRendered()"
      ></pdf-viewer>
`

I integrated this plugin into IONIC and it works perfectly. In my application I have a menu and every time I click on an item, the view is refreshed and a different pdf is loaded. doing this from one moment to another I see this error. I'm not sure how to solve this problem, maybe when trying to exit the component if the current pdf is canceled, maybe the problem is solved.

**Comment by huannxdev** [comment]
it got same it. How can i fix it?. Please help me
