### ISSUE TITLE
don't show PDF

### ISSUE THREAD

**Issue by viniciushvc** [VadimDez/ng2-pdf-viewer#400]
I'm tryng to show an PDF, you can simulate using this file: 

> https://scribd.com/document/391422501/report

I think is about width, needed help, thanks

**Comment by VadimDez** [comment]
Could you please specify what went wrong?
maybe try recreating problem here: https://stackblitz.com/edit/ng2-pdf-viewer

**Comment by viniciushvc** [comment]
i try to recreate using this pdf: [https://viniciushvc.github.io/pdfs/report.pdf](https://viniciushvc.github.io/pdfs/report.pdf
)
, on **stackblitz works**, but on ng2-pdf-viewer repository don't work.

I don't know whats happen.

**Comment by VadimDez** [comment]
I assume you want to fit your PDF inside the page. If so you can try the following CSS:
```css
pdf-viewer {
  display: block;
}
```

**Comment by viniciushvc** [comment]
Still not working using the following CSS:
```
pdf-viewer {
    display: block;
}
```

![demo](https://user-images.githubusercontent.com/16567830/48904215-d1cf2300-ee44-11e8-894b-00e6316b80e3.gif)

- My pdf don't render in the page
- A pdf example render

**Comment by viniciushvc** [comment]
> I'm tryng to show an PDF, you can simulate using this file:
> 
> > https://scribd.com/document/391422501/report
> 
> I think is about width, needed help, thanks
