### ISSUE TITLE
Regression in latest release 5.1.1 -> 5.2 

### ISSUE THREAD

**Issue by arvindnrbt** [VadimDez/ng2-pdf-viewer#401]
##### Bug Report or Feature Request (mark with an `x`)
```
- [x] Regression (a behavior that used to work and stopped working in a new release)
```
So, our pdf viewer stopped working abruptly. When we see the console, the log displays

```e._setCurrentPageNumber: "7" is out of bounds.```

This is occurring in our latest release which (I'm guessing) could be because of the latest merge. Can anyone throw some light on why this happens?

**Comment by VadimDez** [comment]
Are there any hints on how to reproduce this?
