### ISSUE TITLE
<!doctype html> issue

### ISSUE THREAD

**Issue by elandwz** [VadimDez/ng2-pdf-viewer#403]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```
doctype html is quit import in pages, for it means html5, if we remove this tag, will casue browser Quirks mode, a lot of issues. Anyone please help to fix this, really thanks

**Comment by VadimDez** [comment]
Fixed in `6.0.0` See https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600
