### ISSUE TITLE
Can't render bytestream as PDF

### ISSUE THREAD

**Issue by julian-fernandez** [VadimDez/ng2-pdf-viewer#406]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Our app's API returns a bytestream when we request a PDF file. Using that bytestream as source, the <pdf-viewer> component is blank.

HTML:

`                        <div *ngIf="pdfUrl">
                                <pdf-viewer [src]="byteStreamPDF"
                                            [render-text]="true"
                                            [page]="1"
                                            [show-all]="false"
                                            [original-size]="false"
                                            [autoresize]="true"
                                            style="display: block;"
                                ></pdf-viewer> 
                            </div>
`

The console logs the bytestream as such:

![image](https://user-images.githubusercontent.com/7570954/47875994-cf098100-ddf6-11e8-9996-8010c2e0e34a.png)

I've tried (just in case) using a locally hosted .pdf as the source and it works perfectly so I know the library is correctly implemented.

Thank you.

**Comment by shirmanov** [comment]
@julian-fernandez your **byteStreamPDF** should be of **Uint8Array** type then, as **src** property is declared as
src: string | Uint8Array | PDFSource;
