### ISSUE TITLE
Documentation for render-text-mode needed.

### ISSUE THREAD

**Issue by liaothomas** [VadimDez/ng2-pdf-viewer#407]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ X] Documentation issue or request
```
I would like documentation on the different render-text-mode values.  A quick google search seems to show text render mode for PDF to have no consistent meaning.

**Comment by VadimDez** [comment]
Thanks!
Extended docs with dcf9325617ce659e8e7893e5ce23b7a18ffb9f2c and 3d07d0d221f9de4a79558aa627536758b1a58852
