### ISSUE TITLE
Regression: Version 5.2 Broke (page-rendered)

### ISSUE THREAD

**Issue by Warriormuffin** [VadimDez/ng2-pdf-viewer#408]
##### Bug Report or Feature Request (mark with an `x`)
```
- [X] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
The docs state

"Get event when a page is rendered. Called for every page rendered."

This used to be the case but no longer functions that way. Now if you use [page]='pdfPageNumber' to increment the page number this callback is never recalled.

**Comment by VadimDez** [comment]
`(page-rendered)` is working when `[show-all]` is `true` but not when `[show-all]` is `false`
Tested here: https://vadimdez.github.io/ng2-pdf-viewer/

**Comment by Warriormuffin** [comment]
So we will no longer be able to use [show-all]='false' and page-rendered to capture each page of the pdf individually?

**Comment by VadimDez** [comment]
I've just tried in the latest version and it seems to be working. When you set `[show-all]="false"` `(page-rendered)` is called on the first render but not the second. Not sure if that covers your use case. Otherwise you could use something like this:
```js
window.addEventListener('pagechange', (e) => console.log(e));
```

**Comment by Warriormuffin** [comment]
That is not how it worked one version ago though. Was there a reason it needed to change? Before `(page-rendered)` would be called everytime a new pdf page was loaded into the pdf viewer. Now that functionality has stopped working when you have  `[show-all]="false"`

**Comment by VadimDez** [comment]
There were several changes related to how single page is rendered. `PDFSinglePageViewer` and custom event bus are now used.

**Comment by sChupin** [comment]
The `(page-rendered)` event is correctly triggered but the `(text-layer-rendered)` not is still not triggered on page change.
