### ISSUE TITLE
[external-link-target]="'blank'" is not opening in a new window in electron

### ISSUE THREAD

**Issue by jabed07** [VadimDez/ng2-pdf-viewer#417]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
External link not working in the electron
Its opening on the same window.
Below is the code

<pdf-viewer [src]="filePath" [external-link-target]="'blank'" [original-size]="true"
              [render-text]="true"  [zoom]="1"  [autoresize]="true" style="display: block;"
                ></pdf-viewer>

**Comment by LFaseva** [comment]
the same problem

**Comment by sureshkodur** [comment]
I'm also having the same issue. I'm using  [external-link-target]="'blank'" with [render-text]="true" , but not lucky.. Please help me

**Comment by ThisGuyRghtHereee** [comment]
This sounds similar to issue #215

**Comment by vipul-zambare006** [comment]
The below workaround worked for me:

> Important note:

- You should set render-text to true: [render-text]="true"

> HTML
```
<pdf-viewer id="pdf-report-id" class="pdf-container" [src]="pdfData" [original-size]="false" [fit-to-page]="true"
    [render-text]="true" [zoom]="1" (text-layer-rendered)="textLayerRendered($event)">
</pdf-viewer>
```

> Typescript code:

```
textLayerRendered(e: CustomEvent) {
    let externalLinks: HTMLCollectionOf<HTMLAnchorElement>;
    const pdfReport = document.getElementById('pdf-report-id');

    if (pdfReport) {
      externalLinks = pdfReport.getElementsByTagName('a');
    }
    for (let i = 0; i < externalLinks.length; i++) { externalLinks[i].setAttribute('target', '_blank'); }
  }
```

**Comment by jinsts** [comment]
I'm also experiencing the same issue.
I have used the following workaround:

**HTML File**
```
...
<pdf-viewer
  external-link-target="blank"
  [src]="reportObject.src"
  [page]="reportObject.currentPage"
  [show-all]="!reportObject.isPaginated"
  [render-text]="true"
  (after-load-complete)="pdfLoadComplete($event)"
  (text-layer-rendered)="modifyAnchorElementAttributes($event)"
></pdf-viewer>
...
```

**TS File**
```
...
public modifyAnchorElementAttributes(event: CustomEvent): void {
  const textLayer = <HTMLElement>event.target;
  const annotationLayer = textLayer.nextElementSibling;
  const anchorElements = annotationLayer.getElementsByTagName('a');

  for (let i = 0; i < anchorElements.length; i++) {
    anchorElements[i].setAttribute('target', '_blank');
  }
}
...
```

**Comment by TTvanWillegen** [comment]
Same problem here on Angular 8.2.0; ng2-pdf-viewer 6.0.2
I have a PDF with links inside, having set `[external-link-target]='blank'` will still result in links opening in the same tab. 

I have the following settings:
```
<pdf-viewer
                [src]="file?.url"
                [render-text]="true"
                [render-text-mode]="2"
                [external-link-target]="'blank'"
                [original-size]="false"
                [autoresize]="false"
                [show-all]="true" 
                (on-progress)="onPDFLoading($event)"
                [zoom]="zoomLevel / 100"
            ></pdf-viewer>
```
Now, the link I am trying to open is a subdomain of the domain the component is running on, although I doubt that should make a difference (and if it does, can there be an option to also force those to be opened in a new tab?)

I have yet to try above mentioned work-around. I will edit my comment once I have.
