### ISSUE TITLE
CSP unsafe-eval required after release 5.2.2

### ISSUE THREAD

**Issue by loremaps** [VadimDez/ng2-pdf-viewer#419]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
From release `5.2.2` our Content Security Policy gets violated because `unsafe-eval` are not allowed.
I think it might be related to this bump: d1462589175a0794d4dfc818c72076483fa34c27

![image](https://user-images.githubusercontent.com/18003912/49517948-137cb680-f8a6-11e8-8a78-3eecf083e7fe.png)

**Comment by loremaps** [comment]
Looks like it is going to be resolved with the next release:
mozilla/pdf.js#10387

**Comment by loremaps** [comment]
Works with release `5.3.2`

**Comment by maxime1992** [comment]
@loremaps 5.3.2 was working fine but trying to upgrade to 5.3.4 broke it again.
It's been a really painful experience to figure that out as it was happening within a lazy loaded module and the only error I had was `Runtime compiler is not loaded` :scream:.

Any idea why it's happening again?

**Comment by loremaps** [comment]
@maxime1992 yes I believe you are also facing this issue: mozilla/pdf.js#11036
Which appears to be an upstream issue of a `babel` polyfill :unamused:

**Comment by maxime1992** [comment]
Yup thanks I commented there!

**Comment by jkroepke** [comment]
@loremaps its possible that you remove the dependency and re-add pdfjs-dist as peerDependency?
We can just [downgrade](https://github.com/VadimDez/ng2-pdf-viewer/commit/bcf37000053496ec71e800289370913899a8d9bb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) the pdfjs dependencies as we need to get a rescue from this issue.

**Comment by adamdport** [comment]
Did anyone here ever resolve this issue? I'm still having issues with the latest 7.0.1.
