### ISSUE TITLE
Support text-to-speech

### ISSUE THREAD

**Issue by jose2007kj** [VadimDez/ng2-pdf-viewer#42]
sir,if u tell me how to create  i will definitely  try to build and do a pull request.......

**Comment by VadimDez** [comment]
Could you please rephrase or explain with more details? Any example would be ok too

**Comment by jose2007kj** [comment]
sir,....on clicking listen button ...........we will be able to listen to  articles in the current pages ( like  text to speech)..........

**Comment by jose2007kj** [comment]
[pdf-to-text](https://github.com/zetahernandez/pdf-to-text) it's javascript ................sir how to convert javascript to angular 2 ?
