### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jiangyh1024** [VadimDez/ng2-pdf-viewer#421]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I wrapped pdf-viewer as a component
![image](https://user-images.githubusercontent.com/34930870/49708721-b8630f00-fc6b-11e8-9f3b-88476b37cf8d.png)

and use it 
![image](https://user-images.githubusercontent.com/34930870/49708725-c153e080-fc6b-11e8-888d-a27c62c0b727.png)

![image](https://user-images.githubusercontent.com/34930870/49708735-cdd83900-fc6b-11e8-87a2-957a6afb83eb.png)
![image](https://user-images.githubusercontent.com/34930870/49708748-daf52800-fc6b-11e8-8176-cbfbcc11471c.png)
![image](https://user-images.githubusercontent.com/34930870/49708749-de88af00-fc6b-11e8-98eb-53bddda89188.png)

pdf is not directed to pageNumber I set, this issue does not exist in 5.1.0 version

**Comment by jiangyh1024** [comment]
@ColinT  Thanks for replying.  afterPdfLoadComplete is run. Everything works fine if the version is 5.1.x. Reproduction is hard to provide, because it needs to load pdf from server side

**Comment by jiangyh1024** [comment]
@ColinT 
![image](https://user-images.githubusercontent.com/34930870/49778805-f0d51c80-fd41-11e8-9c9d-495ca9f3a9ad.png)

![image](https://user-images.githubusercontent.com/34930870/49778779-d602a800-fd41-11e8-8ce1-f74ec2b04616.png)

but the page index is not 13

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/49778842-14986280-fd42-11e8-88d2-5baa09a6af7d.png)

**Comment by jiangyh1024** [comment]
@ColinT 
![image](https://user-images.githubusercontent.com/34930870/49779023-df404480-fd42-11e8-9515-cc3fcddb3a7d.png)
![image](https://user-images.githubusercontent.com/34930870/49779035-e9fad980-fd42-11e8-9c30-7601f2e8b54f.png)

above is correct using version 5.1.0


below is wrong using version 5.2.3
![image](https://user-images.githubusercontent.com/34930870/49779097-2b8b8480-fd43-11e8-8d46-9236b34c717c.png)

![image](https://user-images.githubusercontent.com/34930870/49779102-334b2900-fd43-11e8-8c66-4a3fce0c9be3.png)

**Comment by jiangyh1024** [comment]
weird ..

**Comment by ColinT** [comment]
Do you get the same problem with other PDFs?

Can you check `(error)` `@Output` to see if there are any errors.
Also looks like there is 1 error on your console. Not sure if that is related.

Without reproduction it is hard to find what is wrong. But you may be able to debug it.

The `page` input causes changes in two places:
https://github.com/VadimDez/ng2-pdf-viewer/blob/381d113800738d09d12f32a9b8a067c4006efbab/src/app/pdf-viewer/pdf-viewer.component.ts#L103-L113

https://github.com/VadimDez/ng2-pdf-viewer/blob/381d113800738d09d12f32a9b8a067c4006efbab/src/app/pdf-viewer/pdf-viewer.component.ts#L290-L294

Check if they are receiving and processing the correct `page` value you want.

**Comment by jiangyh1024** [comment]
@ColinT  Thanks for replying, I will try it.

**Comment by jiangyh1024** [comment]
@ColinT  
![image](https://user-images.githubusercontent.com/34930870/49855366-fdcc3b80-fe27-11e8-9096-8f5359483c50.png)

**Comment by jiangyh1024** [comment]
@ColinT  I correct it by using

![image](https://user-images.githubusercontent.com/34930870/49855478-5bf91e80-fe28-11e8-856f-e246b7e29b8d.png)

But why version 5.1.0 does not have this problem

**Comment by ColinT** [comment]
`ng2-pdf-viewer@5.1.x` used `pdfjs-dist@2.0.550`
`ng2-pdf-viewer@5.2.x` uses `pdfjs-dist@2.0.943`

The dependency upgrade has introduced breaking changes to the underlying viewer.

Based on the error you are getting, it is probably related to issue [#401](https://github.com/VadimDez/ng2-pdf-viewer/issues/401)

The code that throws that error is here:
```js
// pdfjs-dist/web/pdf_viewer.js:5574-5599
    key: '_setCurrentPageNumber',
    value: function _setCurrentPageNumber(val) {
      var resetCurrentPageView = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : false;

      if (this._currentPageNumber === val) {
        if (resetCurrentPageView) {
          this._resetCurrentPageView();
        }
        return;
      }
      if (!(0 < val && val <= this.pagesCount)) {
        console.error(this._name + '._setCurrentPageNumber: "' + val + '" is out of bounds.');
        return;
      }
      var arg = {
        source: this,
        pageNumber: val,
        pageLabel: this._pageLabels && this._pageLabels[val - 1]
      };
      this._currentPageNumber = val;
      this.eventBus.dispatch('pagechanging', arg);
      this.eventBus.dispatch('pagechange', arg);
      if (resetCurrentPageView) {
        this._resetCurrentPageView();
      }
    }
```

pagesCount is set in the `setDocument()` function:
```js
// pdfjs-dist/web/pdf_viewer.js:5616
      var pagesCount = pdfDocument.numPages;
```

You can check if the value is being updated there, using `debugger;` to create a breakpoint.

**Comment by jiangyh1024** [comment]
@ColinT Thanks for replying, I found that  the value is not being updated if there is no delay (settimeout), currently, I install version 5.1.x to fix this issue.  But when will the version 5.2.x fix the problem

**Comment by GuN41Kdev** [comment]
This issue reproduces on a mobile phone. Version 7.0.1.
I think that mobile is purdy slow and it can't calculate all pagesCount before navigating on specific page num.
![image](https://user-images.githubusercontent.com/65912240/127220947-4986ea73-4fca-44fd-a596-a683ce62a336.png)
