### ISSUE TITLE
PDFDocumentProxy is returning pageCache object as empty with angular 7 and ng2-pdf-view 5.2.3

### ISSUE THREAD

**Issue by smlee** [VadimDez/ng2-pdf-viewer#424]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I was getting the pdf width and height from pageCache object which I got from the after-load-complete directive, now it returns an empty array.

**Comment by ColinT** [comment]
You can find the pageCache under:

`PDFDocumentProxy._transport.pageCache`

e.g.:
![image](https://user-images.githubusercontent.com/3926408/50061196-63dbfa00-016b-11e9-97de-f1a64ad39057.png)

This result was generated using the demo on the current master branch.
If you are getting a different result please provide a reproduction.

**Comment by VadimDez** [comment]
@smlee Consider closing this issue if @ColinT answer did help you.
