### ISSUE TITLE
pdfWorkerSrc not working correctly

### ISSUE THREAD

**Issue by AndreyKotofotoff** [VadimDez/ng2-pdf-viewer#427]
##### Bug Report or Feature Request (mark with an `x`)
```
- [x] Bug report
```

Hello.
I have a pdf file with cyrillic fonts.
Your package has a link to pdfjs-dist with version is 2.0.943. This version is not work correctly in Edge (Chrome Ok). (https://github.com/mozilla/pdf.js/issues/10175#issuecomment-442963686).
When i set custom pdf.worker.js by your instruction i see in network tab this script but pdf file not show.

**2.0.943 (cdn link)**
![image](https://user-images.githubusercontent.com/15908484/50486689-2188a780-0a0c-11e9-9a1e-d35215f9b639.png)

**custom worker**
```
constructor(...) {
  (<any>window).pdfWorkerSrc = 'pdf.worker.js';
}
```

![image](https://user-images.githubusercontent.com/15908484/50486964-68c36800-0a0d-11e9-9cb7-eead1a93c4c8.png)

**Comment by ColinT** [comment]
You can try `npm i --save-exact ng2-pdf-viewer@5.2.0` to downgrade to `pdfjs-dist@2.0.550`, and see if it works for your pdf.

**Comment by AndreyKotofotoff** [comment]
> You can try `npm i --save-exact ng2-pdf-viewer@5.2.0` to downgrade to `pdfjs-dist@2.0.550`, and see if it works for your pdf.

It's works!
