### ISSUE TITLE
Text Highlight not working properly in ng2-pdf-viewer

### ISSUE THREAD

**Issue by kalyankumarkoool** [VadimDez/ng2-pdf-viewer#429]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Bug report -> please search issues before submitting
```
On rendering text layer with highlighted words for a text field on component load, ng2-pdf-viewer is not highlighting text by default even though I am sending data to pdfFindController. It will highlight only if you scroll the rendered resume.

**Comment by dhyanaswain** [comment]
Hi Kalyan
You can use **.scrollIntoView()** function

**Comment by khiemdc** [comment]
How can I get total search results with ng2-pdf-viewer? Thank you!

**Comment by nikhilwadibhasme** [comment]
Any update on this issue? highlight issue for spans inside textLayer.
