### ISSUE TITLE
ERROR TypeError: this.pdfMultiPageFindController.setDocument is not a function     at n.setupMultiPageViewer (main.3237c5a0807f3a0b7b8d.bundle.js:1)

### ISSUE THREAD

**Issue by manishbt** [VadimDez/ng2-pdf-viewer#430]
`#####` Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I'm getting this issue when i upload my code on production, pdf-viwer working fine on local machine.
even it return total number of page in pdf file. but still thorw this error
Please help me with this issue.

ERROR TypeError: this.pdfMultiPageFindController.setDocument is not a function
    at n.setupMultiPageViewer (main.3237c5a0807f3a0b7b8d.bundle.js:1)

main.3237c5a0807f3a0b7b8d.bundle.js:1 ERROR Error: Uncaught (in promise): TypeError: this.pdfFindController.setDocument is not a function
TypeError: this.pdfFindController.setDocument is not a function
    at n.resetPdfDocument (main.3237c5a0807f3a0b7b8d.bundle.js:1)

My code is:

html file:------
<pdf-viewer [src]="pdfSrc" [(page)]="page" [rotation]="rotation" [original-size]="originalSize"
                            [fit-to-page]="fitToPage" (after-load-complete)="afterLoadComplete($event)" 
                           [zoom]="zoom"
                            [show-all]="showAll" [stick-to-page]="stickToPage" [render-text]="renderText"
                            [external-link-target]="'blank'" [autoresize]="autoresize" (error)="onError($event)"
                            (on-progress)="onProgress($event)" (page-rendered)="pageRendered($event)"></pdf-viewer>

componet.ts

 pdfSrc: string | PDFSource | ArrayBuffer = '../../assets/pdf-test.pdf';
    page = 1;
    totalPages: number;
    isLoaded = false;
    error: any;
    rotation = 0;
    zoom = 1.0;
    originalSize = false;
    pdf: any;
    renderText = true;
    progressData: PDFProgressData;
    stickToPage = false;
    showAll = true;
    autoresize = true;
    fitToPage = false;
    outline: any[];
    isOutlineShown = false;
    pdfQuery = '';
@ViewChild(PdfViewerComponent) private pdfComponent: PdfViewerComponent;

ngOnInit() {
            this._fileservice.openFile(this.fileToOpen).subscribe(
                (file: ArrayBuffer) => {
                    this.pdfSrc = file;
                },
                err => {
                });
        }
    }

![image](https://user-images.githubusercontent.com/38979643/50902743-bc887500-1441-11e9-8f26-9bbf58740c27.png)
``

**Comment by stoldorma** [comment]
how did you fixed it?

**Comment by stoldorma** [comment]
Thank you :)

**Comment by phpepe** [comment]
I fixed by reverting to version 5.2.0
Seems like 5.2.3 is not compatible with 5.2.0 so need to set exact version under package : use "5.2.0" instead of "^5.2.0"

**Comment by tanzl88** [comment]
Are you guys refering to angular version? I couldnt get pass this problem

**Comment by phpepe** [comment]
No. The version of this package

**Comment by ljudbane** [comment]
Update pdfjs-dist package to 2.0.943 to fix this error.
