### ISSUE TITLE
Search is not working properly.

### ISSUE THREAD

**Issue by hitenzaptech** [VadimDez/ng2-pdf-viewer#431]
I am using ng2-pdf-viewer to display the pdf.
And I have search functionality in my pdf.

In the example below we are searching for the word "procedure" and you can see the words below "procedure" are highlighted.

![img_2313](https://user-images.githubusercontent.com/20186566/50965907-624aeb00-14f9-11e9-93e8-8e6405be38bd.PNG)

My Code for searching is
```
 public search(text: string, caseSensitive: boolean = false) {
    const searchText = text ? text.trim() : "";
    if (!searchText) {
      return;
    }

    this.pdfComponent.pdfFindController.executeCommand("find", {
      caseSensitive: caseSensitive,
      findPrevious: true,
      highlightAll: true,
      phraseSearch: true,
      query: searchText
    });
  }
```
Can anyone please help me out to solve this issue.

**Comment by MSurendarReddy** [comment]
<pdf-viewer #pdfComp [src]="pdfSrc" **[show-all]="false"** [zoom]="zoom" [rotation]="rotation" [(page)]="page"
        [render-text]="true" (on-progress)="onProgress($event)" (after-load-complete)="afterLoadComplete($event)"
        style="display: block;">
    </pdf-viewer>

make show-all to false
