### ISSUE TITLE
Large PDF >300 pages, rendering problems

### ISSUE THREAD

**Issue by davidremus** [VadimDez/ng2-pdf-viewer#440]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Hello,
I have a problem with loading large PDF because, if I scroll down I have to wait until all the pages are rendered.
It's possible to force to render the current page?

Please advice!

**Comment by VadimDez** [comment]
Fixed in `6.0.0` https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600
