### ISSUE TITLE
How to get zoom value?

### ISSUE THREAD

**Issue by erata** [VadimDez/ng2-pdf-viewer#441]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Hi, i use pdf-viewer 2.0.3 version and want to take last zoom value because i use the zoom value setting some other issues. when i use autoresize i could not find what the last zoom value after resize. Could you help about it.

**Comment by tiagoboeing** [comment]
A way is using local variables in Angular to access component.

Define you local variable using `#` (any name)

```
    <pdf-viewer
      [src]="pdf"
      [render-text]="true"
      #component
    ></pdf-viewer>
```

Directly in HTML is possible use with:

`{{ component.zoom | json }}` to view current zoom.

### In TypeScript use:

```
// get component reference
@ViewChild('component') myComp: PdfViewerComponent;`

// use
const currentZoom = this.myComp.zoom;
```

> You have check if(this.myComp && this.myComp.zoom) to not generate zoom undefined errors in console.

Is possible use in HTML too.

`myComp?.zoom` is way...
