### ISSUE TITLE
Unable to create multiple instances of PDF viewer in a single page

### ISSUE THREAD

**Issue by jinsts** [VadimDez/ng2-pdf-viewer#443]
Unable to create multiple instances of PDF viewer in a single page. Changing page or any properties in one affects others also. Once the PDFs are loaded it will be flickering on every action.

**Comment by ColinT** [comment]
Please see the example here: https://stackblitz.com/edit/angular-xmrcns, or submit a reproduction.
The example shows changing pages of two pdf-viewers independently in the same DOM instance.

Please check that your template bindings are correct. You may have mixed your variables between multiple pdf-viewer instances.

**Comment by jinsts** [comment]
Sorry for the delayed reply. Problem was with the template binding. Same constant configuration object was used as default PDF viewer configuration. Solved by  performing a deep clone of the object for each viewer instance. Thanks for the help. 👍
