### ISSUE TITLE
Count of instances in text search

### ISSUE THREAD

**Issue by MicheleTro** [VadimDez/ng2-pdf-viewer#446]
Hi,

How can I know how many instances there are when I make a text search?

I didn't find anything about it.

Thanks.

**Comment by ColinT** [comment]
You can probably get it from the underlying `updatefindmatchescount` event from the `PdfFindController` event bus:
https://github.com/mozilla/pdf.js/blob/ece6a31a442d8d2489817579dfc57ed371135d3a/web/pdf_find_controller.js#L696-L701

I don't think `ng2-pdf-viewer` currently exposes this event in an Angular way.
