### ISSUE TITLE
stackblitz example page not working

### ISSUE THREAD

**Issue by nitslucky** [VadimDez/ng2-pdf-viewer#447]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [x ] Documentation issue or request
```

**Comment by VadimDez** [comment]
Seems to be working fine.

**Comment by nitslucky** [comment]
![image](https://user-images.githubusercontent.com/23555070/53019910-1f642780-3456-11e9-9381-bc9008ac876d.png)

**Comment by nitslucky** [comment]
> Seems to be working fine.

Please check the screenshot pasted above. The given URL for stackblitz on npm and github website is not working. [https://stackblitz.com/edit/ng2-pdf-viewer](https://stackblitz.com/edit/ng2-pdf-viewer)

**Comment by VadimDez** [comment]
It seems like you can't access this file: https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf
You've got net:ERR_FAILED on that file. Can you access it directly?

**Comment by nitslucky** [comment]
Yes I can access the file directly in browser.

**Comment by ezdin** [comment]
Same here, works on firefox but not on chrome.

**Comment by haifzhan** [comment]
Same issue here, demo is not working on Chrome and Firefox
