### ISSUE TITLE
using ngx-pinch-zoom with pdf 

### ISSUE THREAD

**Issue by AmineMediazain** [VadimDez/ng2-pdf-viewer#448]
I tried to use pinch to zoom module with pdf viewer, but I get an issue with canvas size.
any help?

**Comment by kukuandroid** [comment]
I face the same issue, please advice. Thank you

**Comment by AmineMediazain** [comment]
what is exactly your problem ?

**Comment by kukuandroid** [comment]
> what is exactly your problem ?

I try to implement ngx-pinch-zoom library by using this code: 
` <pinch-zoom>
    <div class="oat-pdf-container">
      <pdf-viewer
        [src]="pdfSrc"
        [render-text]="true"
        (after-load-complete)="afterLoadComplete($event)"
        [fit-to-page]="true"
        style="display: block;"
      ></pdf-viewer>
    </div>
  </pinch-zoom>`

**Comment by AmineMediazain** [comment]
Try to see this it can helps :  
http://crystalui.org/components/pinch-zoom
https://www.npmjs.com/package/ngx-pinch-zoom

you can handle zoom events like that :  
<pinch-zoom id="somePinchZoom" (events)="handlePinchZoomEvents($event)">
				<pdf-viewer  [src]="pdfSrc" 
				[page]="page"
				[stick-to-page]="false"
						[show-all]="false"
						[render-text]="true"
						[original-size]="true"
						(page-rendered)="pageRendered($event)"           
						(after-load-complete)="afterLoadComplete($event)"
						style="display: block;max-width:100%"
						(after-load-complete) = "loadComplete()"
						>
				</pdf-viewer>	 
			</pinch-zoom>

**Comment by kukuandroid** [comment]
> http://crystalui.org/components/pinch-zoom

Im trying now, thanks brother =)

**Comment by AmineMediazain** [comment]
you welcome man 👍
