### ISSUE TITLE
Blank page IOS

### ISSUE THREAD

**Issue by erjimmmy** [VadimDez/ng2-pdf-viewer#449]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Hello,

I have a problem when I try to view several times a pdf, because a blank page is rendered. I am developing an ionic app, and I have the problem with IOS plattform.  Android works fine.

Any ideas?

Thanks in advance

**Comment by strerene** [comment]
Hey, 
we are experiencing the same issue, I think this is related to #414

**Comment by rob-moore** [comment]
+1-ing this. We're also having a similar issue where we are intermittently seeing issues of the pdf never loading on iOS

**Comment by VadimDez** [comment]
Fixed in `6.0.0` See https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600

**Comment by kaden0428** [comment]
IOS 14 is working fine but not in IOS 12.4.8.

**Comment by yeshchaubey** [comment]
IOS 14 is working fine but not in IOS 12.4.9.

**Comment by magorismagor** [comment]
Please help!

**Comment by ZeroSkill830** [comment]
The issue is still present

**Comment by danielehrhardt** [comment]
> The issue is still present

Same here!
