### ISSUE TITLE
nativeElement.offsetWidth is 0 with bootstrap v4.0.0-alpha.6

### ISSUE THREAD

**Issue by chunghha** [VadimDez/ng2-pdf-viewer#45]
After updating bootstrap to v4.0.0-alpha.6 from alpha.5, I see a problem with the code below.

`      if (!this._originalSize) {
        viewport = page.getViewport(this.element.nativeElement.offsetWidth / viewport.width, this._rotation);
      }`

In my case, the offsetWidth is 0 so canvas width/height become 0 too which leads to no pdf page displayed.

I use ng-bootstrap
"@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.18"

and bootstrap.min.css in index.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
    integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

(problem, offsetWidth is 0. )
![image](https://cloud.githubusercontent.com/assets/24458075/22071103/bb588eca-dd63-11e6-8bf1-36029345aacb.png)

(same code, just take out bootstrap.min.css from index.html then offsetWidth is there so no problem to see pdf pages.)
![image](https://cloud.githubusercontent.com/assets/24458075/22071113/c079971e-dd63-11e6-9c4e-79ced8c49339.png)

@VadimDez, I am not sure this is an issue of the bootstrap 4 version or you can fix with your code. And, if you need a re-pro, I will try to create one.

**Comment by chunghha** [comment]
plnkr for reproduce:
http://plnkr.co/edit/BIqTgFAz1MsU20wMWlBv?p=preview

You will see no page displayed if you change bootstrap.min. css version in the index.html from '4.0.0-alpha.**5**' to '4.0.0-alpha.**6**'

**Comment by VadimDez** [comment]
Nice plnkr 👍 
Two options that you can try
- remove class `row` on that div
```html
<div style="...">
  <pdf-viewer...
```
- put `pdf-viewer` inside `.col-sm-12` which is inside `.row`
```html
<div class="row">
  <div class="col-sm-12">
    <pdf-viewer...
```

**Comment by chunghha** [comment]
Oh silly me! Verified that without the class="row" works fine.
