### ISSUE TITLE
show-all page rendering order affected by negative margin on parent container

### ISSUE THREAD

**Issue by JoeHogan** [VadimDez/ng2-pdf-viewer#452]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

I was seeing behavior where on multi-page documents with show-all="true" the last page to be rendered was the first page. I debugged this back to the _getVisiblePages() function, which calls the getVisibleElements() function, which used the following sort function:

`function isElementBottomAfterViewTop(view) {
    var element = view.div;
    var elementBottom = element.offsetTop + element.clientTop + element.clientHeight;
    return elementBottom > top;
  }`

in my case, this was reordering the pages such that my first page became the last in the visible pages array, which is used for the rendering queue. It turns out that i had set a negative margin on the pdf-viewer element with css, but this set the element.offsetTop to -1 on the first page element, causing the ordering function above to reorder the page to last. removing the CSS negative margin fixed the issue, but the sort funcition should probably be updated to support negative margins. the offset should be calculated relative to the parent container.

**Comment by ColinT** [comment]
Try adding `position: relative` css to your parent container.

The underlying viewer (`pdfjs-dist`) calculates which pages are visible based on the nearest relatively positioned parent.

Currently `ng2-pdf-viewer` leaves specifying this parent up to the user in this way, which when left 'unspecified' can cause unexpected behaviour.
