### ISSUE TITLE
Read PDF-Dimensions

### ISSUE THREAD

**Issue by tobiasgruber-at** [VadimDez/ng2-pdf-viewer#455]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```
I would like to read the Height and Width of my PDF-Document, similar to the naturalWidth and naturalHeight properties on [Image-Elements](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement). Is it already somehow possible?

**Comment by Gsuz** [comment]
I think you already can.

in the html div add 
(page-rendered)="pageRendered($event)"

then in typescript
console.log(e) to see all information available.
console.log(e.path.0.clientHeight) =  height
console.log(e.path.0.clientWidth)  = width
