### ISSUE TITLE
Unable to auto-resize the pdf.

### ISSUE THREAD

**Issue by aks7665** [VadimDez/ng2-pdf-viewer#462]
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [X ] Documentation issue or request

I implemented the same over at stackblitz.
https://stackblitz.com/edit/ng2-pdf-viewer?file=app%2Fapp.component.html (On there demo link).

< div class="pdf-container" style="width: 360px">
   <pdf-viewer [src]="src"
              [original-size]="false"
              [autoresize]="true"
  ></pdf-viewer>
< /div>

But auto resize does not working.

**Comment by VadimDez** [comment]
Have you tried to add following `CSS` rule?
```css
pdf-viewer {
  display: block;
}
```
https://github.com/VadimDez/ng2-pdf-viewer#autoresize
