### ISSUE TITLE
Need to add custom pdfjs-dist or another version of pdfjs-dist

### ISSUE THREAD

**Issue by ku20043703** [VadimDez/ng2-pdf-viewer#468]
Need to add custom pdfjs-dist or another version of pdfjs-dist
What are the configuration or changes need to make in pdf-viewer to accommodate custom pdf-dist   or another version of pdfjs-dist

**Comment by ku20043703** [comment]
@VadimDez  Looking for ypur help on it

**Comment by ku20043703** [comment]
@VadimDez  I am urgently looking for it. Can you help me on it.

**Comment by VadimDez** [comment]
You could try to alias and point to a different dependency with webpack for example.

**Comment by ku20043703** [comment]
> You could try to alias and point to a different dependency with webpack for example.

Yes how to alias to different version or custom pdfjs-dist

**Comment by mmrzk** [comment]
In my case I had to comment out 1 line inside pdfjs-dist and I used `patch-package` package on npm. It allows for patching code of your dependencies and it worked for me.
