### ISSUE TITLE
PDF appears to be blurry 

### ISSUE THREAD

**Issue by sahilkale** [VadimDez/ng2-pdf-viewer#469]
We are using ng2 pdf viewer to launch pdf book in our applcation , but it appears to be blurry , also when we try to zoom using css zoom (using Transform) it becomes more blurry and text is unreadable , can someone help ?.

![image](https://user-images.githubusercontent.com/49892928/56563282-e61c7500-65c8-11e9-9f29-4eadaac037f8.png)
PDF Viewer Code :
<pdf-viewer [src]="pdfSrc" [render-text]="true" style="display: block; overflow: hidden;"
(after-load-complete)="afterPdfLoadComplete($event)" [show-all]="false" [(page)]="pdfpagenum"
[(zoom)]="pdfzoomval" [autoresize]="true" [original-size]="false" [fit-to-page]="true"
(page-rendered)="pageRendered($event)" (pageChange)="onPageChanged($event)" id="pdfviewer" *ngIf="showPDFReaderComponent">

**Comment by smithchhetri** [comment]
Have you managed to solve this issue?
