### ISSUE TITLE
CORS error in dev only if I include SimplePdfViewerModule.

### ISSUE THREAD

**Issue by manojp1988** [VadimDez/ng2-pdf-viewer#470]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
In Dev, I'm able to add view pdf with this library until I don't add http calls. If I add http call, I'm getting CORS issue. This same issue is not occuring if I don't include SimplePdfViewerModule, and http calls go through fine.

Is there anything special in this module which is causing this issue.?

**Comment by VadimDez** [comment]
SimplePdfViewerModule is a different library, please refer to the author there.
