### ISSUE TITLE
PDF is not resizing according to the screen size/ not responsive enough

### ISSUE THREAD

**Issue by R13104** [VadimDez/ng2-pdf-viewer#472]
Hi All, If I apply zoom In to the PDF view then it should be responsive enough with respect to the screen size but I am not able to find any solution for the same.  

For example -
For screen size 1920 * 1080 the zoom In 200% on PDF view will not show the horizontal scroll but in case of smaller screen size it will show the horizontal scroll. So zoom In values are not ratio proportional with respect to the screen size.

I have tried all the properties of this package to solve this issue.
Please suggest the way to solve the same.

**Comment by the80** [comment]
Same here... [zoom] at 4k is too small in 1080 too large!
