### ISSUE TITLE
Conflict pdf.js 2.0.943 and quill.js 1.3.6

### ISSUE THREAD

**Issue by kminhtri** [VadimDez/ng2-pdf-viewer#475]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Hello,

Just for information :
On IE 11 environment ONLY :
We are using ng2-pdf-viewer 5.2.4 who has pdf.js dependency version 2.0.943.
We are using quilljs version 1.3.6 (it's a WYSWIG editor) too.

Here a jsfiddle with the bug : [https://jsfiddle.net/fca8z1bw/3/](https://jsfiddle.net/fca8z1bw/3/)

pdf.js v2.0.943 create a bug on quilljs editor on color selection button (no opening dropdown list). I try pdf.js version superior 2.1.266 and everything works like a charm.

Maybe you are trying to update your pdf.js dependency version?

Awaiting your new version, we are using ng2-pdf-viewer 5.2.1 who has pdf.js version 2.0.550 :)

Thank you for your library, good job !

**Comment by VadimDez** [comment]
Fixed in `5.3.1`
