### ISSUE TITLE
ERROR Error: "Uncaught (in promise): DataCloneError: The object could not be cloned.

### ISSUE THREAD

**Issue by brokuto** [VadimDez/ng2-pdf-viewer#477]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Hi
I implemented your PDF viewer in my application and on Firefox it works fine with your PDF-URL (https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf).

But I tried with another random PDF off of the Internet (e.g. http://www.pdf995.com/samples/pdf.pdf) and suddenly I get this Error

`ERROR Error: "Uncaught (in promise): DataCloneError: The object could not be cloned.
postMessage@http://localhost:4200/vendor.js:162828:7
sendStreamRequest@http://localhost:4200/vendor.js:162645:7
error@http://localhost:4200/vendor.js:162688:9
setupMessageHandler/</sink.onPull/<@http://localhost:4200/vendor.js:158716:13
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:4200/polyfills.js:3026:17
onInvoke@http://localhost:4200/vendor.js:78760:24
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:4200/polyfills.js:3025:37
./node_modules/zone.js/dist/zone.js/</Zone.prototype.run@http://localhost:4200/polyfills.js:2785:24
scheduleResolveOrReject/<@http://localhost:4200/polyfills.js:3524:29
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:3058:17
onInvokeTask@http://localhost:4200/vendor.js:78751:24
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:3057:41
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://localhost:4200/polyfills.js:2830:28
drainMicroTaskQueue@http://localhost:4200/polyfills.js:3236:25
"`

and nothing is displayed.
Do you know what the issue is? Is it because those PDFs may be protected?

**Comment by hzitoun** [comment]
encountering the same problem on Firefox using angular 7

**Comment by hzitoun** [comment]
I've had the same problem and it was due to CORS policy

**Comment by brokuto** [comment]
> 
> 
> I've had the same problem and it was due to CORS policy

Oh thank you so much. You're a Life saver!
It worked for me with the CORS Plugin for Firefox.
