### ISSUE TITLE
PDF is not rendering only on Firefox Desktop version

### ISSUE THREAD

**Issue by snsakib** [VadimDez/ng2-pdf-viewer#480]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I'm trying to render a PDF file using angular 7.
The PDF file is rendering on every other browser other than Firefox (Desktop version).
The console showing the following error:
Error: Permission denied to access property "__rocketLoaderInlineHandlerProxy"
[Project Link](https://www.snsakib.com/angular-pdf-viewer)

I've done some research, I think it is an issue with Cloudflare CDN.

**Comment by snsakib** [comment]
I've found the solution. I had a firefox add-on named "Facebook Container". It was causing the problem. After disabling the extension everything is working fine. That's why I'm closing this issue.

**Comment by Teiron** [comment]
Please note that "Facebook Container" team already solved the issue https://github.com/mozilla/contain-facebook/issues/384
