### ISSUE TITLE
Two pages side-by-side.

### ISSUE THREAD

**Issue by Charles1972** [VadimDez/ng2-pdf-viewer#483]
There is way to show two page side-by-side (like book)?

**Comment by Charles1972** [comment]
Could be solved using CSS. I'm working on this. When I'll finish i'll write the solution

**Comment by Nishanth-S** [comment]
How did you solve it?

**Comment by Charles1972** [comment]
Unfortunately I've encountered big issues and the result was not good, so I decided to move to another library!

**Comment by shirmanov** [comment]
> Unfortunately I've encountered big issues and the result was not good, so I decided to move to another library!

Which library have you chosen to display two pages?
