### ISSUE TITLE
Deprecated API usage: getViewport is called with obsolete arguments.

### ISSUE THREAD

**Issue by dmytro-gokun** [VadimDez/ng2-pdf-viewer#487]
I see this message in the browser console when using the latest version. It's coming from here: https://github.com/VadimDez/ng2-pdf-viewer/blob/06800082718f83418d20a83fa6c719745188c395/src/app/pdf-viewer/pdf-viewer.component.ts#L332

**Comment by VadimDez** [comment]
Fixed in 5.3.2
