### ISSUE TITLE
[(page)] two way binding still does not work

### ISSUE THREAD

**Issue by jiangyh1024** [VadimDez/ng2-pdf-viewer#488]
```

<pdf-viewer [src]="pdfSrc" [render-text]="true" [stick-to-page]="true" [(page)]="pageVariable" [autoresize]="true"
  [original-size]="false" style="display: block; height: 400px;
width: 400px; overflow: auto" [show-all]="true" (after-load-complete)="onCallback($event)"></pdf-viewer>

<button (click)="onClicked()">get page</button>
```
![image](https://user-images.githubusercontent.com/34930870/59236147-65244600-8c27-11e9-83ee-7b5668948e23.png)

I set pageVariable to 3, but it did not direct to page 3, and after scrolling to other page then click button, it always print '3'

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/59236188-956be480-8c27-11e9-8c6b-028da8f26ad0.png)

It always shows first page regardless of the property 'pageVariable ' I set

**Comment by jiangyh1024** [comment]
@ColinT  hi, long time no see. Are u still here. I am begging for help

**Comment by ColinT** [comment]
Duplicate of https://github.com/VadimDez/ng2-pdf-viewer/issues/223
`[page]` is currently not supported with `[show-all]="true"`

This is an enhancement that is already being tracked on [#445](https://github.com/VadimDez/ng2-pdf-viewer/pull/445). You can use the working demo branch supplied there if you do not want to wait for the merge, as it is currently blocked until further work is done.
