### ISSUE TITLE
Invalid 'reference' directive syntax

### ISSUE THREAD

**Issue by roginneil** [VadimDez/ng2-pdf-viewer#489]
Hi, I'm getting this error when I try to build my application after I installed ng2-pdf-viewer. 
Is there a workaround for this?
![image](https://user-images.githubusercontent.com/42271331/59252161-04643000-8c5e-11e9-8280-99a005f5bf06.png)

**Comment by YangFan17** [comment]
try to update typescript 3.0.0+

**Comment by VadimDez** [comment]
@roginneil please close if updating typescript helps

**Comment by roginneil** [comment]
I downgraded pdf-viewer version to 3.0.8. That's how I fix this issue
