### ISSUE TITLE
Hyperlinks are not working

### ISSUE THREAD

**Issue by gaurav2887** [VadimDez/ng2-pdf-viewer#49]
I am able to view the pdf on the browser but none of the hyperlink works. Is there any option to enable it as I am already using [render-text]="true" and that did not enable hyperlinks?

**Comment by VadimDez** [comment]
Not yet. Work in progress...

**Comment by gaurav2887** [comment]
@VadimDez - Thanks. Please let me know once it's ready.

**Comment by VadimDez** [comment]
Closing as duplicate of #18
