### ISSUE TITLE
canvas memory is not destroying while close the opened pdfs in tabs(max 5 pdf) in ionic v4 cordova (Total canvas memory exceeds the maximum limit (224mb)) and showing the blank pages

### ISSUE THREAD

**Issue by jitendrak414** [VadimDez/ng2-pdf-viewer#492]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

**Comment by VadimDez** [comment]
Which version of `ng2-pdf-viewer` are you using?

**Comment by gamalshaaban1986** [comment]
Hi Vadim,

I am facing the same issue and i am using version 6.0.1

**Comment by seopei** [comment]
I am facing the same issue with Ionic 5 and the newest version of ng2-pdf-viewer.
```
Total canvas memory use exceeds the maximum limit (384 MB).
```

**Comment by seopei** [comment]
I think this one is related to https://github.com/VadimDez/ng2-pdf-viewer/issues/392.
I am having the same problem on Safari ("Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148") so it is not Ionic related.

Maybe this are possible solutions: https://github.com/mozilla/pdf.js/issues/11297 and https://github.com/mozilla/pdf.js/issues/11245
