### ISSUE TITLE
Fit PDF with height of the container

### ISSUE THREAD

**Issue by RahmatAliMalik5** [VadimDez/ng2-pdf-viewer#493]
I am trying to fit the PDF within the height of the container from weeks without any luck. Have tried to use `fit-to-page` with other settings as per suggested in the documentation. I have googled a lot, used the core PDFJS extension in my application to get `page-fit` work, but got nothing.

I have opened question at [StackOverflow](https://stackoverflow.com/questions/56601874/how-the-make-pdf-fit-the-height-ng2-pdf-viewer/56601931#56601931). It is not yet answered.

I would like to have very same config, like we can have by selecting `Page Fit` from `Zoom` option dropdown in PDFJS official example (link to [example](https://mozilla.github.io/pdf.js/web/viewer.html)):
![example of required](https://user-images.githubusercontent.com/31620469/59562992-a795ba80-904d-11e9-81cc-41421769f3cd.PNG)

I have used `fit-to-page` with certain other configs. But every time it fits with the width. I like to fit the PDF with the height, so whole PDF page can be viewed without scrolling in the container.

Here is what, I have got right now:
![image](https://user-images.githubusercontent.com/31620469/59563082-9b5e2d00-904e-11e9-881f-d40b49c5b039.png)

My code snippet is as follows:
```
            <div id="pdfContainerDiv" style='height: 300px;'>
              <pdf-viewer
              [src]='"./assets/images/userFiles/" + file.fileName'
              ([page])=1
              [render-text]='false'
              [original-size]='true'
              [fit-to-page]='true'
              style="display: block; height: 300px;"
              (after-load-complete)='afterLoadComplete($event)'
              (page-rendered)='pageRendered($event)'
              (pageChange)='pageChange($event)'

              ></pdf-viewer>
           </div>
```

Let me know how can I show full page with complete height in that 300px container.

**Comment by VadimDez** [comment]
You have to configure your `CSS` so that the `pdf-viewer` container is taking the entire height of the container like you want it.

**Comment by RahmatAliMalik5** [comment]
After a lot of efforts and a `css` clue from VadimDez, I have found a way for making PDFs stretch to the height of container. I don't know whether it is good approach or not, but it is working great in my scenario.

1.  Add following `css` in your main `style.scss` or `style.css`:

```
.ng2-pdf-viewer-container {
  overflow: hidden;
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
}

```
2. Get `ng2-pdf-viewer` component into your component like this:

```
// other imports
import { PdfViewerComponent } from 'ng2-pdf-viewer';


export class YourComponent{

  @ViewChild(PdfViewerComponent, {static: false})
  private pdfComponent: PdfViewerComponent;

// other code
}
```
3. Then use `(page-rendered)` event function to edit the `currentScaleValue` of the `pdfViewer`. Please check code below:

**In html file**:

```
            <pdf-viewer [src]='"./assets/images/userFiles/" + file.fileName'
            [show-all]="false"
            [autoresize]="true"
            [original-size]='true'
            [fit-to-page]='true'
            [render-text]='false'
            (page-rendered)="pageRendered()"
            ></pdf-viewer>
```

**In your component file**:

```
  // called after pdf page is rendered
  pageRendered() {
    this.pdfComponent.pdfViewer.currentScaleValue = 'page-fit';
  }
```

That's it. Please note, you will notice a flicker or glitch when pdf is updated or browser screen is resized. It is because, `ng2-pdf-viewer` changing the height according the it's settings and then when pdf page is rendered, we change it to the `page-fit`. I hide the pdf for a while when it updates and then show after it loads the settings to the `page-fit`.

Definitely, there are some good approaches to do this. But, this is the only one, I have found after a search of months.

**Comment by Istanful** [comment]
Using @RahmatAliMalik5 [solution](https://github.com/VadimDez/ng2-pdf-viewer/issues/493#issuecomment-520229245) unfortunately messes up the ability to zoom.

As an extension of his answer, if you'd like to be able to use the zoom you can calculate initial zoom and set it on page render.

**In your html:**

```html
		<pdf-viewer
			[show-all]="false"
			[autoresize]="true"
			[original-size]="true"
			[fit-to-page]="true"
			[render-text]="false"
			[page]="page$ | async"
			[zoom]="zoom$ | async"
			(page-rendered)="pageRendered($event)"
			[src]="src"
		></pdf-viewer>
```

**In your component:**
```typescript
	pageRendered(ev) {
		if (this.initialZoomSet) {
			return;
		}

		this.initialZoomSet = true;
		const width = ev.source.div.clientWidth;
		const height = ev.source.div.clientHeight;
		const ratio = width / height;
		const targetHeight = 384;
		const requiredWidth = ratio * targetHeight;
		const scale = requiredWidth / width;
		this.setState('zoom', scale);
	}
```

I use the `initialScaleSet` variable to prevent the initial zoom to be set several times. The target height is the desired height.

**Comment by arunkg16021986** [comment]
@RahmatAliMalik5 . Can you suggest a way to hide it for a while and show after it loads. Please

**Comment by RahmatAliMalik5** [comment]
@arunkg16021986 I worked on that project year before and now have no, how I have done it before. I think the preferred  way will be to use a `boolean` variable initialized by `false` and then use it on the `pdf-viewer` to hide and then show the pdf when rendered with `page-fit` style. Please check the example below, but please keep in mind, I have not tested this code. It is just to share in which way you should think to achieve it:

**Your Component:**
```
// other imports
import { PdfViewerComponent } from 'ng2-pdf-viewer';


export class YourComponent {

  @ViewChild(PdfViewerComponent, {static: false})
  private pdfComponent: PdfViewerComponent;

  hidePdf = true;       // <----- here variable is initialized


  pageRendered() {
    this.pdfComponent.pdfViewer.currentScaleValue = 'page-fit';
   
    setTimeout(() => { hidePdf = false;  } , 100 ); // <----- here we are going to show pdf
  }
}
```

**Your HTML:**

```
<div style='position: relative; height: 100%;'>

            <pdf-viewer
            [hidden]="hidePdf"
            [src]='"./assets/images/userFiles/" + file.fileName'
            [show-all]="false"
            [autoresize]="true"
            [original-size]='true'
            [fit-to-page]='true'
            [render-text]='false'
            (page-rendered)="pageRendered()"
            ></pdf-viewer>
</div>
```



==============================================

I have set the `hidePdf` to `true` in  `setTimeout()` because it will take some milliseconds to update the pdf to `page-fit`. You check it in your code if it works fine without `setTimeout()` or by increasing the time in `setTimeout()` to a bigger value.

**Comment by rocky-23** [comment]
1. How to select and copy a text after converted into canvas?
2. How to avoid bottom gets trim?
Help me out of this. Thanks in advance.
