### ISSUE TITLE
Not able to navigate to a Page just after load

### ISSUE THREAD

**Issue by kakroo** [VadimDez/ng2-pdf-viewer#496]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I am creating an angular app having a feature which can navigate directly to a specific page no. after pdf is loaded.

```
 public onPageLoaded()
{
      this.page=this.globalPage;
 }
 public onPageRendered()
{
      this.page=this.globalPage;
}
```
```
  <ngx-extended-pdf-viewer
    [src]="filePathAndName"
    backgroundColor="#ffffff"
    [height]="'90vh'"
    [useBrowserLocale]="true"
    [zoom]="90"
    [page]="page"
    (pagesLoaded)="onPageLoaded()"
    (pageRendered)="onPageRendered()"
    > 
```

i'm getting the url of the PDF and the page number to be navigated to from an API. The PDF loads fine, but i'm not navigated to the page number. Tried doing it on both `pagesLoaded` & `pageRendered` but that did not work.

Version - 0.9.49

**Comment by kukuandroid** [comment]
pray to God first

**Comment by VadimDez** [comment]
@kakroo You posted to the wrong repo, you're using different library and not `ng2-pdf-viewer`...
