### ISSUE TITLE
Default Rotation

### ISSUE THREAD

**Issue by jdell64** [VadimDez/ng2-pdf-viewer#50]
Is there a way to predict the default rotation of a file? Is it the same orientation that the pdf is in on the system?

Some PDFs open up -90 rotated, and I have to set the rotation to 90, while others open normally and I have to set rotation back to 0. On the system, they both appear to be oriented properly.

**Comment by jonaswinkler** [comment]
Can confirm this issue. Attached is a two page document, which shows up correctly using desktop pdf viewers. With ng2-pdf-viewer, one page is rendered up side down, the other one is rendered correctly.

[rotation_test.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/753126/rotation_test.pdf)

**Comment by rfreedman** [comment]
Can confirm - here is a pdf that renders 180 rotated with ng2-pdf-viewer, but renders correctly when loaded directly by the browser, or viewed with other apps.
[book3-0109F.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/836050/book3-0109F.pdf)

**Comment by marcelot** [comment]
You can handle event "after-load-complete", get selected page and check it's rotation.

`
    afterLoadComplete(pdf:any) {
        pdf.getPage(page_no).then((page:any) => {
            this.rotate = page.pageInfo.rotate;
        });
    }`

**Comment by VadimDez** [comment]
fixed in 2.0.0
