### ISSUE TITLE
Does not render form fields

### ISSUE THREAD

**Issue by carlosrodj** [VadimDez/ng2-pdf-viewer#500]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ x] Feature request
- [ ] Documentation issue or request
```

Render form fields, signatures

**Comment by VadimDez** [comment]
Could you provide an example pdf that doesn't render those fields?

**Comment by carlosrodj** [comment]
Yes of course!

in the chrome viewer, the signature field at the bottom of the page is rendered. Sorry for my English.

https://npaper.com.br/api/papers/document/file/93ae4984-f40f-465b-af19-e9c28475473d
