### ISSUE TITLE
Is it possible to terminate a page rendering?

### ISSUE THREAD

**Issue by ISTAnsver** [VadimDez/ng2-pdf-viewer#502]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [x] Documentation issue or request
```
Users in our system can choose an element in a list. When an element was chosen we show some pdf document. When user will choose some different elemen t then some different pdf document will be rendered. If a previous document haven't been loaded then I see that performance was down because a rendering time became more longer. I think it is because old processes were not end.

**Comment by ISTAnsver** [comment]
I think when _src_ was changed all old processes related to the old pdf document should be terminated.

**Comment by VadimDez** [comment]
Could you try the latest version `6.0.1`? Also don't forget about breaking change. pdf-viewer container now should be scrollable for the best performance. https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#breaking-change
