### ISSUE TITLE
Shouldn't ng2-pdf-viewer use pdf.worker.min.js from pdfjs-dist library?

### ISSUE THREAD

**Issue by LAlves91** [VadimDez/ng2-pdf-viewer#504]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
My project has to work without outside download requests, so we had to include our own pdf.worker.min.js. But this aproach can be quite troublesome, since pdf.worker.min.js version can change depending on pdfjs version.

As pdfjs-dist library (which is included in ng2-pdf-viewer dependencies) already comes with its version of pdf.worker.min.js, wouldn't it be better for ng2-pdf-viewer to use it instead of downloading it from an external source?

**Comment by VadimDez** [comment]
@LAlves91 You can always copy `pdf.worker.min.js` from `node_modules` to your `assets` folder before you build and then set it like this https://github.com/VadimDez/ng2-pdf-viewer#set-custom-path-to-the-worker

**Comment by VadimDez** [comment]
To make setup and use of this library easier - `pdf.worker.min.js` is getting dowloaded from the CDN in the first place. In this way as a developer you don't need to copy and paste `pdf.worker.min.js` to your assets folder and link it in the code.

**Comment by nika1001** [comment]
@VadimDez I'm having the same problem as @LAlves91. Personally I don't like the solution to copy `pdf.worker.min.js` from the already included pdfjs-dist library into `assets` folder mainly because of redundancy (it would also require manually checking for new updates).
I'm thinking wouldn't it be possible to somehow dynamically find out the path of pdf worker within the pdfjs-dist library? Something like `requirejs.toUrl('pdfjs-dist/build/pdf.worker.js');`

**Comment by LAlves91** [comment]
@VadimDez and @nika1001, 

The project I work on had a MAJOR problem recently because of this solution: pdfjs-dist isn't static in ng2-pdf-viewer peer dependencies (pdfjs-dist: "^2.2.228").
*  Problem: our version of pdf.worker.min.js was behind considering the latest pdfjs-dist minor release.
*  Result: PDF viewer wasn't rendering PDF files but browser console didn't show ANY errors. It took me a while to remember the cause could be our fixed version of pdf.worker.

I think this can be seen as an evidence about this solution not being the best aproach to not downloading pdf.worker from an external url.

Best regards.

**Comment by htruong24** [comment]
Hi @LAlves91 , I got the same issue with (pdfjs-dist: "^2.2.228"), could you let me know which version you are using in package.json or the package.json content? 
Thanks so much.

**Comment by LAlves91** [comment]
Hi @htruong24 ,

At the moment, this is how we have declared our PDF dependencies in package.json:

`
    "ng2-pdf-viewer": "5.3.2",
    "pdfjs-dist": "2.1.266",
`

If your project has the same limitations as mine (application shouldn't access external links), the trick is using these steps:

- Fix ng2-pdf-viewer version;
- See which version of pdfjs-dist that specific ng2-pdf-viewer is using;
- With the information of the previous step, fix the version of pdfjs-dist in your package.json.

Once we followed this steps, all our functionalities which had PDF viewers stabilized.

Best regards!

**Comment by htruong24** [comment]
Thanks @LAlves91, let me check to see if it work!

**Comment by pazuza** [comment]
thanks @LAlves91, it's working !

**Comment by eedahl** [comment]
> "pdfjs-dist"

This doesn't really seem to work for me. Using 6.3.2 and 2.4.456. Not sure if it's just me, but access to pdf.worker.min.js seems very flaky, meaning the viewer sometimes works, sometimes doesn't work.

**Comment by eedahl** [comment]
@VadimDez Is this supposed to be fixed in the latest version? It's still attempting to access a CDN for pdf.worker.min.js for some reason.

**Comment by LAlves91** [comment]
@eedahl , greetings!

I don't know if I've made one fact clear before: we use the [default solution](https://github.com/VadimDez/ng2-pdf-viewer#set-custom-path-to-the-worker) to work with a pdf.worker inside our assets.

But in order for it to work correctly, we have to use the right pdf.worker version (in relation to pdfjs-dist lib, which is a ng2-pdf-viewer dependency). So, we use a specific version of both libraries, copying the right worker to our assets folder. When we have the need to update any of the libraries, we have to make sure pdfjs-dist still use the same worker, replacing it if needed.

Best regards!

**Comment by eedahl** [comment]
@LAlves91, hi! Thanks for getting back to me.

I actually tried doing this and it worked locally, but when I deployed it to our server it couldn't find the correct path, trying to GET an endpoint that doesn't exist. This seems like an issue with me not dealing with static files correctly in the context of my setup, though.

**Comment by LAlves91** [comment]
Hey @eedahl !

Sorry for taking so long to answer...I believe you're right. There are two things you should look into:

- How are you importing the pdf.worker file inside your component?
- How are you including the pdf.worker file in your project? Is it in your assets folder? Are the assets being included in production inside angular.json?

Write these informations here, and I'll help you through it!

**Comment by tsiegleauq** [comment]
>  In this way as a developer you don't need to copy and paste pdf.worker.min.js to your assets folder and link it in the code.

My project has the same limitations. But instead of copying and pasting the `pdf.worker.min.js` into my own assets folder, I provided them as an angular asset in my `angular.json`. Perhaps it might help someone. I suppose using this you do not need to care for manual updates in pdfjs-dist anymore. Still, it might be a good idea to stick the version of both libraries to avoid nasty surprises.

```json
"architect": {
    "build": {
        "options": {
            "assets": [
                "src/assets",
                "src/manifest.json",
                {
                    "glob": "pdf.worker.min.js",
                    "input": "node_modules/pdfjs-dist/build/",
                    "output": "/assets/js/"
                }
            ],
```

As documented in the readme, you can provide the following to your pdf-components constructor:
```ts
public constructor() {
    (window as any).pdfWorkerSrc = '/assets/js/pdf.worker.min.js';
}
```

**Comment by magorismagor** [comment]
@LAlves91, I copied the worker from the node_modules/pdfjs-dist folder, and by setting pdfWorkerSrc properly in my constructor, my hosted worker (version 2.6.347) is being used. Thank you for that.  

However, the PDFs are not shown. I followed the instructions stated by @mpstv [here](https://github.com/VadimDez/ng2-pdf-viewer/issues/669#issuecomment-733874470) for logging the error messages to the console, and I got  "The API version "2.5.207" does not match the Worker version "2.6.347". 

In my package.json I have:
"ng2-pdf-viewer": "6.4.0",
 "pdfjs-dist": "2.6.347",

I have checked that inside the node_modules/pdfjs-dist/package.json the version is correct (2.6.347).
In the folder node_modules\ng2-pdf-viewer\node_modules\ the version of the pdfjs-dist if 2.5.207, so I guess that this is the cause of the problem.

Any idea for solving this issue?  

Thanks to all!

**Comment by LAlves91** [comment]
Hi @magorismagor!

Currently, ng2-pdf-viewer doesn't work with pdfjs-dist 2.6.x and above (since this version, pdfjs is exporting its own typings, which clash with previous typings defined at @types/pdfjs-dist). For now, you should downgrade pdfjs-dist version to 2.5.207 in you project.

Cheers!

**Comment by magorismagor** [comment]
What a pity! In fact I was planning to upgrade to the 2.7.570 version in the future in order to use the getFieldObjects() method to get the Acroform.

Do you know if there is any plan to make ng2-pdf-viewer compatible with the new versions of pdfjs?

Thank you so much for your kick reply @LAlves91!

**Comment by LAlves91** [comment]
@magorismagor, no problem at all!

As for the possible update, I'm also really waiting for it! The project I work on has a really problematic screen which blends pdf-viewer and infinite scroll to render multiple documents, one after the other. Hopefully version 2.7.x performance improvements will help me!

@VadimDez is there a plan to release a new version with pdfjs 2.7.570 in the near future?

Thank you!

**Comment by magorismagor** [comment]
Thanks again @LAlves91 

By the way, in another of our sites, with "ng2-pdf-viewer": "6.2.0" and "pdfjs-dist": "2.5.207" in package.json, and with the worker served by Cloudflare, I can see that the version of the downloaded worker is the 2.6.347 (I attach a screen capture of the Google Inspector screen) and ng2-pdf-viewer is working properly. How can this be possible if ng2-pdf-viewer is not compatible with 2.6.x versions?

![capture_worker_2 6](https://user-images.githubusercontent.com/9716146/109064800-21b78700-76eb-11eb-94c8-3bcd11fd1ef7.PNG)

Thank you!

**Comment by LAlves91** [comment]
@magorismagor,

Woow, that's weird! After looking at ng2-pdf-viewer code, this is the part where the URL is created:

```
pdfWorkerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${
        (PDFJS as any).version
      }/pdf.worker.min.js`;
```

As for your question...I really don't have an answer hahahh!  My guess is: as long as there are no breaking changes within the worker's code, it should work all right (it's just a guess though).

**Comment by magorismagor** [comment]
@LAlves91 yes, it is very weird. The good thing with this version is that allows you to fill the form fields of the PDFs, although the 2.7.570 version of pdfjs version has a lot of improvements according to the [release notes](https://github.com/mozilla/pdf.js/releases).  

Let's wait for the @VadimDez feedback.

Thanks to both of you.
