### ISSUE TITLE
Selectable text does not fit the rendered text

### ISSUE THREAD

**Issue by TomLaggna** [VadimDez/ng2-pdf-viewer#505]
##### Bug Report or Feature Request (mark with an `x`)
```
- [x] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
![image](https://user-images.githubusercontent.com/22190102/62772046-da34c000-ba9e-11e9-857b-6bb2ceaa4562.png)

As can be seen in the screenshot, the selectable text is slightly offset when compared to the rendered text. As far as I can tell, the positioning is fine but neither the style (italic heading) nor the font-family seem to be applied (especially noticable in the last line of the selected paragraph).
I would expect this being related to the recent pdfjs update.

**Comment by TomLaggna** [comment]
It seems like that for some PDFs this is a bigger problem than for others, see 
![pdf_textlayer_bug](https://user-images.githubusercontent.com/22190102/62919906-5cc1c600-bda4-11e9-81e5-0e993b42b0a6.PNG)

[Soo.Hostetler-2006.iDMAa.Full.Paper.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/3495560/Soo.Hostetler-2006.iDMAa.Full.Paper.pdf)

**Comment by ftaffelt** [comment]
I just stumbled across this subject. If it helps - the effect only occurs in the Chrome. In Firefox everything works fine. This also occurs with the latest 6.3.0 version of ng2-pdf-viewer.
