### ISSUE TITLE
can i search for a text in a particular page

### ISSUE THREAD

**Issue by pranavs1791** [VadimDez/ng2-pdf-viewer#507]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [* ] Feature request
- [ ] Documentation issue or request
```

can i search for a text in a particular page , say i want to search for a word in only one page , not the entire document

**Comment by frontr-uk** [comment]
@pranavs1791 did you manage to figure this one out?

**Comment by pranavs1791** [comment]
No i didn't
