### ISSUE TITLE
Error: Invalid XRef stream header

### ISSUE THREAD

**Issue by sabarinathancs** [VadimDez/ng2-pdf-viewer#51]
I need to load dynamic pdf, But i was getting  error but it was working while loading file

Error: Invalid XRef stream header  main.js:115144:6
XRef_readXRef@http://localhost:8100/build/main.js:161171:10
XRef_parse@http://localhost:8100/build/main.js:160817:22
PDFDocument_setup@http://localhost:8100/build/main.js:167869:7
PDFDocument_parse@http://localhost:8100/build/main.js:167765:7
LocalPdfManager_ensure/<@http://localhost:8100/build/main.js:168032:19
t@http://localhost:8100/build/polyfills.js:3:11329
LocalPdfManager_ensure@http://localhost:8100/build/main.js:168027:14
BasePdfManager_ensureDoc@http://localhost:8100/build/main.js:167979:14
loadDocument/</<@http://localhost:8100/build/main.js:168460:9
O</d</t.prototype.invoke@http://localhost:8100/build/polyfills.js:3:9092
NgZone</NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvoke@http://localhost:8100/build/main.js:36644:28
O</d</t.prototype.invoke@http://localhost:8100/build/polyfills.js:3:9030
O</v</e.prototype.run@http://localhost:8100/build/polyfills.js:3:6462
h/<@http://localhost:8100/build/polyfills.js:3:4581
O</d</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:9712
NgZone</NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask@http://localhost:8100/build/main.js:36635:28
O</d</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:9640
O</v</e.prototype.runTask@http://localhost:8100/build/polyfills.js:3:7064
i@http://localhost:8100/build/polyfills.js:3:3664
t/this.invoke@http://localhost:8100/build/polyfills.js:3:10876

**Comment by VadimDez** [comment]
@sabarinathancs could you provide part of your code that sets the PDF-viewer so that i can see what are you setting there and what's triggering the issue

**Comment by sabarinathancs** [comment]
import { Component } from '@angular/core';
this my compoent's 

import {AcademicsViewpdfPage} from '../academics-viewpdf/academics-viewpdf';

/*
  Generated class for the AcademicsStudy page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Component({
  selector: 'page-academics-study',
  templateUrl: 'academics-study.html'
})
export class AcademicsStudyPage {

  args:any;
  responseData:any;
  Notes:any;


  constructor(public navCtrl: NavController, public navParams: NavParams,public apiServices:ApiServices,private sanitizer: DomSanitizer) {
    this.args=navParams.data;
    this.loadStudyMaterila();
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad AcademicsStudyPage');
  }

  loadStudyMaterila(){
    let url="StudyNotes/"+this.args.tmid;
    this.apiServices.customeUrl(url).then(data => {
      this.responseData=data;
      this.Notes=this.responseData.Notes;
      console.log(this.Notes);
    });
  }
  viewPdf(urlview:any){
    let url="ViewNotes/"+urlview.nt_id;
    this.apiServices.customeUrl(url).then(data => {
      this.navCtrl.push(AcademicsViewpdfPage, data);
    });

  }
}


this will be my view 

<div>
  <label>PDF src</label>
  <input type="text" hidden placeholder="PDF src" [(ngModel)]="pdfSrc">
</div>
<div>
  <label>Page:</label>
  <input type="number"  hidden placeholder="Page" [(ngModel)]="page">
</div>
<pdf-viewer [src]="pdfSrc"
            [page]="page"
            [original-size]="true"
            style="display: block;"
></pdf-viewer>

**Comment by sabarinathancs** [comment]
Direct link to  download file
http://api.gradetoppers.com/assets/upload/notes/pdf/20/98f13708210194c475687be6106a3b84_4_2915.pdf

other link 

http://api.gradetoppers.com/index.php/student/Download/notes/98f13708210194c475687be6106a3b84_4_2915.pdf/pdf/20/20

for same file

**Comment by sabarinathancs** [comment]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.gradetoppers.com/assets/upload/notes/pdf/20/98f13708210194c475687be6106a3b84_4_2915.pdf. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by VadimDez** [comment]
CORS should be configured properly on the server that serves PDF

**Comment by sabarinathancs** [comment]
I fixed  CORS issue while informing server Team,

I need to entire PDF file in scroll view how add show that ?

**Comment by sabarinathancs** [comment]
Closed
