### ISSUE TITLE
Transparent PDF

### ISSUE THREAD

**Issue by Ncsabak** [VadimDez/ng2-pdf-viewer#518]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ X] Feature request
- [ ] Documentation issue or request
```
Hello!
I would like to show pdf with transparent background, because I want to use the whole page background. How can I do this? Thank you!

**Comment by seopei** [comment]
Do you mean you just want so see the text of the pdf and not the white background of the page?

**Comment by Ncsabak** [comment]
Yes excatly.

**Comment by seopei** [comment]
I think this is not supported by the current version of ng2-pdf-viewer. Maybe this will help: https://stackoverflow.com/questions/45839398/display-pdf-with-transparent-background-with-pdf-js

**Comment by Ncsabak** [comment]
I will try it, thank you!
