### ISSUE TITLE
BLANK SCREEN on Ionic 2 App emulate 

### ISSUE THREAD

**Issue by sabarinathancs** [VadimDez/ng2-pdf-viewer#52]
Hi,
PDF Render works will  Desktop app,
But after run stuff to ionic 2 app still blank page ? is any compatibility issues is need to fix ?

**Comment by sabarinathancs** [comment]
Refused to get unsafe header "Accept-Ranges"  problem in chrome how to fix this issue even in have tried example PDF file too same error Help me please

**Comment by sabarinathancs** [comment]
Please help me

**Comment by JunusErgin** [comment]
I'm having the same error. If you find a solution, please post it here.

**Comment by webdatavisualdev** [comment]
I solved this issue.

Please see following codes:

1. In the .html file:
<pdf-viewer [src]="currentPDF"></pdf-viewer>

2. In the controller:
currentPDF = {
                url: <url of PDF>,
                withCredentials: true,
                httpHeaders: {}
              };

This should be work.

**Comment by VadimDez** [comment]
does this still happen with the latest version `2.0.2`?

**Comment by VadimDez** [comment]
Closing, due to missing feedback
