### ISSUE TITLE
ionic 4 storage cors error

### ISSUE THREAD

**Issue by eclyz** [VadimDez/ng2-pdf-viewer#527]
> Ionic:
> 
>    Ionic CLI                     : 5.4.2 (/home/erdi/.nvm/v12.10.0/lib/node_modules/ionic)
>    Ionic Framework               : @ionic/angular 4.11.1
>    @angular-devkit/build-angular : 0.801.3
>    @angular-devkit/schematics    : 8.1.3
>    @angular/cli                  : 8.1.3
>    @ionic/angular-toolkit        : 2.0.0
> 
> Cordova:
> 
>    Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
>    Cordova Platforms : android 8.1.0
>    Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 13 other plugins)
> 
> Utility:
> 
>    cordova-res : not installed
>    native-run  : 0.2.8 (update available: 0.2.9)
> 
> System:
> 
>    Android SDK Tools : 26.1.1 (/home/erdi/Android/Sdk)
>    NodeJS            : v12.10.0 (/home/erdi/.nvm/v12.10.0/bin/node)
>    npm               : 6.10.3
>    OS                : Linux 4.15

Hey,
I want to open the pdf file from the phone storage but i get this error:
`Access to XMLHttpRequest at 'file:///storage/emulated/0/Android/data/com.test.test/files/test.pdf' from origin 'http://localhost:8100' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, https.`

if i tried webview.convertFileSrc() then this error:
`Access to fetch at 'http://localhost/_app_file_/storage/emulated/0/Android/data/com.test.test/files/test.pdf' from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

my code:
`this.pdfSrc = this.file.externalDataDirectory + this.book.book_file_url` this is not work
`this.pdfSrc = "assets/a.pdf"` this is work

**Comment by asadullazadeh** [comment]
Did you try convert file to Base64 and Blob?

**Comment by eclyz** [comment]
I solved it this way

```
import { File } from '@ionic-native/file/ngx';
constructor(private file: File)
this.file.readAsArrayBuffer(path, file).then(res => {
			console.log(res)
			this.pdfSrc = res
		})
```

**Comment by asadullazadeh** [comment]
> I solved it this way
> 
> ```
> import { File } from '@ionic-native/file/ngx';
> constructor(private file: File)
> this.file.readAsArrayBuffer(path, file).then(res => {
> 			console.log(res)
> 			this.pdfSrc = res
> 		})
> ```

Okay. Thanks for the solution :)
