### ISSUE TITLE
only showing the first two pages?

### ISSUE THREAD

**Issue by koo9** [VadimDez/ng2-pdf-viewer#528]
##### Bug Report or Feature Request (mark with an `x`)
```
- [x] Bug report 
```
looks like the viewer only shows the first two pages in Electron/angular app, when scroll to the third page, the busy spinner shows up and spin forever.

**Comment by VadimDez** [comment]
What versions of `angular` and `ng2-pdf-viewer` are you using?

**Comment by koo9** [comment]
angular 7 and the latest viewer. think it might have to do with Electron. the pdf is loaded locally from electron. now I have to turn show all page off and use prev/next button for the page, looks like the page shows up on prev/next.

**Comment by VadimDez** [comment]
Maybe it has something to do with `CSS`, try setting `height` or change `display` to `block` on the `pdf-viewer` element.
