### ISSUE TITLE
navigation to search result

### ISSUE THREAD

**Issue by ennahar** [VadimDez/ng2-pdf-viewer#530]
Hello, I tried to use module to do a search, the search is done (the searched word is marked) but it does not navigate automatically to the result, how can I solve this problem?

I also have another problem, regarding the launch of the search method in NgViewAfterInit which shows an error message that the executeCommand method is undifined at this stage, but it is not very urgent.

Thank you in advance.

**Comment by Andrew3005** [comment]
also interesting how to navigate between matched words?
thanks
