### ISSUE TITLE
Zoom in mobile device

### ISSUE THREAD

**Issue by asadullazadeh** [VadimDez/ng2-pdf-viewer#533]
Hi,

I was integrated to my ionic application (v4). Plugin worked perfectly but I want zoom with mobile drag. Plugin didn't support this functionally.
What are you suggest me?

**Comment by vijay-flexiloans** [comment]
facing the same issue

**Comment by ulver2812** [comment]
Same here...

**Comment by ulver2812** [comment]
I solved this issue using this:
https://github.com/drozhzhin-n-e/ngx-pinch-zoom

```
    <pinch-zoom>
        <pdf-viewer [src]="src"
                    [original-size]="false"
        ></pdf-viewer>
    </pinch-zoom>
```
