### ISSUE TITLE
DataCloneError: The object could not be cloned.

### ISSUE THREAD

**Issue by mukeshphpdev** [VadimDez/ng2-pdf-viewer#534]
getting error

ERROR Error: "Uncaught (in promise): DataCloneError: The object could not be cloned.
postMessage@https://www.domain.com/vendor.f4f0c72ddd84f978f319.bundle.js:176752:19
sendStreamRequest@https://www.domain.com/vendor.f4f0c72ddd84f978f319.bundle.js:176569:14
error@https://www.domain.com/vendor.f4f0c72ddd84f978f319.bundle.js:176612:9
WorkerTransport_setupMessageHandler/</sink.onPull/<@https://www.domain.com/vendor.f4f0c72ddd84f978f319.bundle.js:172837:18
./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@https://www.domain.com/polyfills.ad755b05f02ecd8d9c41.bundle.js:6888:26
onInvoke@https://www.domain.com/vendor.f4f0c72ddd84f978f319.bundle.js:25275:33
./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@https://www.domain.com/polyfills.ad755b05f02ecd8d9c41.bundle.js:6887:32
./node_modules/zone.js/dist/zone.js/</</Zone.prototype.run@https://www.domain.com/polyfills.ad755b05f02ecd8d9c41.bundle.js:6638:43
scheduleResolveOrReject/<@https://www.domain.com/polyfills.ad755b05f02ecd8d9c41.bundle.js:7372:34
./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@https://www.domain.com/polyfills.ad755b05f02ecd8d9c41.bundle.js:6921:31
onInvokeTask@https://www.domain.com/vendor.f4f0c72ddd84f978f319.bundle.js:25266:33
./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@https://www.domain.com/polyfills.ad755b05f02ecd8d9c41.bundle.js:6920:36
./node_modules/zone.js/dist/zone.js/</</Zone.prototype.runTask@https://www.domain.com/polyfills.ad755b05f02ecd8d9c41.bundle.js:6688:47
drainMicroTaskQueue@https://www.domain.com/polyfills.ad755b05f02ecd8d9c41.bundle.js:7095:35
"

**Comment by edgarMejia** [comment]
This is a CORS problem, you have to allow all CORS on your API.

In my case PlayFramework API:

```java
play.filters.cors {
    pathPrefixes = ["/mobile", "/api", "/resources"]
    allowOrigins = ["*"]
    allowHttpMethods = ["GET", "POST", "DELETE", "PUT", "OPTIONS"]
    preflightMaxAge = 3 days
}
```

For testing install an extension like**CORS Everywhere**:
https://addons.mozilla.org/es/firefox/addon/cors-everywhere/
