### ISSUE TITLE
When we load the same URL for two consecutive requests, the viewer does not emit events like onLoadComplete or onError

### ISSUE THREAD

**Issue by gouravagarwal** [VadimDez/ng2-pdf-viewer#537]
I have a scenario where I have multiple documents. so there is a navigation button. On clicking of it, i start a loader and then stop the loader once the pdf viewer component is loaded in the onLoadComplete and onError methods. It works fine but if the pdf source is same then both these events are not fired and hence the loader does not stop.

**Comment by ulver2812** [comment]
I have the same problem, any workaround?

**Comment by gouravagarwal** [comment]
@ulver2812 What I did is appended a timestamp to the end of the URL, so that every time it loads, the URL is different.
