### ISSUE TITLE
Comment Or Tag Add on Pdf file.

### ISSUE THREAD

**Issue by kamlesh0606** [VadimDez/ng2-pdf-viewer#538]
Hi,

Can we  do this type comment Or Tag system on pdf  ?

Ref. Link -  https://github.com/agentcooper/react-pdf-highlighter
Demo Link - https://agentcooper.github.io/react-pdf-highlighter/

Thanks

**Comment by kamlesh0606** [comment]
Any Update ?

**Comment by VadimDez** [comment]
Duplicate #116

**Comment by kamlesh0606** [comment]
Hi @VadimDez 

#116 is close Without any update.

Thanks
