### ISSUE TITLE
[show-all] is showing first two page only.

### ISSUE THREAD

**Issue by shabbir-dhangot** [VadimDez/ng2-pdf-viewer#54]
show-all is showing first two page only.

<pdf-viewer [src]="pdfSrc" 
              [page]="page" 
              [original-size]="false" 
              [render-text]="false"
              [show-all]="true"
              style="display: block;">

pdfSrc: string = "../assets/pdf/Cuelinks_SDK-Integration_Guide.pdf"
page: number = 5;

I dont know what value give in page.

**Comment by markgoho** [comment]
Same issue, show-all: true is just showing the first two pages

**Comment by Tyler-V** [comment]
Also same issue! Works fine with [show-all]="false" and using pagination to get to each page of the document but show-all is not displaying the last page.

**Comment by fabiodursoexin** [comment]
Same issue

**Comment by jahller** [comment]
Same issue here.

**Comment by clgraf** [comment]
Same problem

**Comment by smlee** [comment]
I have the number of pages stored in my database so i use ngFor by creating an empty array based on the number of pages and index + 1 for the workaround

**Comment by Tyler-V** [comment]
> I have the number of pages stored in my database so i use ngFor by creating an empty array based on the number of pages and index + 1 for the workaround

I'm doing something similar except getting the number of pages after load complete and *ngFor over the remaining pages.

                <pdf-viewer #pdfViewer [src]="url" [page]="1" [(rotation)]="rotation" (after-load-complete)="afterLoad($event)"></pdf-viewer>
                <ng-container *ngFor="let pdf of remainingPdfPages; let i = index">
                    <pdf-viewer [src]="url" [page]="i + 2" [(rotation)]="rotation"></pdf-viewer>
                </ng-container>

Only issue is im now loading the same pdf n times, is there a better way to do this? Can I set [src]= to the pdf document's source loaded in the first <pdf-viewer/>?

**Comment by JonnyNet** [comment]
pdf-viewer.component.js

`PdfViewerComponent.prototype.renderMultiplePages = function () {
        var _this = this;
        var container = this.element.nativeElement.querySelector('div');
        var page = 1;
        this.removeAllChildNodes(container);

        for(let i = 1; i < _this._pdf.numPages+1 ; i++){
            this.renderPage(i)
        }

       /* this.renderPage(page++).then(function () {
            if (page <= _this._pdf.numPages) {
                return _this.renderPage(page++);
            }
        });*/ 
    };`

**Comment by philipdbrown** [comment]
I know this issue is closed, but I'm experiencing it in the following version:
ng2-pdf-viewer: 7.0.1
angular/cli: 11.2.4

**Comment by Or05230** [comment]
> I know this issue is closed, but I'm experiencing it in the following version:
> ng2-pdf-viewer: 7.0.1
> angular/cli: 11.2.4
> 
> Any help would be appreciated.
`
pdf-viewer {
height: 100vh
display:block;
}`

make sure nothing override it.

**Comment by gabayarden** [comment]
Using ng2-pdf-viewer: 7.0.1 and it is not working here again.
Downgraded to 6.4.0 and it works.
Seems like 7.0.1 has some issue

**Comment by conner-fallone** [comment]
So this appears to be something with the scrolling / virtualization implementation. I was having this same issue, but noticed all the pages were still in the DOM, the scroll just wasn't recognized. In my scenario, i was using `overflow-x: unset` to get rid of the horizontal scrollbar that always appears to show (going to write up an issue for this, seems like this lib is not accounting for a vertical scrollbar and renders the page underneath it). If you are doing something special with this scrollbar, you may be interfering with this scroll. In my case, just removing this style fixed it and the scroll started rendering pages. `overflow-x: hidden` also works too.
