### ISSUE TITLE
navigation between matched words

### ISSUE THREAD

**Issue by Andrew3005** [VadimDez/ng2-pdf-viewer#544]
how to navigate between matched words? 
how to get event when search is finished?
thanks

**Comment by NakedFool** [comment]
+1 

Would love to know if i can get event when search is finished.

**Comment by Andrew3005** [comment]
@NakedFool 
what I realize for nav between matched words
`  
nextMatch() {
    const selected = document.querySelector('.highlight.selected');
    const elements = document.querySelectorAll('.highlight');
    let next;
    for (let i = 0; i < elements.length; i++) {
      if (elements[i] == selected) {
        next = elements[i + 1];
        break;
      }
    }
    selected.classList.remove('selected')
    next.classList.add('selected')
    if (next) next.scrollIntoView();
  }
`


it is how to get matches amount:
`
  get matchesCount(): number {
    return this.pdfViewer && this.pdfViewer.pdfFindController ? this.pdfViewer.pdfFindController._matchesCountTotal : 0;
  }
`

how to get event when search is finished, I dont know, but one idea:
when `get matchesCount`  value stop to changes - it mean search ended

**Comment by VadimDez** [comment]
@Andrew3005 you can try doing something similar: https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/app.component.ts#L201-L214

**Comment by Andrew3005** [comment]
@VadimDez but, can I move to previous word? as I understood - no
also want to know, if there exist solution for "search ended" event?
thanks

**Comment by NakedFool** [comment]
@Andrew3005 

As i understand on the newest version navigation is somehow removed right?

As on 6.0.0 i can navigate with enter while on 6.0.2 i can't.

**Comment by Andrew3005** [comment]
@NakedFool as I have discovered pdf js library - yes. but they use PDFFindBar, or something like this
but it is not included in prebuilt version.
I spend too much time on discovering everything with no result, so I do [this](https://github.com/VadimDez/ng2-pdf-viewer/issues/544#issuecomment-562543169) and have to move forward

as I understand, you have to download PDF.JS, build it as you want, and then you can implement it in @VadimDez component

**Comment by NakedFool** [comment]
@Andrew3005  Yeah seems like they removed.

As for this nextMatch() where do you actually call it inside :
` searchQueryChanged(newQuery: string) {
    if (newQuery !== this.pdfQuery) {
      this.pdfQuery = newQuery;
      this.pdfComponent.pdfFindController.executeCommand('find', {
        query: this.pdfQuery,
        highlightAll: true
      });
    } else {
      this.pdfComponent.pdfFindController.executeCommand('findagain', {
        query: this.pdfQuery,
        highlightAll: true
      });
    }
  }
}`

**Comment by Andrew3005** [comment]
yes, for next match it works, but I also need previous match, and event when search is ended

**Comment by Andrew3005** [comment]
@NakedFool  seems [my previous comment](https://github.com/VadimDez/ng2-pdf-viewer/issues/544#issuecomment-562543169) not working as expected. because pages rendering dinamically and if pdf is big, document.querySelector does not get all highlighted elements as expected

**Comment by Andrew3005** [comment]
@NakedFool [this next match](https://github.com/VadimDez/ng2-pdf-viewer/issues/544#issuecomment-563240050) select matched word depending on your current page. will select word not from the beggining of pdf, from your current location
and this nextMatch() works better then my [implementation](https://github.com/VadimDez/ng2-pdf-viewer/issues/544#issuecomment-562543169), would be great to something for previousMatch

@VadimDez any ideas?

**Comment by Andrew3005** [comment]
@VadimDez 
I saw in your component 
`  navigateTo(destination: any) {
    this.pdfComponent.pdfLinkService.navigateTo(destination);
  }`

and also in pdfFindController we have "pageMatches" array
can we combine this?

also in pdfFindController we have field "selected": {matchIdx: 0, pageIdx: 8}, it only getter
any ideas how we can change it? and after changing scroll to selected word

**Comment by timothyblue** [comment]
@Andrew3005 

Not sure if it helps, but I did this today. It reports if nothing matched the search, and the number of matches as it finds them.

```
public afterLoadComplete(pdf: PDFDocumentProxy): void {
    this.pdfComponent.pdfViewer.eventBus.on('updatefindmatchescount', data => {
      console.log('total matches found: ', data.matchesCount.total);
    });

    this.pdfComponent.pdfViewer.eventBus.on('updatefindcontrolstate', data => {
      if (data.state === 0) {
        console.log('no matches found');
      }
    });
  }
```

**Comment by NakedFool** [comment]
@timothyblue  Awesome! 

In this moment for me works like charm, i can manipulate once search is finished!

**Comment by wonjunkang** [comment]
@Andrew3005 Hi Andrew, did you figure out how to implement previous search for this? 
Thanks!

**Comment by Andrew3005** [comment]
@wonjunkang no I didnt
just [this](https://github.com/VadimDez/ng2-pdf-viewer/issues/544#issuecomment-562543169)
keep me informed if you find out something

**Comment by trinhngocdieu** [comment]
@Andrew3005, @wonjunkang  : 
We can do this for nextMatch and previousMatch:

// nextMatch()
this._pdfFindController.executeCommand('findagain', {
          caseSensitive: false, 
          findPrevious: false,
          highlightAll: true, 
          phraseSearch: true, 
          query: "singapore"
        });

// previousMatch()
this._pdfFindController.executeCommand('findagain', {
          caseSensitive: false, 
          findPrevious: true,
          highlightAll: true, 
          phraseSearch: true, 
          query: "singapore"
        });

**Comment by rizqun-polyrific** [comment]
> @Andrew3005
> 
> Not sure if it helps, but I did this today. It reports if nothing matched the search, and the number of matches as it finds them.
> 
> ```
> public afterLoadComplete(pdf: PDFDocumentProxy): void {
>     this.pdfComponent.pdfViewer.eventBus.on('updatefindmatchescount', data => {
>       console.log('total matches found: ', data.matchesCount.total);
>     });
> 
>     this.pdfComponent.pdfViewer.eventBus.on('updatefindcontrolstate', data => {
>       if (data.state === 0) {
>         console.log('no matches found');
>       }
>     });
>   }
> ```

Isn't the state should be 1 for no matches found?

**Comment by Rizqun** [comment]
> @Andrew3005
> 
> Not sure if it helps, but I did this today. It reports if nothing matched the search, and the number of matches as it finds them.
> 
> ```
> public afterLoadComplete(pdf: PDFDocumentProxy): void {
>     this.pdfComponent.pdfViewer.eventBus.on('updatefindmatchescount', data => {
>       console.log('total matches found: ', data.matchesCount.total);
>     });
> 
>     this.pdfComponent.pdfViewer.eventBus.on('updatefindcontrolstate', data => {
>       if (data.state === 0) {
>         console.log('no matches found');
>       }
>     });
>   }
> ```

I think state 0 is found and 1 is not found

**Comment by KSANTHOSHKUMA** [comment]
> @Andrew3005, @wonjunkang : We can do this for nextMatch and previousMatch:
> 
> // nextMatch()
> 
> ```
> this._pdfFindController.executeCommand('findagain', {
>           caseSensitive: false, 
>           findPrevious: false, // next
>           highlightAll: true, 
>           phraseSearch: true, 
>           query: "singapore"
>         });
> ```
> 
> // previousMatch()
> 
> ```
> this._pdfFindController.executeCommand('findagain', {
>           caseSensitive: false, 
>           findPrevious: true, // prev
>           highlightAll: true, 
>           phraseSearch: true, 
>           query: "singapore"
>         });
> ```

This is the exact solution, i am looking for
Thanks @trinhngocdieu
