### ISSUE TITLE
change detection strategy

### ISSUE THREAD

**Issue by Andrew3005** [VadimDez/ng2-pdf-viewer#545]
in html I wrote
`{{cond}}`
in ts I wrote 
  `get cond(){
    console.log('update')
    return null;
  }`

and console.log a lot of times . sometimes doesnot stop

**Comment by VadimDez** [comment]
Sorry, unfortunately I cannot understand this...
Could you please make an example [here](https://stackblitz.com/edit/ng2-pdf-viewer) ?

**Comment by Andrew3005** [comment]
[done](https://stackblitz.com/edit/ng2-pdf-viewer-dvj23w?file=src%2Fapp%2Fapp.component.html)

I upload book with 150+ pages, and in console.log I saw a lot of messages

also please give an answer in previous my issue

as I discover, nextMatch method was enable in 1.10.88 version of pdf.js, as done Victor (dont know how to atach link) in his simple pdf viewer
and in higher versions pdf.js  nextMatch methond removed

so I decided to use your component and pdf.js 1.10.88 and merge some code with Victor
or it can be another implementation of navigation between matched words and get event when search is done?

thanks, looking forward to hearing from you
