### ISSUE TITLE
ERROR Error: Invalid parameter object: need either .data, .range or .url

### ISSUE THREAD

**Issue by whiteblueblack** [VadimDez/ng2-pdf-viewer#552]
Here are my steps：
1.Get pdf resource address: filePath
2.set the variable 
 `  this.filePath = this.sanitizer.bypassSecurityTrustResourceUrl (filePath)`
3. html
`<pdf-viewer id = "pdf-set"  [render-text] = "true"  [src] = "filePath"></ pdf-viewer>`

I got this error: `ERROR Error: Invalid parameter object: need either .data, .range or .url`

packge.json: 
`"@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "@types/pdfjs-dist": "^2.1.2",
    "cordova-browser": "6.0.0",
    "core-js": "^2.5.4",
    "ng2-pdf-viewer": "^6.0.2",
    "ng2-pdfjs-viewer": "^5.0.1",
    "ngx-bootstrap": "^5.2.0",
    "pdfjs-dist": "^2.2.228",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",`

I use iframe is normal, src can parse normally, I have no idea, any help is good
Thanks in advance

**Comment by DanBoSlice** [comment]
Any updates?

**Comment by jindovu** [comment]
any updates for that?, I have same error
