### ISSUE TITLE
Can't scroll to the outline dest

### ISSUE THREAD

**Issue by salvoimpspindox** [VadimDez/ng2-pdf-viewer#558]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

On chrome and firefox with a pdf-viewer without height I cannot navigate to an outline, or navigate to a page.
It's seems to be working only for edge.
If i want the navigation and the scrolling to work I have to put a height to the container of the pdf-viewer.

**Comment by VadimDez** [comment]
Yes, that's an expected behaviour since https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/6.0.0 See breaking change
