### ISSUE TITLE
updateSize() function

### ISSUE THREAD

**Issue by Vi-dot** [VadimDez/ng2-pdf-viewer#56]
Hello,

I wonder why updateSize() function is not in release version ?

**Comment by VadimDez** [comment]
Hi,
Which release do you mean?

**Comment by Vi-dot** [comment]
I tried 1.0.1 and 1.0.2

**Comment by Vi-dot** [comment]
In my case, pdf viewer is in a div resizable by user's hand (using [angular-resizable-element](https://mattlewis92.github.io/angular-resizable-element/demo/)). Then I need to call updateSize() manually.

**Comment by VadimDez** [comment]
Didn't have that case, but now with your example it makes sense.
`updateSize()` will be available in 2.0.0

**Comment by Vi-dot** [comment]
Thanks :)

By the way, in this case, in a page with multiple splitted fragments, and one of them is pdf viewer : 
The window resize event shloud be catch in main view to propagate to its children the right size they need.
But pdf viewer (a child of main view) already catch window resize event. It means that updateSize() is going to be called twice.
I wonder if it is the right way.

**Comment by VadimDez** [comment]
Yes, you're right, but for simplicity of this library i moved resize event inside the component.
Maybe need one more parameter to disable autoresize.

**Comment by Vi-dot** [comment]
You're right, a parameter to disable autoresize is a good solution.
