### ISSUE TITLE
Strings are not loading because of Warning: Ignoring invalid character "95" in hex string

### ISSUE THREAD

**Issue by Balajikrishnaram** [VadimDez/ng2-pdf-viewer#563]
##### Bug Report or Feature Request (mark with an `x`)
Hi Team,

Pdf viewer error while rendering particular pdf. attached the pdf for reference.

Warning: Ignoring invalid character "95" in hex string
pdf.worker.min.js:1 Warning: Ignoring invalid character "109" in hex string
pdf.worker.min.js:1 Warning: Ignoring invalid character "44" in hex string
pdf.worker.min.js:1 Warning: Ignoring invalid character "38" in hex string
pdf.worker.min.js:1 Warning: Ignoring invalid character "37" in hex string
pdf.worker.min.js:1 Warning: Ignoring invalid character "75" in hex string
pdf.worker.min.js:1 Warning: Ignoring invalid character "107" in hex string
pdf.worker.min.js:1 Warning: Ignoring invalid character "87" in hex string
pdf.worker.min.js:1 Warning: Ignoring invalid character "89" in hex string
pdf.worker.min.js:1 Warning: Ignoring invalid character "33" in hex string
pdf.worker.min.js:1 Warning: Ignoring invalid character "107" in hex string
[NAM9246926 BR-00131571_1580428773677.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/4157493/NAM9246926.BR-00131571_1580428773677.pdf)

**Comment by thakurvijendar** [comment]
I am getting this issue too.
The  pdf is rendered nicely on my local.
Problem comes when we deploy the app to kuberneted engine.

Warning: getHexString - ignoring invalid character: 33
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 79
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 84
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 89
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 80
pdf.worker.min.js:22 Warning: getHexString - ignoring additional invalid characters.
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 104
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 116
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 109
2pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 108
pdf.worker.min.js:22 Warning: getHexString - ignoring additional invalid characters.
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 104
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 109
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 116
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 104
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 114
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 115
pdf.worker.min.js:22 Warning: getHexString - ignoring additional invalid characters.
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 116
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 105
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 116
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 108
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 33
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 79
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 84
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 89
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 80
pdf.worker.min.js:22 Warning: getHexString - ignoring additional invalid characters.
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 104
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 116
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 109
2pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 108
pdf.worker.min.js:22 Warning: getHexString - ignoring additional invalid characters.
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 104
pdf.worker.min.js:22 Warning: Indexing all PDF objects

**Comment by SawickiKamil** [comment]
Did you guys solve the problem?

**Comment by darkomenx** [comment]
I have the same issue too with pdf that reading correctly in my reader tool.
I also try to 'repair' it with this online tool but it doesn't change anything : [https://www.ilovepdf.com/repair-pdf](url)
