### ISSUE TITLE
Build error with angular 9

### ISSUE THREAD

**Issue by NakedFool** [VadimDez/ng2-pdf-viewer#574]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

I have upgraded both angular to newest version and ng2-pdf-viewer library to it's latest version.

When i try to build my application i get following error :
![image](https://user-images.githubusercontent.com/18723426/74320467-f59bc300-4d80-11ea-9a9c-2e8dc671918f.png)

Does anyone have an idea what might help with this issue here?

**Comment by TTvanWillegen** [comment]
I also have an error on v6.1.0 (latest) [see #575]. Is this fixed if you downgrade to v6.0.2? Then the two issues might be related...

**Comment by NakedFool** [comment]
@TTvanWillegen 

On version 6.0.2 i still have same issue when trying to build with angular v9.

**Comment by VadimDez** [comment]
Could you please provide an example of how your build script looks like?
I've tried myself with just `ng build` or `ng build --prod` and had no errors.

**Comment by VadimDez** [comment]
And also specify which typescript version you're using

**Comment by NakedFool** [comment]
@VadimDez 

Hey, i'm using `ng build --prod frontend`  - frontend is just the name of project since i'm using nx monorepo.

Typescript version is `"typescript": "~3.4.5"`

**Comment by Adriiad** [comment]
Hey,

Same problem here with `"@angular/core": "8.2.14"` and `"typescript": "~3.5.3"`. The problem suddendly appeared yesterday afternoon.

**Comment by VadimDez** [comment]
I've created a new Angular 9 project with the `ng new angular9-project` and then installed and imported the library `ng2-pdf-viewer`. By running `ng build --prod` I have no errors.
@NakedFool Have you done something different? Help me to reproduce the error.

**Comment by NakedFool** [comment]
@VadimDez  Did exactly the same. Will try build again this day and update on the error.

**Comment by rernens** [comment]
getting the exact problem after upgrading our application to angular 9

> node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:6:22 - error NG6002: Appears in the NgModule.imports of LayoutModule, but could not be resolved to an NgModule class.
> 
> This likely means that the library which declares PdfViewerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

using  angular 9.07, typescript 3.7.5, ng2-pdf-viewer 6.1.2

**Comment by sujeetsinha** [comment]
I'm having  this same issue. Was this solved?

**Comment by dezevitz** [comment]
Any updates on this? I am experiencing the same error.

**Comment by Giusti** [comment]
@VadimDez I am experiencing the same error:

> ERROR in node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:6:22 - error NG6002: Appears in the NgModule.imports of Module, but could not be resolved to an NgModule class.
> 
> This likely means that the library (ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module) which declares PdfViewerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

As explained in the readme, I executed the npm i command, added the module to the imports and pasted the html block in my template. When I run serve I get the error above.

I am running 
Angular: 10.2
Typescript: 4.0.5
ng2-pdf-viewer: 6.3.2

**Comment by shamoon** [comment]
Just another +1 =/ Im guessing no one has ideas on how to fix?

Certainly seems issue should be re-opened @VadimDez ?

**Comment by shamoon** [comment]
Actually! Solved for me using solution described at https://stackoverflow.com/a/60364326/7439053 basically just did `ng serve --prod` and then switched back to `ng serve`
