### ISSUE TITLE
BUG | v6.1.0 | An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by TTvanWillegen** [VadimDez/ng2-pdf-viewer#575]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] Regression (a behavior that used to work and stopped working in a new release)
- [ x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
When building on latest (v6.1.0) I get the following error. Once reverting back to v6.0.2 I no longer get this error.

`ERROR in ../node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:51 - error An accessor cannot be declared in an ambient context.`

**Comment by VadimDez** [comment]
Could you please specify which version on TypeScript you're using in your project?

**Comment by TTvanWillegen** [comment]
I'm not near a pc right now, but for what I can see on my mobile, this is in our dev dependencies:

```
"typescript": "3.5.3",
"typescript-formatter": "^7.2.2"
```

**Comment by VadimDez** [comment]
So it seems like there's a breaking change in the typescript library.
After the upgrade to Angular 9, Typescript was updated to the lates version (`3.7`), which seems to be incompatible with version `3.5`.
Try to stick with `6.0.2` of `ng2-pdf-viewer` in your project for now

**Comment by TTvanWillegen** [comment]
Alrighty, I'll do that until I can get around to updating Angular and TypeScript, thanks!

**Comment by Adriiad** [comment]
Hi, I have the same problem...
my versions : 

```
"@angular/core": "8.2.14"
"typescript": "3.5.3"
""ng2-pdf-viewer": "6.0.2"
```

**Comment by mecp** [comment]
I faced same issue with typescript 3.5.3,  ng2-pdf-viewer at 6.1.0 and Angular v8.2

**Comment by vadymdykyi** [comment]
Same for me.
"ng2-pdf-viewer": "6.1.0",
"typescript": "~3.4.3",
"@angular/core": "~8.1.2",

**Comment by VadimDez** [comment]
Can you please try out the `6.1.1` version?

**Comment by vadymdykyi** [comment]
@VadimDez, now it works. Thank you!
