### ISSUE TITLE
PDF.js v2.3.200 (build: 4ae3f9fc) Mensaje: i.URL is not a constructor

### ISSUE THREAD

**Issue by hexamob** [VadimDez/ng2-pdf-viewer#579]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Load a PDF generates the error reported in de subject.  The error is in line:

let n = new i.URL(window.location.href).origin || "null";

Thank you!

**Comment by hexamob** [comment]
Any update about this issue?

**Comment by VadimDez** [comment]
@hexamob 
I'll take a look a the issue later.
Are there any issues with the actual version?
