### ISSUE TITLE
Autoresize loses quality and can't be recovered

### ISSUE THREAD

**Issue by kousenlsn** [VadimDez/ng2-pdf-viewer#584]
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

#### Repro steps
Use ``` autoresize="true"``` with ```original-size="false"```, with the ```pdf-viewer```tag setten as ```display: block; max-width: 100%``` insde a ```div``` with ```display: flex; width: 50%;``` , the pdf will render to fill the space, but will be blurred.

If you resize the page or increase the width, it will not adjust accordingly, making it less blur or anything.
There should be a way to keep the quality of the rendering.

#### Examples on screen:

Normal quality:
![Normal quality, no autoresize](https://user-images.githubusercontent.com/14895129/76534262-06ab2300-6458-11ea-8b67-1945744e93b7.png)

Autoresized:
![Autoresized, low quality](https://user-images.githubusercontent.com/14895129/76534261-06128c80-6458-11ea-85c0-ac9b6f984781.png)

Zoomed:
![Zoomed in low quality](https://user-images.githubusercontent.com/14895129/76534266-0743b980-6458-11ea-82d8-c2900e080fa7.png)

After resizing:
![After resizing section, keeps low quality](https://user-images.githubusercontent.com/14895129/76534248-01e66f00-6458-11ea-9527-ae4a57899c59.png)

**Comment by ranouf** [comment]
did you find a solution?

**Comment by Sarthhak03** [comment]
are you even active on these issue or not 
????

**Comment by Sarthhak03** [comment]
im leaving this control , searching for better ones .
