### ISSUE TITLE
How do I load last visited page in PDF using ng2-pdfviwer

### ISSUE THREAD

**Issue by SimpliAxis** [VadimDez/ng2-pdf-viewer#586]
Hi Vadim,
I want to load the last visited by user by using ng2-pdf -viewer. I have tried to use scrolltopage, but it is not working. Could you please suggested me any idea ??

**Comment by VadimDez** [comment]
[This](https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#breaking-change) should fix the issue , scroll to page should work.
