### ISSUE TITLE
[(page)] binding (still) doesn't work

### ISSUE THREAD

**Issue by erezhod** [VadimDez/ng2-pdf-viewer#588]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Hi guys,

I have implemented this library in my project and am able to render PDFs just fine, but I am trying to get the current page when scrolling.

I have seen this issue should have been solved in version `6.0.0`, but I'm currently on `6.1.2`, Angular version `9.0.7` and it's not working. I keep getting `Current page: 1` when scrolling.

Here's my code:

**app.component.html**
```
<header id="header">
    <p>Current page: {{ currentPage }}</p>
</header>
<div id="pdf-container" style="margin: 6rem auto 0;">
    <pdf-viewer
        src="/assets/pdf/health.pdf"
        (page-rendered)="onPageRendered($event)"
        [(page)]="currentPage"
        [original-size]="true"
        [show-all]="true"
        [show-borders]="true"></pdf-viewer>
</div>
```

**app.component.ts**
```
import { Component, OnInit, ElementRef, ViewChild, AfterViewInit } from '@angular/core';
import { PdfViewerComponent } from 'ng2-pdf-viewer';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit, AfterViewInit {
    @ViewChild(PdfViewerComponent) pdfViewer: PdfViewerComponent;

    pages: ElementRef[] = [];
    currentPage: number;

    constructor() { }
    ngOnInit() { }
    ngAfterViewInit() { }

    onPageRendered(page: any) {
        this.pages.push(page);
    }
}
```

Hopefully it's something I am doing wrong and this amazing library is fine :)
Thanks!.

**Comment by VadimDez** [comment]
You probably have to add more CSS, see braking changes: https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600

**Comment by erezhod** [comment]
> You probably have to add more CSS, see braking changes: https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600

Ahh I see! Worked great, thank you!
I think it's worth mentioning this under the `[(page)]` option in the `Options` section in the documentation 🙂

For reference, this is the CSS I have added:
```
pdf-viewer {
     display: block;
    height: 100vh;
}
```

**Comment by VadimDez** [comment]
@erezhod Thanks for your feedback! I'll update it.
