### ISSUE TITLE
Error in rollup

### ISSUE THREAD

**Issue by odisi** [VadimDez/ng2-pdf-viewer#59]
When I try use rollup with PdfViewerComponent I receive the following error: 'PdfViewerComponent' is not exported by node_modules\ng2-pdf-viewer\dist\index.js
I searched for solutions but i don't had success. Anybody can help me?

**Comment by VadimDez** [comment]
Is this working now?
Here in dist/index.js it is exporting `PdfViewerComponent`
https://github.com/VadimDez/ng2-pdf-viewer/blob/features/1.0.2/dist/index.js#L3

**Comment by VadimDez** [comment]
Does this error still occur in the latest `2.0.2` version?

**Comment by VadimDez** [comment]
Closing due to missing feedback
