### ISSUE TITLE
polyfills.js:3 GET http://localhost:8100/nullUniGB-UTF16-H 404 (Not Found)

### ISSUE THREAD

**Issue by we868618** [VadimDez/ng2-pdf-viewer#595]
Hi,

I have got an error about nullUniGB-UTF16-H , which caused some characters disappear.
![111](https://user-images.githubusercontent.com/19547977/78213275-c8e46c00-74e4-11ea-9701-3f270787fe9f.jpg)
The web page shows like the picture below.

But actually it should be like this.
![1585804916(1)](https://user-images.githubusercontent.com/19547977/78213344-faf5ce00-74e4-11ea-9eb0-7a12729861dd.png)

In this document, it blocks all Chinese Characters. However, it only happened on some special PDF documents.
![image](https://user-images.githubusercontent.com/19547977/78213487-65a70980-74e5-11ea-92c2-b9f1ba0cd56c.png)

Has anyone met this issue before? or Any solutions?

Thanks,

Ivan Yuan

**Comment by we868618** [comment]
My ng2-pdf-view version is 3.0.8

**Comment by VadimDez** [comment]
Any chance you could try this with the latest version `6.2.0`?
