### ISSUE TITLE
Broken view - viewer cutting spaces & mess characters

### ISSUE THREAD

**Issue by chenZafrir** [VadimDez/ng2-pdf-viewer#600]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ X ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I use angular 8,
The problem is at follows - the viewer shows the PDF like this:
![image](https://user-images.githubusercontent.com/25902373/79866566-a1970580-83e5-11ea-91c3-34dc313679db.png)

I took the PDF from the demo page.
It happens in chrome and edge browsers.

**Comment by VadimDez** [comment]
Can you please provide the steps to reproduce this error?
