### ISSUE TITLE
support for pdf.js v2.4.456

### ISSUE THREAD

**Issue by igorlino** [VadimDez/ng2-pdf-viewer#601]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x ] Feature request
- [ ] Documentation issue or request
```
Hello there,

Is there any plan to update to pdf.js v2.4.456?

This newer release of pdf.js seems to include much better modularity. It includes more or less the work of nearly 6 months with several bugfixes to the application as well as the handling of PDFs

https://github.com/mozilla/pdf.js/releases/tag/v2.4.456

Cheers
Igor

**Comment by hughanderson4** [comment]
FYI, ng2-pdf-viewer version 6.3.0 has broken our MSIE11 compatibility, due to the dependency of pdfjs 2.4 on [WeakMap](https://caniuse.com/#feat=mdn-javascript_builtins_weakmap).

Our workaround was to downgrade ng2-pdf-viewer to 6.2.0.

**Comment by igorlino** [comment]
I see.  IE10 and IE11 not begin the best example of a modern browser, at somepoint pdfjs probably wants to use more features of modern JS, so it may not be the 1st one. 

We only use evergreen browsers in the last 5 years of projects. But if I had to perhaps I would suggest using a polyfill:

https://www.npmjs.com/package/weakmap-polyfill
or
https://github.com/ungap/weakmap

**Comment by igorlino** [comment]
@VadimDez  thanks for the update :) Already in use.

**Comment by albert-asin** [comment]
FYI, here have the same problem with version 6.3.0 : brokes our IE11
Downgrading to 6.2.0 works again
Thanks for your job

**Comment by igorlino** [comment]
The mozilla guys mentioned in the changelog something interesting:

"From now on we produce a non-translated/non-polyfilled build for modern browsers by default. However, we also provide the translated/polyfilled build for older browsers in a separate bundle (with the -es5-dist.zip suffix)."
So, they do provide a separate bundle that has such compatibility.

Not sure how to make such optional dependency work. Some libraries use peer dependency, and you do whatever you want in your webapp at the end.

In the meantime, after many months a new release appeared yesterday,  it includes performance optimizations/improvements:

https://github.com/mozilla/pdf.js/releases/tag/v2.5.207
