### ISSUE TITLE
Re-render a page at any time

### ISSUE THREAD

**Issue by joel-pinho** [VadimDez/ng2-pdf-viewer#605]
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [X] Documentation issue or request
```

I discovered this lib some weeks ago and I'm using it for a new project. It has been a pleasure so far!
Thanks!

I'm not sure that what I'm asking for is not implemented, but I searched in documentation and I haven't found such functionality.

**Question: Is it possible to re-render a page at any time?**

Why I need it?
I need to draw rectangles to highlight or blackout parts of document and I use the (page-rendered) to draw elements previously loaded from my DB at rendering time. It works very well!
I use the canvas this lib creates for each rendered page and it keeps the info all the time until change pdf source.

However, to implement a feature to remove elements (rectangles), since canvas is limited and once you draw a rectangle, you can't go back, I have a solution for it that just needs to force the render of a page already rendered (it will draw elements again for that page, without the removed rectangle).

Is it possible to do it?

Thanks!

**Comment by silvelo** [comment]
Hi @joel-pinho 
I found a solution for this "issue". I create a new canvas element inside the wrapper and seems to work propertly.

The next function create this element:
`
  async afterLoadComplete(pdfData: PDFDocumentProxy) {
    this._pdfService.setTotalPages(pdfData.numPages);
    this._pdfService.setLoaded();
    setTimeout(() => {
      this.canvas = document.querySelector('canvas');
      this.canvas.className = "stack";
      let canvas = document.createElement('canvas');
      let canvasWrapper = document.getElementsByClassName('canvasWrapper')[0];
      canvas.height = canvasWrapper.clientHeight;
      canvas.width = canvasWrapper.clientWidth;
      canvas.className = "stack";
      canvasWrapper.appendChild(canvas);
      this.canvas = canvas;
      this.context = this.canvas.getContext('2d');
    }, 500)
  }
`
And in the main style of angular I put the next:
`
.stack {
  position: absolute;
  top     : 0;
  left    : 0;
}
`

**Comment by silvelo** [comment]
Add the rest of the code for draw and clear, in the component.ts

````
onMouseDown(event: MouseEvent) {
    this.mouseMove = true;
    this.startX = event['layerX']
    this.startY = event['layerY']
  }

  onMouseMove(event: MouseEvent) {

    if (this.mouseMove) {
      this.context.clearRect(0, 0, this.canvas.width, this.canvas.height);
      this.context.beginPath();
      this.lastX = event['layerX'];
      this.lastY = event['layerY'];

      this.context.rect(this.startX, this.startY, this.lastX - this.startX, this.lastY - this.startY);
      this.context.strokeStyle = 'black';

      this.context.stroke();
    }
  }

  onMouseUp(event: MouseEvent) {
    //this.canvas.style.cursor = "default";
    this.mouseMove = false;

  }
```
in the component.html
```
   <pdf-viewer [render-text]="true"
                (mousedown)="onMouseDown($event)"
                (mousemove)="onMouseMove($event)"
                (mouseup)="onMouseUp($event)"
                [render-text-mode]="0"
                [show-all]="false"
                [page]="(page$ | async)"
                [show-borders]="false"
                [fit-to-page]="true"
                (after-load-complete)="afterLoadComplete($event)"
                src="./assets/dummy.pdf"></pdf-viewer>
```
