### ISSUE TITLE
open multiple pages

### ISSUE THREAD

**Issue by Keshavmca12** [VadimDez/ng2-pdf-viewer#61]
Is it possible to open multiple pages at a time like open first 10 pages initially and then load remaining pages .

**Comment by VadimDez** [comment]
Hi, no there's nothing like that. It's either single or all pages.
But you can render all pages and then use CSS to hide/show pages.

**Comment by Keshavmca12** [comment]
But it takes too much time to load all pages and for some files browser get hanged for some time so I thought to use multiple pages to render pdf partially.

**Comment by Vi-dot** [comment]
@Keshavmca12 If you use the last version, pages are lazy-loaded. Which version of library are you using ?

**Comment by Keshavmca12** [comment]
Using  this version in my package.json   "ng2-pdf-viewer": "^1.0.2".Will you please suggest which version should I use??

**Comment by Vi-dot** [comment]
Hm in fact it's going to be ready for version 2.0.0. I don't know if `feature/2.0.0` is working.
You can try to checkout `feature/2.0.0`
Build it `npm run build`
Copy `build/pdf-viewer` to `dist`
Then replace in your package.json the ng2-pdf-viewer git path to your local path.

**Comment by Keshavmca12** [comment]
Its not working through above suggested way so is there any alternative way to do it??

**Comment by VadimDez** [comment]
Closing. Lazy loading is available since `2.0.0`
