### ISSUE TITLE
Angular 9 for Internet Explorer 11 dont work vendor.js compile error

### ISSUE THREAD

**Issue by dark0ni** [VadimDez/ng2-pdf-viewer#612]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
 I use "ng2-pdf-viewer": "^6.3.0" and upgraded my project to "@angular/core": "^9.1.9",
In Chrome i have no Problems but when I try to compile the project in es5 and start IE11 locally I get a error from the vendor.js

```
SCRIPT1010: Indentifier expected
vendor.js (158998,9)
```

```
{
  const { <--- Breaks here
    isNodeJS
  } = __w_pdfjs_require__(7);

  if (isNodeJS) {
    const PDFNodeStream = __w_pdfjs_require__(19).PDFNodeStream;

    pdfjsDisplayAPI.setPDFNetworkStreamFactory(params => {
      return new PDFNodeStream(params);
    });
  } else {
    const PDFNetworkStream = __w_pdfjs_require__(22).PDFNetworkStream;

    let PDFFetchStream;

    if (pdfjsDisplayDisplayUtils.isFetchSupported()) {
      PDFFetchStream = __w_pdfjs_require__(23).PDFFetchStream;
    }

    pdfjsDisplayAPI.setPDFNetworkStreamFactory(params => {
      if (PDFFetchStream && pdfjsDisplayDisplayUtils.isValidFetchUrl(params.url)) {
        return new PDFFetchStream(params);
      }

      return new PDFNetworkStream(params);
    });
  }
}
```

Has anybody an idea what the problem is?

**Comment by skyleguy** [comment]
I am using "ng2-pdf-viewer": "6.0.2" with angular 9.0.5 and I recently started to see the exact same error in IE11. 

pdfs also no longer render properly for me in Edge, it ends up rendering the correct amount of pages, but they are all blank and show the loading spinner forever

**Comment by skyleguy** [comment]
After adding the following dependencies to my own package.json i was able to get past this issue:

    "pdfjs-dist": "2.2.228"

You may need this one as well in the dev-dependencies:

    "@types/pdfjs-dist": "2.1.0",

but im pretty sure it isnt necessary

**Comment by chintan3100** [comment]
Hi Team, It not working. facing below issue in IE 11
![image](https://user-images.githubusercontent.com/1373832/83733037-98e35180-a66a-11ea-85b9-928484c98a40.png)
![image](https://user-images.githubusercontent.com/1373832/83733063-a4367d00-a66a-11ea-8ce1-f0b413945ee1.png)

**Comment by StuMx** [comment]
I did some research on this issue and found out that it's because pdfjs-dist provides a separate -es5 build for older browsers since v2.4.456 and which is the minimum version required by ng2-pdf-viewer since v2.3.0 and 

As a workaround you can use ng2-pdf-viewer@6.2.0 and setting pdfjs-dist@2.3.200 as fixed version in your package.json.

**Comment by dark0ni** [comment]
I tried to use a fixed Version but get errors when i want compile for IE with:
`ng serve --configuration es5`

```
ERROR in ./node_modules/ng2-pdf-viewer/__ivy_ngcc__/node_modules/pdfjs-dist/build/pdf.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\...\node_modules\ng2-pdf-viewer\__ivy_ngcc__\node_modules\pdfjs-dist\build'
ERROR in ./node_modules/ng2-pdf-viewer/__ivy_ngcc__/node_modules/pdfjs-dist/build/pdf.js
Module not found: Error: Can't resolve 'http' in 'C:\Users\...\node_modules\ng2-pdf-viewer\__ivy_ngcc__\node_modules\pdfjs-dist\build'
ERROR in ./node_modules/ng2-pdf-viewer/__ivy_ngcc__/node_modules/pdfjs-dist/build/pdf.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\...\node_modules\ng2-pdf-viewer\__ivy_ngcc__\node_modules\pdfjs-dist\build'

```

**Comment by chintan3100** [comment]
Add below package
![image](https://user-images.githubusercontent.com/1373832/84119892-a9247380-aa52-11ea-9b3d-31c9f71da1a2.png)


![image](https://user-images.githubusercontent.com/1373832/84119950-bfcaca80-aa52-11ea-9d6c-77e926de1221.png)


Set worker js in App component
 (<any>window).pdfWorkerSrc = './scripts/pdf.worker.js';

**Comment by m0py** [comment]
> Add below package
> ![image](https://user-images.githubusercontent.com/1373832/84119892-a9247380-aa52-11ea-9b3d-31c9f71da1a2.png)
> 
> ![image](https://user-images.githubusercontent.com/1373832/84119950-bfcaca80-aa52-11ea-9d6c-77e926de1221.png)
> 
> Set worker js in App component
> (window).pdfWorkerSrc = './scripts/pdf.worker.js';

It works for me without any problems! Thanks!!!

**Comment by robelcik** [comment]
Hello.
Here is my workaround used with the latest version(s). It changes paths in require statements in the viewer code.
I guess it could be "translated" to a proper fix (just change paths in the source code)

In package.json:
```
  "scripts": {
    "ng": "ng",
    "patch-pdf-viewer": "replace-in-file \"/require\\('pdfjs-dist\\/([^e])/g\" \"require('pdfjs-dist/es5/$1\" node_modules/ng2-pdf-viewer/fesm5/ng2-pdf-viewer.* --isRegex",
    "build": "npm run patch-pdf-viewer && ng build",
    ....
  }

"devDependencies": {
    "replace-in-file": "~6.1.0",
}
```

**Comment by Acereddy** [comment]
npm i pdfjs-dist@2.2.228

Was looking into this issue since last 2 days, finally worked for me, Thanks a lot.

**Comment by glappsi** [comment]
> Add below package
> ![image](https://user-images.githubusercontent.com/1373832/84119892-a9247380-aa52-11ea-9b3d-31c9f71da1a2.png)
> 
> ![image](https://user-images.githubusercontent.com/1373832/84119950-bfcaca80-aa52-11ea-9d6c-77e926de1221.png)
> 
> Set worker js in App component
> (window).pdfWorkerSrc = './scripts/pdf.worker.js';

I LOVE YOU!

**Comment by dmytro-gokun** [comment]
@VadimDez Does not this mean that folks who want to support "older" (but still widely used) browsers are bound to 6.2.0 forever? I do not think this is good news. Maybe there is a way around it?

**Comment by salvoimpspindox** [comment]
> Add below package
> ![image](https://user-images.githubusercontent.com/1373832/84119892-a9247380-aa52-11ea-9b3d-31c9f71da1a2.png)
> 
> ![image](https://user-images.githubusercontent.com/1373832/84119950-bfcaca80-aa52-11ea-9d6c-77e926de1221.png)
> 
> Set worker js in App component
> (window).pdfWorkerSrc = './scripts/pdf.worker.js';
> Do not use above code to load worker. It will create performance issue to navigate pdf pages. User below
> (window as any).pdfWorkerSrc = import('pdfjs-dist/webpack');

Hi, I tried using (window as any).pdfWorkerSrc = import('pdfjs-dist/webpack'), but there is a problem changing programmaticaly the src to the pdfComponent, sometimes the file changes other times it doesn't. Do u have any suggestions?
Thanks
