### ISSUE TITLE
Ionic 3/Angular where the PDF is on Google drive shared link -  fails to load PDF

### ISSUE THREAD

**Issue by SuganNaickerf** [VadimDez/ng2-pdf-viewer#614]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I have an Ionic3/Angular project where my PDF is on a Google Drive shared link - pdf viewer fails to load pdf, I get a CORS error. I used DOM Sanitizer and I get an error that a URL is need to load page.

**Comment by VadimDez** [comment]
See this: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-load-a-pdf-from-another-server-cross-domain-request
