### ISSUE TITLE
I have this error (Angular 8)

### ISSUE THREAD

**Issue by GarciaFreelancer** [VadimDez/ng2-pdf-viewer#616]
Uncaught (in promise) 

TypeError: Promise.allSettled is not a function
    at MessageHandler._deleteStreamController (pdf.js:7221)

**Comment by jmeichen** [comment]
me too

**Comment by DavydHabshydze** [comment]
the same, could anyone figured out how to fix it?

**Comment by DavydHabshydze** [comment]
I found a solution! You just need to update zone.js to version 0.10.3 or higher

**Comment by zhangDlufei** [comment]
> I found a solution! You just need to update zone.js to version 0.10.3 or higher

Is there any other way？

**Comment by leiyouyoo** [comment]
> I found a solution! You just need to update zone.js to version 0.10.3 or higher

it's work!

**Comment by adimunteanu** [comment]
thank you! Upgrading to zone.js 0.10.3 worked for me as well
