### ISSUE TITLE
Can't bind to 'stick-to-page' since it isn't a known property of 'pdf-viewer'

### ISSUE THREAD

**Issue by javist7** [VadimDez/ng2-pdf-viewer#62]
Can't bind to 'stick-to-page' since it isn't a known property of 'pdf-viewer'.
1. If 'pdf-viewer' is an Angular component and it has 'stick-to-page' input, then verify that it is part of this module.
2. If 'pdf-viewer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
            [page]="3"
            [original-size]="true"
            [show-all]="true"
            [ERROR ->][stick-to-page]="stickToPage"
            style="display: block;">
</pdf-viewer>

**Comment by VadimDez** [comment]
Which version are you using ?

**Comment by javist7** [comment]
^1.0.2

**Comment by VadimDez** [comment]
`[stick-to-page]` is not available in 1.0.2

**Comment by javist7** [comment]
how i can scroll to page ?
