### ISSUE TITLE
Does not render pages with Ionic 5

### ISSUE THREAD

**Issue by seopei** [VadimDez/ng2-pdf-viewer#625]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Steps to reproduce:
- https://stackblitz.com/edit/ionic-angular-v5-zwqhce
- Click the reload button in the stackblitz preview
- No pages are rendered
- Resize the stackblitz preview
- The pages will be rendered

**Comment by seopei** [comment]
It must be some sort of timing issue. If I reset `this.src` to the same value in a timeout it works. I updated the stackblitz source code.
```
export class AppComponent implements OnInit {
  src = "https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf";

  ngOnInit() {
    // this will fix the issue
    setTimeout(() => this.src += '', 10);
  }
}
```

**Comment by Noext** [comment]
same issue, author solution did not work
