### ISSUE TITLE
PDF links are not opening at all

### ISSUE THREAD

**Issue by versavice** [VadimDez/ng2-pdf-viewer#628]
##### Bug Report or Feature Request (mark with an `x`)
```
- [x] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Marking this as regression since I assume it was working at some point, but I cant click links in my pdf documents. I added the following properties to the pdf-viewer element
`[render-text]="true" [render-text-mode]="1" [external-link-target]="'blank'"`

**Comment by VadimDez** [comment]
Seems to be working fine, tested here: https://vadimdez.github.io/ng2-pdf-viewer/
