### ISSUE TITLE
How to scroll to page?

### ISSUE THREAD

**Issue by xTaz1** [VadimDez/ng2-pdf-viewer#63]
version: ^1.0.2
```
<pdf-viewer [src]="assets/test.pdf"
            [page]="'3'"
            [original-size]="true"
            [show-all]="true"
            style="display: block;">
</pdf-viewer>
```
This code doesn't work. How i can scroll to 3 page in pdf file ?

**Comment by VadimDez** [comment]
The functionality will be available in `2.0.0`.
For now you can use `[(page)]="page"` with `[show-all]="true"`. Or you can always implement your own scrollTo with js.

**Comment by javist7** [comment]
> For now you can use [(page)]="page" with [show-all]="true".
doesn't work

**Comment by VadimDez** [comment]
You can use `[stick-to-page]="true"` available since `2.0.0`. Closing.

**Comment by VadimDez** [comment]
Now you can scroll to a page with the following code, add this to your component that uses `pdf-viewer` component

```ts
// define view child
@ViewChild(PdfViewerComponent) private pdfComponent: PdfViewerComponent;

// ...

scrollToPage(page: number) {
  this.pdfComponent.pdfViewer.scrollPageIntoView({
    pageNumber: page
  });
}
```

and then use it
```ts
scrollToPage(3);
```

**Comment by metanav** [comment]
How can I access PdfViewerComponent, which package?

**Comment by VadimDez** [comment]
@metanav can you try?
```
import { PdfViewerComponent } from 'ng2-pdf-viewer/dist/pdf-viewer.component.js';
```

**Comment by abbasshujah** [comment]
It is not working for me if anyone has made it work can you post an example

**Comment by xTaz1** [comment]
@abbasshujah Memory leaks in this lib, don't use it for large files. See [https://github.com/VadimDez/ng2-pdf-viewer/issues/220](issue-220)

Try to use `pdfjs-dist` and typings for it `@types/pdf`. I don't remember why we didn't use this library, but pdfjs works perfect.

**Comment by abbasshujah** [comment]
I want to be able to programmatically highlight things in PDF which I cant
find in PDF.js, Do you know how to do that in PDF.js

**Comment by ParagBadala** [comment]
Scroll is not working for me when i used it in my project please help me in this

**Comment by pumbhadianilesh** [comment]
> [VadimDez](/VadimDez)

I need to scroll to particular position within a **single page** programmatically (scroll to left or right and top or Bottom).
Please help me in that regard.

Thanks in Advance
