### ISSUE TITLE
Show image blob

### ISSUE THREAD

**Issue by lorrandavid** [VadimDez/ng2-pdf-viewer#632]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [x] Documentation issue or request
```

Is it possible to show an image blob with this component? I've been trying to use it but it shows nothing at all but when I use a pdf blob it works flawlessly. Should I do something different other than create a blob using `URL.createObjectURL()`?

**Comment by VadimDez** [comment]
This component handles `PDF`s and not images.
