### ISSUE TITLE
[original-size]="false", Can I get how much the PDF was scaled by?

### ISSUE THREAD

**Issue by erezhod** [VadimDez/ng2-pdf-viewer#633]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [x] Documentation issue or request
```
Hi guys!
I am writing an overlay for this library that shows html annotations on the PDF (basically, I am putting div squares over the PDF in html).

The thing is, I have the dimensions and coordinates in relation to the original page size, but if it's scaled, these coordinates and size are not valid anymore and I need to re-calculate the coordinates and size of the square by the new scale size.

[This screenshot may explain better](https://imgur.com/a/xjcsHFb)

If I can get how much the page was scaled by compared to the original size, that would help me greatly.

Thank you very much 🙂

**Comment by simianstyle** [comment]
Set reference to pdfviewer
`@ViewChild(PdfViewerComponent) private _pdfViewer: PdfViewerComponent;`

in Html for pdfviewer you should have ` (after-load-complete)="afterLoadComplete($event)" `

in ts
` afterLoadComplete(pdfData: any) {
let data = this._pdfViewer.pdfViewer._pages;
data.forEach(element => {
        element = element.pdfPage;
        if (element._pageInfo.rotate == 90 || element._pageInfo.rotate == 270)
          this.pdfPageDims.push({ height: element._pageInfo.view[2], width: element._pageInfo.view[3] });
        else
          this.pdfPageDims.push({ height: element._pageInfo.view[3], width: element._pageInfo.view[2] });
      });
}
`

This will get you the size of each rendered page and you can compare that to the dimensions of the you had for the coordinates and apply a scaleFactor.

**Comment by jordanboston** [comment]
@simianstyle This is great, thanks so much!!  One thing I'm noticing is that even though this calls my method after-load-complete(), I have had to set a timeout or the data is not there yet, and my vars end up undefined.

Is this just me?  I would thing that after-load-complete would mean it only executes the callback after the pdf is loaded and the data is ready.  Not sure if I'm missing something. 😂
