### ISSUE TITLE
Ionic 3: I can't seem to get the search function to work

### ISSUE THREAD

**Issue by cr1pt0r0** [VadimDez/ng2-pdf-viewer#634]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [X] Documentation issue or request
```

I have tried following the documentations by entering the code below

@ViewChild("pdfViewer") private pdfComponent: PdfViewerComponent;
 
search(stringToSearch: string) {
  this.pdfComponent.pdfFindController.executeCommand('find', {
    caseSensitive: false, findPrevious: undefined, highlightAll: true, phraseSearch: true, query: stringToSearch
  });
}

The issue that I'm having is that "Cannot find name 'PdfViewerComponent'". executeCommand is not a function etc. 

What am I missing?

**Comment by HYNTmusso** [comment]
Hi, i have the same issue. I don't know if it is something related to the browser (i test it on Safari, Edge and Chrome - same issue).
We use the latest version of ng-pdf-viewer (9.1.0) and Angular 13.

I initialize the component like this :

`@ViewChild('preview') private pdfComponent: PdfViewerComponent | undefined;`

and start the command

`this.pdfComponent?.pdfFindController.executeCommand('find', {
        caseSensitive: false,
        findPrevious: undefined,
        highlightAll: true,
        phraseSearch: true,
        query: stringToSearchInsidePDF,
      });`
