### ISSUE TITLE
ng2-pdf-viewer not working in  ssr mode 

### ISSUE THREAD

**Issue by Bizotics-Dev** [VadimDez/ng2-pdf-viewer#636]
Error in serverside rendering mode : window.requestAnimationFrame  is not function
   "ng2-pdf-viewer": "^5.3.4",
    angular-cli :7.1.4

**Comment by olechka-dev** [comment]
@Bizotics-Dev  in your server.ts file import 'domino' package
`const domino = require('domino');`
and mock the missing `requestAnimationFrame`  function
```
const win = domino.createWindow(template);  // template is a variable to which you read your index.html 
global['window'] = win;
win.requestAnimationFrame = () => {};
global['Element'] = {
    prototype: {}
};
```
