### ISSUE TITLE
Can not view PDF from virtual directory (iis platform).

### ISSUE THREAD

**Issue by d052057** [VadimDez/ng2-pdf-viewer#638]
My platform is IIS.  I create a virtual directory in /assets (the actual directory is in D: drive) and I can not view the pdf files.  However, if I put those files inside the /assets/my local drive, it works fine.

I suspect that it is my code likely but I can not find any example how to access data in virtual folder.
I am using Angular 10 with MVC backend and VS2019 visual studio.  

Can any one pinpoint or guide to the right direction please?

Thanks.

**Comment by ayalamac** [comment]
Maybe is CORS related. I had the same problem and solved it with a web.config file inside the folder where the files are. Create this file and put in the following code:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <system.webServer>
   <httpProtocol>
     <customHeaders>
       <add name="Access-Control-Allow-Origin" value="*" />
     </customHeaders>
   </httpProtocol>
 </system.webServer>
</configuration>
```

**Hope this helps!**

**Comment by d052057** [comment]
Here is the string I assigned to [src], https://localhost/assets/images/books/recipe/Home%20Wiring.pdf.
books is a virtual folder located in D: drive.  If I get rid of the virtual folder /books and create the books folder in images folder, it is working fine.
Thanks.
    On Sunday, July 26, 2020, 06:53:28 PM PDT, Andres Ayala <notifications@github.com> wrote:  
 
 


Maybe is CORS related. I had the same problem and solved it with a web.config file inside the folder where the files are. Create this file and put in the following code:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <system.webServer>
   <httpProtocol>
     <customHeaders>
       <add name="Access-Control-Allow-Origin" value="*" />
     </customHeaders>
   </httpProtocol>
 </system.webServer>
</configuration>

Hope this helps!
