### ISSUE TITLE
Angular 9: (error) event emitter emits undefined for protected PDF

### ISSUE THREAD

**Issue by olechka-dev** [VadimDez/ng2-pdf-viewer#639]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

**Actual**: After update to Angular 9 `error` event emitter of `pdf-viewer `component emits `undefined` when I try to open password-protected pdf file (passing object with url to [src] input). With Angular version < 9, `error` used to emit Error object with property `name === 'PasswordException' `, and this was the indication that the file is password protected.
**Expected**: `error` to emit a meaningful error to indicate that password is required for pdf to open

**Comment by vijay-flexiloans** [comment]
> ##### Bug Report or Feature Request (mark with an `x`)
> ```
> - [ ] Regression (a behavior that used to work and stopped working in a new release)
> - [x] Bug report -> please search issues before submitting
> - [ ] Feature request
> - [ ] Documentation issue or request
> ```
> 
> **Actual**: After update to Angular 9 `error` event emitter of `pdf-viewer `component emits `undefined` when I try to open password-protected pdf file (passing object with url to [src] input). With Angular version < 9, `error` used to emit Error object with property `name === 'PasswordException' `, and this was the indication that the file is password protected.
> **Expected**: `error` to emit a meaningful error to indicate that password is required for pdf to open

facing the same issue.

**Comment by HermanPierre** [comment]
Hello, I have the same issue, my error is undefined for a password protected PDF.
