### ISSUE TITLE
ng2-pdf-viewer displaying just 2 page instead all pdf file

### ISSUE THREAD

**Issue by CHOUAIAR** [VadimDez/ng2-pdf-viewer#64]
Hello @VadimDez,

When I use ng2-pdf-viewer in version 1.0.1 I get 2 pages displayed instead of all the file, while it display all the pages in 0.0.14 but with canvas tag. I don't know what I'm missing.

Thanks in advance

**Comment by VadimDez** [comment]
Hi, use the latest version `1.0.2`. The issue is fixed there.

**Comment by CHOUAIAR** [comment]
Thank you @VadimDez I tested just after I posted the question and its working, but I have last question, what must I do ti add the options to the div for each page such as data-page-number, I saw that its added in the pdf_viewer.js and is it possible to have an output returning the selected page?

Thank you very much.
