### ISSUE TITLE
Dot issue in Edge browser while rendering a pdf

### ISSUE THREAD

**Issue by MohamedSahir** [VadimDez/ng2-pdf-viewer#647]
Recently i have faced an issue with edge browser dot appears in the pdf viewer. while rotating a document  ,the dot disappears .not for other browsers.I don't know why it is happens in edge browser . 

use case:
Page 1 - not issue , if click on other page dot appears.

Below Version tested: 
Angular 9
```
**"ng2-pdf-viewer": "~6.1.3",
Microsoft EdgeHTML 18.18363
Microsoft Edge 44.18362.449.0**
```

Attached Screenshot:
![image](https://user-images.githubusercontent.com/20682302/90337911-4972b780-e003-11ea-9526-a7979df9887a.png)

![image](https://user-images.githubusercontent.com/20682302/90338017-3c09fd00-e004-11ea-8263-82694d1d0340.png)

**Comment by serhatoguzkoc** [comment]
Same issue on my project I use version 5.2.4. I think viewer is not support to ie11 
++

**Comment by MohamedSahir** [comment]
ie11 is ok but the edge needs to do support. else provide the details in browser documentation..it will help us to choose plugin before development. At the end of the development, doing testing and during delivery time needs to change a plugin is a difficult part.

my only concern is add the browser doc.
