### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: Cannot read property '_pageInfo' of null

### ISSUE THREAD

**Issue by addguy** [VadimDez/ng2-pdf-viewer#648]
##### Bug Report or Feature Request (mark with an `x`)
```
- [x] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Tried in Angular 8 , 9 , 10 using latest version of this library. 

In html I hook into callback `(after-load-complete)="afterLoadComplete($event)" `

in typescript

` afterLoadComplete(pdf: any) {
    let pages = this._pdfViewer.pdfViewer._pages;
    pages.forEach(element => {
        element = element.pdfPage;
          this.pageDimensions.push({ height: element._pageInfo.view[3]/this.scale, width: element._pageInfo.view[2]/this.scale });
      });
}`

It throws error here. I am loading small pdf ~100kb in size. Now if I put a 8 second delay the error goes away and pdf renders. Otherwise pdf only renders half the page and all pages are rendered with 50% of document showing. But if go back to page 1 then it seems to reload the document or create it in the DOM.  I don't understand why it does this.   Is afterLoadComplete not awaiting actual completion? What am i doing wrong?

**Comment by adguy365** [comment]
ERROR Error: Uncaught (in promise): TypeError: Cannot read property '_pageInfo' of null
TypeError: Cannot read property '_pageInfo' of null
    at pdf.component.ts:52
    at Array.forEach (<anonymous>)
    at pdf.component.ts:50
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at PdfComponent.PageDimensions (pdf.component.ts:66)
    at pdf.component.ts:58
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:41643)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41621)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at invokeTask (zone-evergreen.js:484)
    at ZoneTask.invoke (zone-evergreen.js:469)
defaultErrorLogger @ core.js:6228
handleError @ core.js:6281
next @ core.js:42599
schedulerFn @ core.js:37119
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:37079
(anonymous) @ core.js:41683
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:123
runOutsideAngular @ core.js:41477
onHandleError @ core.js:41680
handleError @ zone-evergreen.js:368
runGuarded @ zone-evergreen.js:136
api.microtaskDrainDone @ zone-evergreen.js:670
drainMicroTaskQueue @ zone-evergreen.js:576
invokeTask @ zone-evergreen.js:484
ZoneTask.invoke @ zone-evergreen.js:469
timer @ zone-evergreen.js:2552
setTimeout (async)
scheduleTask @ zone-evergreen.js:2573
scheduleTask @ zone-evergreen.js:385
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:378
scheduleTask @ zone-evergreen.js:210
scheduleMacroTask @ zone-evergreen.js:233
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1134
(anonymous) @ zone-evergreen.js:2586
proto.<computed> @ zone-evergreen.js:1449
(anonymous) @ pdf.component.ts:83
ZoneAwarePromise @ zone-evergreen.js:960
(anonymous) @ pdf.component.ts:83
(anonymous) @ tslib.es6.js:74
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter @ tslib.es6.js:70
delay @ pdf.component.ts:82
afterLoadComplete @ pdf.component.ts:57
(anonymous) @ pdf.component.html:99
handleEvent @ core.js:46169
callWithDebugContext @ core.js:47826
debugHandleEvent @ core.js:47435
dispatchEvent @ core.js:31513
(anonymous) @ core.js:33381
schedulerFn @ core.js:37171
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:37079
(anonymous) @ ng2-pdf-viewer.js:498
invoke @ zone-evergreen.js:364
onInvoke @ core.js:41643
invoke @ zone-evergreen.js:363
run @ zone-evergreen.js:123
(anonymous) @ zone-evergreen.js:857
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:41621
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
drainMicroTaskQueue @ zone-evergreen.js:569
invokeTask @ zone-evergreen.js:484
invokeTask @ zone-evergreen.js:1621
globalZoneAwareCallback @ zone-evergreen.js:1658
Show 36 more frames
