### ISSUE TITLE
Display pdf file from azure blob file url

### ISSUE THREAD

**Issue by nirav5884** [VadimDez/ng2-pdf-viewer#649]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [x] Documentation issue or request
```

Trying to load the pdf file uploaded in my local azure storage blob (using file url), but getting the error "Trying to use fetch and pass in mode: no-cors".
My local azure storage url is: http://127.0.0.1:10000/container/myfiles/file.pdf

`<pdf-viewer [src]="fileUrl" [render-text]="true" style="display: block;" [external-link-target]="'blank'" [show-all]="true">`

**Comment by VadimDez** [comment]
Sounds like you have to enable CORS.
