### ISSUE TITLE
Can't bind to 'src' since it isn't a known property of 'pdf-viewer'.

### ISSUE THREAD

**Issue by lubo08** [VadimDez/ng2-pdf-viewer#65]
Template parse errors:
Can't bind to 'src' since it isn't a known property of 'pdf-viewer'.
1. If 'pdf-viewer' is an Angular component and it has 'src' input, then verify that it is part of this module.
2. If 'pdf-viewer' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("<div class="row">
  <pdf-viewer [ERROR ->][src]="pdfSrc"
              [page]="page"
              [original-size]="true"
"): t@1:14

**Comment by lubo08** [comment]
I add this to global app module. When I move declaration to page module than it work OK.

**Comment by ladmini** [comment]
I have the same problem as you, but I haven't solved it yet. Could you please tell me more about it? I hope to get your reply, thank you very much!!!

**Comment by thanikc** [comment]
> I add this to global app module. When I move declaration to page module than it work OK.

What does that mean? Is this change reflected in the documentation somewhere?

**Comment by lubo08** [comment]
Hi. I did not found this in documentation. But if I wanted use it I have to define it in component of every page where is used. Just I wanted add it global to app.component.ts but this will not work.  So I add it to mypage.component.ts, PdfViewerComponent declaration.

@NgModule({
  imports: [BrowserModule],
  declarations: [AppComponent, PdfViewerComponent],
  bootstrap: [AppComponent]
})

**Comment by stephane317** [comment]
Yes you can't share the module in different sub-module of the angular app but can't use it global in the main app.module
Any fix for that ? 
thanks
