### ISSUE TITLE
Not using bundled pdf.worker.min.js

### ISSUE THREAD

**Issue by eedahl** [VadimDez/ng2-pdf-viewer#650]
https://github.com/VadimDez/ng2-pdf-viewer/blob/2e0e03146c1bcf53754f24decdbb4fd1ef741490/src/app/pdf-viewer/pdf-viewer.component.ts#L249

This here means the viewer isn't using the bundled PDF worker. Is this intentional?

**Comment by petrusgomes** [comment]
Yes,. According to [README](https://github.com/VadimDez/ng2-pdf-viewer/blob/master/README.md#set-custom-path-to-the-worker), this is the default behavior.
[This comment](https://github.com/VadimDez/ng2-pdf-viewer/issues/504#issuecomment-684922898) seems like a good way to use the bundled worker (you may need to install pdfjs-dist)

**Comment by jarodsmk** [comment]
@petrusgomes - I think the issue here is that it bundles a `pdf.worker.js` even though it uses one from Cloudflare - 

Unless I'm missing something it doesn't make sense to have a dependency (and quite a sizable one) if it's not being used
