### ISSUE TITLE
Warning: Indexing all PDF Objects 

### ISSUE THREAD

**Issue by HeihoffJ** [VadimDez/ng2-pdf-viewer#652]
My backend creates a PDF based on a formular I submitted. The next page should show the Pdf Documents. I use ng2-pdf-viewer for that purpose. My problem is, that every time I run it the very first time I start my browser I always get the "pdf.worker.min.js:22 Warning: Indexing all PDF objects" warning. When I submit my next formular I dont get the error again and instead it shows the pdf documents.

My GET Request looks as follow:

```
 this.pdfService.getMaterialPdf().subscribe((file: ArrayBuffer) => {this.pdfMaterial = file});
in the pdfService:
```

```
   getMaterialPdf() : Observable<any>
  {
    return this.http.get(this.url+'Material', {responseType:"arraybuffer"});
  }
```
and the response from the server:

```
app.get("/pdf/Material", (req, res) => {
      fs.readFile(materialPath,(err, data) => {
        if (err) {
          throw err;
        }
  
        res.send((data));
      });
    });

```

**Comment by HeihoffJ** [comment]
The problem is still as it is. Please do not mark it as stale.

**Comment by stephanrauh** [comment]
The message indicates your PDF file contains a faulty xref table. Please check if the warning is also shown on https://mozilla.github.io/pdf.js/web/viewer.html. If it happens over there, too, the ticket hasn't anything to do with ng2-pdf-viewer.

**Comment by HeihoffJ** [comment]
Unfortunately the warning doesnt show on this website. 
Even when I submit my next formular within a new Chrome Instance (checked Mozilla Firefox as well), the PDF is shown. It only happens when I restart my computer. 
I create my PDF Document with the pdfmake (http://pdfmake.org/#/). 
My Xref Table looks like this if it helps:
xref
0 24
0000000000 65535 f 
0000010809 00000 n 
0000010866 00000 n 
0000010747 00000 n 
0000010726 00000 n 
0000000015 00000 n 
0000004763 00000 n 
0000004609 00000 n 
0000004499 00000 n 
0000004449 00000 n 
0000010578 00000 n 
0000009501 00000 n 
0000008234 00000 n 
0000008146 00000 n 
0000008172 00000 n 
0000008198 00000 n 
0000010913 00000 n 
0000008310 00000 n 
0000008522 00000 n 
0000009033 00000 n 
0000015222 00000 n 
0000009650 00000 n 
0000009861 00000 n 
0000010207 00000 n 
trailer
