### ISSUE TITLE
[Feature Request] Ability to rotate single page.

### ISSUE THREAD

**Issue by aakashbh2** [VadimDez/ng2-pdf-viewer#659]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [X] Feature request
- [ ] Documentation issue or request
```
I want to rotate a single page instead of entire PDF. Please add the ability to do so.

**Comment by hughanderson4** [comment]
Hello ng2-pdf-viewer community!  Please try my solution of it on this StackBlitz:

https://stackblitz.com/edit/ng2-pdf-viewer-bvgels?file=src%2Fstyles.css

I added a todo in the code where you could adjust the page's margins when changing from Portrait to Landscape, if desired.

@VadimDez maybe such function could be added to the library?  Our UX team is requesting it as well.

🍺
