### ISSUE TITLE
Is it possible to save the pdf to local storage?

### ISSUE THREAD

**Issue by sysueasy** [VadimDez/ng2-pdf-viewer#66]
Is it any approach to save the pdf link file into native iOS/Android storage?

**Comment by VadimDez** [comment]
@sysueasy What do you exactly mean? So is it "local storage" or "native storage" ?

**Comment by VadimDez** [comment]
Closing, incomplete information.

**Comment by shankmr** [comment]
how can we send pdf generated from byte array to save in AWS?
