### ISSUE TITLE
'pdf-viewer' is not a known element:

### ISSUE THREAD

**Issue by najmulansari** [VadimDez/ng2-pdf-viewer#661]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
**I am trying to integrate pdf-viewer in ionic/angular, but getting below error.**

```
'pdf-viewer' is not a known element:
1. If 'pdf-viewer' is an Angular component, then verify that it is part of this module.
2. If 'pdf-viewer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Ng
![Capture](https://user-images.githubusercontent.com/10203537/94715544-9bee0600-031b-11eb-95e6-a18055eab5c1.PNG)
Module.schemas' of this component to suppress this message.
core.js:7813 Can't bind to 'src' since it isn't a known property of 'pdf-viewer'.
core.js:7813 Can't bind to 'render-text' since it isn't a known property of 'pdf-viewer'.

```
I am using 

Angular CLI: 10.0.8
Node: 12.16.0
OS: win32 x64
Angular: 10.0.14

Ionic : 6.11.10

Could you please help to fix the issue.

**Comment by manojmanic** [comment]
import pdf-viewer in your module.it works fine

**Comment by VadimDez** [comment]
@najmulansari please follow the instructions in the [README.md](https://github.com/VadimDez/ng2-pdf-viewer/blob/master/README.md)

**Comment by vinceclicks** [comment]
I have followed the documentation exactly and I have this issue.

**Comment by MathieuDV** [comment]
I think [this link](https://stackoverflow.com/a/58673241) explain the problem
