### ISSUE TITLE
Unable to view PDF in iOS14

### ISSUE THREAD

**Issue by harivenkatesh-id** [VadimDez/ng2-pdf-viewer#663]
When opening a PDF document in ionic4 - iOS 14 its not loading PDF, shows white screen with error "Setting up fake worker failed: \"Cannot load script at: https://cdnjs.cloudflare.com/cjax/libs/pdf.js/2.4.456/pdf.worker.min.js\"."

Attached screenshot for reference.

![Simulator Screen Shot - iPad (8th generation) - 2020-10-05 at 13 18 51](https://user-images.githubusercontent.com/59644592/95196523-d19c5e80-07f5-11eb-8b8d-9283ce382c9c.png)

**Comment by harivenkatesh-id** [comment]
Its working well on iOS 13.x and Android

**Comment by jamesonsaunders** [comment]
Same issue

**Comment by VadimDez** [comment]
@jamesonsaunders did you overwrite `pdfWorkerSrc` to a custom worker path?
