### ISSUE TITLE
Error on Safari The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/o…

### ISSUE THREAD

**Issue by demanzano** [VadimDez/ng2-pdf-viewer#664]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

On Safari both desktop (v11.1.2) and iOS (14.0.0) trying to visualize a PDF fails and the error callback get the above error (see screenshot attached)
But your demo link works fine in Safari, so there is something else, what could be ? I've just installed and pkg as the docs says, and indeed on Chrome and Firefox it works fine !

Any idea ?

thanks!

Ale
![Screen Shot 2020-10-06 at 18 18 11](https://user-images.githubusercontent.com/19893681/95229376-cac71900-0800-11eb-9b6b-e833f3a20d2d.png)

**Comment by deveshmishra34** [comment]
Any updates on this..?

**Comment by LuisManuel1983** [comment]
Hi I'm getting this error exactly but for Android. I using this library in an Ionic app and when I test on the browser (Ionic serve) works fine, but when I test on android emulator or device, I get this errror

**Comment by iosifnicolae2** [comment]
Any update on this?

**Comment by iosifnicolae2** [comment]
I found a solution.

I did the same changes as in [this](https://github.com/VadimDez/ng2-pdf-viewer/commit/59c72bdb122e185d72eed66e7e9fe6f058fa6020) commit for my Angular project and now it's working.


Also, I've used `esnext` as `tsconfig` module.
https://github.com/VadimDez/ng2-pdf-viewer/blob/59c72bdb122e185d72eed66e7e9fe6f058fa6020/tsconfig.json#L10

**Comment by stephanrauh** [comment]
That rings a bell... I've been fighting this bug for several weeks. @iosifnicolae2, you're right, loading the ES5 version of the pdf.js worker is a solution. A solution that sacrifices less performance is adding this polyfill to the ES2015 version of the pdf.worker.js file:

```typescript
if (!Promise.allSettled) {
  Promise.allSettled = function (promises) {
    let mappedPromises = promises.filter(o => !!o).map(p => {
      return p.then(value => {
        return {
          status: 'fulfilled',
          value
        };
      }).catch(reason => {
        return {
          status: 'rejected',
          reason
        };
      });
    });
    return Promise.all(mappedPromises);
  };
}
```

Also see https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/358#issuecomment-718445879 and the rest of the thread.
