### ISSUE TITLE
Need to expose canvas context

### ISSUE THREAD

**Issue by nbaua** [VadimDez/ng2-pdf-viewer#665]
```
- [ X] Feature request
```
Hi, 

We want to access the canvas object for adding signature on the existing PDF file.
It should be pretty straight with canvas accessible before hand (or once the page is rendered).

Currently this is not accessible unless you scavenge the entire DOM, also once it is accessible it still difficult to do much on the canvas either.

**Comment by stephanrauh** [comment]
This feature requires a modification of the base library, pdf.js. I suppose that's out of scope of this project.
