### ISSUE TITLE
PDF scrollPageIntoView is not working

### ISSUE THREAD

**Issue by Anand-Paul** [VadimDez/ng2-pdf-viewer#666]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
scrollPageIntoView is not working 
Here is PDF Element
` @ViewChild('pdfViewer') pdfViewerContainer`

Here is scrolling function 
`scrollToPage(page: number): void {
    this.pdfViewerContainer.pdfViewer.scrollPageIntoView({
      pageNumber: page,
    })
  }`

Here is the HTML
` <pdf-viewer
      [src]="pdfSrc"
      [render-text]="true"
      [show-all]="true"
      [show-borders]="true"
      [zoom]="zoom"
      [original-size]="false"
      [autoresize]="true"
      [fit-to-page]="true"
      [zoom-scale]="zoomScale"
      [stick-to-page]="true"
      [(page)]="pageVariable"
      (after-load-complete)="afterLoadComplete($event)"
      #pdfViewer
    ></pdf-viewer>`

Environment  :
Angular 9 - local

**Comment by harivenkatesh-id** [comment]
Yes im able to reproduce this issue too. Any workaround or solution ?

**Comment by hughanderson4** [comment]
Hello ng2-pdf-viewer community!  Please try my solution of it.

```ts

    constructor(private _domElement: ElementRef) {
    }

    scrollToPage(newPage: number) {
        const page: HTMLDivElement =
            this._domElement.nativeElement.querySelector(`pdf-viewer .page[data-page-number="${newPage}"]`);
        if (page) {
            const scrollbar = this._findPdfScrollbar();
            scrollbar.scrollTo({
                top: Math.max(0, page.offsetTop),
                behavior: 'smooth'
            });
        }
    }

    private _findPdfScrollbar() {
        return this._domElement.nativeElement.querySelector('pdf-viewer .ng2-pdf-viewer-container');
    }
```

I even made you a [StackBlitz](https://stackblitz.com/edit/ng2-pdf-viewer-618uxp?file=src%2Fapp%2Fapp.component.ts) :beer:

@VadimDez maybe such function could be updated in the library?

**Comment by VadimDez** [comment]
@Anand-Paul can you try to define dimensions (`height`) for `pdf-viewer` element?
See `breaking changes` part in [here](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/6.0.0)

**Comment by manojmanic** [comment]
> Hello ng2-pdf-viewer community! Please try my solution of it.
> 
> ```ts
>     constructor(private _domElement: ElementRef) {
>     }
> 
>     scrollToPage(newPage: number) {
>         const page: HTMLDivElement =
>             this._domElement.nativeElement.querySelector(`pdf-viewer .page[data-page-number="${newPage}"]`);
>         if (page) {
>             const scrollbar =
>                 this._domElement.nativeElement.querySelector('pdf-viewer .ng2-pdf-viewer-container');
>             scrollbar.scrollTo({
>                 top: Math.max(0, page.offsetTop),
>                 behavior: 'smooth'
>             });
>         }
>     }
> ```
> 
> I even made you a [StackBlitz](https://stackblitz.com/edit/ng2-pdf-viewer-618uxp?file=src%2Fapp%2Fapp.component.ts) 🍺
> 
> @VadimDez maybe such function could be updated in the library?

Hello is that possible way to scroll option can use in thumbnail view ?
