### ISSUE TITLE
PDF from external link is not working

### ISSUE THREAD

**Issue by bhadresharya** [VadimDez/ng2-pdf-viewer#667]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
PDF is not loaded when PDF src url is other than - https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf
Any external url link with http or https won't work.

**Comment by VadimDez** [comment]
It will, see if you get CORS error from the source of the file.

**Comment by KOSSOKO** [comment]
@VadimDez i'm facing the same issue with this pdf https://gara-ebook-storage-dev.s3.eu-west-3.amazonaws.com/1/ebooks-data/ebook-1608418728507/ebook-file-1608498919187/Hercule_Poirot_Le_Crime_De_L_Orient_Express.pdf.
I have CORS error, but how enable « Access-Control-Allow-Origin » for your plugin ?

**Comment by faizaldong** [comment]
@VadimDez Im facing same issue. below is for your code reference

`<pdf-viewer
        *ngIf="video.isMedia === 'pdf'"
        [src]="pdf"
        [render-text]="true"
        [style.height.px]="pdfHeight"
        [external-link-target]="'blank'"
        [original-size]="false"
        style="display: block;"
        class="frame-wrapper__video feature-wrapper__iframe feature-wrapper__iframe-pdf"
      ></pdf-viewer>`
      
    In consoe log, I getting this CORS error
    
![Screenshot 2021-02-15 at 2 35 55 PM](https://user-images.githubusercontent.com/17352624/107913326-2b2e4a00-6f9b-11eb-9921-c9ddc44bb558.png)

**Comment by faizaldong** [comment]
> It will work if you provide an external PDF link! See if you get CORS error from the source of the file.

@VadimDez  what do you mean by providing `external PDF link` ? I don't see `external PDF link` option from your document.

**Comment by KOSSOKO** [comment]
@faizaldong where do host your file ? You have a CORS issue. Enable Cors origin from your server dmedia.gozero.tech

**Comment by faizaldong** [comment]
for someone still struggling with this issue even after enable CORS origin in your server, my suggestion to add origin parameter in url with value localhost like below

`var url = "https://xxxx.xxx.xxxxx";
url = url + '?origin=localhost'; `

**Comment by hugoblanc** [comment]
> for someone still struggling with this issue even after enable CORS origin in your server, my lead dev suggested to add origin parameter in url with value localhost like below
> 
> `var url = "https://xxxx.xxx.xxxxx"; url = url + '?origin=localhost'; `
> 
> refer here: https://stackoverflow.com/a/64693106

Give the lead dev a gold medal

**Comment by xinthose** [comment]
We had the same issue with CloudFront.  Had to use Legacy cache settings in edit default behavior, then it worked.
