### ISSUE TITLE
Stackblitz sample not working in Android pixel mobile emulator

### ISSUE THREAD

**Issue by yoganathan55** [VadimDez/ng2-pdf-viewer#668]
I have tried to use your [stackblitz](https://stackblitz.com/edit/ng2-pdf-viewer) sample provided by your website. It's not loading. 

![image](https://user-images.githubusercontent.com/69343763/96217007-5843ff00-0f9f-11eb-94c8-fc22d8a150bf.png)

**Comment by ckc52403050** [comment]
Same Issue here, both deployed web and built apk on Android.

**Comment by VadimDez** [comment]
This issue has something to do with stackblitz itself i guess.
https://vadimdez.github.io/ng2-pdf-viewer/ seems to be working on Andorid emulator, not sure if i can do something about it
