### ISSUE TITLE
Local PDF worker doesn't work after Angular 10 upgrade.

### ISSUE THREAD

**Issue by N-Andronopoulos** [VadimDez/ng2-pdf-viewer#669]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I was using this:
```
  ngOnInit(): void {
   // Load the PDF worker locally so we don't depend on CloudFlare
   (window as any).pdfWorkerSrc = './assets/pdf.worker.min.js';
  }
```
But after upgrading to Angular 10 the pdf library doesn't fetch or render the pdfs in the component.
If I comment out this line it works again. I tested it with dev and prod builds, but on localhost without https.

**Comment by VadimDez** [comment]
@N-Andronopoulos have you seen any errors in the console? Was the `pdf-worker.min.js` loaded in the `network` tab?

**Comment by N-Andronopoulos** [comment]
Yes It did load the worker (it worked before the upgrade) and it didn't produce any errors.

**Comment by mpstv** [comment]
Hi everyone.
@N-Andronopoulos you can try add `onerror` handler to `pdf-viewer` like:
```html
<pdf-viewer [src]="pdfSrc"
            (error)="logError($event)"
></pdf-viewer>
```
```javascript
logError(error) {
  console.error(error);
}
```

I was confused that the ng2-pdf-viewer does not log an error but shows a white screen. I spent a lot of time to understand that it is necessary to add an event handler.

@VadimDez what do you think about change this behavior in future?
