### ISSUE TITLE
Disable data:-images

### ISSUE THREAD

**Issue by HansCronau** [VadimDez/ng2-pdf-viewer#673]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```

I'm working on an application that, for security reasons, has a limited Content Security Policy directive: `img-src 'self'`.
While ng2-pdf-viewer works fine, it does throw errors: "Refused to load the image '`data:image/gif;base64,(...)`'". The main culprit appears to be the spinner gif. It's absence is no issue to us.
We would like to disable data:-sources in ng2-pdf-viewer to avoid these errors.

**Comment by stephanrauh** [comment]
The spinner GIF is defined in CSS, so you can override it. This is the standard definition:
```css
.pdfViewer .page .loadingIcon {
    position: absolute;
    display: block;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    background: url(images/loading-icon.gif) center no-repeat;
```
