### ISSUE TITLE
Central Zoom and Pan Feature

### ISSUE THREAD

**Issue by princ09** [VadimDez/ng2-pdf-viewer#674]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```
when zoomed, pdf zoom from top left corner but what I need/required is a zoom from central. also want users to move around(pan) the pdf instead of scrolling it.

**Comment by Helias** [comment]
implemented in https://github.com/VadimDez/ng2-pdf-viewer/pull/1199
