### ISSUE TITLE
Show-all Page is not in order

### ISSUE THREAD

**Issue by arsy29** [VadimDez/ng2-pdf-viewer#68]
I have a url for pdf and had set show-all to true, all pages were displayed but the order is all over the place it started as page1 then page 3 then page2 ......

**Comment by liangwenzhong** [comment]
have u resolve this problem ? 
r u use the retina code?

**Comment by liangwenzhong** [comment]
@VadimDez

**Comment by VadimDez** [comment]
@arsy29 Did you check your CSS, maybe there're some rules that overwrite positioning of div blocks?

**Comment by VadimDez** [comment]
Closing, incomplete information.
