### ISSUE TITLE
offline not work

### ISSUE THREAD

**Issue by martyandreas** [VadimDez/ng2-pdf-viewer#682]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I am trying to display a pdf offline. I proceeded like here in an old bug report: https://github.com/VadimDez/ng2-pdf-viewer/issues/473
when i add the pdf.worker.min.js to scripts, no pdf is displayed anymore(online and offline). No error in console.

script from here: https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.5.207/pdf.worker.min.js

- I insert the js in the angular.js under scripts: "src/assets/js/pdf.worker.min.js"
- run npm install

Package version: 6.3.2
Angular version: 8.2.14

**Comment by zuk38** [comment]
You have to use data url as pdf worker url. 

Example: 
    this.httpClient.get('/assets/libs/pdf.worker.min.js', {
      responseType: 'blob'
    }).subscribe(file => {
      const fileReader = new FileReader();

      fileReader.onload = (e) => {
        (<any> window).pdfWorkerSrc = e.target.result;
      };

      fileReader.readAsDataURL(file);
    });
