### ISSUE TITLE
Page height is wrong with [fit-to-page]="true" and custom page border

### ISSUE THREAD

**Issue by FirstVertex** [VadimDez/ng2-pdf-viewer#684]
## Bug Report

In certain layout, initial page height is too short.
Resizing browser "fixes" page height issue.
When using custom border width, after resizing to "fix" page height, it is still too short.

### Stackblitz Demo of Bug
https://stackblitz.com/edit/ng2-pdf-viewer-3g1vea?file=src/app/app.component.css
When initially visiting the Stackblitz, notice that the height of pages is wrong, with part of page 2 showing.
Resize width of Preview screen, and the page height is "fixed".
As seen in Example 5, when attempting to test with [show-borders]="false", a different issue arises with page height too tall.
When customizing the border size, the width is also slightly off, but it isn't as obvious.  The left/right sides do not touch the edges.  In the Stackblitz they are 6px away (9px - 3px).

Here is another even simpler Stackblitz who has the bug:
https://stackblitz.com/edit/ng2-pdf-viewer-618uxp?file=src%2Fapp%2Fapp.component.ts
This one has hardcoded viewer height of 500px with no fancy Flex container.

### Background
To match our UI, we must tone down the default page border.
When reducing the size from 9px to 3px, there is still height issue after resizing (3rd/4th example in Stackblitz).

I hope there is not hardcoded 9px border in ng2-pdf-viewer.  If there is, can we instead use [offsetWidth](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth) / [offsetHeight](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight) so that border size could be customized by developer?  With proper computation of client height/width including border and margin, I think js option of [show-borders] could be eliminated altogether, and instead developer could suppress or customize default border with just css.

**Comment by hughanderson4** [comment]
The width is also slightly off, but it isn't as obvious.  The left/right sides do not touch the edges, they are 6px away (9px - 3px).
