### ISSUE TITLE
Blank page IOS #449

### ISSUE THREAD

**Issue by yeshchaubey** [VadimDez/ng2-pdf-viewer#685]
IOS 14 is working fine but not in IOS 12.4.9.

Please help!

_Originally posted by @yeshchaubey in https://github.com/VadimDez/ng2-pdf-viewer/issues/449#issuecomment-725895322_

**Comment by VadimDez** [comment]
Any errors or warnings in the console?

**Comment by yeshchaubey** [comment]
Thanks for response. No Any errors or warnings in the console.

**Comment by sheldonpang** [comment]
![image](https://user-images.githubusercontent.com/8623419/100275465-eea21200-2f9a-11eb-89a8-57baec4ee70d.png)

Error on this.loadingTask.promise, onError emit undefined object

**Comment by simeraro1** [comment]
@VadimDez  same for me, not rendering on iOS 12.4.9 on iphone 5s, any news about this? Thanks for help

**Comment by yeshchaubey** [comment]
@VadimDez please help.

**Comment by magorismagor** [comment]
I am interested in a solution too! Thanks.

**Comment by stephanrauh** [comment]
You need to add the `Promise.all` polyfill:

```typescript
if (!Promise.allSettled) {
  Promise.allSettled = function (promises) {
    let mappedPromises = promises.filter(o => !!o).map(p => {
      return p.then(value => {
        return {
          status: 'fulfilled',
          value
        };
      }).catch(reason => {
        return {
          status: 'rejected',
          reason
        };
      });
    });
    return Promise.all(mappedPromises);
  };
}
```

Note you also need to add it to the pdf.worker.min.js file. That, in turn, means you must host it locally so you can modify it.

Plus, make sure you're using `zone.js` 0.10.3`. Older versions don't implement `Promise.all`, and 0.11.3 breaks it again.

**Comment by yeshchaubey** [comment]
@stephanrauh Thanks for your response.

As per your suggestion, i'm unable to resolve this issue and also facing problem to run **ng2-pdf-viewer** on **iPhone 12 version 14.4**

**Comment by ZeroSkill830** [comment]
@VadimDez I have the same issue, the pdf is blank on IOS 12

**Comment by png995** [comment]
This issue still persist. No error logs found on console.

**Comment by innokentiiya-tr** [comment]
Any updates on this issue?
