### ISSUE TITLE
CPS error

### ISSUE THREAD

**Issue by szymonlacki** [VadimDez/ng2-pdf-viewer#686]
Hello, i have got a problem with CSP on production mode. Can someone help me? Best regards.

![image](https://user-images.githubusercontent.com/37595359/99508672-28648e80-2985-11eb-8447-ccceb7ddd86f.png)

**Comment by stephanrauh** [comment]
Download the file pdf.worker.min.js and add it to your project, e.g. to the `assets` folder. If you don't care about performance, the easiest approach is to include it in the `scripts` section of the `angular.json`. However, adding this line to your app.module.ts should to the trick, too:

```typescript
(window as any).pdfWorkerSrc = '/assets/pdf.worker.min.js'
```

**Comment by szymonlacki** [comment]
Yeah, I have already added locally in a similar way. Thank you and best regards.

**Comment by micarsls** [comment]
Is this issue not yet fixed at the latest version? We still need to import it locally? As I am experiencing this issue at version 9.1.5
