### ISSUE TITLE
Some functionality does not work if src is given as Uint8Array

### ISSUE THREAD

**Issue by risajef** [VadimDez/ng2-pdf-viewer#687]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I figured out that a some functionality does not work if the `[src]` parameter is given as Uint8Array.
I tried to do search and it throws:
```TypeError: Cannot read property 'getPage' of null```

In my setup I have a back-end service serving the pdf.
If I store the bytes in the front-end and give them to the `pdf-viewer [src]` afterwards it can display the pdf. But search does not work then.
If I link the pdf directly in the `[src]` argument search does work.

But I want the pdf as bytes because I have to add and remove annotations in the pdf.

**Comment by hughanderson4** [comment]
Bump!
