### ISSUE TITLE
Need to load all pages of pdf like in 5.3.1

### ISSUE THREAD

**Issue by dmdshubham** [VadimDez/ng2-pdf-viewer#696]
Hello, I need all pages load at once, like it does earlier in 5.3.1 version. issue with earlier version was, page change were not happen at scrolling the pdf or we could not jump over the page.

**Comment by VadimDez** [comment]
Rendering all pages at one is resource consuming and might freeze your page or even freeze your browser completely. Therefore this won't be considered nor implemented.
