### ISSUE TITLE
Make Demo mobile friendly

### ISSUE THREAD

**Issue by VadimDez** [VadimDez/ng2-pdf-viewer#697]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [x] Documentation issue or request
```
At the moment demo is completely not mobile friendly and not usable on mobile. Would be nice to have a desktop and mobile friendly demo at the same time.

**Comment by Kuldeepsharma2002** [comment]
Good

**Comment by srizzon** [comment]
@VadimDez can I get this issue or you're working on it?

**Comment by VadimDez** [comment]
@srizzon that would be awesome if you could make it mobile friendly 👍

**Comment by denisenanni** [comment]
Hi, I see there are some UI issues, can I work on them?
![pdf-viewer](https://user-images.githubusercontent.com/28294992/169663222-03067bff-9bc6-4596-9c90-d007f8a0a3af.png)

**Comment by VadimDez** [comment]
@denisenanni Sure thing!
