### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by seopei** [VadimDez/ng2-pdf-viewer#699]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```
Could you make a new release please?

**Comment by VadimDez** [comment]
There are few things to fix before i can make a new release. Once the issue related to #688 that breaks the build is fixed - i'll make a new release.
