### ISSUE TITLE
ng2-pdf-viewer data-page-number option absent

### ISSUE THREAD

**Issue by CHOUAIAR** [VadimDez/ng2-pdf-viewer#70]
Hello @VadimDez,

I'm using the ng2-pdf-viewer to display pdf files in thumbnails and I'm facing an issue with the options like data-page-number, div.pdfViewer.removePageBorders. Especially that in this example https://vadimdez.github.io/ng2-pdf-viewer/ its absent but in the code that I got from the ripo https://github.com/VadimDez/ng2-pdf-viewer it's present.

![git error](https://cloud.githubusercontent.com/assets/13586821/24288509/f3310c9e-107d-11e7-8af1-adca39c85830.jpg)

![components](https://cloud.githubusercontent.com/assets/13586821/24290349/ee72eb9e-1084-11e7-86c1-5cee7bc0fb07.jpg)

My question is what should I do to have this options in the div?
Thank you in advance.

**Comment by VadimDez** [comment]
Hi, the master contains different version from 1.0.2, that will be published later, probably 2.0.0.

**Comment by CHOUAIAR** [comment]
Great thanks for the answer, do you have any idea when this version will be published?

**Comment by VadimDez** [comment]
As soon as i will have time to fix few things

**Comment by VadimDez** [comment]
Added `data-page-number` since version `1.1.4`.
