### ISSUE TITLE
[external-link-target] seems to be broken

### ISSUE THREAD

**Issue by stephanrauh** [VadimDez/ng2-pdf-viewer#701]
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

I didn't manage to use the attribute `[external-link-target]` at https://pdfviewer.net/ng2-pdf-viewer/links. It's simply ignored. I tried to dig into the issue. The attributes sets `PDFJS.externalLinkTarget` - but current versions of pdf.js simply ignore that attribute.

Has the API of pdf.js changed since the initial implementation? Or is the error on my side?

Source codes are here: https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/master/src/app/ng2-pdf-viewer/ng2-links-call-angular

**Comment by VadimDez** [comment]
I think PDFJS implementation is changed, let me verify this

**Comment by VadimDez** [comment]
So this is how to set `external link target`: https://github.com/mozilla/pdf.js/issues/7779#issuecomment-635051650 and this is a LinkTarget enum: https://github.com/mozilla/pdf.js/blob/0629a8f553a600c834a88408cef348aade35c800/src/display/display_utils.js#L390-L396
