### ISSUE TITLE
Zooming on other than first page does not work as expected.

### ISSUE THREAD

**Issue by risajef** [VadimDez/ng2-pdf-viewer#703]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
When going to page 3 on [https://vadimdez.github.io/ng2-pdf-viewer/](https://vadimdez.github.io/ng2-pdf-viewer/) and then I zoom in continuously I end up at page one.
On [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html) it works as expected.

**Comment by MinadorCH** [comment]
We also have encountered this problem: If the zoom is set on another page than the first one the current page changes dramatically. It even gets worse the closer /farther away we are to the document. (zoom << 1 or zoom >> than 1)

**Comment by MinadorCH** [comment]
For everyone who has a similar problem: A quick fix for this problem is to set the `stick-to-page` variable to `true`. This results in the zoom functionality to stick to the closest page.
