### ISSUE TITLE
Get currentPageNumber()

### ISSUE THREAD

**Issue by IbrahimGerbiqi** [VadimDez/ng2-pdf-viewer#706]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ X] Feature request
- [ ] Documentation issue or request
```
For a couple of days, i was working with PDF Viewer and I hade a pretty good success while making functions that I needed for my task but within my task todo list i hade to make that pdf will serve only 5 pages at a time and I should know user on which page it is but I could figure it out how to get a current page number.

Is there any function or any way that i can get a currentPageNumber that is being shown to the user not rendered pages but the exact page number that is being shown on user?

**Comment by IbrahimGerbiqi** [comment]
I found a solution i was supposed to use **pagechanging** and on ts 

HTML
`(pagechanging)="pagechanging($event)"`

TS
```
pagechanging(e: CustomEvent){
    this.page = e.pageNumber; // the page variable
}
```

Credits: https://stackoverflow.com/a/62206601/9801505

**Comment by ajai06** [comment]
(pagechanging) event not firing
