### ISSUE TITLE
ng2-pdf-viewer - pdf not centered and 100% width

### ISSUE THREAD

**Issue by EventfulG** [VadimDez/ng2-pdf-viewer#71]
Hello,
I'm using the ng2-pdf-viewer to display pdf files in my app (builded with ionic2) but are some things i can't figure it out. 

1. from where I should download the files for this project https://vi-dot.github.io/ng2-pdf-viewer/
The files I have  downloaded from here https://github.com/VadimDez/ng2-pdf-viewer does not include the last 3 options showed in the demo page (enable page border, enhance text selection, render hyperlinks) and the pdf does not have the border.

2. I didn't succeed in loading my .pdf file centered and 100% width (i see only a part width left indent) and i don't know what i'm doing wrong. I attach a preview. 
![17555144_1799323373720230_983495885_n](https://cloud.githubusercontent.com/assets/26686110/24330039/9d9a3790-121e-11e7-94bf-aa85cb033ef2.png)

3. in this case is there a way to add a horizontal/vertical scroll to see the entire pdf

4. i don't know if it has to do or my mobile phone but after installing my app, when i try to zoom in/zoom out or go to next page, the .pdf is loading slowly.  

Thank you in advance.

**Comment by VadimDez** [comment]
Demo page for the project is here - https://vadimdez.github.io/ng2-pdf-viewer/

It's your job to center it, by adding correct CSS rules to your wrapper element around ng2-pdf-viewer. Example:
```html
<div>
  <ng2-df-viewer ....></ng2-pdf-viewer>
</div>
```
`<div>` in this case should have CSS rules for width/max-width and center it's child elements.

**Comment by EventfulG** [comment]
Thank you for your quick answer. 

Following your suggestion i added some css. This solved some issues less  the one that concerns  the .pdf to be "fit to window" - to use all the space available on horizontal. Is it possible to achive this using just css or there are other settings/ code to write?

I noticed the differences between the demo (from https://vadimdez.github.io/ng2-pdf-viewer/) and more complete version (from https://vi-dot.github.io/ng2-pdf-viewer/). Is there a way to download the second component version?

Thank you.

**Comment by VadimDez** [comment]
Just CSS is fine.
The features from second example are already merged with this repo. Will be published under 2.0.0.
