### ISSUE TITLE
How to get the current page number

### ISSUE THREAD

**Issue by ajai06** [VadimDez/ng2-pdf-viewer#710]
Angular 6,

how to get the current page number?

**Comment by mpellerin42** [comment]
Hi, I'm trying this lib to see if it fits our needs and I have the same question. In your example, you show a presentation use case where you get the total page number on load and manage manually the current page number. But there is another common use case which doesn't seem to be covered: showing all pages with the page index in an external toolbar, so you know you're in page `3 of 21` for example, with the current page number updated automatically while scrolling.
