### ISSUE TITLE
Several errors while building app with --prod flag

### ISSUE THREAD

**Issue by dionisioleonardo** [VadimDez/ng2-pdf-viewer#715]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
When I try to build my app for production, I get the following errors:
![image](https://user-images.githubusercontent.com/28509696/105785872-b13a1080-5f5a-11eb-9800-e970838d085d.png)

I'm using the 6.3.2 version.

I'm importing it on a shared module, and exporting it to the other modules:
![image](https://user-images.githubusercontent.com/28509696/105786154-45a47300-5f5b-11eb-943f-8d11766d9e60.png)

Even if I don't use it on any component/page, I get the error just from importing it.

Weird things:

- It was working at least until last week (last successful deploy);
- It works on Windows machines, but I get these error in Linux environments;

Searched a lot and got nothing.

Any help?

Thanks in advance.

**Comment by markabrahams** [comment]
I got this error today as well.

It looks like the "latest" version of the pdfjs-dist npm went from version 2.5.207 to 2.6.347 a day ago.

Setting pdfjs-dist back to the previous version fixed the errors for me i.e. add this line to your package.json dependencies:
   `"pdfjs-dist": "2.5.207",`

**Comment by finzero** [comment]
> I got this error today as well.
> 
> It looks like the "latest" version of the pdfjs-dist npm went from version 2.5.207 to 2.6.347 a day ago.
> 
> Setting pdfjs-dist back to the previous version fixed the errors for me i.e. add this line to your package.json dependencies:
> `"pdfjs-dist": "2.5.207",`

you're my savior thank you..

**Comment by danzrou** [comment]
Same here
@markabrahams unfortunately that doesn't solve it because it still installed `pdfjs-dist` under `ng2-pdf-viewer` separately :-(

**Comment by hafizihamid** [comment]
> Same here
> @markabrahams unfortunately that doesn't solve it because it still installed `pdfjs-dist` under `ng2-pdf-viewer` separately

I only found `pdfjs-dist` on package-lock.json

**Comment by danzrou** [comment]
well, its probably a difference between how yarn and npm resolve dependencies.
Using npm actually did not add an additional `pdfjs-dist` dependency under `ng2-pdf-viewer`, however, yarn did

**Comment by hafizihamid** [comment]
> well, its probably a difference between how yarn and npm resolve dependencies.
> Using npm actually did not add an additional `pdfjs-dist` dependency under `ng2-pdf-viewer`, however, yarn did

noted try to installed ```pdfjs-dist``` separately, got error on importing ```ng2-pdf-viewer` as ```Cannot find module 'ng2-pdf-viewer' or its corresponding type declarations.```

**Comment by danzrou** [comment]
the real solution here would be moving them from `dependencies` into `peerDependencies` and exact version

**Comment by almothafar** [comment]
I got the same issue, adding `"pdfjs-dist": "2.5.207",` to package.json with npm solved my issue, what I did exactly is I added this, remove the `package-lock.json` file and `node_modules` folder, then I did run `npm i`, that did fix my issue.

**Comment by hafizihamid** [comment]
> I got the same issue, adding `"pdfjs-dist": "2.5.207",` to package.json with npm solved my issue, what I did exactly is I added this, remove the `package-lock.json` file and `node_modules` folder, then I did run `npm i`, that did fix my issue.

tried, but still got error on importing ```PdfViewerModule```, as ```Cannot find module 'ng2-pdf-viewer' or its corresponding type declarations.ts(2307)```

**Comment by almothafar** [comment]
@hafizihamid  just like wat documentations says:
```typescript
import { PdfViewerModule } from 'ng2-pdf-viewer';
```
![image](https://user-images.githubusercontent.com/13887564/105844719-55b36580-5fe2-11eb-8f46-c28a67dca2b7.png)

**Comment by sandu2d** [comment]
@danzrou Did you find a solution for yarn?
Is it possible to fix depencies in a project with yarn?

In yarn.lock I have:
```
ng2-pdf-viewer@^6.3.2:
  version "6.3.2"
  resolved "https://registry.yarnpkg.com/ng2-pdf-viewer/-/ng2-pdf-viewer-6.3.2.tgz#07189207893ceb4c086e9b6ebd74fdbb31982af1"
  integrity sha512-H2tBhDd+Lq6CUzK2g54HsCcZDR2wTn1sDjYqKY3yF0Ydasl2R5ppCKynZBU/zge4EKvmHglJI120FbQMpJKDYQ==
  dependencies:
    "@types/pdfjs-dist" "^2.1.4"
    pdfjs-dist "^2.4.456"
    tslib "^1.10.0"
```

And it is installing:
```
pdfjs-dist@^2.4.456:
  version "2.6.347"
  resolved "https://registry.yarnpkg.com/pdfjs-dist/-/pdfjs-dist-2.6.347.tgz#f257ed66e83be900cd0fd28524a2187fb9e25cd5"
  integrity sha512-QC+h7hG2su9v/nU1wEI3SnpPIrqJODL7GTDFvR74ANKGq1AFJW16PH8VWnhpiTi9YcLSFV9xLeWSgq+ckHLdVQ==
```

**Comment by almothafar** [comment]
@sandu2d in yarn I think there is something called `"resolutions"`: 
Try:
```json
"resolutions": {
    "pdfjs-dist": "2.5.207"
  }
```

Docs: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by dionisioleonardo** [comment]
> I got this error today as well.
> 
> It looks like the "latest" version of the pdfjs-dist npm went from version 2.5.207 to 2.6.347 a day ago.
> 
> Setting pdfjs-dist back to the previous version fixed the errors for me i.e. add this line to your package.json dependencies:
> `"pdfjs-dist": "2.5.207",`

This! This solves the issue when using npm. Thank you very much @markabrahams 

But it would be interesting if ng2-pdf-viewer solved it out of the box.
I'm guessing if the correct version is set on the package.json file it would fix it.

**Comment by sandu2d** [comment]
@almothafar Yes, it worked. Thank you!

**Comment by farhanramli-work** [comment]
Hi, I have folllowed all the instruction which I have done

importing it on a shared module
```import { PdfViewerModule } from 'ng2-pdf-viewer'```

```
@NgModule({
  declarations: [
    AdminComponent,
    DashboardComponent,
    CreateRoleComponent,
    RoleListingComponent,
    UpdateRoleComponent,
    CreateUserComponent,
    UpdateUserComponent,
    UserListingComponent,
    AddNewLocationComponent,
    EditLocationComponent,
    OffDayComponent,
    NewHolidayComponent,
    ApplicantComponent,
    AppointmentListComponent,
    EditAppointmentComponent,
    ReportComponent,
    LocationComponent,
    StaffComponent,
    AddStaffComponent,
    EditStaffComponent,
    ResultComponent,
    ResultListComponent,
  ],
  imports: [
    CommonModule,
    AdminRoutingModule,
    SharedModule,
    ReactiveFormsModule,
    FullCalendarModule,
    FormsModule,
    PdfViewerModule,
  ],
})
export class AdminModule {}
```

**Comment by farhanramli-work** [comment]
Hi, I have folllowed all the instruction in which I have done

importing this code on a shared module

```import { PdfViewerModule } from 'ng2-pdf-viewer'```

```
@NgModule({
  declarations: [
    AdminComponent,
    DashboardComponent,
    CreateRoleComponent,
    RoleListingComponent,
    UpdateRoleComponent,
    CreateUserComponent,
    UpdateUserComponent,
    UserListingComponent,
    AddNewLocationComponent,
    EditLocationComponent,
    OffDayComponent,
    NewHolidayComponent,
    ApplicantComponent,
    AppointmentListComponent,
    EditAppointmentComponent,
    ReportComponent,
    LocationComponent,
    StaffComponent,
    AddStaffComponent,
    EditStaffComponent,
    ResultComponent,
    ResultListComponent,
  ],
  imports: [
    CommonModule,
    AdminRoutingModule,
    SharedModule,
    ReactiveFormsModule,
    FullCalendarModule,
    FormsModule,
    PdfViewerModule,
  ],
})
export class AdminModule {}
```

I have 
- deleted package-lock.son file
- deleted entire node_modules folder
- reinstall npm

on my local upon running ```ng build --prod``` the warning message as below appear

![image](https://user-images.githubusercontent.com/78056691/105923935-3404bd80-6078-11eb-8579-ba869fcf357d.png)

don't think as a big issue as it is just warning

I am deploying this code on gitlab pipeline, and upon building pipeline, error as below appear

![image](https://user-images.githubusercontent.com/78056691/105924074-8940cf00-6078-11eb-9d5f-8ccf54049c69.png)

I am not sure what seems to be the problem during this build pipeline as my local seems to be working fine, 

kindly help

**Comment by almothafar** [comment]
@farhanramli-work 
Before you do your steps, which what exactly I did, did you specify or "force" package `pdfjs-dist` to version 2.5.207? 
```console
npm install pdfjs-dist@2.5.207 --save
```

You should be having this (`"pdfjs-dist": "2.5.207"`) in your dependencies in package.json.

**Comment by farhanramli-work** [comment]
@almothafar 

already done the given steps

**Comment by brainwind-software** [comment]
@farhanramli-work 
You added:
>     "pdfjs-dist": "^2.5.207",
but you have to add:
>     "pdfjs-dist": "2.5.207",

And I would add it before 'ng2-pdf-viewer'

**Comment by almothafar** [comment]
@farhanramli-work Oh I didn't see the package.json file you posted, but yes as what @brainwind-software said, you need to remove `^`, this will install the latest of 2.x so it will install 2.6.347, the problem in 2.6.347 and you need 2.5.207 to fix it.

**Comment by Rahul-kalsha** [comment]
I got the same issue, Need to add a dependencies library, and the issue will be fixed for me.
`"@types/pdfjs-dist": "~2.0.1",
"ng2-pdf-viewer": "^6.3.2"`

OR else decrease **ng2-pdf-viewer** version number  and add **pdfjs-dist**
`"pdfjs-dist": "~2.5.207",
"ng2-pdf-viewer": "~5.3.4",`

**Comment by rahul-network** [comment]
@Rahul-kalsha The fix you have provided worked properly. Thanks for saving our lot of time.

**Comment by sraza295** [comment]
@markabrahams Thanks bro you saved my day

**Comment by narendrasinghrathore** [comment]
> I got the same issue, Need to add a dependencies library, and the issue will be fixed for me.
> `"@types/pdfjs-dist": "~2.0.1", "ng2-pdf-viewer": "^6.3.2"`
> 
> OR else decrease **ng2-pdf-viewer** version number and add **pdfjs-dist**
> `"pdfjs-dist": "~2.5.207", "ng2-pdf-viewer": "~5.3.4",`

Not working.

**Comment by webkhushboo** [comment]
Not working , I am facing the issue again

**Comment by sraza295** [comment]
Follow above steps, your issue will be resolved

**Comment by webkhushboo** [comment]
`"pdfjs-dist": "~2.5.207", "ng2-pdf-viewer": "~5.3.4" `This works for me

**Comment by sraza295** [comment]
Good.
This also worked for me

**Comment by chiragbhadani09** [comment]
> I got the same issue, Need to add a dependencies library, and the issue will be fixed for me.
> `"@types/pdfjs-dist": "~2.0.1", "ng2-pdf-viewer": "^6.3.2"`
> 
> OR else decrease **ng2-pdf-viewer** version number and add **pdfjs-dist**
> `"pdfjs-dist": "~2.5.207", "ng2-pdf-viewer": "~5.3.4",`

@Rahul-kalsha  You are a great visions thanks boy i love you.

**Comment by VadimDez** [comment]
Fixed in version [6.4.0](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/6.4.0)

**Comment by AdrianMartinezCode** [comment]
I tried the version 6.4.2 of ng2-pdf-viewer with angular version 8.2.14.
In chrome it works fine, but when i try at firefox the error that throw me is about of zone.js and multiple messages only importing the module in any own module at project.
I solved trying version by version of ng2-pdf-viewer and pdfjs-dist, the next versions it works for me at chrome and firefox:
`"ng2-pdf-viewer": "^5.3.4",` and `"pdfjs-dist": "^2.5.207",`
If i try only installing the ng2-pdf-viewer and automaticly this package install the dependencies will not work because the package install the pdfjs-dist of version that it not compatible with my typescript, you MUST install every package and version manually.

**Comment by fsalazarsch** [comment]
> I got the same issue, adding `"pdfjs-dist": "2.5.207",` to package.json with npm solved my issue, what I did exactly is I added this and removed the `package-lock.json` file and `node_modules` folder, then I did run `npm i`, that did fix my issue.

made this and still is laubching that error,

**Comment by fsalazarsch** [comment]
> brainwind

Man, where is your adress to send you a six pack, you're my savior

**Comment by Andrea4007** [comment]
Como lo implementaste en el app.module.ts?

> AdrianMartinezCódigo

**Comment by vinaytalluri4u** [comment]
Getting the following error while running npm run test  
● Test suite failed to run

    Cannot find module 'ng2-pdfjs-viewer' from 'src/app/shared/shared.module.ts'

    Require stack:
      src/app/shared/shared.module.ts
      src/app/pages/administration/users/edit-user/edit-user.component.spec.ts

      138 | import {OktaAuthenticationService} from "./services/authentications/okta-authentication.service";
      139 | import {DocusignConfigService} from "../domain/docusign-config/docusign-config.service";
    > 140 | import { PdfJsViewerModule } from 'ng2-pdfjs-viewer';
          | ^
      141 |
      142 |
      143 |

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (src/app/shared/shared.module.ts:140:1)
