### ISSUE TITLE
Update to Angular 4 don't work with this library

### ISSUE THREAD

**Issue by brasycad** [VadimDez/ng2-pdf-viewer#72]
Some days ago, Angular launch new version 4.  Its necesary update the library because new compiler error appear.
Thank you in advance

**Comment by VadimDez** [comment]
Just tried myself didn't see any error.
Could you provide steps how to reproduce it?

**Comment by brasycad** [comment]
Hi  Valdim:

here you are the angular 4 error—>

'ERROR in /Users/josemanuelvillaralarcon/GitHub/brasycad-imoveis/node_modules/ng2-pdf-viewer/dist/pdf-viewer.component.d.ts (3,49): Cannot extend an interface 'OnInit'. Did you mean 'implements’?’

thanks you in advance




GERENTE
José Manuel Villar Alarcon
jmvalarcon@brasycad.com <mailto:jmvalarcon@brasycad.com>
+55 83 98181-8666
www.brasycad.com <http://www.brasycad.com/>

**Comment by brasycad** [comment]
One more issue:

I fix previous error and the get new error like this:

pdf-viewer.component.js:5Uncaught TypeError: Cannot read property 'prototype' of undefined
    at __extends (pdf-viewer.component.js:5)
    at pdf-viewer.component.js:10
    at Object.__WEBPACK_AMD_DEFINE_FACTORY__ (pdf-viewer.component.js:242)
    at __webpack_require__ (bootstrap 664fdf9…:52)
    at Object.<anonymous> (index.js:2)
    at __webpack_require__ (bootstrap 664fdf9…:52)
    at Object.719 (app.component.ts:7)
    at __webpack_require__ (bootstrap 664fdf9…:52)
    at Object.677 (src async:7)
    at __webpack_require__ (bootstrap 664fdf9…:52)
__extends @ pdf-viewer.component.js:5
(anonymous) @ pdf-viewer.component.js:10
__WEBPACK_AMD_DEFINE_FACTORY__ @ pdf-viewer.component.js:242
__webpack_require__ @ bootstrap 664fdf9…:52
(anonymous) @ index.js:2
__webpack_require__ @ bootstrap 664fdf9…:52
719 @ app.component.ts:7
__webpack_require__ @ bootstrap 664fdf9…:52
677 @ src async:7
__webpack_require__ @ bootstrap 664fdf9…:52
1586 @ main.bundle.js:1110
__webpack_require__ @ bootstrap 664fdf9…:52
webpackJsonpCallback @ bootstrap 664fdf9…:23
(anonymous) @ main.bundle.js:1


thanks again

> Inicio del mensaje reenviado:
> 
> De: "José Manuel Villar alarcón" <jmvalarcon@gmail.com>
> Asunto: Re: [VadimDez/ng2-pdf-viewer] Update to Angular 4 don't work with this library (#72)
> Fecha: 30 de marzo de 2017, 8:26:19 GMT-3
> Para: VadimDez/ng2-pdf-viewer <reply@reply.github.com>
> 
> Hi  Valdim:
> 
> here you are the angular 4 error—>
> 
> 'ERROR in /Users/josemanuelvillaralarcon/GitHub/brasycad-imoveis/node_modules/ng2-pdf-viewer/dist/pdf-viewer.component.d.ts (3,49): Cannot extend an interface 'OnInit'. Did you mean 'implements’?’
> 
> thanks you in advance
> 
> 
> 
> 
> GERENTE
> José Manuel Villar Alarcon
> jmvalarcon@brasycad.com <mailto:jmvalarcon@brasycad.com>
> +55 83 98181-8666
> www.brasycad.com <http://www.brasycad.com/>

**Comment by VadimDez** [comment]
@brasycad could you tell me - which version of `ng2-pdf-viewer` are you using ?

**Comment by brasycad** [comment]
Hi vadim. 
Version ng2-pdf-viewer@1.0.2, I guess the last..

**Comment by CHOUAIAR** [comment]
Hello all,
I'm using Angular 4.0.0 and its working for me the only problem Im having is 

Error: Uncaught (in promise): TypeError: Cannot read property 'getDirection' of undefined and its seems like its caused by 

document.getElementsByTagName('html')[0].dir = _ui_utils.mozL10n.getDirection();

Kind regards.

**Comment by sireneweb** [comment]
we have the same problem, we use webpack with angular 4.0

**Comment by Irocode** [comment]
i have the same error:
pdf-viewer.component.js:5Uncaught TypeError: Cannot read property 'prototype' of undefined
    at __extends (pdf-viewer.component.js:5)
    at pdf-viewer.component.js:10

**Comment by janneromell** [comment]
We have a problem that ngAnimate (using Angular 4) stops working after having ng2-pdf-viewer as a dependency. Could it be that the library overwrite another npm package that angular animate is dependent on. Will try to change declared order in package.json to see if that helps.

**Comment by VadimDez** [comment]
Created new release `1.1.0`.
