### ISSUE TITLE
new version with angular universal 11

### ISSUE THREAD

**Issue by mbabaei0** [VadimDez/ng2-pdf-viewer#727]
##### Bug Report or Feature Request (mark with an `x`)
```

- [ ] Bug report

/home/moniaz/testwebsites/server/server/main.js:3221
document.webL10n = function (window, document, undefined) {
^
ReferenceError: document is not defined
    at Object.<anonymous> (/home/moniaz/testwebsites/server/server/main.js:3221:1)
    at __w_pdfjs_require__ (/home/moniaz/testwebsites/server/server/main.js:175:30)

```

**Comment by VadimDez** [comment]
Thank you for feedback, I'll check.

**Comment by kevinvarela** [comment]
I have the same problem. When will the solution be ?

**Comment by kevinvarela** [comment]
In my case is with Angular Universal 9
I think it is a general error when you use server side rendering. 
When Angular Universal in Node.js side use window or document variables. It is when produced the error

**Comment by mbabaei0** [comment]
@kevinvarela for now you can just change package.json  :
`"ng2-pdf-viewer": "^6.3.2" ` and `"pdfjs-dist": "^2.5.207" ` to:
`"pdfjs-dist": "2.5.207" ` and `"ng2-pdf-viewer": "6.3.2"  `

**Comment by kevinvarela** [comment]
@mbabaei0 Thank for your help. It works perfect.

**Comment by markhughes** [comment]
Affects Angular Universal >= 8 from my testing.  Replicated 6.4.0 

The issue seems to come and go a lot. Try the solutions here: 

- https://github.com/VadimDez/ng2-pdf-viewer/issues/173
- https://github.com/VadimDez/ng2-pdf-viewer/issues/636

**Comment by markhughes** [comment]
@VadimDez here is what is causing the issue:

https://github.com/VadimDez/ng2-pdf-viewer/compare/6.3.2...6.4.0#diff-33fbb91559706e83ab83a68031ea011b1d9c65d4ba490423946b7d74b32b11d0R26

**Comment by markhughes** [comment]
the link didn't work, sorry, screenshot:

![image](https://user-images.githubusercontent.com/1357323/110894692-69294e80-834c-11eb-9b30-11271cdeb999.png)

**Comment by VadimDez** [comment]
@markhughes thanks, I was already kinda sure where the problem is, but not sure how to fix it yet 😔

**Comment by mlauinger** [comment]
`"pdfjs-dist": "2.5.207"` does not work for me with `"ng2-pdf-viewer": "6.3.2"` when using the `pdf.worker.js` from the dist-package as `pdfWorkerSrc`.
There are no errors, but the PDF just wont show.

**Comment by markhughes** [comment]
@mlauinger try setting up this: https://github.com/fgnass/domino

**Comment by markhughes** [comment]
quick resource to help you: https://dev.to/danywalls/how-keep-your-document-object-in-angular-ssr-with-domino-package-2b9e

**Comment by jakubkeller** [comment]
Setting up with domino doesn't work for this particular issue either.

**Comment by markhughes** [comment]
@jakubkeller can you show your implementation? This worked for me.

**Comment by jakubkeller** [comment]
@markhughes 

server.ts
```js
import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';
import { readFileSync } from 'fs';
import * as domino from 'domino';

import { APP_BASE_HREF } from '@angular/common';

// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/browser');
  const indexView = 'index';
  const template = readFileSync(join(distFolder, 'index.html')).toString();

  const wnd: any = domino.createWindow(template);
  wnd.Object = Object;
  wnd.Math = Math;
  global['window'] = wnd;
  global['document'] = wnd.document;
  global['branch'] = null;
  global['object'] = wnd.object;
  global['Event'] = wnd.Event;
  global['KeyboardEvent'] = window.KeyboardEvent;
  wnd.requestAnimationFrame = () => {};
// ...

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

import 'zone.js/dist/zone-node';
import { AppServerModule } from './src/main.server';

export * from './src/main.server';
```
shared.module.ts
```js
// ...
import { PdfViewerModule } from 'ng2-pdf-viewer';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    NgSelectModule,
    NgbModule,
    NgxMaskModule,
    NgxPaginationModule,
    ReactiveFormsModule,
    RouterModule,
    UiSwitchModule,
    PdfViewerModule
// ...
})
export class SharedModule { }
```

**Comment by markhughes** [comment]
@jakubkeller but what is your error? judging by this, `document` is defined globally?

**Comment by jakubkeller** [comment]
@markhughes Sorry it took me a bit. Got the entire error stack as well, hope it helps.

Otherwise, the application works when I comment out just the `PdfViewerModule`...

```
...\dist\server\main.js:102787
document.webL10n = function (window, document, undefined) {
^

ReferenceError: document is not defined
    at Object.<anonymous> (C:\Users\jakeller\Projects\Transend\dist\server\main.js:102787:1)
    at __w_pdfjs_require__ (C:\Users\jakeller\Projects\Transend\dist\server\main.js:99741:30)
    at Object.<anonymous> (C:\Users\jakeller\Projects\Transend\dist\server\main.js:102625:1)
    at __w_pdfjs_require__ (C:\Users\jakeller\Projects\Transend\dist\server\main.js:99741:30)
    at Object.<anonymous> (C:\Users\jakeller\Projects\Transend\dist\server\main.js:99925:20)
    at __w_pdfjs_require__ (C:\Users\jakeller\Projects\Transend\dist\server\main.js:99741:30)
    at C:\Users\jakeller\Projects\Transend\dist\server\main.js:99805:18
    at C:\Users\jakeller\Projects\Transend\dist\server\main.js:99808:10
    at webpackUniversalModuleDefinition (C:\Users\jakeller\Projects\Transend\dist\server\main.js:99719:20)
    at Object.BPYd (C:\Users\jakeller\Projects\Transend\dist\server\main.js:99721:3)

A server error has occurred.
node exited with 1 code.
```

**Comment by jakubkeller** [comment]
@markhughes Sorry it took me a bit. Got the entire error stack as well, hope it helps.

Otherwise, the application works when I comment out just the `PdfViewerModule`...

```
C:\Users\...\...\...\dist\server\main.js:102787
document.webL10n = function (window, document, undefined) {
^

ReferenceError: document is not defined
    at Object.<anonymous> (C:\Users\...\...\...\dist\server\main.js:102787:1)
    at __w_pdfjs_require__ (C:\Users\...\...\...\dist\server\main.js:99741:30)
    at Object.<anonymous> (C:\Users\...\...\...\dist\server\main.js:102625:1)
    at __w_pdfjs_require__ (C:\Users\...\...\...\dist\server\main.js:99741:30)
    at Object.<anonymous> (C:\Users\...\...\...\dist\server\main.js:99925:20)
    at __w_pdfjs_require__ (C:\Users\...\...\...\dist\server\main.js:99741:30)
    at C:\Users\...\...\...\dist\server\main.js:99805:18
    at C:\Users\...\...\...\dist\server\main.js:99808:10
    at webpackUniversalModuleDefinition (C:\Users\...\...\...\dist\server\main.js:99719:20)
    at Object.BPYd (C:\Users\...\...\...\dist\server\main.js:99721:3)

A server error has occurred.
node exited with 1 code.
```

**Comment by jakubkeller** [comment]
@markhughes any traction on this?

**Comment by markhughes** [comment]
@jakubkeller not sure, you don't have document defined early enough or in the right cirumstances.

```
ReferenceError: document is not defined
```

Try defining it earlier.

**Comment by VadimDez** [comment]
@arturovt didn't you have some ideas on how to make so that it also works also with `SSR`?

**Comment by arturovt** [comment]
Yeah, sure, I have some idea and will try to implement it, not promising that it'll be successful :smile:

**Comment by markhughes** [comment]
Not stale, still an issue

**Comment by captainboroda** [comment]
Hi guys, any update on that issue ?

**Comment by markhughes** [comment]
Not stale

**Comment by arturgorowski** [comment]
Hi, any update on that issue?

**Comment by remy33** [comment]
I have struggled with it a while ago and stomped back since I was upgrading this library among everything during code maintaining.
IIRC the workaround is to use those exact versions in package.json, ( as depencies, not devDepencies!)
`        "pdfjs-dist": "2.5.207",
        "ng2-pdf-viewer": "6.3.2",
        "@types/pdfjs-dist": "2.1.7"
`
And add:
```
    const win = domino.createWindow(templetes[Modes.DESKTOP]);
    win.requestAnimationFrame = () => { }; //workaround for PdfViewerModule
    global['window'] = win;
    global['document'] = win.document;
```
To your server.ts

Cheers.

**Comment by markhughes** [comment]
Not stale

**Comment by ergaibiYasin** [comment]
> @markhughes Sorry it took me a bit. Got the entire error stack as well, hope it helps.
> 
> Otherwise, the application works when I comment out just the `PdfViewerModule`...
> 
> ```
> C:\Users\...\...\...\dist\server\main.js:102787
> document.webL10n = function (window, document, undefined) {
> ^
> 
> ReferenceError: document is not defined
>     at Object.<anonymous> (C:\Users\...\...\...\dist\server\main.js:102787:1)
>     at __w_pdfjs_require__ (C:\Users\...\...\...\dist\server\main.js:99741:30)
>     at Object.<anonymous> (C:\Users\...\...\...\dist\server\main.js:102625:1)
>     at __w_pdfjs_require__ (C:\Users\...\...\...\dist\server\main.js:99741:30)
>     at Object.<anonymous> (C:\Users\...\...\...\dist\server\main.js:99925:20)
>     at __w_pdfjs_require__ (C:\Users\...\...\...\dist\server\main.js:99741:30)
>     at C:\Users\...\...\...\dist\server\main.js:99805:18
>     at C:\Users\...\...\...\dist\server\main.js:99808:10
>     at webpackUniversalModuleDefinition (C:\Users\...\...\...\dist\server\main.js:99719:20)
>     at Object.BPYd (C:\Users\...\...\...\dist\server\main.js:99721:3)
> 
> A server error has occurred.
> node exited with 1 code.
> ```

@jakubkeller any solution for this??

**Comment by remy33** [comment]
> > @markhughes Sorry it took me a bit. Got the entire error stack as well, hope it helps.
> > Otherwise, the application works when I comment out just the `PdfViewerModule`...
> > ```
> > C:\Users\...\...\...\dist\server\main.js:102787
> > document.webL10n = function (window, document, undefined) {
> > ^
> > 
> > ReferenceError: document is not defined
> >     at Object.<anonymous> (C:\Users\...\...\...\dist\server\main.js:102787:1)
> >     at __w_pdfjs_require__ (C:\Users\...\...\...\dist\server\main.js:99741:30)
> >     at Object.<anonymous> (C:\Users\...\...\...\dist\server\main.js:102625:1)
> >     at __w_pdfjs_require__ (C:\Users\...\...\...\dist\server\main.js:99741:30)
> >     at Object.<anonymous> (C:\Users\...\...\...\dist\server\main.js:99925:20)
> >     at __w_pdfjs_require__ (C:\Users\...\...\...\dist\server\main.js:99741:30)
> >     at C:\Users\...\...\...\dist\server\main.js:99805:18
> >     at C:\Users\...\...\...\dist\server\main.js:99808:10
> >     at webpackUniversalModuleDefinition (C:\Users\...\...\...\dist\server\main.js:99719:20)
> >     at Object.BPYd (C:\Users\...\...\...\dist\server\main.js:99721:3)
> > 
> > A server error has occurred.
> > node exited with 1 code.
> > ```
> 
> @jakubkeller any solution for this??

I've posted a workaround.

**Comment by dave-vdg** [comment]
Not stale, still an issue

**Comment by alfmos** [comment]
@remy33 should we revert to 6.3.2, current version being 8.0.2?

**Comment by remy33** [comment]
Maybe things have changed, but this is how I manage to have it work.

‫בתאריך יום ו׳, 26 באוג׳ 2022 ב-16:50 מאת ‪Alfonso Moscato‬‏ <‪
***@***.***‬‏>:‬

**Comment by alfmos** [comment]
Not stale

**Comment by rajibhalder** [comment]
Not stale. Stil an issue.
