### ISSUE TITLE
how to get selected text from pdf viewer

### ISSUE THREAD

**Issue by pboymt** [VadimDez/ng2-pdf-viewer#729]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```
Is there a API to set a listener to watch the 'select' event or get the selected text in this module?

**Comment by naitaibai** [comment]
I also want to get information about the selected text, such as location and content.
How should I do it?

**Comment by pboymt** [comment]
Oh, I solved it. I get selected text by using the DOM API `getSelection()`. I set the event 'mouseup' listener with this function.

```typescript
selectedText(): void {
    console.log(getSelection().toString());
}
```

**Comment by wquintanilhadasilva** [comment]
Eu precisei extrair o texto selecionado e criar um highlight em torno dele. Utilizei o código abaixo:

I needed to extract the selected text and create a highlight around it. I used the code below:

**In the template code:**
`<ng2-pdfjs-viewer
  viewerId="1"
  #pdfViewerOnDemand
  (onDocumentLoad)="pagesLoadedEvent($event)"
  [download]="false">
</ng2-pdfjs-viewer>`

In typescript code:

`@ViewChild(PdfViewerComponent) pdfComponent!: PdfJsViewerComponent;

public pagesLoadedEvent(event: any): void {
	this.pdfComponent.PDFViewerApplication.appConfig.viewerContainer.onmouseup = this.selectedTextEvent;
}

selectedTextEvent(event): void {

	// Get application instance
	var viewer = event.view.PDFViewerApplication;

	//Get selected text
	var content = event.view.getSelection().toString();

	var selection = event.view.getSelection()

	// Get selected page
	var page = viewer.page;

	// Highlight coords
	var pageIndex = viewer.pdfViewer.currentPageNumber;
	var page = viewer.pdfViewer.getPageView(pageIndex);
	var pageRect = page.canvas.getClientRects()[0];
	var selectionRects: any[] = selection.getRangeAt(0).getClientRects();
	var viewport = page.viewport;

	var selectedCoords: any[] = [];
	for(let i = 0; i < selectionRects.length; i++) {
	  const value: DOMRect = selectionRects[i];
	  selectedCoords.push(viewport.convertToPdfPoint(value.left - pageRect.x, value.top - pageRect.y).concat(
		viewport.convertToPdfPoint(value.right - pageRect.x, value.bottom - pageRect.y)));
	}

	// Highlight selected text
	var pageElement = page.canvas.parentElement;
	var viewport = page.viewport;
	selectedCoords.forEach(function (rect) {
	  var bounds = viewport.convertToViewportRectangle(rect);
	  var el = document.createElement('div');
	  el.setAttribute('style', 'position: absolute; background-color: pink; opacity: 0.3;' +
		'left:' + Math.min(bounds[0], bounds[2]) + 'px; top:' + Math.min(bounds[1], bounds[3]) + 'px;' +
		'width:' + Math.abs(bounds[0] - bounds[2]) + 'px; height:' + Math.abs(bounds[1] - bounds[3]) + 'px;');
	  pageElement.appendChild(el);
	});

}`

**Comment by rocky-23** [comment]
1. How to select and copy a text after converted into canvas?
2. How to avoid bottom gets trim?

**Comment by hathemi** [comment]
@pboymt could you provide full solution please! code of getSelection() ?
