### ISSUE TITLE
No Event returning the selected page

### ISSUE THREAD

**Issue by CHOUAIAR** [VadimDez/ng2-pdf-viewer#73]
Hello @VadimDez ,

I'm using the ng2-pdf-viewer to display pdf files in thumbnails and I'm wondering if it is possible to have an event emitting the clicked page number of the displayed PDF file.

Thank you in advance.

**Comment by VadimDez** [comment]
Yes,  there's `pageChange` event.
To use it, add function `onPageChange` to your component

```ts
onPageChange(page: number) {
  console.log('onPageChange');
  console.log(page);
}
```

and then in your html add `(pageChange)="onPageChange($event)"`:
```html
<pdf-viewer [src]="pageSrc"
            [(page)]="page"
            [show-all]="false"
            (pageChange)="onPageChange($event)"
></pdf-viewer>
```

**Comment by CHOUAIAR** [comment]
Hello @VadimDez,

Thank you for the answer but this event will emit just the displayed page when we select to show just one, my question was about the case when we display all the pages and the user click on a specific page get the number of this page ( an event triggered on click).

Thank you in advance.

**Comment by Vigneshjana** [comment]
@CHOUAIAR Did you get the solution for getting the page number on click? If so please explain how you achieve it.
Thanks in advance
