### ISSUE TITLE
Module '"../../../../@types/pdfjs-dist"' has no exported member 'PDFPromise'

### ISSUE THREAD

**Issue by julianfrancodev** [VadimDez/ng2-pdf-viewer#739]
##### Bug Report or Feature Request
```
- [ ] Regression
- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
```

Hello there i got the next error with  ```"ng2-pdf-viewer": "^6.4.0"```  version. Thx

```Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:100 - error TS2305: Module '"../../../../@types/pdfjs-dist"' has no exported member 'PDFPromise'.```

``` export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist'; ```

**Comment by srizzon** [comment]
I've the same issue

**Comment by srizzon** [comment]
@julianfrancodev  What is your node version?

**Comment by julianfrancodev** [comment]
@srizzon 15.11.0

**Comment by srizzon** [comment]
I found the solution 🎉

Just add this in your package.json, after ng2-pdf-viewer:

> "@types/pdfjs-dist": "2.1.7"

**Comment by julianfrancodev** [comment]
@srizzon don't works for me :(, what's your ```ng2-pdf-viewer``` version ?

**Comment by srizzon** [comment]
Try use these versions:

> "ng2-pdf-viewer": "6.3.2",
> "@types/pdfjs-dist": "2.1.7",
> "pdfjs-dist": "2.5.207"

**Comment by markabrahams** [comment]
Issue seems to have be triggered by @types/pdfjs-dist moving from version 2.1.7 to 2.7.0 about 4 hours ago.

Can confirm that @srizzon's suggested versions fix the problem for me:

```
"ng2-pdf-viewer": "6.3.2",
"@types/pdfjs-dist": "2.1.7",
"pdfjs-dist": "2.5.207"
```

**Comment by srizzon** [comment]
@markabrahams yes! I think the issue was triggered by a new version of @types/pdfjs-dist

**Comment by almothafar** [comment]
Before month #715 and now this, what is going on with these libraries!

**Comment by ankit1296** [comment]
what is happening with this library 
I am using 5.3.4 version with angular 7. 
Tried installing types/pdfjs-dist also tried removing all node modules and installing again but still doesn't work.

**Comment by almothafar** [comment]
For me I added `"@types/pdfjs-dist": "~2.1.7"` but that didn't solve my issue:
![image](https://user-images.githubusercontent.com/13887564/111285011-6169f280-8649-11eb-9ee3-53702cd6acbc.png)

![image](https://user-images.githubusercontent.com/13887564/111285131-7ba3d080-8649-11eb-965a-f6393dd4f894.png)

**Comment by VadimDez** [comment]
Fixed in version `6.4.1`

**Comment by DavidDev96** [comment]
> Try use these versions:
> 
> > "ng2-pdf-viewer": "6.3.2",
> > "@types/pdfjs-dist": "2.1.7",
> > "pdfjs-dist": "2.5.207"

This also solved our problem after updating to @angular/cli                       13.3.9

**Comment by chandan-bcsg** [comment]
Hi is there no way to upgrade beyond 2.5.207 ?  it is reporitng security vulentabilibites  Please advice how to upgrade unable to proceed  beyon 2.5.207 version ?
