### ISSUE TITLE
Annotate the open pdf

### ISSUE THREAD

**Issue by ravipatel2293** [VadimDez/ng2-pdf-viewer#74]
I want to annotate open pdf in browser but i'm not able to find configuration for that.
So what configuration parameters do i need to set to use annotating functionality in the given library.

**Comment by VadimDez** [comment]
> to annotate open pdf

Could you explain what do you mean by that ?

**Comment by ravipatel2293** [comment]
Annotating in the sense you can highlight the text, you can add notes for particular text in the pdf.
so i want to add this functionality in this library so, how can i do that?

**Comment by Vi-dot** [comment]
@ravipatel2293 
You need first to enable text layer `[render-text]="true"`
Then you should use [rangy](https://github.com/timdown/rangy) library. It gives you cross-browser functions to get selected box.
Here is an example : 
```
let rangySelection = rangy.getSelection();
let rect = rangySelection.nativeSelection.getRangeAt(0).getBoundingClientRect();
// rect contains {left, top, width, height} of selected box
```

**Comment by chitgoks** [comment]
Something like this
[Annotationeer](https://www.youtube.com/watch?time_continue=2&v=g2YAn-Yvlss)

**Comment by kbatyrbayev** [comment]
> @ravipatel2293
> You need first to enable text layer `[render-text]="true"`
> Then you should use [rangy](https://github.com/timdown/rangy) library. It gives you cross-browser functions to get selected box.
> Here is an example :
> 
> ```
> let rangySelection = rangy.getSelection();
> let rect = rangySelection.nativeSelection.getRangeAt(0).getBoundingClientRect();
> // rect contains {left, top, width, height} of selected box
> ```

Hi, how get highlight text, and where use rangy?

**Comment by ani2479** [comment]
Can anyone with an example please? I tried to do the annotation part but it is not working.

**Comment by kbatyrbayev** [comment]
> Can anyone with an example please? I tried to do the annotation part but it is not working. I need to be able to highlight text or images. Is that possible using ng2-pdf-viewer?
> 
> Thanks

Hi, I'm working on it too. At the moment I have done: https://stackblitz.com/edit/angular-73w6ru-canvas-rect-zxejd8?embed=1&file=src/app/app.component.ts
Now it must be connected with ng2-pdf-viewer.

**Comment by kbatyrbayev** [comment]
> Can anyone with an example please? I tried to do the annotation part but it is not working. I need to be able to highlight text or images. Is that possible using ng2-pdf-viewer?
> 
> Thanks

Hi, I have done https://github.com/kbatyrbayev/ng-pdf-highlighter
But at the moment it is in development.

**Comment by ShahidBhat** [comment]
Hi All,

Can we fetch text which the user selects on the pdf ?

**Comment by SivasankarThalavai** [comment]
https://github.com/mathiasconradt/pdfjs-annotator

**Comment by souravprakashjena** [comment]
@ShahidBhat  did you get any solution ?
