### ISSUE TITLE
Getting erro after updating the package to the latest version

### ISSUE THREAD

**Issue by syedraashidhussain** [VadimDez/ng2-pdf-viewer#742]
Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:5:100 - error TS2305: Module '"../../../../@types/pdfjs-dist"' has no exported member 'PDFPromise'.

5 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';

**Comment by VadimDez** [comment]
Are you using version `6.4.1`?

**Comment by marius1992** [comment]
I am using the following versions:
    "ng2-pdf-viewer": "6.4.1",
    "pdfjs-dist": "2.6.347"

And I receive the following errors:

ERROR in node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts(5,10): error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFDocumentProxy'.
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts(5,28): error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFSource'.
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts(5,39): error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFProgressData'.
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts(1,10): error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFJSStatic'.
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts(5,10): error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFJSStatic'.
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts(5,23): error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFDocumentProxy'.
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts(5,41): error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFViewerParams'.
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts(5,58): error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFPageProxy'.
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts(5,72): error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFSource'.
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts(5,83): error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFProgressData'.
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts(5,100): error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFPromise'.
node_modules/pdfjs-dist/types/display/annotation_storage.d.ts(30,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(596,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(600,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(604,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(774,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(778,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(907,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(911,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(916,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(920,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(925,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(1001,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdfjs-dist/types/display/api.d.ts(1099,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by gabrieliulianmilitaru96** [comment]
ERROR in ./node_modules/ng2-pdf-viewer/fesm5/ng2-pdf-viewer.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined

I'm using:
"ng2-pdf-viewer": "6.4.1",
"pdfjs-dist": "2.5.207"

**Comment by gabrieliulianmilitaru96** [comment]
> Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:5:100 - error TS2305: Module '"../../../../@types/pdfjs-dist"' has no exported member 'PDFPromise'.
> 
> 5 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';

Did you manage to solve this?

**Comment by marius1992** [comment]
> ERROR in ./node_modules/ng2-pdf-viewer/fesm5/ng2-pdf-viewer.js
> Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
> TypeError: Cannot read property 'kind' of undefined
> 
> I'm using:
> "ng2-pdf-viewer": "6.4.1",
> "pdfjs-dist": "2.5.207"

Did you solve this, @gabrieliulianmilitaru96 ? @VadimDez we need some help here please :)

**Comment by VadimDez** [comment]
Guys don't install `pdfjs-dist` manually.

**Comment by gabrieliulianmilitaru96** [comment]
> Guys don't install `pdfjs-dist` manually. Install `ng2-pdf-viewer` only.

I tried but we still have that problem

**Comment by VadimDez** [comment]
I did clean install of the version `6.4.1` and have no errors. Maybe try deleting `ng2-pdf-viewer` first and then install it again. Let me know if that works.

**Comment by gabrieliulianmilitaru96** [comment]
I also did it and I have this error: 
ERROR in ./node_modules/ng2-pdf-viewer/fesm5/ng2-pdf-viewer.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined

**Comment by VadimDez** [comment]
It's a different error from the one reported by the author of the issue.

**Comment by syedraashidhussain** [comment]
Thanks Vadym, it got solved after deleting and re-installing. But I am not
sure why this issue occurred in first place.


*Thanks and Regards,*
*Syed Raashid Hussain*
*Contact- 7377213161*

**Comment by yabasha** [comment]
I have the following version

```
Angular CLI: 7.3.4
Node: 10.19.0
OS: linux x64
Angular: 7.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.0
@angular-devkit/build-angular     0.13.0
@angular-devkit/build-optimizer   0.13.0
@angular-devkit/build-webpack     0.13.0
@angular-devkit/core              10.1.1
@angular-devkit/schematics        7.3.4
@angular/cdk                      7.3.3
@angular/cli                      7.3.4
@angular/material                 7.3.3
@angular/pwa                      0.1001.1
@ngtools/webpack                  7.3.0
@schematics/angular               7.3.4
@schematics/update                0.13.4
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
```

I installed `V6.4.1` and everything worked as expected when I run `npm start` but when I want to build the app I get the following error:

```
ERROR in ./node_modules/ng2-pdf-viewer/fesm5/ng2-pdf-viewer.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
```

Please advice,
