### ISSUE TITLE
ERROR in ./node_modules/ng2-pdf-viewer/fesm5/ng2-pdf-viewer.js Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js): TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by gabrieliulianmilitaru96** [VadimDez/ng2-pdf-viewer#743]
ERROR in ./node_modules/ng2-pdf-viewer/fesm5/ng2-pdf-viewer.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined

I'm using:
"ng2-pdf-viewer": "6.4.1",
"pdfjs-dist": "2.5.207"

**Comment by VadimDez** [comment]
What angular version are you using?

**Comment by gabrieliulianmilitaru96** [comment]
7.3.6

**Comment by dayus20** [comment]
Hi, I have the same error with version 6.4.1
using angular 7.2.0

**Comment by naixin-coder** [comment]
I have similar problem，so, what's the mothed to resolve ?

**Comment by stgoymz** [comment]
Hi, I went through various posts and the dependencies that worked for me are as follows
`   "@angular-devkit/build-angular": "~0.803.19",
    "@angular-devkit/build-ng-packagr": "~0.803.19",
    
    "ng2-pdf-viewer": "^6.2.0",
    "@types/pdfjs-dist": "^2.1.1",
    "pdfjs-dist": "^2.3.200",
`

**Comment by juanisn** [comment]
> Hi, I went through various posts and the dependencies that worked for me are as follows
> ` "@angular-devkit/build-angular": "~0.803.19", "@angular-devkit/build-ng-packagr": "~0.803.19", "ng2-pdf-viewer": "^6.2.0", "@types/pdfjs-dist": "^2.1.1", "pdfjs-dist": "^2.3.200",`

Hi, not worked for me :(. I'm using Angular 7.2.9

**Comment by Nisihitha** [comment]
I have tried with above versions, still facing the error, can anyone help me in fixing this issue

**Comment by t5ar** [comment]
> 
> 
> I have tried with above versions, still facing the error, can anyone help me in fixing this issue

Has anyone fixed this?

**Comment by AlexLivshitz** [comment]
Same error with angular 8.1.2
Any solution?

**Comment by Sachin2491** [comment]
I am getting same error. 

Angular: 7.0.4
ng2-pdf-viewer : 6.4.1

I have tried with lower versions of ng2-pdf-viewer but still getting errors

**Comment by EricLewe** [comment]
Another cause of this issue was due to wrong cli version:
https://github.com/VadimDez/ng2-pdf-viewer/issues/594#issuecomment-927271784

**Comment by melkor54248** [comment]
Is there any update on this?

**Comment by gjoforte** [comment]
Any update on this?

**Comment by himajaM** [comment]
> I am getting same error.
> 
> Angular: 7.0.4 ng2-pdf-viewer : 6.4.1
> 
> I have tried with lower versions of ng2-pdf-viewer but still getting errors

This solution worked well for me... Thank you!!!

**Comment by himajaM** [comment]
> it works in this version
> 
> "ng2-pdf-viewer": "^5.1.3", "pdfjs-dist": "2.5.207",

This solution worked well for me, thank you!!!
