### ISSUE TITLE
Moderately large PDF files crashing on tablet devices

### ISSUE THREAD

**Issue by ashish-koshy** [VadimDez/ng2-pdf-viewer#746]
##### Bug Report or Feature Request (mark with an `x`)
```
- [] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Issue:
Moderately large PDF files almost always crash on tablet devices. I have tested this on a normal chrome browser and chromium web-view for android as well. 

What I observed:
Your viewer seems to paint all the pages to the DOM at once as soon as the PDF loads. This happens regardless of whether a given page is visible in the DOM or not. On low powered android devices like a tablet, this causes a graphics memory leak leading to all the apps crashing due to low available heap memory.

I fired up this sample implementation of PDFjs from Mozilla that loads a large PDF file:
https://mozilla.github.io/pdf.js/web/viewer.html

If you poke around in the DOM you can see how the canvas layer and the text layer are not rendered for all pages initially. Its only when you scroll towards those pages that these get added as nodes. 

![image](https://user-images.githubusercontent.com/55425558/111715178-4c73a600-8879-11eb-9291-0b6ed7375e53.png)

I tried loading this page on the same tablet and it never seems to crash.

**Comment by ashish-koshy** [comment]
@VadimDez  Here is my very lean and simple implementation of PDFjs in angular where I lazy load each page of the PDF into the DOM only when it is visible inside the viewport.

https://github.com/ashish-koshy/ng2-lean-pdf-viewer

I tested this version on the failing tablet devices and it seems to be working fine.

**Comment by ashish-koshy** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#i-want-to-render-all-100-pages-in-a-document-at-a-high-resolution-is-it-a-good-idea

I want to render all 100 pages in a document at a high resolution. Is it a good idea?
Not really. You can count yourself: a letter page size is 816⨉1056px at 96DPI (and if you have a HiDPI display, multiply each dimension by window.devicePixelRatio, e.g., 2), so you will need a canvas that takes up 816⨉1056⨉4 = 3,446,784 bytes (don't forget to multiply that by e.g., 2⨉2 = 4 if it's a HiDPI display). This requires you to allocate 3.5Mb (or 14Mb) per page. You need a decent amount of memory to hold the 100 canvases, and it does not count the time that is spent on rendering them.

The demo viewer creates, renders, and holds canvases only for visible pages to reduce the amount of used memory. Our recommendation is to create and render only visible pages.

**Comment by VadimDez** [comment]
Have you tested if the same thing happens here https://vadimdez.github.io/ng2-pdf-viewer/ ?

**Comment by ashish-koshy** [comment]
@VadimDez Good question. Will try this out. I will try testing this out on the tablet devices that were failing earlier. I just quickly checked it in the desktop version and it seems fine. I checked your code on the demo page and it looks like you are handling the pages exactly the way that mozilla recommends. 

As for the fix. I am using my custom implementation in at the moment. it hasn't given me any trouble so far. Thank you for checking this out  :-)

I simply use NASA's Apollo 17 flightplan as a large reference PDF. it has 600 pages
https://www.hq.nasa.gov/alsj/a17/A17_FlightPlan.pdf
