### ISSUE TITLE
Pdf-viewer is not a angular component

### ISSUE THREAD

**Issue by rohan2934** [VadimDez/ng2-pdf-viewer#75]
after updating angular 2 rc5  to angular 2.4 pdf-viewer gives an error that is not a angular component
![error](https://cloud.githubusercontent.com/assets/13061832/24575876/e82d31a4-16ce-11e7-9979-da478c1f2fb7.PNG)

**Comment by VadimDez** [comment]
Check your configuration it seems like you didn't add ng2-pdf-viewer to your app

**Comment by victorschinaider** [comment]
@VadimDez, why PdfViewer isn't a angular module?

**Comment by ces10** [comment]
same error (angular@2.4.6, ng2-pdf-viewer@1.0.2,pdfjs-dist@1.7.416)

From my appModule.ts:
`import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { RouterModule, RouteReuseStrategy } from "@angular/router";
import { PdfViewerComponent } from "ng2-pdf-viewer";
....
declarations: [
            AppComponent,
            PdfViewerComponent,
...
`

From my component:
`import {Component, ViewChild} from "@angular/core";
import {Route, ActivatedRoute} from '@angular/router';
import { BibliographyServices } from "../services/bibliographyServices";
import { JournalArticle } from "../models/Bibliography";
import 'rxjs/Rx'; //for map function
import { PdfViewerComponent } from "ng2-pdf-viewer";

@Component({
    selector: "pdf-edit-component",
    templateUrl: "./pdfEditComponent.html",
    host: { class: "pageComponent" }
})

export class PdfEditComponent {
    public pdfSrc: string = 'https://vadimdez.github.io/ng2-pdf-viewer/pdf-test.pdf';
    page: number = 1;

    constructor(public pdfViewerComponent: PdfViewerComponent, private bibliographyService: BibliographyServices, private route: ActivatedRoute) {
    }
...
`
And my html page:
`<div>
      <label>PDF src</label>
      <input type="text" placeholder="PDF src" [(ngModel)]="pdfSrc">
  </div>
  <div>
      <label>Page:</label>
      <input type="number" placeholder="Page" [(ngModel)]="page">
  </div>
  <pdf-viewer [src]="pdfSrc"
              [page]="page"
              [original-size]="true"
              style="display: block;"
  ></pdf-viewer>`

I don't see if I'm forgetting something

**Comment by rohan2934** [comment]
i have the same issue....

**Comment by 4rpit** [comment]
+1 Same Issue

**Comment by rohan2934** [comment]
any timeline???
thank you.

**Comment by VadimDez** [comment]
Could anybody show me how to reproduce it? Tried myself got no problems.

@ces10 your problem is that you doing something that you shouldn't, Remove `public pdfViewerComponent: PdfViewerComponent` from
```js
constructor(public pdfViewerComponent: PdfViewerComponent) {}
```

**Comment by ces10** [comment]
@VadimDez  Many thanks, it works!

**Comment by balamca7** [comment]
ERROR Error: Uncaught (in promise): Error: Template parse errors:
'pdf-viewer' is not a known element:
1. If 'pdf-viewer' is an Angular component, then verify that it is part of this module.
2. If 'pdf-viewer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("dth: 150px;height: 200px;" >
                <p>click me to view PDF in Iframe!</p>
                [ERROR ->]<pdf-viewer 
                 ></pdf-viewer>
            </div>
"): ng:///SelfModule/EditComponent.html@305:16

**Comment by balamca7** [comment]
ERROR Error: Uncaught (in promise): Error: Template parse errors:
'pdf-viewer' is not a known element:
1. If 'pdf-viewer' is an Angular component, then verify that it is part of this module.
2. If 'pdf-viewer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("dth: 150px;height: 200px;" >
                <p>click me to view PDF in Iframe!</p>
                [ERROR ->]<pdf-viewer 
                 ></pdf-viewer>
            </div>
"): ng:///SelfModule/EditComponent.html@305:16

**Comment by VadimDez** [comment]
@balamca7 here's documentation: https://github.com/VadimDez/ng2-pdf-viewer
see how to integrate it in your project there.

**Comment by balamca7** [comment]
@VadimDez 
yes i follow this document, but get this error.

**Comment by VadimDez** [comment]
@balamca7 the error that you've sent before is saying that component is not found - means that you imported `PdfViewerModule` in the wrong place or imported it wrongly.

**Comment by AndrWeisR** [comment]
For anyone else, I had this problem when I had a module for my page component, and I had added the PdfViewerModule import in app.module.ts instead of my page-level module.ts. I moved the PdfViewerModule import to my page-level module.ts.

**Comment by dschmitt-fc** [comment]
I was having this issue even with the import in the sub-module. I'm not sure which of these things did the trick, but I closed VS Code, did `npm install`, reran `ng build --watch`, then opened VS Code again.

**Comment by viru-rishu** [comment]
I was having this issue, I checked all the possible solutions, but in vain. I was opening a mat dialog from component and showing pdf in that mat dialog, then this error is coming "Pdf-viewer is not an angular component". I tried adding Pdfviewer at the app module, page module but did not work, then I checked the module file and found out that I have not added the mat dialog component in my main module file i.e this error. I added a mat dialog component in my module and everything works fine.

So, please check things carefully, the problem might be somewhere else, not in this pdf viewer module.
