### ISSUE TITLE
Warning in angular v11

### ISSUE THREAD

**Issue by khan990** [VadimDez/ng2-pdf-viewer#754]
Although the application compiles and works just fine. There is a warning while building angular 11 application.

```
Warning: Entry point 'ng2-pdf-viewer' contains deep imports into '/Users/[project path]/node_modules/pdfjs-dist/es5/build/pdf', '/Users/[project path]/node_modules/pdfjs-dist/es5/web/pdf_viewer'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
```

**Comment by avaHamza** [comment]
`Warning: Entry point 'ng2-pdf-viewer' contains deep imports into '/[path]/node_modules/ng2-pdf-viewer/node_modules/pdfjs-dist/es5/build/pdf', '/[path]/node_modules/ng2-pdf-viewer/node_modules/pdfjs-dist/es5/web/pdf_viewer'. This is probably not a problem, but may cause the compilation of entry points to be out of order.`

Angular v10
"ng2-pdf-viewer": 2.4.1


"@types/pdfjs-dist": ^2.7.0
"pdfjs-dist": ^2.6.347

Can someone see what it is about and how to remove/fix this warning? @VadimDez

**Comment by AvaH7986** [comment]
Warning: Entry point 'ng2-pdf-viewer' contains deep imports into '/[path]/node_modules/ng2-pdf-viewer/node_modules/pdfjs-dist/es5/build/pdf', '/[path]/node_modules/ng2-pdf-viewer/node_modules/pdfjs-dist/es5/web/pdf_viewer'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

Angular v10
"ng2-pdf-viewer": 2.4.1

"@types/pdfjs-dist": ^2.7.0
"pdfjs-dist": ^2.6.347

Can someone see what it is about and how to remove/fix this warning? @VadimDez

**Comment by masaanli** [comment]
Got exactly the same issue here, Angular 11.

**Comment by arturovt** [comment]
This is only a warning, which happens because of how Mozilla ships the `pdfjs-dist` package.

You can create an `ngcc.config.js` file on the root level:

```
- src
  - main.ts
 - package.json
 - ngcc.config.js
```

And its content should be as follows:
```js
module.exports = {
  packages: {
    'ng2-pdf-viewer': {
      ignorableDeepImportMatchers: [/pdfjs-dist/],
    },
  },
};
```

Note that this is the recommended way **advised by the Angular CLI team**, but I can't guarantee that it will work in all your applications, and I can't know why it wouldn't work.. At least it works in mine :)

**Comment by jeslove** [comment]
> This is only a warning, which happens because of how Mozilla ships the `pdfjs-dist` package.
> 
> You can create an `ngcc.config.js` file on the root level:
> 
> ```
> - src
>   - main.ts
>  - package.json
>  - ngcc.config.js
> ```
> 
> And its content should be as follows:
> 
> ```js
> module.exports = {
>   packages: {
>     'ng2-pdf-viewer': {
>       ignorableDeepImportMatchers: [/pdfjs-dist/],
>     },
>   },
> };
> ```
> 
> Note that this is the recommended way **advised by the Angular CLI team**, but I can't guarantee that it will work in all your applications, and I can't know why it wouldn't work.. At least it works in mine :)

This end up working for me too Thanks
