### ISSUE TITLE
How to resolve google firbase Cors issue on UAE countries? 

### ISSUE THREAD

**Issue by Krishan93** [VadimDez/ng2-pdf-viewer#756]
I am unable to resolve the firebase Cors issue. I have developed a website by google firebase auth, firebase real-time database. when I test my website some of the other countries. it is working well (India, China, USA,). but in UAE countries firebase auth is not working. I was getting Cors issue. I have added a few more Cors extensions. but it did not work. we do not know. what to do now. if any have the answer. please share us

**Comment by VadimDez** [comment]
https://github.com/VadimDez/ng2-pdf-viewer/issues?q=cors
