### ISSUE TITLE
How can i get the PDFPageViewport?

### ISSUE THREAD

**Issue by ws2823147532** [VadimDez/ng2-pdf-viewer#76]
Hello, I want to get the` width` and `height` of a pdf. And  I find  these two attribute in the `PDFPageViewport` . I saw the source: there is only the  
```javascript
afterLoadComplete: EventEmitter<PDFDocumentProxy>;
```
so, how can I get the PDFPageViewport? Please help me.

**Comment by ws2823147532** [comment]
sorry, I find 
```javascript
getPage(number: number): PDFPromise<PDFPageProxy>; 
```
in `PDFDocumentProxy`. Use this can help me.

**Comment by reenezden** [comment]
Hello, how were you able to get the height and width of the pdf document?
