### ISSUE TITLE
Issue with Mozilla compatibility

### ISSUE THREAD

**Issue by aleguern** [VadimDez/ng2-pdf-viewer#761]
Hello, I've been using your library on every browsers but in firefox it seems to be not working. 

```
- [ ] Regression
- [X] Bug report 
- [ ] Feature request
- [ ] Documentation issue or request
```

I copy pasted the example in the documentation and it just does not show on firefox and there's no errors in the console. 

Thanks,

**Comment by hifos** [comment]
I have the same issue, It doesnt work in Mozilla and IOS devices. I test in Chrome and Safari for IOS 14 and IOS 12, Safari for desktop with same error:
![WhatsApp Image 2021-04-26 at 13 09 10](https://user-images.githubusercontent.com/83023671/116278907-8e331e80-a74c-11eb-8b4f-6a99c6260b27.jpeg)
