### ISSUE TITLE
Access rendering canvas / setting pixel density / DPI of the rendered page

### ISSUE THREAD

**Issue by LouAdrien** [VadimDez/ng2-pdf-viewer#764]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ x] Feature request
```
Hi, great work with the lib! I am looking to be able to setup the exact pixel density for the rendered page.

My intent was to setup the canvas logical size to a higher resolution, but maintain the page viewport to the desired display resolution to achieve the desired effect.
The technic is described here in the [Rendering the page](https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples) section, as well as [here](https://stackoverflow.com/a/38166802/1703287)

The issue is currently we do not have any access to the final canvas BEFORE its rendered (accessible only after page render), to setup its logical size, nor can I find call to page.render() in the current source to find a way to hack it.

Any suggestion of even a place to look to achieve the desired results?
Regards,

**Comment by seopei** [comment]
Maybe you can try to set the `maxCanvasPixels` like this
```
const pdfOptions: PDFViewerParams | any = {
      eventBus: eventBus,
      container: this.element.nativeElement.querySelector('div'),
      removePageBorders: !this._showBorders,
      linkService: this.pdfMultiPageLinkService,
      textLayerMode: this._renderText
        ? this._renderTextMode
        : RenderTextMode.DISABLED,
      findController: this.pdfMultiPageFindController,
      maxCanvasPixels: 1000
    };
```

**Comment by LouAdrien** [comment]
@seopei thanks for the suggestion! But I was looking for a solution that would use the currently available settings exposed by the ng2-pdf-viewer component inputs. Not sure how I could use the settings you just shared

**Comment by seopei** [comment]
I do not think it is possible at the moment with the current version. But if `maxCanvasPixels` the property you are looking for you have to fork this repo, use `maxCanvasPixels` as an input property for the component and then make a PR.
