### ISSUE TITLE
why PdfViewer isn't a angular module?

### ISSUE THREAD

**Issue by victorschinaider** [VadimDez/ng2-pdf-viewer#77]
I think it'll be good to be a module.

**Comment by VadimDez** [comment]
By the time this component was written angular2 didn't have modules but components instead.

**Comment by victorschinaider** [comment]
@VadimDez, can i try something?

**Comment by VadimDez** [comment]
will probably be a module in version 2

**Comment by victorschinaider** [comment]
https://blog.engineyard.com/2016/tree-shaking

**Comment by VadimDez** [comment]
Angular Module is something different from ES Modules.

**Comment by victorschinaider** [comment]
Year, it's true, but Tree-Shaking is a concept and can be extended to any module framework.

Material2 (Angular 2), in their last release,  adopted this pattern (https://github.com/angular/material2/releases/tag/2.0.0-beta.3, in MaterialModule).

**Comment by VadimDez** [comment]
`ng2-pdf-viewer` is a single component that you import in your code, there're no other exported components. Could you explain me what do you want to tree-shake here?

**Comment by victorschinaider** [comment]
Vadim,
I don't want nothing. I'm just trying to help, asking questions.

I don't know what you expect from your library, i consider that it'll expand, because it's great, and when you expand, you need more types and components (or not). Maybe in the future you will not have only one component, maybe you'll have more, i don't know.

I think it's like a OOP. You maybe have a little software, and it doesn't need this pattern, but it's a pattern and you follow, independently of the size of it, and implements from begining is better, i think.

When i asked *"why PdfViewer isn't a angular module?"*, it was to undestand the motivation. When i talked about tree-shaking, i was opposing my affirmation to follow to a better solution.

When i asked *"@VadimDez, can i try something?"*,  i was justing a beginner programmer want to contribute with this great tool, and with the open source community.

Well, i'm right this tool will grow so much with angular 2. I wish you success.

**Comment by VadimDez** [comment]
It is really hard to get your point.
You ask why it's not angular module, and then you send the Angular-Material that did remove Modules and reverted to components. 
Then you say about tree-shaking which should already work, since i'm exporting the component.
I can't completely get the picture of what you're asking...
