### ISSUE TITLE
Is there a way for me get the total number of pages in the pdf file?

### ISSUE THREAD

**Issue by jackli199311** [VadimDez/ng2-pdf-viewer#78]
Hi there,

I want to use the "page" functionally, but how can I prevent the users from going to a page that does not exist in the pdf file?

**Comment by VadimDez** [comment]
Yes, see https://github.com/VadimDez/ng2-pdf-viewer#after-load-complete .
it actually does it for you, it does check bounds when switching from one page to another pdf page

**Comment by Bobisback** [comment]
Ya but what should I do if I need the max amount of pages?

**Comment by BarGol00683** [comment]
.html
`<pdf-viewer (after-load-complete)="afterLoadComplete($event)"> </pdf-viewer>`

.ts
`afterLoadComplete(pdf: PDFDocumentProxy) {
    this.totalPages = pdf.numPages;
  }`

**Comment by Pelon-Pelonete** [comment]
@BarGol00683 Did you find the answer?

**Comment by BarGol00683** [comment]
@Pelon-Pelonete No, I don't need total pages anymore.

**Comment by johannesMatevosyan** [comment]
use **after-load-complete**  event for that:
```
<pdf-viewer [src]="srcString" [render-text]="true" [zoom]="zoomScale" [original-size]="false" [show-all]="true"
        (after-load-complete)="afterLoadComplete($event)" style="display: block;">
      </pdf-viewer>
```
and in callback:

```
  afterLoadComplete(pdf): void {
    this.totalPages = pdf.numPages;
  }
```
