### ISSUE TITLE
How to know if user scrolled till end of pdf.

### ISSUE THREAD

**Issue by sulabh9999** [VadimDez/ng2-pdf-viewer#786]
I want to know if user is scrolled till end of pdf. I checked `(pageChange)="pdfPageChange($event)"` shows only recent page index. Is there any way to know. 

Basically I want to know if user has read document completely. 

Please help.

**Comment by bsmarcosj** [comment]
I'm interested in this functionality too. Is there any way to do that?

Best regards.
