### ISSUE TITLE
CSS issue when used along with bootstrap.

### ISSUE THREAD

**Issue by Vickyraz** [VadimDez/ng2-pdf-viewer#795]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

**Overview :**
I am having an issue when using ng2-pdf-viewer in a project along with bootstrap.min.js. The issue is pages in pdf overlap with each other.
I have included the following CDN for bootstrap CSS in index.html. (With out this, there is no issue.)

`<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">`

**Issue screenshot :**

![image](https://user-images.githubusercontent.com/17909417/120502487-1bb6fd80-c3e0-11eb-8d7e-e4588f2d9793.png)

**Version info :**
Library : Latest version - 7.0.1 (Worked fine in 6.4.1)
Angular : Checked in Angular 9

**Browser :**
Chrome (Version 91.0.4472.77), Edge (Version 90.0.818.62)

**To Reproduce :**
Create a sample project with ng2-pdf-viewer.
Add the following code in index.html
`<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">`

**Fix :**
This same issue occurred in ngx-extended-pdf-viewer and I have raised the following issue.
[https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/783](url)

As pointed out by @stephanrauh , the following fix works for me. Same has to be fixed in the library.
```
* {
-webkit-box-sizing: content-box;
-moz-box-sizing: content-box;
box-sizing: content-box;
}
```

Thanks,
Raz

**Comment by stephanrauh** [comment]
If I'm not mistaken, this also fixes problems with PrimeNG.

Oh, and of course the CSS rule should only affect the PDF viewer itself, not the rest of the application. Please make it a local CSS rule. :)
