### ISSUE TITLE
Auto height when fit to page

### ISSUE THREAD

**Issue by blairjo** [VadimDez/ng2-pdf-viewer#796]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x ] Feature request
- [ ] Documentation issue or request
```

Hi,

The examples I have looked at generally involve manually setting a height property, even when width is automatically being calculated to fit the container.  

What I'd like is to for the pdf-viewer expand it's width to fit the container (which it already does), but then automatically expand it's height also, so that when showing **all** pages, you can simply scroll the main website page rather than having to scroll the pdf-viewer element.

I have header elements etc on the page that will be a different height on different devices, so calculating a fixed height for the pdf-viewer it tricky. I'd like it just to expand vertically to take up space on the page.

Is this possible with current options? 

Thanks

**Comment by trewok** [comment]
I'd be interested in knowing this too, bumping
