### ISSUE TITLE
Version 6.4.1 causes stuck on the App startup interface on IOS14.5, which works fine on Android

### ISSUE THREAD

**Issue by 1797890817** [VadimDez/ng2-pdf-viewer#798]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Version 6.4.1 causes stuck on the App startup interface on IOS14.5, which works fine on Android
ionic cli        6.16.2
cordova       8.1.2
Xcode   12.5

Compilation is normal, and the console launched does not see any meaningful information to help analyze the problem.

**Comment by innokentiiya-tr** [comment]
Looks like duplicate of this issue https://github.com/VadimDez/ng2-pdf-viewer/issues/685
