### ISSUE TITLE
Styling issue when trying to putting pdf viewer to right of html content

### ISSUE THREAD

**Issue by ja74687** [VadimDez/ng2-pdf-viewer#804]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
#422 
Hey bug returned in version 7.0.1 when i back to 6.4.1 everything i ok :)

**Comment by jorahsh** [comment]
I'm also seeing something very similar to this:
![image](https://user-images.githubusercontent.com/30536613/122301542-0a7cef00-cebe-11eb-806a-7872cbef8926.png)

Here is the html in Angular:
![image](https://user-images.githubusercontent.com/30536613/122300772-056b7000-cebd-11eb-8e57-ef72230593b1.png)
And I'm even using the position: relative trick in the scss file:
![image](https://user-images.githubusercontent.com/30536613/122301872-8a0abe00-cebe-11eb-985b-8d17cf9eed13.png)

I just updated from 6.3.2 to 7.0.1 when I updated the project to Angular 11.
![image](https://user-images.githubusercontent.com/30536613/122301137-80348b00-cebd-11eb-9f5e-0a86fa5b4e7e.png)
![image](https://user-images.githubusercontent.com/30536613/122301184-94788800-cebd-11eb-863a-32ffe81da30a.png)

For some reason, the pdf data will load, but not display. It's also not throwing any errors.

**Comment by ja74687** [comment]
How you load src, I load blob from rest API and work :)

**Comment by ja74687** [comment]
Maybe try downgrade to 6.4.1 run: npm i ng2-pdf-viewer@6.4.1 --save

**Comment by jorahsh** [comment]
Originally the type I was setting src to was an ArrayBuffer. I tried Uint8Array and URL string. As I mentioned above, the file data loads but it is not rendering for any of these types. I switched to using version 6.4.1 of ng2-pdf-viewer and version 2.5.207 of pdfjs-dist and it fixes this issue.
