### ISSUE TITLE
Add a rendered event in promise

### ISSUE THREAD

**Issue by scheibapps** [VadimDez/ng2-pdf-viewer#81]
page.getTextContent().then((textContent) => {
            var index = _this._showAll ? page.pageIndex : 0;
            var canvas = container.querySelectorAll('canvas')[index];
            canvas.parentNode.insertBefore(_this.buildSVG(viewport, textContent), canvas);
            canvas.style.position = 'absolute';
            canvas.style.top = '0';
            canvas.style.left = '0';
            canvas.style.zIndex = '-1';
	    **_this.renderer.emit(true);_**
        });

Something like this so that I can know when the view has rendered.

**Comment by VadimDez** [comment]
Released in `4.1.0`
https://github.com/VadimDez/ng2-pdf-viewer#page-rendered
