### ISSUE TITLE
Digital Signature is not visible in ng2-pdf-viewer (version 7.0.1)

### ISSUE THREAD

**Issue by dheerajnal** [VadimDez/ng2-pdf-viewer#810]
As suggested by couple of devs on github and stackoverflow i removed code which hides the digital signature from annotation,js file from pdfjs-dist library , but still not able to see the digital signature.

if (data.fieldType === 'Sig') {
   this.setFlags(AnnotationFlag.HIDDEN);
  }

Please help me on this.

**Comment by LAlves91** [comment]
Hi @dheerajnal !

There are some extra steps to take in order for this fix to work:

- By default, this library will download pdf.worker.min.js from an external link. If you want your custom worker to be used instead, you have to follow the instructions given [here](https://github.com/VadimDez/ng2-pdf-viewer#set-custom-path-to-the-worker);
- Also, if you're "patching" this pdf.worker.js code, make sure the version you downloaded is the same as the one used in pdfjs-dist;
- Last but not least: I think it's a good idea to minify your version of pdf.worker.js for performance reasons.

Good news: pdf.js's latest version shows digital signatures by itself, without having to patch this code! Hopefully, soon, we won't need to worry about this!

**Comment by dheerajnal** [comment]
> Hi @dheerajnal !
> 
> There are some extra steps to take in order for this fix to work:
> 
> * By default, this library will download pdf.worker.min.js from an external link. If you want your custom worker to be used instead, you have to follow the instructions given [here](https://github.com/VadimDez/ng2-pdf-viewer#set-custom-path-to-the-worker);
> * Also, if you're "patching" this pdf.worker.js code, make sure the version you downloaded is the same as the one used in pdfjs-dist;
> * Last but not least: I think it's a good idea to minify your version of pdf.worker.js for performance reasons.
> 
> Good news: pdf.js's latest version shows digital signatures by itself, without having to patch this code! Hopefully, soon, we won't need to worry about this!

Thanks
