### ISSUE TITLE
Invoke URL retrieval manually 

### ISSUE THREAD

**Issue by Alexettels** [VadimDez/ng2-pdf-viewer#82]
My pdfSrc variable changes asynchronously and the document isn't even tried to be fetch after the url is changed.

How can I invoke the retrieval of the URL manually?

**Comment by VadimDez** [comment]
Dynamic change of src should work. See here https://vadimdez.github.io/ng2-pdf-viewer/

**Comment by VadimDez** [comment]
Closing.
