### ISSUE TITLE
Error import inside node modules version 7.0.1

### ISSUE THREAD

**Issue by dinhtheloc** [VadimDez/ng2-pdf-viewer#821]
I just installed version 7.0.1 and receive error mess: 

ERROR in ../node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:13 - error TS1005: '=' expected.

5 import type { PDFSource, PDFProgressData } from './typings';
              ~
../node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:49 - error TS1005: ';' expected.

5 import type { PDFSource, PDFProgressData } from './typings';

What should i do to fix it ?

**Comment by lufo88ita** [comment]
https://github.com/VadimDez/ng2-pdf-viewer/issues/785

Maybe is the same problem?

**Comment by matheusmurta** [comment]
For angular 7, use the version "ng2-pdf-viewer": "^5.2.2" that will work very well
