### ISSUE TITLE
Annotations not shown correctly

### ISSUE THREAD

**Issue by RobinBomkampDv** [VadimDez/ng2-pdf-viewer#824]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Existing comments in a pdf file are not shown correctly. 
The image is not correct and the text "[{{type}} Annotation]" is shown. 
If you hover the comment it is showing the correct comment, but without time and date. (Only placeholders are shown.)

![image](https://user-images.githubusercontent.com/43467426/134167667-58c2300e-2419-4289-8085-6a281dab355e.png)

I have tested this with the current demo page. A test with pdfjs-dist is working.

Example file:
[1 with comment.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/7202887/1.with.comment.pdf)

**Comment by rbdv159** [comment]
Hey there, this is still an issue for us.

**Comment by Akxe** [comment]
Indeed, here is another PDF with annotations problem: [Faktura - ISCOD.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/7600888/Faktura.-.ISCOD.pdf)

**Comment by rbdv159** [comment]
Still relevant.

**Comment by rbdv159** [comment]
And again. Still relevant.

**Comment by rbdv159** [comment]
Not stale

**Comment by rbdv159** [comment]
Still relevant. :)

**Comment by melnikovic** [comment]
Indeed, this is still relevant.

**Comment by melnikovic** [comment]
Can someone look at it? This ticket is open for one year now.

**Comment by melnikovic** [comment]
I did update ng2-pdf-viewer to version 9.1.2, and pdfWorker to 2.14.305 and still getting same issue with {{date}} and {{time}}

**Comment by RobinBomkamp** [comment]
Still not stale
