### ISSUE TITLE
can't now show digital signature PKCS#7

### ISSUE THREAD

**Issue by sabardotnet** [VadimDez/ng2-pdf-viewer#828]
my program generate a watermark or image signed. show in chrome or other pdf application the watermark is visible. but when show in ng2-pdf-viewer the watermark is not visible. 

this is the pdf file : https://drive.google.com/file/d/1QR6JJHe8zMmgImeOKUEgplv0fIAwNn8L/view?usp=sharing

thanks for answering

**Comment by sebalr** [comment]
Any update on this? I saw that the PR has conflicts

**Comment by LAlves91** [comment]
Hey @sebalr !

Actually, my PR updating PDF.js to 2.11.338 was merged! It'll be available in ng2-pdf-viewer's next release!

**Comment by VadimDez** [comment]
Can we close this? [7.0.2 was released](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/7.0.2), did it fix this issue?

**Comment by piotrm221** [comment]
> Can we close this? [7.0.2 was released](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/7.0.2), did it fix this issue?

Hello, I am using `7.0.2` version of `ng2-pdf-viewer`. This issue with displaying signature seems to be not resolved. I am using pdf with Adobe signature, but the signature is not displayed when the pdf is loaded (other elements are loaded properly like inputs or checkboxes, etc.). When I get annotations from the component API I see that there is an element with `fieldType` of `'Sig'`. I tested it as well [on the playground page](https://vadimdez.github.io/ng2-pdf-viewer/) and the `'Sig'` element is not displayed. Any update on this issue?
