### ISSUE TITLE
Annotation layer problem on iOS

### ISSUE THREAD

**Issue by aviad-biskits** [VadimDez/ng2-pdf-viewer#831]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
  "dependencies": {
    "@angular/animations": "12.1.2",
    "@angular/cdk": "12.1.2",
    "@angular/common": "12.1.2",
    "@angular/compiler": "12.1.2",
    "@angular/core": "12.1.2",
    "@angular/flex-layout": "^12.0.0-beta.34",
    "@angular/forms": "12.1.2",
    "@angular/localize": "12.1.2",
    "@angular/material": "^12.1.2",
    "@angular/material-moment-adapter": "^12.2.1",
    "@angular/platform-browser": "12.1.2",
    "@angular/platform-browser-dynamic": "12.1.2",
    "@angular/router": "12.1.2",
    "@ng-bootstrap/ng-bootstrap": "^10.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@pdftron/webviewer": "^7.3.3",
    "@swimlane/ngx-charts": "^18.0.1",
    "@types/pdfjs-dist": "^2.7.5",
    "angular2-signaturepad": "^3.0.4",
    "animate.css": "^4.1.1",
    "file-saver": "^2.0.5",
    "hammerjs": "^2.0.8",
    "jsdoc": "^3.6.7",
    "lottie-web": "^5.7.12",
    "mat-table-exporter": "^10.2.3",
    "moment": "^2.29.1",
    "ng2-pdf-viewer": "^7.0.1",
    "ngx-device-detector": "^2.1.1",
    "ngx-image-compress": "^11.0.3",
    "ngx-image-cropper": "^3.3.5",
    "ngx-lottie": "^7.0.3",
    "ngx-toastr": "^14.0.0",
    "npm-check-updates": "^11.8.3",
    "pdfjs-dist": "^2.10.377",
    "rxjs": "^7.2.0",
    "socket.io-client": "^4.1.3",
    "stream": "0.0.2",
    "sweetalert2": "^11.0.18",
    "tslib": "^2.3.0",
    "xlsx": "^0.17.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.1.2",
    "@angular/cli": "^12.1.2",
    "@angular/compiler-cli": "12.1.2",
    "@types/jasmine": "^3.8.1",
    "@types/node": "^16.3.3",
    "protractor": "~7.0.0",
    "ts-node": "~10.1.0",
    "typescript": "^4.3.5"
  }

on iOS the annotation layer is not visible although being rendered, 
the annotation layer has no z-index priority over the canvas.  setting a z-index value and a position on the annotation layer resolve it for me.

**Comment by Akxe** [comment]
How about you make it into a pull request? It should be a simple fix
