### ISSUE TITLE
How to show error msg in ng2pdf viewer for unsupported format

### ISSUE THREAD

**Issue by MohamedSahir** [VadimDez/ng2-pdf-viewer#837]
i am using ng2pdf viewer, the pdf viewer shows pdf if the format is pdf, but other than pdf format we need to show the No preview available, the format is not supported inside document viewer .is there any attribute to show in this case

**Comment by VadimDez** [comment]
Sure thing, there's a [callback called "error"](https://github.com/VadimDez/ng2-pdf-viewer#error) and here how [i used it](https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/app.component.html#L203)
