### ISSUE TITLE
Error when run ionic build ios --prod flag

### ISSUE THREAD

**Issue by filippodicostanzo** [VadimDez/ng2-pdf-viewer#84]
Cannot determine the module for class PdfViewerComponent in /Users/filippodicostanzo/Desktop/IonicProjects/CostaEventiFinal/node_modules/ng2-pdf-viewer/dist/pdf-viewer.component.d.ts!
[10:31:01]  ionic-app-script task: "build" 

Can i resolve it?

`{
  "name": "costa-eventi-app",
  "author": "Filippo Di Costanzo",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/app-scripts": "^1.2.0",
    "@ionic/storage": "1.1.7",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "angularfire2": "^2.0.0-beta.8",
    "date-fns": "^1.28.2",
    "intl": "^1.2.5",
    "ion2-calendar": "^1.0.1",
    "ionic-angular": "2.0.1",
    "ionic-native": "2.4.1",
    "ionic2-calendar": "^0.2.3",
    "ionicons": "3.0.0",
    "moment": "^2.17.1",
    "ng2-pdf-viewer": "^1.1.0",
    "rxjs": "^5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^1.1.4",
    "typescript": "2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "ionic-plugin-keyboard",
    "cordova-plugin-splashscreen"
  ],
  "cordovaPlatforms": [],
  "description": "CostaEventiUpdate: An Ionic project"
}
`

**Comment by VadimDez** [comment]
Does this error still happen in the latest `2.0.2` version?

**Comment by VadimDez** [comment]
Closing, no feedback...
