### ISSUE TITLE
Error " '=' expected" with package when launching 'ng serve'

### ISSUE THREAD

**Issue by Yowims** [VadimDez/ng2-pdf-viewer#842]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I've installed the package but when I'm launching 'ng serve' command I have these errors :

![image](https://user-images.githubusercontent.com/28302626/145373711-f6bafa32-0722-4e1e-b842-ad4a68e5cd44.png)

How can I fix this?

**Comment by VadimDez** [comment]
@Yowims Could you show me your dependencies? What version of `ng2-pdf-viewer` are you using? Are you installing a custom version of pdf-viewer?

**Comment by akyrey** [comment]
I had the same error using version 7 due to tslib version (version 7 requires tslib >= 2.0.0)

**Comment by Florian-crg** [comment]
Same error with "ng2-pdf-viewer": "^7.0.2",
