### ISSUE TITLE
I can't show a file PDF get by blob responseType

### ISSUE THREAD

**Issue by Dilo07** [VadimDez/ng2-pdf-viewer#843]
Hi,
I'm using ng2-pdf-viewer": "7.0.1", and I can't show a pdf file taken from the service that returns a Blob response type.

-- this is my service
 
![image](https://user-images.githubusercontent.com/73889330/145386198-a5f61ffe-298f-4384-b573-d43897d1f15e.png)

--- this is ts file

![image](https://user-images.githubusercontent.com/73889330/145386259-0ee32c52-d96b-4403-bd3d-16c523d2b40a.png)

-- this html file

![image](https://user-images.githubusercontent.com/73889330/145386419-113fe0f9-072e-4dc7-8bce-089c31afb187.png)

-- this is console error
![image](https://user-images.githubusercontent.com/73889330/145386299-73798c31-6afd-4b68-9941-a1b9401af0ad.png)

Could you help me?

**Comment by VadimDez** [comment]
Take a look at this: 
https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/app.component.ts#L51-L65
