### ISSUE TITLE
pdf presentation gets blurry when zooming in

### ISSUE THREAD

**Issue by smout74** [VadimDez/ng2-pdf-viewer#849]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [x] Documentation issue or request
```
Hi,
I have an Ionic (6.0.0) + Angular (13.1.1) + ng2-pdf-viewer (7.0.1) application tho show some pdf's.
The pdf's are from the larger format (A0-format). When zooming in on the details shown in the pdf, the view gets blurry compared to when shown on pc (Adobe Acrobat). Is there some setting to enhance the rendering to get a crisper presentation ?
I attached some screenshots, I hope the difference is still visible after uploading.

Thanks

app:
![app-Window](https://user-images.githubusercontent.com/39618522/148910762-bac38f94-d059-4249-b33a-854fac4d4783.png)

pc:
![pc-Window](https://user-images.githubusercontent.com/39618522/148910786-67535db8-6a5a-4754-9191-6182da4b171e.png)

**Comment by ranouf** [comment]
Did you find a solution?

**Comment by smout74** [comment]
No, not yet, I just upgraded to version 8.0.2 yesterday and was working on other parts of the application. I have had no time yet to test this version on "bigger" pdf's but I expect the result will be the same as before.

**Comment by smout74** [comment]
As a test, I tried the ngx-extended-pdf-viewer module, if you add in your constructor: "pdfDefaultOptions.maxCanvasPixels = -1" your pdf can zoom _a lot sharper_. Keep in mind you should propably add this as an **option** because it makes rendering a lot **slower**. (it has something to do with default rendering up to 4096 x 4096 pixels)

Due to time issues I have not found a similar setting in the ng2-pdf-viewer but I expect there should be a similar setting. Maybe I will look further later.

Hopefully VadimDez can add this as a standard option in the future.

**Comment by stephanrauh** [comment]
@ranouf @smout74 Thanks for recommending my library. :) I suppose it's possible to do the same trick with ng2-pdf-viewer, too. The `maxCanvasPixels` property is a property of the underlying library (pdf.js). At the moment, I can't tell you how to access it, but I'm sure it's possible.

However, I went to great lengths to allow users to use the maximum possible resolution. That's where ngx-extended-pdf-viewer has an edge over every other solution based on pdf.js.

That said, my general recommendation is to use ng2-pdf-viewer if you need a no-nonsense solution. It's fine, and it does the trick for most people. Only use ngx-extended-pdf-viewer if you need the bells and whistles. But if you do, you'll love it! :)

**Comment by smout74** [comment]
@ranouf, I can use/compile it without any issues with angular 13 + ionic 6. I compile as a PWA, not a native app but that probably has nothing to do with it. I also use the "bleeding-edge" option.

@stephanrauh, I see the "maxCanvasPixels" is indeed a setting in the pdf.js, thanks for explaining.

`  (function checkCanvasSizeLimitation() {
    if (isIOS || isAndroid) {
      compatibilityParams.maxCanvasPixels = 5242880;
    }
  })();

...

  maxCanvasPixels: {
    value: 16777216,
    compatibility: compatibilityParams.maxCanvasPixels,
    kind: OptionKind.VIEWER
  },

...

const MAX_CANVAS_PIXELS = _app_options.compatibilityParams.maxCanvasPixels || 16777216;

...

    this.maxCanvasPixels = options.maxCanvasPixels || MAX_CANVAS_PIXELS;
`

**Comment by UsamaParkar** [comment]
Has anyone found a solution for this yet?

**Comment by MaxXx1313** [comment]
So far I've managed to fix it by adding a directive to change `maxCanvasPixels`:

```ts

import { Directive, Host, OnDestroy, OnInit } from '@angular/core';
import { PdfViewerComponent } from 'ng2-pdf-viewer';
import { Subscription } from 'rxjs';



@Directive({
  selector: 'pdf-viewer'
})
export class DetailsDirective implements OnInit, OnDestroy {
  private _sub!: Subscription;

  constructor(
    @Host() private cmp: PdfViewerComponent,
  ) {
  }

  ngOnInit() {
    this._sub = this.cmp.afterLoadComplete.subscribe(() => {
      this.cmp.pdfViewer.maxCanvasPixels = -1;
      this.cmp.pdfViewer.setDocument(this.cmp.pdfViewer.pdfDocument); // reload layout
    });
  }

  ngOnDestroy() {
    this._sub.unsubscribe();
  }

}
```

**Comment by Satyabrata-Pal1** [comment]
@MaxXx1313 How do I use this directive ? Is it to be used in the pdf-viewer component as an attribute directive or Is there some other way

**Comment by MaxXx1313** [comment]
> @MaxXx1313 How do I use this directive ? Is it to be used in the pdf-viewer component as an attribute directive or Is there some other way

It's enough to add it to a module declaration:
@NgModule({
    declarations: [ 
        DetailsDirective,
    ],

**Comment by Satyabrata-Pal1** [comment]
@MaxXx1313 Thank you for replying
this.cmp.pdfViewer.setDocument(this.cmp.pdfViewer.pdfDocument); // reload layout

I am getting the output in the console , however it is not working 
On debugging 
this.cmp.pdfViewer.pdfDocument - is coming as undefined
Is it a version issue? What version are you using?

**Comment by smout74** [comment]
with this directive it works better, it is even possible to gain some speed (if needed) an set the "useOnlyCssZoom" to true.
