### ISSUE TITLE
API Returns Stream, not URL

### ISSUE THREAD

**Issue by derobiom** [VadimDez/ng2-pdf-viewer#85]
My API returns a stream of data representing a pdf, so I do not have a URL.  I suppose that I could work around this by saving on the server and making a second api call.  But are there any examples of rendering  the stream?

**Comment by jjacobs33589** [comment]
I too would like to know if this is possible if I just have a byte array representation of the pdf

**Comment by Sergeon** [comment]
Maybe this kind of workaround can help with your issue in the short term. The idea is to use the `window.Url.createObjectUrl()` to generate a temporary url that serves the blob, and the set it as the pdf-viewer `src`. Let's say you fetch your blob in a component handler like this:

```typescript
     this.service.getDocumentFile(id).subscribe( res => {
         this.blobUrl = window.URL.createObjectURL(res.json() );
     })
```

Then in the component template you use pdf viewer like:
```html
    <pdf-viewer [src]="blobUrl" ... ></pdf-viewer>
```
Then the viewer should display the blob (works on my machine! :-P )
I hope this helps you in the short term.

**Comment by thwefl** [comment]
see also #88 for direct stream usage
