### ISSUE TITLE
Possible Error - PDF Dimension when it has comments

### ISSUE THREAD

**Issue by FabioLins** [VadimDez/ng2-pdf-viewer#851]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

<html>
<body>
<p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">Hi Vadym,</span></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">How are you? I hope fine and safe!</span></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><br aria-hidden="true" style="-webkit-font-smoothing: antialiased;"></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">I would like your help concerning the PDF preview component. We are a little bit crazy about the issue!</span></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><br aria-hidden="true" style="-webkit-font-smoothing: antialiased;"></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><a href="https://www.npmjs.com/package/ng2-pdf-viewer/v/7.0.0" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable" class="x_editor-rtfLink" data-linkindex="0" id="LPlnk547373" style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: rgb(74, 110, 224); background: transparent;"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">https://www.npmjs.com/package/ng2-pdf-viewer/</span></a><div id="LPBorder_GTaHR0cHM6Ly93d3cubnBtanMuY29tL3BhY2thZ2UvbmcyLXBkZi12aWV3ZXIvdi83LjAuMA.." class="LPBorder909061" style="-webkit-font-smoothing: antialiased; margin: 16px 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit; width: 778.5px; position: relative; max-width: 800px; min-width: 424px;">

  | ng2-pdf-viewerAngular 5+ component for rendering PDFwww.npmjs.com
-- | --

</div></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><br aria-hidden="true" style="-webkit-font-smoothing: antialiased;"></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">Scenario:</span></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><br aria-hidden="true" style="-webkit-font-smoothing: antialiased;"></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">We use your library to display the PDF, and we have a "<b style="-webkit-font-smoothing: antialiased;">CDK Drag and Drop</b>" to select a position in the displayed PDF to set up a visual mark related to an "electronic" signature.</span></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><br aria-hidden="true" style="-webkit-font-smoothing: antialiased;"></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">It worked very well until an end-user attached a PDF containing "a comment". </span></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><br aria-hidden="true" style="-webkit-font-smoothing: antialiased;"></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">If it contains a comment in the PDF, then the vertical coordinate (Y) increases between 50 or 100 the size compared to the same PDF without any comments.</span></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><br aria-hidden="true" style="-webkit-font-smoothing: antialiased;"></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">"</span><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit; background: transparent;"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">boundingClientRect.y</span></span><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">"</span></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><br aria-hidden="true" style="-webkit-font-smoothing: antialiased;"></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">Could you help us?</span></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);"><br aria-hidden="true" style="-webkit-font-smoothing: antialiased;"></span></p><p style="-webkit-font-smoothing: antialiased; margin-top: 0pt; margin-bottom: 0pt; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background: transparent; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(14, 16, 26);"><span style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); background: rgba(0, 0, 0, 0);">We use the version: 6.4.1</span></p><div style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><div style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br aria-hidden="true" style="-webkit-font-smoothing: antialiased;"></div><div style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Best regards,</div><div style="-webkit-font-smoothing: antialiased; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Fábio Pacheco</div>
</body>
</html>

**Comment by Piyush132000** [comment]
hii, if anyone not working on it then I want to contribute.
