### ISSUE TITLE
Encourage the library authors to publish an Ivy distribution.

### ISSUE THREAD

**Issue by Odonno** [VadimDez/ng2-pdf-viewer#852]
Like it is said, will you consider moving to Ivy?

**Comment by medziedcherif-tn** [comment]
yes you need to publish new updates for Ivy!

**Comment by PhilippSonntagORGADATA** [comment]
[Pull Request](https://github.com/VadimDez/ng2-pdf-viewer/pull/857) was created for Angular 13 / Ivy update.

**Comment by NashIlli** [comment]
+1 Thanks!

**Comment by VadimDez** [comment]
Done as #857 is merged and version [8.0.0](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/8.0.0) is released
