### ISSUE TITLE
Error on charge on Safari

### ISSUE THREAD

**Issue by luisdalopez56** [VadimDez/ng2-pdf-viewer#860]
##### Bug Report or Feature Request (mark with an `x`)
```
- [X] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
It seems that the previous support for Safari has stopped working, and now on my MAC I can't see the pdfs, this happens in the latest versions it seems to be. I am using angular with version 7.0.2

**Comment by VadimDez** [comment]
Does [this demo](https://vadimdez.github.io/ng2-pdf-viewer/) work fine for you?
