### ISSUE TITLE
pdfComponent.pdfLinkService.navigateTo is not working on ng2-pdf-viewer in angular8

### ISSUE THREAD

**Issue by yugal236** [VadimDez/ng2-pdf-viewer#867]
<div *ngIf="outline">
      <ul *ngFor="let item of outline" class="outline-list">
        <li>
          <a (click)="navigateTo(item.dest)" id="{{item.dest}}">
            {{ item.title }}
          </a>

          <ul *ngFor="let child of item.items">
            <li>
              <a (click)="navigateTo(child.dest)">
                {{ child.title }}
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  afterLoadComplete(pdf: PDFDocumentProxy) {
    this.pdf = pdf;

    this.loadOutline();
  }
  loadOutline() {
    this.pdf.getOutline().then((outline: any[]) => {
      this.outline = outline;
    });
  }
 navigate(destination: any) {
    this.pdfComponent.pdfLinkService.navigateTo(destination);
  }

//Getting Error

ERROR TypeError: this.pdfComponent.pdfLinkService.navigateTo is not a function

**Comment by YishuVohra** [comment]
I am facing the same issue also, any updates?
