### ISSUE TITLE
Render text layer to html

### ISSUE THREAD

**Issue by handyCAPS** [VadimDez/ng2-pdf-viewer#87]
Is there any way to use renderTextLayer to get an HTML overlay to select the text from ? I can't currently select the text from a pdf without getting extra spaces and repeating words. [This example](https://vi-dot.github.io/ng2-pdf-viewer/) does pretty much exactly what I need, but I can't get that code to work.

**Comment by VadimDez** [comment]
What about version `1.1.5` ?

**Comment by eoliveiramg** [comment]
i have this problem, and i use 1.2.5 version.

**Comment by VadimDez** [comment]
Have you tried version `2.0.2`?

**Comment by eoliveiramg** [comment]
Not, but i will try.
