### ISSUE TITLE
Rotation not working properly while switching between diffrent pdf

### ISSUE THREAD

**Issue by MohamedSahir** [VadimDez/ng2-pdf-viewer#870]
- [ x] Bug report -> please search issues before submitting
.

we have menu like page1 , page2 ....page n. each page click send the request and bind the pdf and rotation saved in database.

when click between page 1 and page 2 , for each page get response from server. but page rotation not working properly its shows incorrect behaviour -180 shows as 180 sometimes, 180 shows as -180 sometimes.

For reproduce that , i have create sample demo with dummy data in stackblitz
[demo](https://stackblitz.com/edit/ng2-pdf-viewer-xlmitp?file=src%2Fapp%2Fapp.component.ts).

video attached.

https://user-images.githubusercontent.com/20682302/154682210-860fbbde-2f2f-43e1-8f01-e6c11592c1b6.mp4

![image](https://user-images.githubusercontent.com/20682302/154681430-5cfe7088-929b-484c-b130-a0de53898c59.png)

solution tried. not works

add change detection, setTimeout  and   afterLoadComplete(pdfData: any): void {
        this.rotate = -180; // set rotation value from  database 
}

**Comment by VadimDez** [comment]
Using your demo I don't get the same behaviour as you do. For me it seems to work fine.
Isn't rotation -180 equal to 180 in UI anyway?

**Comment by MohamedSahir** [comment]
@VadimDez  yes 180 is not same as -180. i think you misunderstood my question. please click between the document 1 and document 2 up-to 10 times , you can reproduce the scenario  1 time, 1 document will showing different angle in between it will change .
Again i have attached a video, 


still issue exist we can reproduce more frequently in real-time development.
Now in this case also while switching two pdf with different rotation, initially rotation showing as top to bottom or bottom  to top and again its changing it reverse .

usecase not working : setting different document with rotation.

intially 0.
document  => 1.pdf 
rotation=> 180

document =>2.pdf 
rotation => -180

document 3=> 3.pdf 
rotation => 90


rotation works properly in this scenario .without setting different src , setting the rotation alone works as expected.

https://user-images.githubusercontent.com/20682302/154799207-eb574dd7-c5a4-4220-ae5c-ce7932c1ea5c.mp4

**Comment by MohamedSahir** [comment]
@VadimDez  any quick solution for this issue, Basically we want a feature like save caching for rotation for each pdf items, there is no built-in cache feature available , that's what we are storing the rotation degree in  database and sending along with each pdf . at that time frequently issue occurs .the rotation angle not properly  updated in angular view.

if you are not able to reproduce the issue , let me know
