### ISSUE TITLE
Print PDF doesn't work in Mobile devices (both Android, iOS)

### ISSUE THREAD

**Issue by saivenkateshkurella93** [VadimDez/ng2-pdf-viewer#872]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request

```
Hi,

I have been trying to implement the PDF print functionality across Windows, Mac, Android and iOS devices. 
Printing PDF works fine on Windows and Mac Laptop/Desktop devices. But it doesn't work in Mobile devices(Both Android/iOS).

Here is the code snippet for your reference:

in templete file:
```
<pdf-viewer
	[src]="blobUrl"
	[render-text]="true"
	[external-link-target]="'blank'"
	[original-size]="false"
	[zoom-scale]="'page-width'"
         [style]="{ height: 'fit-content' }"
	>
</pdf-viewer>
```

in the component file: 
```
onPrintPdf() {
	const iframe = document.createElement('iframe');
	iframe.style.display = 'none';
	iframe.src = this.blobUrl;
	document.body.appendChild(iframe);
	iframe.contentWindow.print();
	   }
```

In iOS devices, it only prints the first page and in Android devices, it's a blank page.
On debugging, observation is that in iOS devices, PDF has an `<img>` tag where as in windows/Mac laptops it's an `<embed>` tag. Does this has to do anything with the OS? Not sure if this a good pointer, but just an observation made if it might help.

Would appreciate your response on this issue.

Thanks.

**Comment by Hirokumi** [comment]
Hello, 

I see the same problem impossible to display the pdf on mobile. Tested on iOS (iPad, iPhone), and Android (Huawei, OnePlus, Samsung). On chrome, Safari, Samsung Browser, and into a web view

The screen remains white and the pageInitialized event is not launched.

![image](https://user-images.githubusercontent.com/2638564/158155210-50319ff9-1d07-4cca-ba25-b205bf7f908b.png)

**Comment by thoechtl** [comment]
Try setting the height to 100% oder a pixel value, `fit-content` did not work for me, too. I use `style="display: block; height: 100%"` and it works fine on mobile and desktop.

**Comment by saivenkateshkurella93** [comment]
> Try setting the height to 100% or a pixel value, `fit-content` did not work for me, too. I use `style="display: block; height: 100%"` and it works fine on mobile and desktop.

thanks for your input @thoechtl . I tried style="display: block; height: 100%" but it still only prints only the first page of the document in mobile iOS device.

**Comment by saivenkateshkurella93** [comment]
@VadimDez Please have at look at this when you get a chance. Thanks.

**Comment by davidoween** [comment]
The same happens to me. any solution?
