### ISSUE TITLE
Not working in mobile app for both android and ios

### ISSUE THREAD

**Issue by sundarvelu** [VadimDez/ng2-pdf-viewer#876]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x ] Feature request
- [ ] Documentation issue or request
```
I am not able to see pdf file in viewer. It seems like an blank screen

**Comment by thoechtl** [comment]
For me it works in an Ionic/Angular app for iOS and Android. Maybe you forgot to set the style attributes width and height ...

**Comment by crrajaguru** [comment]
For me not working in mobile chrome browser(Style attributes width and height given). It works on system only.

**Comment by vishwanath1004** [comment]
I am facing the same issue. Can someone help me in this?
