### ISSUE TITLE
Project failed to compile for ng2-pdf-viewer 5.3.4

### ISSUE THREAD

**Issue by adkeaesph007** [VadimDez/ng2-pdf-viewer#877]
Getting the below error while compilation for ng2-pdf-viewer versions from 3 to 5.3.4- 
ERROR in node_modules/pdfjs-dist/types/src/display/api.d.ts(1431,5): error TS1127: Invalid character.
node_modules/pdfjs-dist/types/src/display/metadata.d.ts(10,5): error TS1127: Invalid character.

node version - 12.9.0
npm version - 6.9.0

angular-cli - 7.3.9

Note - Upgrading the angular cli version is not an option, as doing so would lead to many other errors.

**Comment by pysingh09** [comment]
I fixed the same problem by installing this pdfjs-dist manually 

`npm install @types/pdfjs-dist@2.1.7`

**Comment by lakinmindfire** [comment]
Issue happened again
