### ISSUE TITLE
Cant use pipes when src includes options

### ISSUE THREAD

**Issue by shamoon** [VadimDez/ng2-pdf-viewer#878]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Hi, thanks for this package, its great. I have an issue that either I could use some help with a workaround or i have an idea how to 'fix'.

I have implemented a password prompt for protected pdfs, this works great using similar code as described [here](https://github.com/VadimDez/ng2-pdf-viewer/issues/283). The problem is that in order to use this I need to set the `password` option of `src` and then I can no longer use my `safeUrl` pipe which runs `this.sanitizer.bypassSecurityTrustResourceUrl`.

If you try to do something like:
```
this.viewerSrc = {
        url: this.safeUrlPipe.transform(this.pdfUrl),
        password: this.password,
      }
```
or
```
<pdf-viewer [src]="{ url: pdfUrl | safeUrl, password: password }"
```
you get the error [`Safe value must use [property]=binding after bypass security with DomSanitizer`](https://stackoverflow.com/questions/45351434/safe-value-must-use-property-binding-after-bypass-security-with-domsanitizer). In other words, you cant do that.

### Possible Solution
I would be happy to (try to) implement a PR for this if you are interested @VadimDez but the only solution I can think of is to change the component to separate the URL and options, so it could be used like:
`<pdf-viewer [url]="pdfUrl | safeUrl" [options]="{ password: password }">...`

I could imagine that change wouldn't be so hard to do, and we could maintain backwards compatibility but I wouldn't try unless you think it would be helpful.

Otherwise, is there a workaround for this I havent thought of?

Thanks all!

**Comment by VadimDez** [comment]
Could you try something like this?

```ts
this.viewerSrc = {
  url: this.sanitizer.sanitize(SecurityContext.RESOURCE_URL, this.safeUrlPipe.transform(this.pdfUrl))!,
  password: this.password,
}
```

**Comment by shamoon** [comment]
Thanks for your reply! I think this works because it effectively undoes what the pipe did =)

*But* Im not positive I need to sanitize the URL the pdf viewer at all.

Either way, I will close this and update things if I figure out otherwise. Thank you again!
