### ISSUE TITLE
Display PDF from Byte Array

### ISSUE THREAD

**Issue by jjacobs33589** [VadimDez/ng2-pdf-viewer#88]
I'm hitting a service that generates a pdf based on data sent it and returns the pdf in a byte array. Is there a way to use this plugin to display the pdf?

**Comment by thwefl** [comment]
@jjacobs33589
 Yeah, it's possible. The 'source' Input can handle with string | Uint8Array | PDFDocumentProxy.

In my application i use an Uint8Array.
```typescript
  public downloadUint8Array(fileUrl: string): Observable<Uint8Array> {
    return this._http
      .get(fileLink, { responseType: ResponseContentType.ArrayBuffer })
      .map((response: Response) => response.arrayBuffer())
      .map((arrayBuffer: ArrayBuffer) => new Uint8Array(arrayBuffer))
      .first();
  }
```

**Comment by jjacobs33589** [comment]
Thank you @thwefl 

I tried that and I'm able to get the pdf back as a Uint8Array but when I try to display it I get the following error
pdf.combined.js:39233 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.

polyfills.js:3 GET http://localhost:8100/37,80,68,70,45,49,46,52,10,37,226,227,207,211,10,56,3…,10,115,116,97,114,116,120,114,101,102,10,56,56,50,53,10,37,37,69,79,70,10 404 (Not Found)

It's still trying to treat it as a link to a pdf instead of a Uint8Array

in my ts file I have it declared as follows

`pdf: Uint8Array`

In my html file I have 

`<pdf-viewer src="{{pdf}}" original-size="true" show-all="true"></pdf-viewer>`

Am I displaying it wrong?

**Comment by thwefl** [comment]
@jjacobs33589 
I could reproduce your error. You forget the square brackets for the 'src' input. In your example it uses the native 'src' HTML attribute. That's the reason for your error.

Try to change your code from
```html
<pdf-viewer src="{{pdf}}" original-size="true" show-all="true"></pdf-viewer>
```
into 

(one-time binding)
```html
<pdf-viewer [src]="pdf" original-size="true" show-all="true"></pdf-viewer>
```
or 

(two-way binding)
```html
<pdf-viewer [(src)]="pdf" original-size="true" show-all="true"></pdf-viewer>
```

**Comment by jjacobs33589** [comment]
That was it! It's working for me now. Thank you!

**Comment by Darey0406** [comment]
I am doing the same operation to retreive the byte array , but the PDF viewer is displaying blank. I am displaying it in modal pop up.
```
    preview(any:Any): Observable<Uint8Array>{
        return this.http.post(API_BASE_URL+'/api/CreatePdf',JSON.stringify(any),this.authenticationService.getToken('application/json'))
        .map((response: Response) => response.arrayBuffer())
      .map((arrayBuffer: ArrayBuffer) => new Uint8Array(arrayBuffer))
      .first();
    }
```
   ```
 pdfSource: Uint8Array;
    OnPreview()
    {
        this.Service.preview(this.data).subscribe(
x=> this.pdfSource = x, 
            error => {
                if (error.status == 404) {
                } else {
                    this.alertService.error(error)
                }
            }
        );
    }
```

```
  <pdf-viewer [src]="pdfSource" 
              [original-size]="true" 
              [show-all]="true"
              [zoom]="1.3"
  ></pdf-viewer>
```

**Comment by pawantiwari1** [comment]
Yes Same problem facing also return stream of bytes and print in console but not display in page i am using pdfviewer and iframe tage in html  please suggest as a full code how to display a page

**Comment by lauraiurb** [comment]
Same problem here, is not displaying the pdf...please show an example

**Comment by robinmaple** [comment]
Same issue here. No errors, but pdf is not showing.

**Comment by VadimDez** [comment]
Here's and example how to load pdf with `HttpClient`:

```ts
import { Component } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';

@Component({
  selector: 'app-root',
  template: `<pdf-viewer [src]="pdfSrc" [show-all]="true"></pdf-viewer>`
})
export class AppComponent {
  pdfSrc: any;

  constructor(private http: HttpClient) {
    this.http.get('https://vadimdez.github.io/ng2-pdf-viewer/pdf-test.pdf', { responseType: 'arraybuffer' })
    .subscribe((file: ArrayBuffer) => {
      this.pdfSrc = new Uint8Array(file);
      // or directly passing ArrayBuffer
      // this.pdfSrc = file;
    });
  }
}
```

 Let me know if it works for you

**Comment by robinmaple** [comment]
My Web API returns PDF file as byte[]. To get it working, I have to do a conversion to Uint8Array. Hopefully this helps.

         this._http.get(URL)
            .map((file:any) => file.json())
            .subscribe(
                (data:any) => {
                        this.src=this.convertDataURIToBinary(data);
                }
            );

    convertDataURIToBinary(dataURI: string) {
        var raw = window.atob(dataURI);
        var rawLength = raw.length;
        var array = new Uint8Array(new ArrayBuffer(rawLength));
    
        for(var i = 0; i < rawLength; i++) {
        array[i] = raw.charCodeAt(i);
        }
        return array;
    }

**Comment by thanveerahamed** [comment]
Hi Vadim,

I was able to setup ng2-pdf-viewer by following all the steps mentioned on your blog. I am trying to load the pdf on ngInit(). For some reason, the pdf even with a single page takes forever to load. Shows loading screen always. When I did inspect element on chrome and removed the class "removePageBorders" for one of the div, the pdf is visible immediately. I was also able to see a warning in Chrome console. 

pdf.js:7064 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.

It would be great if you can help cross this roadblock. Let me know if you need more info.

**Comment by VadimDez** [comment]
@thanveerahamed check out the source how i used this component in the demo https://github.com/VadimDez/ng2-pdf-viewer/tree/master/src/app

**Comment by thanveerahamed** [comment]
Thank you @VadimDez . I was able to get it working with some tweaks. It works perfectly as expected. But I see some error on "ng serve".

ERROR in src/app/purchaseorderreviewform/purchaseorderreviewform.component.ts(48,19): error TS2304: Cannot find name 'PDFProgressData'.
src/app/purchaseorderreviewform/purchaseorderreviewform.component.ts(77,7): error TS2304: Cannot find name 'PDFJS'.
src/app/purchaseorderreviewform/purchaseorderreviewform.component.ts(84,28): error TS2304: Cannot find name 'PDFDocumentProxy'.
src/app/purchaseorderreviewform/purchaseorderreviewform.component.ts(104,30): error TS2304: Cannot find name 'PDFProgressData'.

I tried to remove these variables, but after that the pdf never loaded. Keeping them works, but gives these errors. 

Please advise.

**Comment by VadimDez** [comment]
@thanveerahamed get the latest version `3.0.7`

**Comment by bhushangahire** [comment]
PDF-1.4 ArrayBuffer Stream is not rendering the PDF. But the Sample from above is rendering fine which is PDF-1.3. Is there any issue or I am missing anything? 
FYI, I am using Promise Http Get call.
