### ISSUE TITLE
Getting an error when running my code

### ISSUE THREAD

**Issue by karol-oman** [VadimDez/ng2-pdf-viewer#884]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Getting this issue when I run my server:
`ERROR in node_modules/pdfjs-dist/types/src/display/api.d.ts(1431,5): error TS1127: Invalid character.`
`web-app_1  | node_modules/pdfjs-dist/types/src/display/metadata.d.ts(10,5): error TS1127: Invalid character.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(1,13): error TS1005: '=' expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(1,40): error TS1005: ';' expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(2,13): error TS1005: '=' expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(2,38): error TS1005: ';' expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(3,1): error TS1128: Declaration or statement expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(3,13): error TS1005: ';' expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(3,87): error TS1005: ';' expected.`

**Comment by danielehrhardt** [comment]
What was the problem?
