### ISSUE TITLE
When pdf is behind secure / authenticated end point

### ISSUE THREAD

**Issue by slusset** [VadimDez/ng2-pdf-viewer#886]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ x] Feature request
- [ ] Documentation issue or request
```
If the [src] refers to a PDF that is behind a secure URL how to intercept the Http request to set the Bearer token on the request headers?  I have an Http Interceptor for http requests originating from Angular, however the PDF [src] tag I believe utilizes the browser native http functionality which does not get intercepted.

**Comment by ftaffelt** [comment]
Sounds like #309. In the Options option object you should be able to pass your bearer token as an Http Header.
