### ISSUE TITLE
Closing Large Files - Transport destroyed

### ISSUE THREAD

**Issue by og77036** [VadimDez/ng2-pdf-viewer#889]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Hi,

I tried to search for this issue before submitting but couldn't find an answer on how to resolve. I found issue when opening a large file (~200 pages) and closing it is throwing "pdf_viewer.js:9203 Unable to get page 'n' to initialize viewer Error: Transport destroyed". This is because it is closing before all pages are rendered. We would like to be able to close a file without having to wait for all to finish rendering. I tried calling the destroy() on the PDFDocumentProxy and cleanup() and also tried setting it to null but none are working.

**Comment by Et3rnal** [comment]
I have the same issue. It doesn't go through `(error)` or any other event!

The exception/error appears for every page in the file that didn't get to render
Stack:
![image](https://user-images.githubusercontent.com/441522/171091949-18a405ea-b7df-4118-9d2c-c3a9090a565b.png)

The error will appear if the view is closed/destroyed while the page is rendering (the loader is still visible, but half the page is rendered only)
