### ISSUE TITLE
I get watermark instead of pdf

### ISSUE THREAD

**Issue by segfaultDelirium** [VadimDez/ng2-pdf-viewer#890]
I get this watermark instead of the pdf, is this supposed to be like that? 
![remove_watermark](https://user-images.githubusercontent.com/82722872/167912818-21432545-be93-4325-93d6-a8a5457fa90d.png)

here is html part:
`<pdf-viewer 
        [src]="pdf"
        [render-text]="true"
        [original-size]="false"
        style="width: 400px; height: 500px"
      ></pdf-viewer>`

here is ts part:
`this.http.post(generateSPZUrl, payload, {
      responseType: 'blob'
    }).subscribe(async blob => {
      this.pdf = await (blob as Blob).arrayBuffer();
    });`

**Comment by VadimDez** [comment]
Code looks ok

**Comment by segfaultDelirium** [comment]
sorry, this was backend issue
