### ISSUE TITLE
Namespace '"Z:/Manish_Project/pdf-viewer-project/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

### ISSUE THREAD

**Issue by man88100ni** [VadimDez/ng2-pdf-viewer#892]
ERROR in ./node_modules/pdfjs-dist/build/pdf.js 2418:53
Module parse failed: Unexpected token (2418:53)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
intent: renderingIntent,
renderInteractiveForms: renderInteractiveForms === true,
annotationStorage: annotationStorage?.getAll() || null
});
}
ERROR in ./node_modules/pdfjs-dist/web/pdf_viewer.js 895:20
Module parse failed: Unexpected token (895:20)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
this._on(eventName, listener, {
external: true,
once: options?.once
});
}

node version => v12.16.1

Angular CLI: 9.1.15
Node: 12.16.1
OS: win32 x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

@angular-devkit/architect 0.901.15
@angular-devkit/build-angular 0.901.15
@angular-devkit/build-optimizer 0.901.15
@angular-devkit/build-webpack 0.901.15
@angular-devkit/core 9.1.15
@angular-devkit/schematics 9.1.15
@angular/cli 9.1.15
@ngtools/webpack 9.1.15
@schematics/angular 9.1.15
@schematics/update 0.901.15
rxjs 6.5.5
typescript 3.8.3
webpack 4.42.0

**Comment by tattivitorino** [comment]
same here
