### ISSUE TITLE
How to jump to specific line in PDF?

### ISSUE THREAD

**Issue by AnderssonPeter** [VadimDez/ng2-pdf-viewer#894]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```

Hi I see that i can use `page` to jump to a specific page, but i need to jump to a specific line of a specific page, i have the y coordinate if that helps.

**Comment by VijiSridhar95** [comment]
@AnderssonPeter . It would be helpful if you can share the code here. How did you get the y co-ordinate, in which callback did you get the co-ordinate and jump to the specific line?

**Comment by AnderssonPeter** [comment]
Sorry I don't have access to that project any more :(

**Comment by VijiSridhar95** [comment]
@AnderssonPeter  any reference how  destArray works. (destArray: [undefined, { name: 'XYZ' }, 0, this.y] ) What is 'XYZ' 
?

**Comment by AnderssonPeter** [comment]
Can't remember but I think it's a magic string so you should not change it.

To get the y coordinate of the line you have to use pdfjs to analyse the pages and the pages texts.

This was something we did at build time.
