### ISSUE TITLE
PDF Viewer does not work with PDF from byte array

### ISSUE THREAD

**Issue by No1e** [VadimDez/ng2-pdf-viewer#895]
Hi Vadym,

we have specific requirement to load PDF from byte array, becase we get PDFs from the server side as byte array. We tried that out, but for some reason it does not work.

Can you please give us an example app, where this works?

Thank you and best regards,
Novak

**Comment by VadimDez** [comment]
[Not sure if this helps](https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/app.component.ts#L51-L65) otherwise search through issues, there were multiple questions about how to show pdf from backend

**Comment by seal-tm** [comment]
@VadimDez By changing my Solution with an ArrayBuffer to use a Blob and then URL.createObjectURL(...) the Application can now displays the PDF again.

In my case I updated ng2-pdf-viewer 7.0.1 to 9.0.0
