### ISSUE TITLE
EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on PdfViewerComponent

### ISSUE THREAD

**Issue by nessgor** [VadimDez/ng2-pdf-viewer#9]
pdf.html
```
<ion-header>
  <ion-toolbar>
    <ion-title>
      {{pdf.name}}
    </ion-title>
    <ion-buttons start>
      <button (click)="dismiss()">
        <span primary showWhen="ios">Cancel</span>
        <ion-icon name="md-close" showWhen="android,windows"></ion-icon>
      </button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>

<ion-content>
  <pdf-viewer src="{{pdf.url}}" [original-size]="false" [show-all]="true"></pdf-viewer>
</ion-content>
```

pdf.ts
```
import { Component } from '@angular/core';
import { Platform, NavParams, ViewController } from 'ionic-angular';
import { PdfViewerComponent } from 'ng2-pdf-viewer';

@Component({
  templateUrl: 'build/pages/pdf/pdf.html',
  directives: [PdfViewerComponent]
})

export class PDFContentPage {
  pdf;

  constructor(
      public platform: Platform,
      public params: NavParams,
      public viewCtrl: ViewController
  ) {
    this.pdf = {
      name: this.params.get("name"),
      url:  this.params.get("url"),
    }
  }

  dismiss() {
    this.viewCtrl.dismiss();
  }
}
```

Got stuck when using @0.0.9, error stack:
![1](https://cloud.githubusercontent.com/assets/11316684/18035857/a56ebf14-6d90-11e6-9a2b-3b108f9d31f9.PNG)
![2](https://cloud.githubusercontent.com/assets/11316684/18035859/a808cbac-6d90-11e6-8d0c-004942cfe148.PNG)
![3](https://cloud.githubusercontent.com/assets/11316684/18035860/a9fce542-6d90-11e6-82a7-a15089cdfb1a.PNG)
![4](https://cloud.githubusercontent.com/assets/11316684/18035862/abcfb3fe-6d90-11e6-8c0a-5f126c082627.PNG)
![5](https://cloud.githubusercontent.com/assets/11316684/18035863/ad8adb60-6d90-11e6-94c1-62448abb5b49.PNG)

Really have no idea what's going on this time.

**Comment by nessgor** [comment]
package.json
```
{
    "dependencies": {
        "@angular/common": "2.0.0-rc.3",
        "@angular/compiler": "2.0.0-rc.3",
        "@angular/core": "2.0.0-rc.3",
        "@angular/platform-browser": "2.0.0-rc.3",
        "@angular/platform-browser-dynamic": "2.0.0-rc.3",
        "@angular/http": "2.0.0-rc.3",
        "es6-shim": "^0.35.0",
        "ionic-angular": "2.0.0-beta.10",
        "ionic-native": "1.3.2",
        "ionicons": "3.0.0",
        "reflect-metadata": "^0.1.3",
        "rxjs": "5.0.0-beta.6",
        "zone.js": "^0.6.12",
        "angularfire2": "2.0.0-beta.2",
        "firebase": "3.2.1",
        "ng2-pdf-viewer": "0.0.9",
        "moment": "2.14.1"
    },
    "devDependencies": {
        "del": "2.2.0",
        "gulp": "3.9.1",
        "gulp-tslint": "^5.0.0",
        "gulp-watch": "4.3.5",
        "ionic-gulp-browserify-typescript": "^1.1.0",
        "ionic-gulp-fonts-copy": "^1.0.0",
        "ionic-gulp-html-copy": "^1.0.0",
        "ionic-gulp-sass-build": "^1.0.0",
        "ionic-gulp-scripts-copy": "^2.0.0",
        "ionic-gulp-tslint": "^1.0.0",
        "run-sequence": "1.1.5",
        "tslint": "^3.10.1",
        "tslint-ionic-rules": "^0.0.3"
    },
    "cordovaPlugins": [
        "cordova-plugin-device",
        "cordova-plugin-console",
        "cordova-plugin-whitelist",
        "cordova-plugin-splashscreen",
        "cordova-plugin-statusbar",
        "ionic-plugin-keyboard",
        "cordova-plugin-inappbrowser"
    ],
    "cordovaPlatforms": [
        "ios", {
            "platform": "ios",
            "version": "",
            "locator": "ios"
        }
    ],
    "name": "fbtest",
    "description": "fbtest: An Ionic project"
}
```

**Comment by VadimDez** [comment]
@nessgor, Thanks! Tried it myself and i think it might be because of incompatible versions. The component uses RC5 as dependency since version 0.0.8.

**Comment by sd5869** [comment]
Facing the same issue can you suggest any work around I have tried 

- [FileOpener](http://ionicframework.com/docs/v2/native/fileopener/)

**Comment by nessgor** [comment]
I have found a similar issue:
http://stackoverflow.com/questions/35971299/angular2-exception-no-directive-annotation-found-on-alert/35978010

I follow the solution provided by Murhaf Sousli and the issue is gone!
Hope it help the others!

**Comment by sd5869** [comment]
Even downgrading to version 0.0.7 fixes the issue then refer to [#5](https://github.com/VadimDez/ng2-pdf-viewer/issues/5) to get things working

**Comment by calebsimmons** [comment]
Can there be a version that implements the fix at [#5](https://github.com/VadimDez/ng2-pdf-viewer/issues/5) but uses RC4 as a dependency? This package works great with ionic2 but ionic will not move to RC5 until beta 12 is released. They have no confirmed date on when that will happen, so it would be helpful to have a repo that has compatible code with ionic at beta 11.

**Comment by VadimDez** [comment]
I published `0.0.8-alpha.1`, please check if that solves the problem

**Comment by calebsimmons** [comment]
Yes, this seems to work. Thanks!

**Comment by nessgor** [comment]
0.0.8-alpha.1 works perfectly. Sweet.

**Comment by VadimDez** [comment]
Thanks for feedback!
