### ISSUE TITLE
Support for download files

### ISSUE THREAD

**Issue by ahmedabdelhafez** [VadimDez/ng2-pdf-viewer#906]
please add support to donwload the pdf file

**Comment by JulienLecoq** [comment]
Yes, this would be very cool

**Comment by SoyDiego** [comment]
Have the same problem here. On Iphone (Browser Chrome) doesn't work.
Hope can fix that.

Thanks!

**Comment by WasiakSzymon** [comment]
Agree, it would be very nice to have download option
