### ISSUE TITLE
Height and Width of pdfviewer container.

### ISSUE THREAD

**Issue by thegreatrravi111** [VadimDez/ng2-pdf-viewer#910]
Suppose we have a pdf with some pages oriented as horizontal and some pages are in portrait then how we can keep ideal size for pdfviewer !
Because if we fixed the width and height it will cut it.

**Comment by VadimDez** [comment]
You can see what I've done here: https://vadimdez.github.io/ng2-pdf-viewer/
Here's [demo. source code](https://github.com/VadimDez/ng2-pdf-viewer/tree/master/src/app)
