### ISSUE TITLE
Original-size causes the pdf not to display

### ISSUE THREAD

**Issue by daBishMan** [VadimDez/ng2-pdf-viewer#93]
The following is the way I have my pdf-viewer working.   
`<pdf-viewer [src]="resumePdfViewerObject"
                      [page]="page"
                      [zoom]="zoom"
                      [rotation]="0"
                      [render-text]="false"
                      [show-all]="showAll"
                      [original-size]="true"
                      (after-load-complete)="onLoadComplete($event)">
          </pdf-viewer>
`

if I change the original-size to false, the pfd does not display, any ideas ?

**Comment by daBishMan** [comment]
not a component issue

**Comment by kilofafeure** [comment]
Could you explain how you solved it? I am also experiencing the same thing and I am not able to solve it. Thanks in advance.

**Comment by mikelweb** [comment]
Mee too, the same issue. Any clue?

**Comment by daBishMan** [comment]
My viewer in angular Cli 1.3.0 and NG 4.2.4 is

>  <div class="pt-1 px-0 container"
           style="overflow-x: auto;">
        <pdf-viewer *ngIf="resumePdfViewerObject"
                    [src]="resumePdfViewerObject"
                    [page]="page"
                    [zoom]="zoom"
                    [rotation]="0"
                    [render-text]="false"
                    [show-all]="showAll"
                    [original-size]="originalSize"
                    class="resume-pd-viewer"
                    (after-load-complete)="onLoadComplete($event)"
                    [style.display]="resumeViewerHidden === true ? 'none' : 'block'">
        </pdf-viewer>
      </div>

my resumePDFViewerObject is:

` this.resumePdfViewerObject = {
            url: resumeViewerUrl,
            withCredentials: true
         };`

that seems to work for me, I hope that is helpful
