### ISSUE TITLE
zoom-scale

### ISSUE THREAD

**Issue by Karman40** [VadimDez/ng2-pdf-viewer#933]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Hello,

I would like to create an A4 size preview block.

I know the width of the element (box - 24px) and based on this I calculate its height proportionately. (box - 24px * 1.4142)

In this case, in principle, I will receive an A4 size block.
Nevertheless, when you load an A4 PDF file, for some reason it can be scrolled in both the y and x directions.
How can I eliminate this?

```
<pdf-viewer
     [src]="file"
     [original-size]="false"
     [external-link-target]="'blank'"
     [ngStyle]="{width: '100%', height: (box2.offsetWidth-24)*1.4142+'px'}"
></pdf-viewer>
```

If `overflow-x: hidden`, then the height is perfect.
If `overflow-y: hidden`, then the width is perfect.
However, by default, the pdf file hangs below the scroll bar on both the "x" and "y" axes.

In the case of a 1-page PDF file, the 10px margin-bottom value is unnecessary and the box will be too small.
In the case of multi-page PDF files, the 10px value after the last page is unnecessary and confusing.

In addition to the height error, the width must be appropriate and fit the content.

![image](https://user-images.githubusercontent.com/32225709/195610502-cdcfc0e9-72b4-4a10-90b6-57937ed8805f.png)

**Comment by Karman40** [comment]
@VadimDez Do you have any suggestions?

**Comment by guppylein** [comment]
I had a similar problem with horizontal scrollbar shown when using ```[zoom-scale]="'page-width'"```.

I think the problem is that an inner container takes up too much space. The problem can be made clearer if you set ```[show-borders]="true"```, then you see, that the right border is cut off.

Adding the following style in my components scss-file resolved my problem:
```
::ng-deep .pdfViewer .page {
    overflow: hidden !important;
}
```

**Comment by Karman40** [comment]
@guppylein I tried it, unfortunately it didn't help me.
