### ISSUE TITLE
Upgrade to use a supported version of pdf.js

### ISSUE THREAD

**Issue by naviln** [VadimDez/ng2-pdf-viewer#936]
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [] Feature request
- [ ] Documentation issue or request
```

Hi there,
I reported a bug that is affecting my users over at the pdf.js repo: https://github.com/mozilla/pdf.js/issues/15629

Which they have kindly resolved and merged into their main branch.

ng2-pdf-viewer is still using pdfjs-dist version: 2.14.305, which they have told me is not supported.

I was just wondering if it is possible to migrate forward to the latest version of pdf.js - 2.16.105? 
(I really want this bugfix!)

Thanks

**Comment by egonknapen** [comment]
I specify which pdf.worker is being used, by:

		(window as any).pdfWorkerSrc = './assets/pdfjs/pdf.worker.min.js';
		pdfjsLib.GlobalWorkerOptions.workerSrc = './assets/pdfjs/pdf.worker.min.js';


You could just download the latest and try it.

**Comment by naviln** [comment]
@egonknapen Thanks for your response!

So I've had a go at adding the latest pdfjs distribution to my angular project.

I've added "pdfjs-dist": "^3.0.279" to my package.json file, and over in angular.json added a command to copy it into /assets/pdfjs like this:

```
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            etc...
            "assets": [
              {
                "glob": "**/*",
                "input": "node_modules/pdfjs-dist/build/",
                "output": "/assets/pdfjs/"
              }
```

Then I added the command to my component as you suggested (on ngOnInit):

`(window as any).pdfWorkerSrc = './assets/pdfjs/pdf.worker.min.js';`

I ran the app, and unfortunately faced this error:

```
Error captured:  Error: The API version "3.0.279" does not match the Viewer version "2.11.338".
    at new BaseViewer (pdf_viewer.js:8770:13)
    at PDFViewer._createSuperInternal (pdf_viewer.js:10655:283)
    at new PDFViewer (pdf_viewer.js:10673:19)
    at PdfViewerComponent.setupMultiPageViewer (ng2-pdf-viewer.mjs:450:35)
    at PdfViewerComponent.initialize (ng2-pdf-viewer.mjs:629:14)
    at ng2-pdf-viewer.mjs:300:22
    at timer (zone.js:2378:1)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
```

Do you have any suggestions on how to resolve this? Is there a separate place to configure the viewer version? Or have I done something incorrectly?

Cheers!

**Comment by egonknapen** [comment]
@naviln so I got to try it, unfortunately you are right, it doesn't seem to work. Probably just have to wait until the developer of this plugin updates it.

**Comment by naviln** [comment]
> @naviln so I got to try it, unfortunately you are right, it doesn't seem to work. Probably just have to wait until the developer of this plugin updates it.
> 
> I didn't get your error message, it just didn't work.

OK, thanks for trying. Hopefully we can get an update on this! In the meantime I am exploring other libraries, like https://www.npmjs.com/package/ngx-extended-pdf-viewer

**Comment by egonknapen** [comment]
> OK, thanks for trying. Hopefully we can get an update on this! In the meantime I am exploring other libraries, like https://www.npmjs.com/package/ngx-extended-pdf-viewer

I put that library on my todo list a few weeks back. I was looking into it because of new swipe functionality in firefox, to see if that's in the newest pdfjs. I was hoping this package gets updated earlier.
