### ISSUE TITLE
Add load progress callback

### ISSUE THREAD

**Issue by pj-r** [VadimDez/ng2-pdf-viewer#94]
Would it be hard to add an event emitter for progress of loading pdf document?
I did quick research and looks like it could be done.

from pdfjs src/display/api.js we can find:
```
loadingTask.onProgress({
  loaded: data.loaded,
  total: data.total,
});
```
add an event emitter to pdf-viewer.component.ts:
```
@Output('on-progress') onProgress = new EventEmitter<any>();
```
change the line in pdf-viewer.component.ts to handle progress event:
```
PDFJS.getDocument(src).then((pdf: PDFDocumentProxy) => {
```
---->
```
PDFDocumentLoadingTask task = PDFJS.getDocument(src);
task.onProgress = (any) => { this.onProgress(any); };
task.then((pdf: PDFDocumentProxy) => {
```

Note: Just pseudo code. Havent tested if it works.

**Comment by VadimDez** [comment]
You can use different approach, by just settings `isLoading = true;` before and then change to `isLoading = false` once `after-load-complete` event is called.

**Comment by pj-r** [comment]
In my case the problem is that for example with IE loading some bigger pdf files can take up to 3 minutes and it would be nice to show progress for the user so he/she can determine how long the coffee break will be.

There is one example file: [https://github.com/mozilla/pdf.js/issues/7989](#7989)

**Comment by pj-r** [comment]
Nice work, Thanks!
