### ISSUE TITLE
Pdf viewer didn't work without internet connection

### ISSUE THREAD

**Issue by jackcoral89** [VadimDez/ng2-pdf-viewer#942]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Uploading the pdf file doesn't seem to work without an internet connection (I need it to work without an internet connection). Looks like you're looking for a cdn. It's correct ?

![image](https://user-images.githubusercontent.com/27479143/202512462-554b5d03-ce71-44fd-84e4-b9db48c01d44.png)

Thanks for support!

**Comment by jackcoral89** [comment]
From plugin owner not seem.

**Comment by VadimDez** [comment]
You have to pass path to pdf-worker that is hosted by you instead. Here's how to achieve that:
https://github.com/VadimDez/ng2-pdf-viewer#set-custom-path-to-the-worker

**Comment by jackcoral89** [comment]
> Hello, I've the same problem :( Any update ?

That's solution. Cheers

https://github.com/VadimDez/ng2-pdf-viewer/issues/942#issuecomment-1329520136
