### ISSUE TITLE
Detect scroll to end of document

### ISSUE THREAD

**Issue by ravz** [VadimDez/ng2-pdf-viewer#945]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [X] Feature request
- [X] Documentation issue or request
```

Hello, is there any way to detect that user has scrolled to the end of the PDF document ?

**Comment by NishadAbdul** [comment]
Is there any way?

**Comment by leonardomnds** [comment]
I also needed the scroll event, this was the solution I used.

on .html
```
<pdf-viewer (after-load-complete)="listenScroll()" ...otherProps></pdf-viewer>
```

and on .ts
```
constructor(
    @Inject(DOCUMENT)
    private document: Document,
    private renderer: Renderer2
  ) { }

  listenScroll(): void {
    const scrollableEl = this.document.querySelector<HTMLDivElement>('.ng2-pdf-viewer-container');

    if (!scrollableEl) { return; }

    this.renderer.listen(scrollableEl, 'scroll', (event: Event) => {
      const isScrollEnd = scrollableEl.scrollHeight - scrollableEl.scrollTop <= scrollableEl.clientHeight;
      if (isScrollEnd) { console.log('scroll end') }
    });
  }
```

**Comment by maomh** [comment]
> I also needed the scroll event, this was the solution I used.
> 
> on .html
> 
> ```
> <pdf-viewer (after-load-complete)="listenScroll()" ...otherProps></pdf-viewer>
> ```
> 
> and on .ts
> 
> ```
> constructor(
>     @Inject(DOCUMENT)
>     private document: Document,
>     private renderer: Renderer2
>   ) { }
> 
>   listenScroll(): void {
>     const scrollableEl = this.document.querySelector<HTMLDivElement>('.ng2-pdf-viewer-container');
> 
>     if (!scrollableEl) { return; }
> 
>     this.renderer.listen(scrollableEl, 'scroll', (event: Event) => {
>       const isScrollEnd = scrollableEl.scrollHeight - scrollableEl.scrollTop <= scrollableEl.clientHeight;
>       if (isScrollEnd) { console.log('scroll end') }
>     });
>   }
> ```



Thanks very much!!!

I changed to use the page numuber to instead of the scroll envent, it works good.

on .html

``` <pdf-viewer ... [(page)]="pdfPageNumber" (after-load-complete)="onLoadComplete($event)">```

on .ts

```
  private pdfLastPageNumber = 0;
  hasScrolledToBottom = false;
  pdfPageNumber = 1;
  ...

  onLoadComplete(pdf: PDFDocumentProxy) {
    this.pdfLastPageNumber = pdf._pdfInfo.numPages;

    const pdfEl = document.querySelector('.ng2-pdf-viewer-container');
    if (pdfEl) {
      pdfEl.addEventListener('scroll', () => {
        if (this.hasScrolledToBottom) {
          return;
        }
        if (this.pdfPageNumber == this.pdfLastPageNumber) {
          this.hasScrolledToBottom = true;
          console.log('Scrolled to the bottom of the page');
        }
      });
    }
```

**Comment by TomasMasiulis** [comment]
DEV: https://github.com/VadimDez/ng2-pdf-viewer/issues/945
