### ISSUE TITLE
The Zoom logic is backwards

### ISSUE THREAD

**Issue by EricBPower** [VadimDez/ng2-pdf-viewer#95]
Larger zoom numbers should result in larger documents lowering the zoom should result in a smaller document.  

When OriginalSize=true it works as expected, but when originalSize=false it does the opposite sizing.

**Comment by citizentim** [comment]
+1 I've just noticed this as well.  Would be great to get a fix.

**Comment by citizentim** [comment]
Would someone mind commenting on this?

**Comment by citizentim** [comment]
Actually, this appears to have been resolved by 2.0.2.

**Comment by EricBPower** [comment]
Appears to be working now I tested in 2.0.2.
