### ISSUE TITLE
Better find/search

### ISSUE THREAD

**Issue by Starter3** [VadimDez/ng2-pdf-viewer#951]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```
Documentation shows sample to search text, but how to 
1. Find Next, 
2. Find Previous and 
3. Zoom to Rect (where the search text was found), especially if the pdf file contains pages in different sizes and when 100% zoom brings horizontal scroll bar and the searched text resides in the other side, then viewer need to bring it to visible area. 
Mozilla viewer (https://mozilla.github.io/pdf.js/web/viewer.html) does all this excellently can this be achieved in this viewer.

**Comment by bradymesser** [comment]
For 1. and 2.
```
searchQueryChanged(newQuery: string) {
    const type = newQuery !== this.pdfQuery ? '' : 'again';
    this.pdfQuery = newQuery;

    this.pdfComponent.eventBus.dispatch('find', {
      type,
      query: this.pdfQuery,
      highlightAll: true,
      caseSensitive: false,
      phraseSearch: true,
      // findPrevious: undefined,
    });
  }
```


Needed the same functionality and found this in the code for the github.io example, to find next you would pass in `type: 'again'` then set `findPrevious: false`
To find previous would be the same as above but set findPrevious to true
