### ISSUE TITLE
Angular 15 Problem

### ISSUE THREAD

**Issue by ja74687** [VadimDez/ng2-pdf-viewer#955]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Hello

I update my frontend app to Angular 15 and I have big problem:
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/24416487/206482893-d1b6fa38-2630-4d42-88e0-bb0fea024ffd.png">
Do you have any idea how I can fix it ??

**Comment by elnipa** [comment]
We experience the same problem. Introduced in @Angular-devkit v15.0.3.
V15.0.2 is working fine.

**Comment by AnthonyNahas** [comment]
I had the same problem! I can confirm that downgrading angular devkit to 15.0.2 solved the problem with angular v15 projects

**Comment by ja74687** [comment]
I fix when I remove # from pdf-js, maybe would have to include pdf-js to ng2-pdf-viewer and edit file in pdf-js :)

**Comment by lekhmanrus** [comment]
That was fixed in https://github.com/angular/angular-cli/commit/97373016cfe2635125015b2fec390f43d22ebf31 - just need to wait for a new release. 🙂

**Comment by ja74687** [comment]
Hey

angular-cli have update to 15.0.4, problem was fixed :)
