### ISSUE TITLE
CSP restrictions 

### ISSUE THREAD

**Issue by Pauline3** [VadimDez/ng2-pdf-viewer#965]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ X ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
Hello, 
I have a  project with a CSP configuration : 
```
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data:
    />
```
When I try to open the viewer, I have the following error :

**Refused to create a worker from 'blob:http://localhost:63399/751506b8-8158-4e99-a708-ffb6c570deaa' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.**

**Comment by naviln** [comment]
Hi @Pauline3 

I had the same issue, I appended the below to my CSP config for it to work:

`"; worker-src blob:"`
