### ISSUE TITLE
Save PDF to PNG - Get PDFJS Canvas Element

### ISSUE THREAD

**Issue by aa-telali** [VadimDez/ng2-pdf-viewer#97]
I'd like to get to the PDFJS canvas in order to save it as a PNG or JPEG using `canvas.toDataURL`.

Example code below:

```javascript
// Download button (PNG)
onSaveAsPng() {
   var canvas = document.getElementById("mycanvas");
   var img = canvas.toDataURL("image/png");
   // Need to show/save this somehow too..
});

// Download button (JPEG with quality 80%)
onSaveAsJpeg() {
   var canvas = document.getElementById("mycanvas");
   var img = canvas.toDataURL("image/jpeg", 0.8);
});
```

As found here: http://usefulangle.com/post/24/pdf-to-jpeg-png-with-pdfjs

**Comment by dharmendra-verma** [comment]
How can i save the pdf after drawing over canvas?

**Comment by aa-telali** [comment]
@VadimDez As you've moved away from using the canvas now is there another way, maybe a function you could add, to allow us to save the PDF page to a PNG?
