### ISSUE TITLE
Force download of the entire file

### ISSUE THREAD

**Issue by lilSvensken** [VadimDez/ng2-pdf-viewer#974]
Hi, @VadimDez 

I need to implement a document search to get the number of matches. To do this, I use "updatefindmatchescount". The problem is that with a large number of pages in a pdf document, loading may take time and the number of matches does not become relevant immediately. Is there a property that allows you to render the entire pdf file at once? Or a wiretap to download the last page of a pdf file

"@angular/cli": "^8.3.24"
"ng2-pdf-viewer": "^6.4.1"

**Comment by VijiSridhar95** [comment]
@lilSvensken any solution how to load all the pages in the pdf at once?
