### ISSUE TITLE
Bug with prerendering - angular universal -  Error: Module not found: Error: Can't resolve 'canvas'

### ISSUE THREAD

**Issue by AnthonyNahas** [VadimDez/ng2-pdf-viewer#978]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

I am trying to improve the initial load performance of my angular app using angular universal and prerendering. 
Since I am relying in my deps on ng2-pdf-viewer, while prerendering I am getting the following error which will break the build:

```bash
./node_modules/ng2-pdf-viewer/node_modules/pdfjs-dist/build/pdf.js:7849:27-44 - Error: Module not found: Error: Can't resolve 'canvas' in '/Users/anthonynahas/git/nahaus.de/admin.nahaus.de/node_modules/ng2-pdf-viewer/node_modules/pdfjs-dist/build'
```

![Bildschirm­foto 2023-03-06 um 21 08 48](https://user-images.githubusercontent.com/20149774/223219345-e557c8c5-ce70-4005-9026-62be3d91c3b0.png)

We need support of server side rendering in order to continue using this library...

**Comment by RikJS** [comment]
Encountered the same issue today, also can't use this library till it gets fixed :(

**Comment by VadimDez** [comment]
Have you tried [this](https://github.com/VadimDez/ng2-pdf-viewer/issues/908#issuecomment-1221414595) ?
