### ISSUE TITLE
PDF Auto Resize

### ISSUE THREAD

**Issue by aa-telali** [VadimDez/ng2-pdf-viewer#98]
Hi all,

[Using v1.1.0]

Original Question: How would I get the pdf to grow and shrink with the width of the page?

Update: Looking at the code I think the resize behaviour has been moved from the sample to the internal implementation of the pdf-viewer, and it looks like (above 480px) it should do what I'm expecting (increase the size of the visible PDF when I increase the page width)..

I've got:

```
.div-pdf {
      margin-left: auto;
      margin-right: auto;
      width: 100%;
   }
   pdf-viewer {
      display: block;
   }
```
```
<div class="div-pdf">
                <pdf-viewer 
                  [src]="pdfSrc" 
                  [page]="pdfPage" 
                  [original-size]="pdfOriginalSize" 
                  [show-all]="pdfShowAll" 
                  [render-text]="pdfRenderText" 
                  [zoom]="pdfZoom" 
                  [rotation]="pdfRotation">
                </pdf-viewer>
              </div>
```
```
  pdfPage = 1;
  pdfRotation = 0;
  pdfZoom = 1.0;
  pdfOriginalSize = false;
  pdfShowAll = false;
  pdfRenderText = false;
```

Any ideas? I've noticed this is what happens on the demo but can't seem to find the right code in the source...

Thanks in advance!

**Comment by mihilranathunga** [comment]
simply said the rendered PDF is not responsive. Even the demo is not responsive. But PDFJS demo is responsive. May be this has something to with the PDFJS version used in this component since the PDFJS demo uses unreleased newer version.

I'm also interested in this feature

**Comment by celloman** [comment]
I'm also interested in this feature. I appears that the logic for resizing is present in the repository but not in the npm package yet.

**Comment by PendelinP** [comment]
+1 I'm also pretty interested in this feature ;) Thanks

**Comment by priya1890** [comment]
This  129c37f fix has not been added to the npm package. Please verify

**Comment by whatwehaveunlearned** [comment]
what happened with this?
