### ISSUE TITLE
Pdf viewer elements are rendering in the DOM but not visible 

### ISSUE THREAD

**Issue by rajeshkannavelu** [VadimDez/ng2-pdf-viewer#987]
Hello,

Currently on angular 15 version, when I try to render the pdf file, I could see all the pages in the DOM but is not visible in the web page.
Is this a known issue or I'm doing any thing wrong?

Can I get any solution please?
Thanks in advance.

**Comment by Fr3eX** [comment]
Hey @rajeshkannavelu  without code we can't help. can you provide us more details ?

**Comment by rajeshkannavelu** [comment]
In the DOM, we could see that the all the elements have been rendered but in the html it is not visible. But when i give some fixed size to the pdf-viewer in the style like style= "height:1000px ;widht:1000px;" the html is now display the content.

![image](https://user-images.githubusercontent.com/72302478/229349187-1c6ba543-bdcd-490e-bb88-c123fe5a62c3.png)

Non-working,
 <div class="pdf-container top-margin" [hidden]="isCropImage">
      <pdf-viewer [src]="pdfSrc" [render-text]="true" [page]="currentpage" [show-all]="true" [original-size]="true"
        [fit-to-page]="false" (after-load-complete)="afterLoadComplete($event)" style="display: block;">
      </pdf-viewer>
    </div>

  public uploadFile(event:any) {
    let $img: any = document.querySelector('#upload-doc');
    if(event.target.files[0].type == 'application/pdf'){
      if (typeof (FileReader) !== 'undefined') {
        let reader = new FileReader();
        reader.onload = (e: any) => {
          this.pdfSrc = e.target.result;
        };
        this.isPdfUploaded = true;
        reader.readAsArrayBuffer($img.files[0]);
      }
    } else{
      alert('please upload pdf file')
    }
  }

![image](https://user-images.githubusercontent.com/72302478/229348947-44446c36-5fe5-41fb-806d-bda9fb833d9e.png)

**Comment by rajeshkannavelu** [comment]
Note: This is working when the download the source from the repo, but when I manually setup this in some standalone app it is not showing rendered pdf file in the browser. If I give some standard height and width then I could able to see the pdf.
