### ISSUE TITLE
scale not correctly updated on pdf-viewer rotation for pdf page with 90° rotation 

### ISSUE THREAD

**Issue by QuentinChaumont** [VadimDez/ng2-pdf-viewer#992]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Hi, first of all thanks for your work.

**Configuration of pdf-viewer :**

 [original-size]="false"
 [page]="pageNumber"
 [render-text]="true"
 [show-all]="false"
 [rotation]="rotation"
 [show-borders]="false"
 [src]="src"
 [zoom-scale]="'page-width'"

**Description of the issue :**

When I'am using a _pdf with pages already rotated_ on pdf-viewer it display perfectly.
But when I apply a pdf-viewer rotation of 90° on it the width scale is not updated. So my pdf succesfully rotate but it is cropped because width scale did not update.

**Resolution of the issue :**

I managed to find the reason on pdf-viewer.component.ts line 323 : 
`          const rotation = this._rotation || page.rotate;
`
The fix is simple : 
`          const rotation = this._rotation + page.rotate;
`

**Explanation of the fix :**

Without fix :   const rotation = this._rotation || page.rotate; :

1 - pdf page with rotation already applyed on it is loaded
2 -  const rotation = 90 (from page.rotate) :heavy_check_mark: 
3- I apply pdfViewer rotation on it
4- const rotation = 90 (from  this._rotation) :negative_squared_cross_mark:

With fix :    const rotation = this._rotation + page.rotate; :

1 - pdf page with rotation already applyed on it is loaded
2 -  const rotation = 90 (from this._rotation 0 + page.rotate 90 ) :heavy_check_mark: 
3- I apply pdfViewer rotation on it
4- const rotation = 180 (from this._rotation 90 + page.rotate 90 ) :heavy_check_mark: 

I'm doing pull request to fix this for you.

Have a good day

**Comment by VadimDez** [comment]
@QuentinChaumont thanks for the PR! i've just tested and see no difference before and after applying your changes. Can you please make some screenshots showing the difference before vs after?

**Comment by QuentinChaumont** [comment]
It's a very specific use-case appear only with pdf saved with internal rotation in some pages. 

For normal pdf pages without internal rotation (page.rotation) it's work fine with 90° rotation and zoom-scale= 'page-width' the pdf resize to take all the width space : 

![Capture d’écran du 2023-04-14 09-14-15](https://user-images.githubusercontent.com/23658725/231972859-3673c391-3414-4a81-897a-b75096217eba.png)

When I go to the third page of my pain in the ass pdf which has an internal rotation (page.rotation = 90), you can see that the pdf does not resize to use full width :

![Capture d’écran du 2023-04-14 09-14-47](https://user-images.githubusercontent.com/23658725/231973328-025a27a5-bc22-4e0c-b54a-b80acc169337.png)

After my quick fix, behaviour does not change normal pages rotation but fix the pages with internal rotation :

![Capture d’écran du 2023-04-14 09-17-12](https://user-images.githubusercontent.com/23658725/231973627-6ff5573b-7687-4fb5-903b-2c2f0f85e502.png)

**Comment by QuentinChaumont** [comment]
If you want to try by yourself i give you my pdf :

- first and second page are normal
- third pages has internal page rotation of 90° (it's created the problem)

**Comment by QuentinChaumont** [comment]
Thx for your time.

**Comment by VadimDez** [comment]
Thanks @QuentinChaumont, I could replicate the issue with your PDF, will publish `9.1.5` soon
