### ISSUE TITLE
Rotation default value not working

### ISSUE THREAD

**Issue by daniela-alves** [VadimDez/ng2-pdf-viewer#999]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

When I define the rotation by default when I load the document is not applied.

Example:
https://stackblitz.com/edit/ng2-pdf-viewer-qtq9ny?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.css

By default I defined 180. When the document is loaded the rotation is not applied and seems to be 0.
If I click on the test button to set the rotation to 90, works.

**Comment by ftaffelt** [comment]
i think this is the same like #976

**Comment by daniela-alves** [comment]
Yes, you are right. Did you found a workaround until we have a fix?

**Comment by marcelocerqueira69** [comment]
@ftaffelt yeah, probably is. The wquestion is: does someone know how to overcome that isssue?

**Comment by Ricardo-Guia** [comment]
> @ftaffelt yeah, probably is. The wquestion is: does someone know how to overcome that isssue?

@marcelocerqueira69, I would like to have it resolved too or even a way to achieve that

**Comment by helderdias15** [comment]
Same issue right here

**Comment by daniela-alves** [comment]
I haven't found yet a solution. Can someone help me, please?

**Comment by lcvalves** [comment]
Any news regarding this issue?

**Comment by mediamix1950** [comment]
Same problem here, very annoying because the first page of the document is not rotated at loading.. Any idea when it will be corrected? 
Thx for support

**Comment by jarodsmk** [comment]
Seems there's an internal change detection issue with the library. 

I overcame this by forcing the code which sets the new default rotation amount to be a macro task, delaying it's execution:

your-pdf-display.component.ts
```ts
...
rotation = 0;

ngOnInit(){
  setTimeout(() => {
    this.rotation = 90;
  }, 0);
}
...
```


your-pdf-display.component.html
```html
...
<pdf-viewer
  ...
  [rotation]="rotation">
</pdf-viewer>
...
```
